-- ALLEMAND
INSERT INTO categories (id, name, slug, level, language) VALUES ('agriculture-agroalimentaire', 'Landwirtschaft & Lebensmittelindustrie', 'agriculture-agroalimentaire', 0, 'de');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
-- Landwirtschaftliche Ausrüstung
('materiel-agricole', 'Landwirtschaftliche Ausrüstung', 'materiel-agricole', 'agriculture-agroalimentaire', 1, 'de'),
('tracteurs-agricoles', 'Landwirtschaftliche Traktoren', 'tracteurs-agricoles', 'materiel-agricole', 2, 'de'),
('micro-tracteurs', 'Kleintraktoren', 'micro-tracteurs', 'materiel-agricole', 2, 'de'),
('motoculteurs', 'Motorhacken', 'motoculteurs', 'materiel-agricole', 2, 'de'),
('moissonneuses-batteuses', 'Mähdrescher', 'moissonneuses-batteuses', 'materiel-agricole', 2, 'de'),
('charrues', 'Pflüge', 'charrues', 'materiel-agricole', 2, 'de'),
('herses', 'Eggen', 'herses', 'materiel-agricole', 2, 'de'),
('semoirs', 'Sämaschinen', 'semoirs', 'materiel-agricole', 2, 'de'),
('pulverisateurs-agricoles', 'Landwirtschaftliche Sprühgeräte', 'pulverisateurs-agricoles', 'materiel-agricole', 2, 'de'),
('remorques-agricoles', 'Landwirtschaftliche Anhänger', 'remorques-agricoles', 'materiel-agricole', 2, 'de'),
('broyeurs-agricoles', 'Schredder', 'broyeurs-agricoles', 'materiel-agricole', 2, 'de'),
('epandeurs-agricoles', 'Streuer', 'epandeurs-agricoles', 'materiel-agricole', 2, 'de'),
('tarieres-mecaniques', 'Mechanische Erdbohrer', 'tarieres-mecaniques', 'materiel-agricole', 2, 'de'),
('presses-a-balles', 'Ballenpressen', 'presses-a-balles', 'materiel-agricole', 2, 'de'),
('elevateurs-agricoles', 'Landwirtschaftliche Hebegeräte', 'elevateurs-agricoles', 'materiel-agricole', 2, 'de'),

-- Werkzeuge & Anbaugeräte
('outils-equipements-de-culture', 'Werkzeuge & Anbaugeräte', 'outils-equipements-de-culture', 'agriculture-agroalimentaire', 1, 'de'),
('beches', 'Spaten', 'beches', 'outils-equipements-de-culture', 2, 'de'),
('pelles', 'Schaufeln', 'pelles', 'outils-equipements-de-culture', 2, 'de'),
('rateaux', 'Rechen', 'rateaux', 'outils-equipements-de-culture', 2, 'de'),
('houes', 'Hacken', 'houes', 'outils-equipements-de-culture', 2, 'de'),
('sarcleuses', 'Unkrautstecher', 'sarcleuses', 'outils-equipements-de-culture', 2, 'de'),
('binettes', 'Haken', 'binettes', 'outils-equipements-de-culture', 2, 'de'),
('secateurs', 'Baumscheren', 'secateurs', 'outils-equipements-de-culture', 2, 'de'),
('cisailles', 'Scheren', 'cisailles', 'outils-equipements-de-culture', 2, 'de'),
('arrosoirs', 'Gießkannen', 'arrosoirs', 'outils-equipements-de-culture', 2, 'de'),
('pulverisateurs-manuels', 'Handsprühgeräte', 'pulverisateurs-manuels', 'outils-equipements-de-culture', 2, 'de'),
('brouettes', 'Schubkarren', 'brouettes', 'outils-equipements-de-culture', 2, 'de'),
('gants-de-jardin', 'Gartenhandschuhe', 'gants-de-jardin', 'outils-equipements-de-culture', 2, 'de'),
('lames-agricoles', 'Landwirtschaftliche Klingen', 'lames-agricoles', 'outils-equipements-de-culture', 2, 'de'),
('filets-de-recolte', 'Erntenetze', 'filets-de-recolte', 'outils-equipements-de-culture', 2, 'de'),

-- Bewässerungssysteme
('systemes-irrigation', 'Bewässerungssysteme', 'systemes-irrigation', 'agriculture-agroalimentaire', 1, 'de'),
('tuyaux-d-arrosage', 'Gartenschläuche', 'tuyaux-d-arrosage', 'systemes-irrigation', 2, 'de'),
('goutte-a-goutte', 'Tropfbewässerung', 'goutte-a-goutte', 'systemes-irrigation', 2, 'de'),
('programmateurs-irrigation', 'Bewässerungscomputer', 'programmateurs-irrigation', 'systemes-irrigation', 2, 'de'),
('aspersions', 'Sprinkleranlagen', 'aspersions', 'systemes-irrigation', 2, 'de'),
('pompes-a-eau', 'Wasserpumpen', 'pompes-a-eau', 'systemes-irrigation', 2, 'de'),
('motopompes', 'Motorpumpen', 'motopompes', 'systemes-irrigation', 2, 'de'),
('raccords-irrigation', 'Bewässerungsverbinder', 'raccords-irrigation', 'systemes-irrigation', 2, 'de'),
('filtres-d-eau', 'Wasserfilter', 'filtres-d-eau', 'systemes-irrigation', 2, 'de'),
('arroseurs', 'Beregnungsanlagen', 'arroseurs', 'systemes-irrigation', 2, 'de'),
('reservoirs-d-eau', 'Wasserbehälter', 'reservoirs-d-eau', 'systemes-irrigation', 2, 'de'),

-- Saatgut & Pflanzen
('semences-plants', 'Saatgut & Pflanzen', 'semences-plants', 'agriculture-agroalimentaire', 1, 'de'),
('semences-potageres', 'Gemüsesamen', 'semences-potageres', 'semences-plants', 2, 'de'),
('semences-cerealieres', 'Getreidesamen', 'semences-cerealieres', 'semences-plants', 2, 'de'),
('semences-fourrageres', 'Futtersamen', 'semences-fourrageres', 'semences-plants', 2, 'de'),
('plants-de-legumes', 'Gemüsepflanzen', 'plants-de-legumes', 'semences-plants', 2, 'de'),
('plants-fruitiers', 'Obstpflanzen', 'plants-fruitiers', 'semences-plants', 2, 'de'),
('plants-d-arbres', 'Baumpflanzen', 'plants-d-arbres', 'semences-plants', 2, 'de'),
('graines-biologiques', 'Biologische Samen', 'graines-biologiques', 'semences-plants', 2, 'de'),
('graines-hybrides', 'Hybridsamen', 'graines-hybrides', 'semences-plants', 2, 'de'),
('bulbes', 'Zwiebeln', 'bulbes', 'semences-plants', 2, 'de'),
('jeunes-pousses', 'Junge Sprossen', 'jeunes-pousses', 'semences-plants', 2, 'de'),

-- Düngemittel & Bodenverbesserer
('engrais-fertilisants', 'Düngemittel & Bodenverbesserer', 'engrais-fertilisants', 'agriculture-agroalimentaire', 1, 'de'),
('engrais-chimiques', 'Chemische Dünger', 'engrais-chimiques', 'engrais-fertilisants', 2, 'de'),
('engrais-organiques', 'Organische Dünger', 'engrais-organiques', 'engrais-fertilisants', 2, 'de'),
('compost', 'Kompost', 'compost', 'engrais-fertilisants', 2, 'de'),
('fumiers', 'Stallmist', 'fumiers', 'engrais-fertilisants', 2, 'de'),
('amendements-calcaires', 'Kalkhaltige Bodenverbesserer', 'amendements-calcaires', 'engrais-fertilisants', 2, 'de'),
('stimulateurs-de-croissance', 'Wachstumsförderer', 'stimulateurs-de-croissance', 'engrais-fertilisants', 2, 'de'),
('terreaux', 'Pflanzerden', 'terreaux', 'engrais-fertilisants', 2, 'de'),
('substrats-agricoles', 'Landwirtschaftliche Substrate', 'substrats-agricoles', 'engrais-fertilisants', 2, 'de'),
('additifs-nutritifs', 'Nahrungsergänzungsmittel', 'additifs-nutritifs', 'engrais-fertilisants', 2, 'de'),

-- Pflanzenschutzmittel
('produits-phytosanitaires', 'Pflanzenschutzmittel', 'produits-phytosanitaires', 'agriculture-agroalimentaire', 1, 'de'),
('insecticides-agricoles', 'Landwirtschaftliche Insektizide', 'insecticides-agricoles', 'produits-phytosanitaires', 2, 'de'),
('fongicides', 'Fungizide', 'fongicides', 'produits-phytosanitaires', 2, 'de'),
('herbicides', 'Herbizide', 'herbicides', 'produits-phytosanitaires', 2, 'de'),
('traitements-biologiques', 'Biologische Behandlungen', 'traitements-biologiques', 'produits-phytosanitaires', 2, 'de'),
('repulsifs-naturels', 'Natürliche Repellentien', 'repulsifs-naturels', 'produits-phytosanitaires', 2, 'de'),
('pieges-anti-nuisibles', 'Schädlingsfallen', 'pieges-anti-nuisibles', 'produits-phytosanitaires', 2, 'de'),
('protections-pour-cultures', 'Pflanzenschutz', 'protections-pour-cultures', 'produits-phytosanitaires', 2, 'de'),

-- Tierhaltung & Tierpflege
('elevage-soins-animaux', 'Tierhaltung & Tierpflege', 'elevage-soins-animaux', 'agriculture-agroalimentaire', 1, 'de'),
('aliments-pour-betail', 'Tierfutter', 'aliments-pour-betail', 'elevage-soins-animaux', 2, 'de'),
('aliments-pour-volailles', 'Geflügelfutter', 'aliments-pour-volailles', 'elevage-soins-animaux', 2, 'de'),
('aliments-pour-ovins-caprins', 'Schaf- und Ziegenfutter', 'aliments-pour-ovins-caprins', 'elevage-soins-animaux', 2, 'de'),
('complements-nutritionnels', 'Nahrungsergänzungsmittel', 'complements-nutritionnels', 'elevage-soins-animaux', 2, 'de'),
('produits-veterinaires', 'Veterinärprodukte', 'produits-veterinaires', 'elevage-soins-animaux', 2, 'de'),
('mangeoires', 'Futtertröge', 'mangeoires', 'elevage-soins-animaux', 2, 'de'),
('abreuvoirs', 'Tränken', 'abreuvoirs', 'elevage-soins-animaux', 2, 'de'),
('clotures-electriques', 'Elektrische Zäune', 'clotures-electriques', 'elevage-soins-animaux', 2, 'de'),
('parcs-cages', 'Gehege & Käfige', 'parcs-cages', 'elevage-soins-animaux', 2, 'de'),

-- Stallbedarf & Ausstattung
('equipements-stables-structures', 'Stallbedarf & Ausstattung', 'equipements-stables-structures', 'agriculture-agroalimentaire', 1, 'de'),
('boxes-pour-animaux', 'Tierboxen', 'boxes-pour-animaux', 'equipements-stables-structures', 2, 'de'),
('clotures-agricoles', 'Landwirtschaftliche Zäune', 'clotures-agricoles', 'equipements-stables-structures', 2, 'de'),
('portails-agricoles', 'Landwirtschaftliche Tore', 'portails-agricoles', 'equipements-stables-structures', 2, 'de'),
('abris-pour-animaux', 'Tierunterstände', 'abris-pour-animaux', 'equipements-stables-structures', 2, 'de'),
('chenils-boxes', 'Hundezwinger & Boxen', 'chenils-boxes', 'equipements-stables-structures', 2, 'de'),
('patures-clotures', 'Weidezäune', 'patures-clotures', 'equipements-stables-structures', 2, 'de'),
('granges-batiments', 'Scheunen & Gebäude', 'granges-batiments', 'equipements-stables-structures', 2, 'de'),

-- Maschinen-Ersatzteile
('pieces-detachees-equipements', 'Maschinen-Ersatzteile', 'pieces-detachees-equipements', 'agriculture-agroalimentaire', 1, 'de'),
('pieces-tracteurs', 'Traktorenteile', 'pieces-tracteurs', 'pieces-detachees-equipements', 2, 'de'),
('pieces-moissonneuses', 'Mähdrescherteile', 'pieces-moissonneuses', 'pieces-detachees-equipements', 2, 'de'),
('pieces-motoculteurs', 'Motorkultivatorteile', 'pieces-motoculteurs', 'pieces-detachees-equipements', 2, 'de'),
('pieces-broyeurs', 'Schredderteile', 'pieces-broyeurs', 'pieces-detachees-equipements', 2, 'de'),
('pieces-epandeurs', 'Streugerteile', 'pieces-epandeurs', 'pieces-detachees-equipements', 2, 'de'),
('filtres-agricoles', 'Landwirtschaftliche Filter', 'filtres-agricoles', 'pieces-detachees-equipements', 2, 'de'),
('courroies-agricoles', 'Landwirtschaftliche Riemen', 'courroies-agricoles', 'pieces-detachees-equipements', 2, 'de'),
('chaines-agricoles', 'Landwirtschaftliche Ketten', 'chaines-agricoles', 'pieces-detachees-equipements', 2, 'de'),
('pneus-agricoles', 'Landwirtschaftliche Reifen', 'pneus-agricoles', 'pieces-detachees-equipements', 2, 'de'),

-- Transport & Logistik
('transport-logistique-agricole', 'Transport & Logistik', 'transport-logistique-agricole', 'agriculture-agroalimentaire', 1, 'de'),
('vehicules-utilitaires-agricoles', 'Nutzfahrzeuge für Landwirtschaft', 'vehicules-utilitaires-agricoles', 'transport-logistique-agricole', 2, 'de'),
('chariots-elevateurs', 'Gabelstapler', 'chariots-elevateurs', 'transport-logistique-agricole', 2, 'de'),
('transpalettes', 'Palettenhubwagen', 'transpalettes', 'transport-logistique-agricole', 2, 'de'),
('diables', 'Sackkarren', 'diables', 'transport-logistique-agricole', 2, 'de'),
('roues-de-manutention', 'Transporträder', 'roues-de-manutention', 'transport-logistique-agricole', 2, 'de'),
('benne-a-grain', 'Korbboden', 'benne-a-grain', 'transport-logistique-agricole', 2, 'de'),
('souleveurs', 'Hebezeuge', 'souleveurs', 'transport-logistique-agricole', 2, 'de'),
('gerbeurs', 'Stapler', 'gerbeurs', 'transport-logistique-agricole', 2, 'de'),
('plateformes-de-travail', 'Arbeitsbühnen', 'plateformes-de-travail', 'transport-logistique-agricole', 2, 'de'),
('echelles-agricoles', 'Landwirtschaftliche Leitern', 'echelles-agricoles', 'transport-logistique-agricole', 2, 'de'),
('plateaux', 'Plattformen', 'plateaux', 'transport-logistique-agricole', 2, 'de'),
('caisses', 'Kisten', 'caisses', 'transport-logistique-agricole', 2, 'de'),
('palettes', 'Paletten', 'palettes', 'transport-logistique-agricole', 2, 'de'),
('conteneurs', 'Container', 'conteneurs', 'transport-logistique-agricole', 2, 'de'),
('charrettes-agricoles', 'Landwirtschaftliche Karren', 'charrettes-agricoles', 'transport-logistique-agricole', 2, 'de'),
('bennes-basculantes', 'Kipper', 'bennes-basculantes', 'transport-logistique-agricole', 2, 'de'),

-- Bienenstockausrüstung & Imkerei
('equipement-ruchers-apiculture', 'Bienenstockausrüstung & Imkerei', 'equipement-ruchers-apiculture', 'agriculture-agroalimentaire', 1, 'de'),
('ruches', 'Bienenstöcke', 'ruches', 'equipement-ruchers-apiculture', 2, 'de'),
('cadres-de-ruche', 'Wabenrahmen', 'cadres-de-ruche', 'equipement-ruchers-apiculture', 2, 'de'),
('cire-gaufree', 'Prägewachs', 'cire-gaufree', 'equipement-ruchers-apiculture', 2, 'de'),
('enfumoirs', 'Räuchergeräte', 'enfumoirs', 'equipement-ruchers-apiculture', 2, 'de'),
('extracteurs-de-miel', 'Honigschleudern', 'extracteurs-de-miel', 'equipement-ruchers-apiculture', 2, 'de'),
('equipements-apiculteurs', 'Imkerausrüstung', 'equipements-apiculteurs', 'equipement-ruchers-apiculture', 2, 'de'),
('pieges-a-essaims', 'Schwarmfallen', 'pieges-a-essaims', 'equipement-ruchers-apiculture', 2, 'de'),

-- Werkzeuge & Produkte für Gesundheitskontrolle
('controle-sanitaire-outils-produits', 'Werkzeuge & Produkte für Gesundheitskontrolle', 'controle-sanitaire-outils-produits', 'agriculture-agroalimentaire', 1, 'de'),
('desinfectants-agricoles', 'Landwirtschaftliche Desinfektionsmittel', 'desinfectants-agricoles', 'controle-sanitaire-outils-produits', 2, 'de'),
('pulverisateurs-sanitaires', 'Sanitäre Sprühgeräte', 'pulverisateurs-sanitaires', 'controle-sanitaire-outils-produits', 2, 'de'),
('pieges-a-insectes', 'Insektenfallen', 'pieges-a-insectes', 'controle-sanitaire-outils-produits', 2, 'de'),
('filets-anti-oiseaux', 'Vogelschutznetze', 'filets-anti-oiseaux', 'controle-sanitaire-outils-produits', 2, 'de'),
('systemes-protection-cultures', 'Pflanzenschutzsysteme', 'systemes-protection-cultures', 'controle-sanitaire-outils-produits', 2, 'de'),
('stations-meteo-agricoles', 'Landwirtschaftliche Wetterstationen', 'stations-meteo-agricoles', 'controle-sanitaire-outils-produits', 2, 'de'),

-- Zubehör & Verbrauchsmaterial
('accessoires-consommables', 'Zubehör & Verbrauchsmaterial', 'accessoires-consommables', 'agriculture-agroalimentaire', 1, 'de'),
('ficelles-agricoles', 'Landwirtschaftliche Schnüre', 'ficelles-agricoles', 'accessoires-consommables', 2, 'de'),
('cordages', 'Tauwerk', 'cordages', 'accessoires-consommables', 2, 'de'),
('sangles', 'Spanngurte', 'sangles', 'accessoires-consommables', 2, 'de'),
('attaches-pour-plants', 'Pflanzenbefestigungen', 'attaches-pour-plants', 'accessoires-consommables', 2, 'de'),
('boites-d-emballage', 'Verpackungsboxen', 'boites-d-emballage', 'accessoires-consommables', 2, 'de'),
('sacs-alimentaires', 'Lebensmittelbeutel', 'sacs-alimentaires', 'accessoires-consommables', 2, 'de'),
('etiquettes-agricoles', 'Landwirtschaftliche Etiketten', 'etiquettes-agricoles', 'accessoires-consommables', 2, 'de');

-- ITALIANO
INSERT INTO categories (id, name, slug, level, language) VALUES ('agriculture-agroalimentaire', 'Agricoltura & Agroalimentare', 'agriculture-agroalimentaire', 0, 'it');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
-- Attrezzature agricole
('materiel-agricole', 'Attrezzature agricole', 'materiel-agricole', 'agriculture-agroalimentaire', 1, 'it'),
('tracteurs-agricoles', 'Trattori agricoli', 'tracteurs-agricoles', 'materiel-agricole', 2, 'it'),
('micro-tracteurs', 'Micro-trattori', 'micro-tracteurs', 'materiel-agricole', 2, 'it'),
('motoculteurs', 'Motozappe', 'motoculteurs', 'materiel-agricole', 2, 'it'),
('moissonneuses-batteuses', 'Mietitrebbie', 'moissonneuses-batteuses', 'materiel-agricole', 2, 'it'),
('charrues', 'Aratri', 'charrues', 'materiel-agricole', 2, 'it'),
('herses', 'Erpici', 'herses', 'materiel-agricole', 2, 'it'),
('semoirs', 'Seminatrici', 'semoirs', 'materiel-agricole', 2, 'it'),
('pulverisateurs-agricoles', 'Irroratrici agricole', 'pulverisateurs-agricoles', 'materiel-agricole', 2, 'it'),
('remorques-agricoles', 'Rimorchi agricoli', 'remorques-agricoles', 'materiel-agricole', 2, 'it'),
('broyeurs-agricoles', 'Trituratori', 'broyeurs-agricoles', 'materiel-agricole', 2, 'it'),
('epandeurs-agricoles', 'Spandiconcime', 'epandeurs-agricoles', 'materiel-agricole', 2, 'it'),
('tarieres-mecaniques', 'Trivellatrici meccaniche', 'tarieres-mecaniques', 'materiel-agricole', 2, 'it'),
('presses-a-balles', 'Presse per balle', 'presses-a-balles', 'materiel-agricole', 2, 'it'),
('elevateurs-agricoles', 'Sollevatori agricoli', 'elevateurs-agricoles', 'materiel-agricole', 2, 'it'),

-- Strumenti & attrezzature di coltivazione
('outils-equipements-de-culture', 'Strumenti & attrezzature di coltivazione', 'outils-equipements-de-culture', 'agriculture-agroalimentaire', 1, 'it'),
('beches', 'Vanghe', 'beches', 'outils-equipements-de-culture', 2, 'it'),
('pelles', 'Pale', 'pelles', 'outils-equipements-de-culture', 2, 'it'),
('rateaux', 'Rastrelli', 'rateaux', 'outils-equipements-de-culture', 2, 'it'),
('houes', 'Zappe', 'houes', 'outils-equipements-de-culture', 2, 'it'),
('sarcleuses', 'Sarcleatrici', 'sarcleuses', 'outils-equipements-de-culture', 2, 'it'),
('binettes', 'Zappette', 'binettes', 'outils-equipements-de-culture', 2, 'it'),
('secateurs', 'Cesoie', 'secateurs', 'outils-equipements-de-culture', 2, 'it'),
('cisailles', 'Cesoie pesanti', 'cisailles', 'outils-equipements-de-culture', 2, 'it'),
('arrosoirs', 'Annaffiatoi', 'arrosoirs', 'outils-equipements-de-culture', 2, 'it'),
('pulverisateurs-manuels', 'Pompe a spruzzo manuali', 'pulverisateurs-manuels', 'outils-equipements-de-culture', 2, 'it'),
('brouettes', 'Carriole', 'brouettes', 'outils-equipements-de-culture', 2, 'it'),
('gants-de-jardin', 'Guanti da giardino', 'gants-de-jardin', 'outils-equipements-de-culture', 2, 'it'),
('lames-agricoles', 'Lame agricole', 'lames-agricoles', 'outils-equipements-de-culture', 2, 'it'),
('filets-de-recolte', 'Reti per raccolto', 'filets-de-recolte', 'outils-equipements-de-culture', 2, 'it'),

-- Sistemi di irrigazione
('systemes-irrigation', 'Sistemi di irrigazione', 'systemes-irrigation', 'agriculture-agroalimentaire', 1, 'it'),
('tuyaux-d-arrosage', 'Tubi per irrigazione', 'tuyaux-d-arrosage', 'systemes-irrigation', 2, 'it'),
('goutte-a-goutte', 'Goccia a goccia', 'goutte-a-goutte', 'systemes-irrigation', 2, 'it'),
('programmateurs-irrigation', 'Programmatori per irrigazione', 'programmateurs-irrigation', 'systemes-irrigation', 2, 'it'),
('aspersions', 'Aspersori', 'aspersions', 'systemes-irrigation', 2, 'it'),
('pompes-a-eau', 'Pompe per acqua', 'pompes-a-eau', 'systemes-irrigation', 2, 'it'),
('motopompes', 'Motopompe', 'motopompes', 'systemes-irrigation', 2, 'it'),
('raccords-irrigation', 'Raccordi per irrigazione', 'raccords-irrigation', 'systemes-irrigation', 2, 'it'),
('filtres-d-eau', 'Filtri per acqua', 'filtres-d-eau', 'systemes-irrigation', 2, 'it'),
('arroseurs', 'Irrigatori', 'arroseurs', 'systemes-irrigation', 2, 'it'),
('reservoirs-d-eau', 'Serbatoi per acqua', 'reservoirs-d-eau', 'systemes-irrigation', 2, 'it'),

-- Semi & piante
('semences-plants', 'Semi & piante', 'semences-plants', 'agriculture-agroalimentaire', 1, 'it'),
('semences-potageres', 'Semi da orto', 'semences-potageres', 'semences-plants', 2, 'it'),
('semences-cerealieres', 'Semi cerealicoli', 'semences-cerealieres', 'semences-plants', 2, 'it'),
('semences-fourrageres', 'Semi foraggeri', 'semences-fourrageres', 'semences-plants', 2, 'it'),
('plants-de-legumes', 'Piante da orto', 'plants-de-legumes', 'semences-plants', 2, 'it'),
('plants-fruitiers', 'Piante da frutto', 'plants-fruitiers', 'semences-plants', 2, 'it'),
('plants-d-arbres', 'Piante arboree', 'plants-d-arbres', 'semences-plants', 2, 'it'),
('graines-biologiques', 'Semi biologici', 'graines-biologiques', 'semences-plants', 2, 'it'),
('graines-hybrides', 'Semi ibridi', 'graines-hybrides', 'semences-plants', 2, 'it'),
('bulbes', 'Bulbi', 'bulbes', 'semences-plants', 2, 'it'),
('jeunes-pousses', 'Giovani germogli', 'jeunes-pousses', 'semences-plants', 2, 'it'),

-- Concimi & fertilizzanti
('engrais-fertilisants', 'Concimi & fertilizzanti', 'engrais-fertilisants', 'agriculture-agroalimentaire', 1, 'it'),
('engrais-chimiques', 'Concimi chimici', 'engrais-chimiques', 'engrais-fertilisants', 2, 'it'),
('engrais-organici', 'Concimi organici', 'engrais-organiques', 'engrais-fertilisants', 2, 'it'),
('compost', 'Compost', 'compost', 'engrais-fertilisants', 2, 'it'),
('fumiers', 'Letami', 'fumiers', 'engrais-fertilisants', 2, 'it'),
('amendements-calcaires', 'Amendamenti calcarei', 'amendements-calcaires', 'engrais-fertilisants', 2, 'it'),
('stimulateurs-de-croissance', 'Stimolatori di crescita', 'stimulateurs-de-croissance', 'engrais-fertilisants', 2, 'it'),
('terreaux', 'Terricci', 'terreaux', 'engrais-fertilisants', 2, 'it'),
('substrats-agricoles', 'Substrati agricoli', 'substrats-agricoles', 'engrais-fertilisants', 2, 'it'),
('additifs-nutritifs', 'Additivi nutritivi', 'additifs-nutritifs', 'engrais-fertilisants', 2, 'it'),

-- Prodotti fitosanitari
('produits-phytosanitaires', 'Prodotti fitosanitari', 'produits-phytosanitaires', 'agriculture-agroalimentaire', 1, 'it'),
('insecticides-agricoles', 'Insetticidi agricoli', 'insecticides-agricoles', 'produits-phytosanitaires', 2, 'it'),
('fongicides', 'Fungicidi', 'fongicides', 'produits-phytosanitaires', 2, 'it'),
('herbicides', 'Erbicidi', 'herbicides', 'produits-phytosanitaires', 2, 'it'),
('traitements-biologiques', 'Trattamenti biologici', 'traitements-biologiques', 'produits-phytosanitaires', 2, 'it'),
('repulsifs-naturels', 'Repellenti naturali', 'repulsifs-naturels', 'produits-phytosanitaires', 2, 'it'),
('pieges-anti-nuisibles', 'Trappole anti-parassiti', 'pieges-anti-nuisibles', 'produits-phytosanitaires', 2, 'it'),
('protections-pour-cultures', 'Protezioni per colture', 'protections-pour-cultures', 'produits-phytosanitaires', 2, 'it'),

-- Allevamento & cura degli animali
('elevage-soins-animaux', 'Allevamento & cura degli animali', 'elevage-soins-animaux', 'agriculture-agroalimentaire', 1, 'it'),
('aliments-pour-betail', 'Alimenti per bestiame', 'aliments-pour-betail', 'elevage-soins-animaux', 2, 'it'),
('aliments-pour-volailles', 'Alimenti per pollame', 'aliments-pour-volailles', 'elevage-soins-animaux', 2, 'it'),
('aliments-pour-ovins-caprins', 'Alimenti per ovini e caprini', 'aliments-pour-ovins-caprins', 'elevage-soins-animaux', 2, 'it'),
('complements-nutritionnels', 'Integratori nutrizionali', 'complements-nutritionnels', 'elevage-soins-animaux', 2, 'it'),
('produits-veterinaires', 'Prodotti veterinari', 'produits-veterinaires', 'elevage-soins-animaux', 2, 'it'),
('mangeoires', 'Mangimi', 'mangeoires', 'elevage-soins-animaux', 2, 'it'),
('abreuvoirs', 'Abbeveratoi', 'abreuvoirs', 'elevage-soins-animaux', 2, 'it'),
('clotures-electriques', 'Recinzioni elettriche', 'clotures-electriques', 'elevage-soins-animaux', 2, 'it'),
('parcs-cages', 'Parchi & gabbie', 'parcs-cages', 'elevage-soins-animaux', 2, 'it'),

-- Attrezzature stalle & strutture
('equipements-stables-structures', 'Attrezzature stalle & strutture', 'equipements-stables-structures', 'agriculture-agroalimentaire', 1, 'it'),
('boxes-pour-animaux', 'Box per animali', 'boxes-pour-animaux', 'equipements-stables-structures', 2, 'it'),
('clotures-agricoles', 'Recinzioni agricole', 'clotures-agricoles', 'equipements-stables-structures', 2, 'it'),
('portails-agricoles', 'Cancelli agricoli', 'portails-agricoles', 'equipements-stables-structures', 2, 'it'),
('abris-pour-animaux', 'Rifugi per animali', 'abris-pour-animaux', 'equipements-stables-structures', 2, 'it'),
('chenils-boxes', 'Canili & box', 'chenils-boxes', 'equipements-stables-structures', 2, 'it'),
('patures-clotures', 'Pascoli & recinzioni', 'patures-clotures', 'equipements-stables-structures', 2, 'it'),
('granges-batiments', 'Fienili & edifici', 'granges-batiments', 'equipements-stables-structures', 2, 'it'),

-- Ricambi & componenti
('pieces-detachees-equipements', 'Ricambi & componenti', 'pieces-detachees-equipements', 'agriculture-agroalimentaire', 1, 'it'),
('pieces-tracteurs', 'Ricambi trattori', 'pieces-tracteurs', 'pieces-detachees-equipements', 2, 'it'),
('pieces-moissonneuses', 'Ricambi mietitrebbie', 'pieces-moissonneuses', 'pieces-detachees-equipements', 2, 'it'),
('pieces-motoculteurs', 'Ricambi motozappe', 'pieces-motoculteurs', 'pieces-detachees-equipements', 2, 'it'),
('pieces-broyeurs', 'Ricambi trituratori', 'pieces-broyeurs', 'pieces-detachees-equipements', 2, 'it'),
('pieces-epandeurs', 'Ricambi spandiconcime', 'pieces-epandeurs', 'pieces-detachees-equipements', 2, 'it'),
('filtres-agricoles', 'Filtri agricoli', 'filtres-agricoles', 'pieces-detachees-equipements', 2, 'it'),
('courroies-agricoles', 'Cinghie agricole', 'courroies-agricoles', 'pieces-detachees-equipements', 2, 'it'),
('chaines-agricoles', 'Catene agricole', 'chaines-agricoles', 'pieces-detachees-equipements', 2, 'it'),
('pneus-agricoles', 'Pneumatici agricoli', 'pneus-agricoles', 'pieces-detachees-equipements', 2, 'it'),

-- Trasporto & logistica
('transport-logistique-agricole', 'Trasporto & logistica', 'transport-logistique-agricole', 'agriculture-agroalimentaire', 1, 'it'),
('vehicules-utilitaires-agricoles', 'Veicoli utilitari agricoli', 'vehicules-utilitaires-agricoles', 'transport-logistique-agricole', 2, 'it'),
('chariots-elevateurs', 'Carrelli elevatori', 'chariots-elevateurs', 'transport-logistique-agricole', 2, 'it'),
('transpalettes', 'Transpallet', 'transpalettes', 'transport-logistique-agricole', 2, 'it'),
('diables', 'Carrelli a mano', 'diables', 'transport-logistique-agricole', 2, 'it'),
('roues-de-manutention', 'Ruote per movimentazione', 'roues-de-manutention', 'transport-logistique-agricole', 2, 'it'),
('benne-a-grain', 'Benne per granaglie', 'benne-a-grain', 'transport-logistique-agricole', 2, 'it'),
('souleveurs', 'Sollevatori', 'souleveurs', 'transport-logistique-agricole', 2, 'it'),
('gerbeurs', 'Carrelli compattatori', 'gerbeurs', 'transport-logistique-agricole', 2, 'it'),
('plateformes-de-travail', 'Piattaforme di lavoro', 'plateformes-de-travail', 'transport-logistique-agricole', 2, 'it'),
('echelles-agricoles', 'Scale agricole', 'echelles-agricoles', 'transport-logistique-agricole', 2, 'it'),
('plateaux', 'Piattaforme', 'plateaux', 'transport-logistique-agricole', 2, 'it'),
('caisses', 'Casse', 'caisses', 'transport-logistique-agricole', 2, 'it'),
('palettes', 'Pallet', 'palettes', 'transport-logistique-agricole', 2, 'it'),
('conteneurs', 'Container', 'conteneurs', 'transport-logistique-agricole', 2, 'it'),
('charrettes-agricoles', 'Carretti agricoli', 'charrettes-agricoles', 'transport-logistique-agricole', 2, 'it'),
('bennes-basculantes', 'Benne basculanti', 'bennes-basculantes', 'transport-logistique-agricole', 2, 'it'),

-- Attrezzature per arnie & apicoltura
('equipement-ruchers-apiculture', 'Attrezzature per arnie & apicoltura', 'equipement-ruchers-apiculture', 'agriculture-agroalimentaire', 1, 'it'),
('ruches', 'Arnie', 'ruches', 'equipement-ruchers-apiculture', 2, 'it'),
('cadres-de-ruche', 'Telaini per arnie', 'cadres-de-ruche', 'equipement-ruchers-apiculture', 2, 'it'),
('cire-gaufree', 'Cera goffrata', 'cire-gaufree', 'equipement-ruchers-apiculture', 2, 'it'),
('enfumoirs', 'Fumatori', 'enfumoirs', 'equipement-ruchers-apiculture', 2, 'it'),
('extracteurs-de-miel', 'Estrattori di miele', 'extracteurs-de-miel', 'equipement-ruchers-apiculture', 2, 'it'),
('equipements-apiculteurs', 'Attrezzature per apicoltori', 'equipements-apiculteurs', 'equipement-ruchers-apiculture', 2, 'it'),
('pieges-a-essaims', 'Trappole per sciami', 'pieges-a-essaims', 'equipement-ruchers-apiculture', 2, 'it'),

-- Strumenti e prodotti per controllo sanitario
('controle-sanitaire-outils-produits', 'Strumenti e prodotti per controllo sanitario', 'controle-sanitaire-outils-produits', 'agriculture-agroalimentaire', 1, 'it'),
('desinfectants-agricoles', 'Disinfettanti agricoli', 'desinfectants-agricoles', 'controle-sanitaire-outils-produits', 2, 'it'),
('pulverisateurs-sanitaires', 'Pompe a spruzzo sanitarie', 'pulverisateurs-sanitaires', 'controle-sanitaire-outils-produits', 2, 'it'),
('pieges-a-insectes', 'Trappole per insetti', 'pieges-a-insectes', 'controle-sanitaire-outils-produits', 2, 'it'),
('filets-anti-oiseaux', 'Reti anti-uccelli', 'filets-anti-oiseaux', 'controle-sanitaire-outils-produits', 2, 'it'),
('systemes-protection-cultures', 'Sistemi di protezione delle colture', 'systemes-protection-cultures', 'controle-sanitaire-outils-produits', 2, 'it'),
('stations-meteo-agricoles', 'Stazioni meteorologiche agricole', 'stations-meteo-agricoles', 'controle-sanitaire-outils-produits', 2, 'it'),

-- Accessori & consumabili
('accessoires-consommables', 'Accessori & consumabili', 'accessoires-consommables', 'agriculture-agroalimentaire', 1, 'it'),
('ficelles-agricoles', 'Corde agricole', 'ficelles-agricoles', 'accessoires-consommables', 2, 'it'),
('cordages', 'Cavi', 'cordages', 'accessoires-consommables', 2, 'it'),
('sangles', 'Cinghie', 'sangles', 'accessoires-consommables', 2, 'it'),
('attaches-pour-plants', 'Fissaggi per piante', 'attaches-pour-plants', 'accessoires-consommables', 2, 'it'),
('boites-d-emballage', 'Scatole per imballaggio', 'boites-d-emballage', 'accessoires-consommables', 2, 'it'),
('sacs-alimentaires', 'Sacchetti alimentari', 'sacs-alimentaires', 'accessoires-consommables', 2, 'it'),
('etiquettes-agricoles', 'Etichette agricole', 'etiquettes-agricoles', 'accessoires-consommables', 2, 'it');