*** Begin Patch

-- French
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('mode-et-accessoires', 'Mode & Accessoires', 'mode-et-accessoires', NULL, 0, 'fr');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('chaussures', 'Chaussures', 'chaussures', 'mode-et-accessoires', 1, 'fr'),
('bijoux-montres', 'Bijoux & Montres', 'bijoux-montres', 'mode-et-accessoires', 1, 'fr'),
('sacs-main', 'Sacs à main', 'sacs-main', 'mode-et-accessoires', 1, 'fr'),
('accessoires-mode', 'Accessoires de mode', 'accessoires-mode', 'mode-et-accessoires', 1, 'fr');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('baskets', 'Baskets', 'baskets', 'chaussures', 2, 'fr'),
('sneakers', 'Sneakers', 'sneakers', 'chaussures', 2, 'fr'),
('running', 'Running', 'running', 'chaussures', 2, 'fr'),
('lifestyle', 'Lifestyle', 'lifestyle', 'chaussures', 2, 'fr'),
('montantes', 'Montantes', 'montantes', 'chaussures', 2, 'fr'),
('basses', 'Basses', 'basses', 'chaussures', 2, 'fr'),
('slip-on', 'Slip-on', 'slip-on', 'chaussures', 2, 'fr'),
('derbies', 'Derbies', 'derbies', 'chaussures', 2, 'fr'),
('richelieu', 'Richelieu', 'richelieu', 'chaussures', 2, 'fr'),
('mocassins', 'Mocassins', 'mocassins', 'chaussures', 2, 'fr'),
('escarpins', 'Escarpins', 'escarpins', 'chaussures', 2, 'fr'),
('ballerines', 'Ballerines', 'ballerines', 'chaussures', 2, 'fr'),
('salomes', 'Salomés', 'salomes', 'chaussures', 2, 'fr'),
('mules', 'Mules', 'mules', 'chaussures', 2, 'fr'),
('chelsea', 'Chelsea', 'chelsea', 'chaussures', 2, 'fr'),
('monk', 'Monk', 'monk', 'chaussures', 2, 'fr'),
('bottes', 'Bottes', 'bottes', 'chaussures', 2, 'fr'),
('bottines', 'Bottines', 'bottines', 'chaussures', 2, 'fr'),
('cuissardes', 'Cuissardes', 'cuissardes', 'chaussures', 2, 'fr'),
('cavalieres', 'Cavalières', 'cavalieres', 'chaussures', 2, 'fr'),
('pluie', 'Pluie', 'pluie', 'chaussures', 2, 'fr'),
('fourrees', 'Fourrées', 'fourrees', 'chaussures', 2, 'fr'),
('motardes', 'Motardes', 'motardes', 'chaussures', 2, 'fr'),
('sandales-plates', 'Sandales plates', 'sandales-plates', 'chaussures', 2, 'fr'),
('sandales-compensees', 'Sandales compensées', 'sandales-compensees', 'chaussures', 2, 'fr'),
('tongs', 'Tongs', 'tongs', 'chaussures', 2, 'fr'),
('nu-pieds', 'Nu-pieds', 'nu-pieds', 'chaussures', 2, 'fr'),
('claquettes', 'Claquettes', 'claquettes', 'chaussures', 2, 'fr'),
('espadrilles', 'Espadrilles', 'espadrilles', 'chaussures', 2, 'fr'),
('football', 'Football', 'football', 'chaussures', 2, 'fr'),
('futsal', 'Futsal', 'futsal', 'chaussures', 2, 'fr'),
('basketball', 'Basketball', 'basketball', 'chaussures', 2, 'fr'),
('tennis-chaussures', 'Tennis', 'tennis-chaussures', 'chaussures', 2, 'fr'),
('golf-chaussures', 'Golf', 'golf-chaussures', 'chaussures', 2, 'fr'),
('running-trail', 'Running Trail', 'running-trail', 'chaussures', 2, 'fr'),
('skateboard', 'Skateboard', 'skateboard', 'chaussures', 2, 'fr'),
('fitness', 'Fitness', 'fitness', 'chaussures', 2, 'fr'),
('premiers-pas', 'Premiers pas', 'premiers-pas', 'chaussures', 2, 'fr'),
('ecole', 'École', 'ecole', 'chaussures', 2, 'fr'),
('lumineuses-led', 'Lumineuses LED', 'lumineuses-led', 'chaussures', 2, 'fr'),
('automatique', 'Automatique', 'automatique', 'bijoux-montres', 2, 'fr'),
('quartz', 'Quartz', 'quartz', 'bijoux-montres', 2, 'fr'),
('connectee', 'Connectée', 'connectee', 'bijoux-montres', 2, 'fr'),
('chronographe', 'Chronographe', 'chronographe', 'bijoux-montres', 2, 'fr'),
('plongee', 'Plongée', 'plongee', 'bijoux-montres', 2, 'fr'),
('sport-gps', 'Sport GPS', 'sport-gps', 'bijoux-montres', 2, 'fr'),
('bracelet-cuir', 'Bracelet cuir', 'bracelet-cuir', 'bijoux-montres', 2, 'fr'),
('bracelet-acier', 'Bracelet acier', 'bracelet-acier', 'bijoux-montres', 2, 'fr'),
('bracelet-silicone', 'Bracelet silicone', 'bracelet-silicone', 'bijoux-montres', 2, 'fr'),
('chaines-fines', 'Chaînes fines', 'chaines-fines', 'bijoux-montres', 2, 'fr'),
('ras-de-cou', 'Ras de cou', 'ras-de-cou', 'bijoux-montres', 2, 'fr'),
('sautoirs', 'Sautoirs', 'sautoirs', 'bijoux-montres', 2, 'fr'),
('multi-rangs', 'Multi-rangs', 'multi-rangs', 'bijoux-montres', 2, 'fr'),
('medailles', 'Médailles', 'medailles', 'bijoux-montres', 2, 'fr'),
('croix', 'Croix', 'croix', 'bijoux-montres', 2, 'fr'),
('initiales', 'Initiales', 'initiales', 'bijoux-montres', 2, 'fr'),
('pierres-precieuses', 'Pierres précieuses', 'pierres-precieuses', 'bijoux-montres', 2, 'fr'),
('pierres-semi-precieuses', 'Pierres semi-précieuses', 'pierres-semi-precieuses', 'bijoux-montres', 2, 'fr'),
('perles', 'Perles', 'perles', 'bijoux-montres', 2, 'fr'),
('or', 'Or', 'or', 'bijoux-montres', 2, 'fr'),
('argent', 'Argent', 'argent', 'bijoux-montres', 2, 'fr'),
('vermeil', 'Vermeil', 'vermeil', 'bijoux-montres', 2, 'fr'),
('puces', 'Puces', 'puces', 'bijoux-montres', 2, 'fr'),
('creoles', 'Créoles', 'creoles', 'bijoux-montres', 2, 'fr'),
('pendantes', 'Pendantes', 'pendantes', 'bijoux-montres', 2, 'fr'),
('clips-boucles', 'Clips boucles', 'clips-boucles', 'bijoux-montres', 2, 'fr'),
('bracelets-chaine', 'Bracelets chaîne', 'bracelets-chaine', 'bijoux-montres', 2, 'fr'),
('gourmette', 'Gourmette', 'gourmette', 'bijoux-montres', 2, 'fr'),
('joncs', 'Joncs', 'joncs', 'bijoux-montres', 2, 'fr'),
('manchettes', 'Manchettes', 'manchettes', 'bijoux-montres', 2, 'fr'),
('tennis-bijoux', 'Tennis bijoux', 'tennis-bijoux', 'bijoux-montres', 2, 'fr'),
('perles-bracelets', 'Perles bracelets', 'perles-bracelets', 'bijoux-montres', 2, 'fr'),
('cuir-tresse', 'Cuir tressé', 'cuir-tresse', 'bijoux-montres', 2, 'fr'),
('charms', 'Charms', 'charms', 'bijoux-montres', 2, 'fr'),
('alliance', 'Alliance', 'alliance', 'bijoux-montres', 2, 'fr'),
('solitaire', 'Solitaire', 'solitaire', 'bijoux-montres', 2, 'fr'),
('chevaliere', 'Chevalière', 'chevaliere', 'bijoux-montres', 2, 'fr'),
('empilables', 'Empilables', 'empilables', 'bijoux-montres', 2, 'fr');

-- Level 3 - Sacs à main
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('sacs-a-bandouliere', 'Sacs à bandoulière', 'sacs-a-bandouliere', 'sacs-main', 3, 'fr'),
('sacs-a-dos-mode', 'Sacs à dos mode', 'sacs-a-dos-mode', 'sacs-main', 3, 'fr'),
('sacs-de-voyage', 'Sacs de voyage', 'sacs-de-voyage', 'sacs-main', 3, 'fr'),
('porte-documents', 'Porte-documents', 'porte-documents', 'sacs-main', 3, 'fr'),
('sacs-de-sport', 'Sacs de sport', 'sacs-de-sport', 'sacs-main', 3, 'fr'),
('sacs-de-plage', 'Sacs de plage', 'sacs-de-plage', 'sacs-main', 3, 'fr'),
('pochettes', 'Pochettes', 'pochettes', 'sacs-main', 3, 'fr'),
('cartables', 'Cartables', 'cartables', 'sacs-main', 3, 'fr'),
('sacs-a-main-luxe', 'Sacs à main luxe', 'sacs-a-main-luxe', 'sacs-main', 3, 'fr');

-- Level 3 - Accessoires de mode
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('ceintures', 'Ceintures', 'ceintures', 'accessoires-mode', 3, 'fr'),
('portefeuilles', 'Portefeuilles', 'portefeuilles', 'accessoires-mode', 3, 'fr'),
('lunettes-de-soleil', 'Lunettes de soleil', 'lunettes-de-soleil', 'accessoires-mode', 3, 'fr'),
('montres', 'Montres', 'montres', 'accessoires-mode', 3, 'fr'),
('bijoux', 'Bijoux', 'bijoux', 'accessoires-mode', 3, 'fr'),
('cravates', 'Cravates', 'cravates', 'accessoires-mode', 3, 'fr'),
('echarpes', 'Écharpes', 'echarpes', 'accessoires-mode', 3, 'fr'),
('chapeaux', 'Chapeaux', 'chapeaux', 'accessoires-mode', 3, 'fr'),
('casquettes', 'Casquettes', 'casquettes', 'accessoires-mode', 3, 'fr'),
('gants-mode', 'Gants', 'gants-mode', 'accessoires-mode', 3, 'fr');

-- Arabic
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('mode-et-accessoires', 'الموضة والإكسسوارات', 'mode-et-accessoires', NULL, 0, 'ar');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('chaussures', 'الأحذية', 'chaussures', 'mode-et-accessoires', 1, 'ar'),
('bijoux-montres', 'المجوهرات والساعات', 'bijoux-montres', 'mode-et-accessoires', 1, 'ar'),
('sacs-main', 'حقائب اليد', 'sacs-main', 'mode-et-accessoires', 1, 'ar'),
('accessoires-mode', 'إكسسوارات الموضة', 'accessoires-mode', 'mode-et-accessoires', 1, 'ar');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('baskets', 'أحذية رياضية', 'baskets', 'chaussures', 2, 'ar'),
('sneakers', 'سنيكرز', 'sneakers', 'chaussures', 2, 'ar'),
('running', 'الجري', 'running', 'chaussures', 2, 'ar'),
('lifestyle', 'لايف ستايل', 'lifestyle', 'chaussures', 2, 'ar'),
('montantes', 'مرتفعة', 'montantes', 'chaussures', 2, 'ar'),
('basses', 'منخفضة', 'basses', 'chaussures', 2, 'ar'),
('slip-on', 'سهل الارتداء', 'slip-on', 'chaussures', 2, 'ar'),
('derbies', 'ديربي', 'derbies', 'chaussures', 2, 'ar'),
('richelieu', 'أكسفورد', 'richelieu', 'chaussures', 2, 'ar'),
('mocassins', 'موكاسين', 'mocassins', 'chaussures', 2, 'ar'),
('escarpins', 'كعب عالي', 'escarpins', 'chaussures', 2, 'ar'),
('ballerines', 'باليرينا', 'ballerines', 'chaussures', 2, 'ar'),
('salomes', 'ماري جين', 'salomes', 'chaussures', 2, 'ar'),
('mules', 'ميول', 'mules', 'chaussures', 2, 'ar'),
('chelsea', 'تشيلسي', 'chelsea', 'chaussures', 2, 'ar'),
('monk', 'راهب', 'monk', 'chaussures', 2, 'ar'),
('bottes', 'أحذية طويلة', 'bottes', 'chaussures', 2, 'ar'),
('bottines', 'أحذية قصيرة', 'bottines', 'chaussures', 2, 'ar'),
('cuissardes', 'أحذية فوق الركبة', 'cuissardes', 'chaussures', 2, 'ar'),
('cavalieres', 'أحذية ركوب', 'cavalieres', 'chaussures', 2, 'ar'),
('pluie', 'مطر', 'pluie', 'chaussures', 2, 'ar'),
('fourrees', 'مبطنة بالفرو', 'fourrees', 'chaussures', 2, 'ar'),
('motardes', 'أحذية دراجات نارية', 'motardes', 'chaussures', 2, 'ar'),
('sandales-plates', 'صنادل مسطحة', 'sandales-plates', 'chaussures', 2, 'ar'),
('sandales-compensees', 'صنادل بكعب مرتفع', 'sandales-compensees', 'chaussures', 2, 'ar'),
('tongs', 'شباشب', 'tongs', 'chaussures', 2, 'ar'),
('nu-pieds', 'صنادل مفتوحة', 'nu-pieds', 'chaussures', 2, 'ar'),
('claquettes', 'صنادل رياضية', 'claquettes', 'chaussures', 2, 'ar'),
('espadrilles', 'إسبادريل', 'espadrilles', 'chaussures', 2, 'ar'),
('football', 'كرة قدم', 'football', 'chaussures', 2, 'ar'),
('futsal', 'فوتسال', 'futsal', 'chaussures', 2, 'ar'),
('basketball', 'كرة سلة', 'basketball', 'chaussures', 2, 'ar'),
('tennis-chaussures', 'تنس', 'tennis-chaussures', 'chaussures', 2, 'ar'),
('golf-chaussures', 'غولف', 'golf-chaussures', 'chaussures', 2, 'ar'),
('running-trail', 'جري تريل', 'running-trail', 'chaussures', 2, 'ar'),
('skateboard', 'لوح تزلج', 'skateboard', 'chaussures', 2, 'ar'),
('fitness', 'لياقة بدنية', 'fitness', 'chaussures', 2, 'ar'),
('premiers-pas', 'أولى خطوات', 'premiers-pas', 'chaussures', 2, 'ar'),
('ecole', 'مدرسة', 'ecole', 'chaussures', 2, 'ar'),
('lumineuses-led', 'مضيئة LED', 'lumineuses-led', 'chaussures', 2, 'ar'),
('automatique', 'أوتوماتيك', 'automatique', 'bijoux-montres', 2, 'ar'),
('quartz', 'كوارتز', 'quartz', 'bijoux-montres', 2, 'ar'),
('connectee', 'ذكية', 'connectee', 'bijoux-montres', 2, 'ar'),
('chronographe', 'كرونوغراف', 'chronographe', 'bijoux-montres', 2, 'ar'),
('plongee', 'غوص', 'plongee', 'bijoux-montres', 2, 'ar'),
('sport-gps', 'رياضة GPS', 'sport-gps', 'bijoux-montres', 2, 'ar'),
('bracelet-cuir', 'سوار جلد', 'bracelet-cuir', 'bijoux-montres', 2, 'ar'),
('bracelet-acier', 'سوار فولاذ', 'bracelet-acier', 'bijoux-montres', 2, 'ar'),
('bracelet-silicone', 'سوار سيليكون', 'bracelet-silicone', 'bijoux-montres', 2, 'ar'),
('chaines-fines', 'سلاسل رفيعة', 'chaines-fines', 'bijoux-montres', 2, 'ar'),
('ras-de-cou', 'قصيرة', 'ras-de-cou', 'bijoux-montres', 2, 'ar'),
('sautoirs', 'طويلة', 'sautoirs', 'bijoux-montres', 2, 'ar'),
('multi-rangs', 'متعددة الطبقات', 'multi-rangs', 'bijoux-montres', 2, 'ar'),
('medailles', 'ميداليات', 'medailles', 'bijoux-montres', 2, 'ar'),
('croix', 'صلبان', 'croix', 'bijoux-montres', 2, 'ar'),
('initiales', 'أحرف أولى', 'initiales', 'bijoux-montres', 2, 'ar'),
('pierres-precieuses', 'أحجار كريمة', 'pierres-precieuses', 'bijoux-montres', 2, 'ar'),
('pierres-semi-precieuses', 'أحجار شبه كريمة', 'pierres-semi-precieuses', 'bijoux-montres', 2, 'ar'),
('perles', 'لؤلؤ', 'perles', 'bijoux-montres', 2, 'ar'),
('or', 'ذهب', 'or', 'bijoux-montres', 2, 'ar'),
('argent', 'فضة', 'argent', 'bijoux-montres', 2, 'ar'),
('vermeil', 'فيرمي', 'vermeil', 'bijoux-montres', 2, 'ar'),
('puces', 'صغيرة', 'puces', 'bijoux-montres', 2, 'ar'),
('creoles', 'دائري', 'creoles', 'bijoux-montres', 2, 'ar'),
('pendantes', 'متدلية', 'pendantes', 'bijoux-montres', 2, 'ar'),
('clips-boucles', 'كليب', 'clips-boucles', 'bijoux-montres', 2, 'ar'),
('bracelets-chaine', 'سلاسل', 'bracelets-chaine', 'bijoux-montres', 2, 'ar'),
('gourmette', 'سلسلة مميزة', 'gourmette', 'bijoux-montres', 2, 'ar'),
('joncs', 'صلب', 'joncs', 'bijoux-montres', 2, 'ar'),
('manchettes', 'عريض', 'manchettes', 'bijoux-montres', 2, 'ar'),
('tennis-bijoux', 'تنس', 'tennis-bijoux', 'bijoux-montres', 2, 'ar'),
('perles-bracelets', 'لؤلؤ', 'perles-bracelets', 'bijoux-montres', 2, 'ar'),
('cuir-tresse', 'جلد مضفر', 'cuir-tresse', 'bijoux-montres', 2, 'ar'),
('charms', 'تعويذات', 'charms', 'bijoux-montres', 2, 'ar'),
('alliance', 'زواج', 'alliance', 'bijoux-montres', 2, 'ar'),
('solitaire', 'وحيد', 'solitaire', 'bijoux-montres', 2, 'ar'),
('chevaliere', 'خاتم خاتم', 'chevaliere', 'bijoux-montres', 2, 'ar'),
('empilables', 'قابل للتراكم', 'empilables', 'bijoux-montres', 2, 'ar');

-- Level 3 - حقائب اليد (Sacs à main)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('sacs-a-bandouliere', 'حقائب كتف', 'sacs-a-bandouliere', 'sacs-main', 3, 'ar'),
('sacs-a-dos-mode', 'حقائب ظهر موضة', 'sacs-a-dos-mode', 'sacs-main', 3, 'ar'),
('sacs-de-voyage', 'حقائب سفر', 'sacs-de-voyage', 'sacs-main', 3, 'ar'),
('porte-documents', 'حقائب وثائق', 'porte-documents', 'sacs-main', 3, 'ar'),
('sacs-de-sport', 'حقائب رياضية', 'sacs-de-sport', 'sacs-main', 3, 'ar'),
('sacs-de-plage', 'حقائب شاطئ', 'sacs-de-plage', 'sacs-main', 3, 'ar'),
('pochettes', 'حقائب صغيرة', 'pochettes', 'sacs-main', 3, 'ar'),
('cartables', 'حقائب مدرسية', 'cartables', 'sacs-main', 3, 'ar'),
('sacs-a-main-luxe', 'حقائب يد فاخرة', 'sacs-a-main-luxe', 'sacs-main', 3, 'ar');

-- Level 3 - إكسسوارات الموضة (Accessoires de mode)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('ceintures', 'أحزمة', 'ceintures', 'accessoires-mode', 3, 'ar'),
('portefeuilles', 'محافظ', 'portefeuilles', 'accessoires-mode', 3, 'ar'),
('lunettes-de-soleil', 'نظارات شمسية', 'lunettes-de-soleil', 'accessoires-mode', 3, 'ar'),
('montres', 'ساعات', 'montres', 'accessoires-mode', 3, 'ar'),
('bijoux', 'مجوهرات', 'bijoux', 'accessoires-mode', 3, 'ar'),
('cravates', 'ربطات عنق', 'cravates', 'accessoires-mode', 3, 'ar'),
('echarpes', 'وشاحات', 'echarpes', 'accessoires-mode', 3, 'ar'),
('chapeaux', 'قبعات', 'chapeaux', 'accessoires-mode', 3, 'ar'),
('casquettes', 'كابات', 'casquettes', 'accessoires-mode', 3, 'ar'),
('gants-mode', 'قفازات', 'gants-mode', 'accessoires-mode', 3, 'ar');

-- English
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('mode-et-accessoires', 'Fashion & Accessories', 'mode-et-accessoires', NULL, 0, 'en');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('chaussures', 'Shoes', 'chaussures', 'mode-et-accessoires', 1, 'en'),
('bijoux-montres', 'Jewelry & Watches', 'bijoux-montres', 'mode-et-accessoires', 1, 'en'),
('sacs-main', 'Handbags', 'sacs-main', 'mode-et-accessoires', 1, 'en'),
('accessoires-mode', 'Fashion Accessories', 'accessoires-mode', 'mode-et-accessoires', 1, 'en');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('baskets', 'Trainers', 'baskets', 'chaussures', 2, 'en'),
('sneakers', 'Sneakers', 'sneakers', 'chaussures', 2, 'en'),
('running', 'Running', 'running', 'chaussures', 2, 'en'),
('lifestyle', 'Lifestyle', 'lifestyle', 'chaussures', 2, 'en'),
('montantes', 'High-top', 'montantes', 'chaussures', 2, 'en'),
('basses', 'Low-top', 'basses', 'chaussures', 2, 'en'),
('slip-on', 'Slip-ons', 'slip-on', 'chaussures', 2, 'en'),
('derbies', 'Derby shoes', 'derbies', 'chaussures', 2, 'en'),
('richelieu', 'Oxford shoes', 'richelieu', 'chaussures', 2, 'en'),
('mocassins', 'Loafers', 'mocassins', 'chaussures', 2, 'en'),
('escarpins', 'Pumps', 'escarpins', 'chaussures', 2, 'en'),
('ballerines', 'Ballet flats', 'ballerines', 'chaussures', 2, 'en'),
('salomes', 'Mary Janes', 'salomes', 'chaussures', 2, 'en'),
('mules', 'Mules', 'mules', 'chaussures', 2, 'en'),
('chelsea', 'Chelsea boots', 'chelsea', 'chaussures', 2, 'en'),
('monk', 'Monk strap shoes', 'monk', 'chaussures', 2, 'en'),
('bottes', 'Boots', 'bottes', 'chaussures', 2, 'en'),
('bottines', 'Ankle boots', 'bottines', 'chaussures', 2, 'en'),
('cuissardes', 'Thigh-high boots', 'cuissardes', 'chaussures', 2, 'en'),
('cavalieres', 'Riding boots', 'cavalieres', 'chaussures', 2, 'en'),
('pluie', 'Rain boots', 'pluie', 'chaussures', 2, 'en'),
('fourrees', 'Fur-lined boots', 'fourrees', 'chaussures', 2, 'en'),
('motardes', 'Biker boots', 'motardes', 'chaussures', 2, 'en'),
('sandales-plates', 'Flat sandals', 'sandales-plates', 'chaussures', 2, 'en'),
('sandales-compensees', 'Wedge sandals', 'sandales-compensees', 'chaussures', 2, 'en'),
('tongs', 'Flip-flops', 'tongs', 'chaussures', 2, 'en'),
('nu-pieds', 'Barefoot sandals', 'nu-pieds', 'chaussures', 2, 'en'),
('claquettes', 'Slides', 'claquettes', 'chaussures', 2, 'en'),
('espadrilles', 'Espadrilles', 'espadrilles', 'chaussures', 2, 'en'),
('football', 'Football', 'football', 'chaussures', 2, 'en'),
('futsal', 'Futsal', 'futsal', 'chaussures', 2, 'en'),
('basketball', 'Basketball', 'basketball', 'chaussures', 2, 'en'),
('tennis-chaussures', 'Tennis', 'tennis-chaussures', 'chaussures', 2, 'en'),
('golf-chaussures', 'Golf', 'golf-chaussures', 'chaussures', 2, 'en'),
('running-trail', 'Trail running', 'running-trail', 'chaussures', 2, 'en'),
('skateboard', 'Skateboard', 'skateboard', 'chaussures', 2, 'en'),
('fitness', 'Fitness', 'fitness', 'chaussures', 2, 'en'),
('premiers-pas', 'First steps', 'premiers-pas', 'chaussures', 2, 'en'),
('ecole', 'School', 'ecole', 'chaussures', 2, 'en'),
('lumineuses-led', 'Light-up LED', 'lumineuses-led', 'chaussures', 2, 'en'),
('automatique', 'Automatic', 'automatique', 'bijoux-montres', 2, 'en'),
('quartz', 'Quartz', 'quartz', 'bijoux-montres', 2, 'en'),
('connectee', 'Smartwatch', 'connectee', 'bijoux-montres', 2, 'en'),
('chronographe', 'Chronograph', 'chronographe', 'bijoux-montres', 2, 'en'),
('plongee', 'Diving', 'plongee', 'bijoux-montres', 2, 'en'),
('sport-gps', 'Sports GPS', 'sport-gps', 'bijoux-montres', 2, 'en'),
('bracelet-cuir', 'Leather strap', 'bracelet-cuir', 'bijoux-montres', 2, 'en'),
('bracelet-acier', 'Steel strap', 'bracelet-acier', 'bijoux-montres', 2, 'en'),
('bracelet-silicone', 'Silicone strap', 'bracelet-silicone', 'bijoux-montres', 2, 'en'),
('chaines-fines', 'Fine chains', 'chaines-fines', 'bijoux-montres', 2, 'en'),
('ras-de-cou', 'Choker', 'ras-de-cou', 'bijoux-montres', 2, 'en'),
('sautoirs', 'Long necklaces', 'sautoirs', 'bijoux-montres', 2, 'en'),
('multi-rangs', 'Multi-strand', 'multi-rangs', 'bijoux-montres', 2, 'en'),
('medailles', 'Medallions', 'medailles', 'bijoux-montres', 2, 'en'),
('croix', 'Crosses', 'croix', 'bijoux-montres', 2, 'en'),
('initiales', 'Initials', 'initiales', 'bijoux-montres', 2, 'en'),
('pierres-precieuses', 'Precious stones', 'pierres-precieuses', 'bijoux-montres', 2, 'en'),
('pierres-semi-precieuses', 'Semi-precious stones', 'pierres-semi-precieuses', 'bijoux-montres', 2, 'en'),
('perles', 'Pearls', 'perles', 'bijoux-montres', 2, 'en'),
('or', 'Gold', 'or', 'bijoux-montres', 2, 'en'),
('argent', 'Silver', 'argent', 'bijoux-montres', 2, 'en'),
('vermeil', 'Vermeil', 'vermeil', 'bijoux-montres', 2, 'en'),
('puces', 'Studs', 'puces', 'bijoux-montres', 2, 'en'),
('creoles', 'Hoops', 'creoles', 'bijoux-montres', 2, 'en'),
('pendantes', 'Drop earrings', 'pendantes', 'bijoux-montres', 2, 'en'),
('clips-boucles', 'Clip-ons', 'clips-boucles', 'bijoux-montres', 2, 'en'),
('bracelets-chaine', 'Chain bracelets', 'bracelets-chaine', 'bijoux-montres', 2, 'en'),
('gourmette', 'ID bracelets', 'gourmette', 'bijoux-montres', 2, 'en'),
('joncs', 'Bangles', 'joncs', 'bijoux-montres', 2, 'en'),
('manchettes', 'Cuffs', 'manchettes', 'bijoux-montres', 2, 'en'),
('tennis-bijoux', 'Tennis bracelets', 'tennis-bijoux', 'bijoux-montres', 2, 'en'),
('perles-bracelets', 'Pearl bracelets', 'perles-bracelets', 'bijoux-montres', 2, 'en'),
('cuir-tresse', 'Braided leather', 'cuir-tresse', 'bijoux-montres', 2, 'en'),
('charms', 'Charms', 'charms', 'bijoux-montres', 2, 'en'),
('alliance', 'Wedding band', 'alliance', 'bijoux-montres', 2, 'en'),
('solitaire', 'Solitaire', 'solitaire', 'bijoux-montres', 2, 'en'),
('chevaliere', 'Signet ring', 'chevaliere', 'bijoux-montres', 2, 'en'),
('empilables', 'Stackable', 'empilables', 'bijoux-montres', 2, 'en');

-- Level 3 - Handbags
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('sacs-a-bandouliere', 'Shoulder bags', 'sacs-a-bandouliere', 'sacs-main', 3, 'en'),
('sacs-a-dos-mode', 'Fashion backpacks', 'sacs-a-dos-mode', 'sacs-main', 3, 'en'),
('sacs-de-voyage', 'Travel bags', 'sacs-de-voyage', 'sacs-main', 3, 'en'),
('porte-documents', 'Briefcases', 'porte-documents', 'sacs-main', 3, 'en'),
('sacs-de-sport', 'Sports bags', 'sacs-de-sport', 'sacs-main', 3, 'en'),
('sacs-de-plage', 'Beach bags', 'sacs-de-plage', 'sacs-main', 3, 'en'),
('pochettes', 'Clutches', 'pochettes', 'sacs-main', 3, 'en'),
('cartables', 'School bags', 'cartables', 'sacs-main', 3, 'en'),
('sacs-a-main-luxe', 'Luxury handbags', 'sacs-a-main-luxe', 'sacs-main', 3, 'en');

-- Level 3 - Fashion Accessories
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('ceintures', 'Belts', 'ceintures', 'accessoires-mode', 3, 'en'),
('portefeuilles', 'Wallets', 'portefeuilles', 'accessoires-mode', 3, 'en'),
('lunettes-de-soleil', 'Sunglasses', 'lunettes-de-soleil', 'accessoires-mode', 3, 'en'),
('montres', 'Watches', 'montres', 'accessoires-mode', 3, 'en'),
('bijoux', 'Jewelry', 'bijoux', 'accessoires-mode', 3, 'en'),
('cravates', 'Ties', 'cravates', 'accessoires-mode', 3, 'en'),
('echarpes', 'Scarves', 'echarpes', 'accessoires-mode', 3, 'en'),
('chapeaux', 'Hats', 'chapeaux', 'accessoires-mode', 3, 'en'),
('casquettes', 'Caps', 'casquettes', 'accessoires-mode', 3, 'en'),
('gants-mode', 'Gloves', 'gants-mode', 'accessoires-mode', 3, 'en');

-- Spanish
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('mode-et-accessoires', 'Moda y Accesorios', 'mode-et-accessoires', NULL, 0, 'es');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('chaussures', 'Zapatos', 'chaussures', 'mode-et-accessoires', 1, 'es'),
('bijoux-montres', 'Joyas y Relojes', 'bijoux-montres', 'mode-et-accessoires', 1, 'es'),
('sacs-main', 'Bolsos', 'sacs-main', 'mode-et-accessoires', 1, 'es'),
('accessoires-mode', 'Accesorios de moda', 'accessoires-mode', 'mode-et-accessoires', 1, 'es');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('baskets', 'Zapatillas', 'baskets', 'chaussures', 2, 'es'),
('sneakers', 'Zapatillas deportivas', 'sneakers', 'chaussures', 2, 'es'),
('running', 'Running', 'running', 'chaussures', 2, 'es'),
('lifestyle', 'Lifestyle', 'lifestyle', 'chaussures', 2, 'es'),
('montantes', 'Altas', 'montantes', 'chaussures', 2, 'es'),
('basses', 'Bajas', 'basses', 'chaussures', 2, 'es'),
('slip-on', 'Sin cordones', 'slip-on', 'chaussures', 2, 'es'),
('derbies', 'Derby', 'derbies', 'chaussures', 2, 'es'),
('richelieu', 'Oxford', 'richelieu', 'chaussures', 2, 'es'),
('mocassins', 'Mocasines', 'mocassins', 'chaussures', 2, 'es'),
('escarpins', 'Tacones', 'escarpins', 'chaussures', 2, 'es'),
('ballerines', 'Bailarinas', 'ballerines', 'chaussures', 2, 'es'),
('salomes', 'Mary Janes', 'salomes', 'chaussures', 2, 'es'),
('mules', 'Mules', 'mules', 'chaussures', 2, 'es'),
('chelsea', 'Botas Chelsea', 'chelsea', 'chaussures', 2, 'es'),
('monk', 'Monk strap', 'monk', 'chaussures', 2, 'es'),
('bottes', 'Botas', 'bottes', 'chaussures', 2, 'es'),
('bottines', 'Botines', 'bottines', 'chaussures', 2, 'es'),
('cuissardes', 'Botas por encima de la rodilla', 'cuissardes', 'chaussures', 2, 'es'),
('cavalieres', 'Botas de equitación', 'cavalieres', 'chaussures', 2, 'es'),
('pluie', 'Botas de lluvia', 'pluie', 'chaussures', 2, 'es'),
('fourrees', 'Botas forradas', 'fourrees', 'chaussures', 2, 'es'),
('motardes', 'Botas de moto', 'motardes', 'chaussures', 2, 'es'),
('sandales-plates', 'Sandalias planas', 'sandales-plates', 'chaussures', 2, 'es'),
('sandales-compensees', 'Sandalias con cuña', 'sandales-compensees', 'chaussures', 2, 'es'),
('tongs', 'Chanclas', 'tongs', 'chaussures', 2, 'es'),
('nu-pieds', 'Sandalias descalzas', 'nu-pieds', 'chaussures', 2, 'es'),
('claquettes', 'Slides', 'claquettes', 'chaussures', 2, 'es'),
('espadrilles', 'Alpargatas', 'espadrilles', 'chaussures', 2, 'es'),
('football', 'Fútbol', 'football', 'chaussures', 2, 'es'),
('futsal', 'Futsal', 'futsal', 'chaussures', 2, 'es'),
('basketball', 'Baloncesto', 'basketball', 'chaussures', 2, 'es'),
('tennis-chaussures', 'Tenis', 'tennis-chaussures', 'chaussures', 2, 'es'),
('golf-chaussures', 'Golf', 'golf-chaussures', 'chaussures', 2, 'es'),
('running-trail', 'Trail running', 'running-trail', 'chaussures', 2, 'es'),
('skateboard', 'Skateboard', 'skateboard', 'chaussures', 2, 'es'),
('fitness', 'Fitness', 'fitness', 'chaussures', 2, 'es'),
('premiers-pas', 'Primeros pasos', 'premiers-pas', 'chaussures', 2, 'es'),
('ecole', 'Escuela', 'ecole', 'chaussures', 2, 'es'),
('lumineuses-led', 'LED luminosas', 'lumineuses-led', 'chaussures', 2, 'es'),
('automatique', 'Automático', 'automatique', 'bijoux-montres', 2, 'es'),
('quartz', 'Cuarzo', 'quartz', 'bijoux-montres', 2, 'es'),
('connectee', 'Reloj inteligente', 'connectee', 'bijoux-montres', 2, 'es'),
('chronographe', 'Cronógrafo', 'chronographe', 'bijoux-montres', 2, 'es'),
('plongee', 'Buceo', 'plongee', 'bijoux-montres', 2, 'es'),
('sport-gps', 'GPS deportivo', 'sport-gps', 'bijoux-montres', 2, 'es'),
('bracelet-cuir', 'Correa de cuero', 'bracelet-cuir', 'bijoux-montres', 2, 'es'),
('bracelet-acier', 'Correa de acero', 'bracelet-acier', 'bijoux-montres', 2, 'es'),
('bracelet-silicone', 'Correa de silicona', 'bracelet-silicone', 'bijoux-montres', 2, 'es'),
('chaines-fines', 'Cadenas finas', 'chaines-fines', 'bijoux-montres', 2, 'es'),
('ras-de-cou', 'Choker', 'ras-de-cou', 'bijoux-montres', 2, 'es'),
('sautoirs', 'Collares largos', 'sautoirs', 'bijoux-montres', 2, 'es'),
('multi-rangs', 'Multicapas', 'multi-rangs', 'bijoux-montres', 2, 'es'),
('medailles', 'Medallas', 'medailles', 'bijoux-montres', 2, 'es'),
('croix', 'Cruces', 'croix', 'bijoux-montres', 2, 'es'),
('initiales', 'Iniciales', 'initiales', 'bijoux-montres', 2, 'es'),
('pierres-precieuses', 'Piedras preciosas', 'pierres-precieuses', 'bijoux-montres', 2, 'es'),
('pierres-semi-precieuses', 'Piedras semipreciosas', 'pierres-semi-precieuses', 'bijoux-montres', 2, 'es'),
('perles', 'Perlas', 'perles', 'bijoux-montres', 2, 'es'),
('or', 'Oro', 'or', 'bijoux-montres', 2, 'es'),
('argent', 'Plata', 'argent', 'bijoux-montres', 2, 'es'),
('vermeil', 'Vermeil', 'vermeil', 'bijoux-montres', 2, 'es'),
('puces', 'Pendientes pequeños', 'puces', 'bijoux-montres', 2, 'es'),
('creoles', 'Aros', 'creoles', 'bijoux-montres', 2, 'es'),
('pendantes', 'Pendientes colgantes', 'pendantes', 'bijoux-montres', 2, 'es'),
('clips-boucles', 'Pendientes de clip', 'clips-boucles', 'bijoux-montres', 2, 'es'),
('bracelets-chaine', 'Pulseras de cadena', 'bracelets-chaine', 'bijoux-montres', 2, 'es'),
('gourmette', 'Pulsera identificativa', 'gourmette', 'bijoux-montres', 2, 'es'),
('joncs', 'Brazaletes rígidos', 'joncs', 'bijoux-montres', 2, 'es'),
('manchettes', 'Brazaletes anchos', 'manchettes', 'bijoux-montres', 2, 'es'),
('tennis-bijoux', 'Pulseras tenis', 'tennis-bijoux', 'bijoux-montres', 2, 'es'),
('perles-bracelets', 'Pulseras de perlas', 'perles-bracelets', 'bijoux-montres', 2, 'es'),
('cuir-tresse', 'Cuero trenzado', 'cuir-tresse', 'bijoux-montres', 2, 'es'),
('charms', 'Charms', 'charms', 'bijoux-montres', 2, 'es'),
('alliance', 'Alianza', 'alliance', 'bijoux-montres', 2, 'es'),
('solitaire', 'Solitaire', 'solitaire', 'bijoux-montres', 2, 'es'),
('chevaliere', 'Anillo sello', 'chevaliere', 'bijoux-montres', 2, 'es'),
('empilables', 'Apilables', 'empilables', 'bijoux-montres', 2, 'es');

-- Level 3 - Bolsos (Handbags)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('sacs-a-bandouliere', 'Bolsos de hombro', 'sacs-a-bandouliere', 'sacs-main', 3, 'es'),
('sacs-a-dos-mode', 'Mochilas de moda', 'sacs-a-dos-mode', 'sacs-main', 3, 'es'),
('sacs-de-voyage', 'Bolsos de viaje', 'sacs-de-voyage', 'sacs-main', 3, 'es'),
('porte-documents', 'Portafolios', 'porte-documents', 'sacs-main', 3, 'es'),
('sacs-de-sport', 'Bolsos de deporte', 'sacs-de-sport', 'sacs-main', 3, 'es'),
('sacs-de-plage', 'Bolsos de playa', 'sacs-de-plage', 'sacs-main', 3, 'es'),
('pochettes', 'Bolsos de mano', 'pochettes', 'sacs-main', 3, 'es'),
('cartables', 'Carteles', 'cartables', 'sacs-main', 3, 'es'),
('sacs-a-main-luxe', 'Bolsos de lujo', 'sacs-a-main-luxe', 'sacs-main', 3, 'es');

-- Level 3 - Accesorios de moda (Fashion Accessories)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('ceintures', 'Cinturones', 'ceintures', 'accessoires-mode', 3, 'es'),
('portefeuilles', 'Carteras', 'portefeuilles', 'accessoires-mode', 3, 'es'),
('lunettes-de-soleil', 'Gafas de sol', 'lunettes-de-soleil', 'accessoires-mode', 3, 'es'),
('montres', 'Relojes', 'montres', 'accessoires-mode', 3, 'es'),
('bijoux', 'Joyería', 'bijoux', 'accessoires-mode', 3, 'es'),
('cravates', 'Corbatas', 'cravates', 'accessoires-mode', 3, 'es'),
('echarpes', 'Bufandas', 'echarpes', 'accessoires-mode', 3, 'es'),
('chapeaux', 'Sombreros', 'chapeaux', 'accessoires-mode', 3, 'es'),
('casquettes', 'Gorras', 'casquettes', 'accessoires-mode', 3, 'es'),
('gants-mode', 'Guantes', 'gants-mode', 'accessoires-mode', 3, 'es');

-- German
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('mode-et-accessoires', 'Mode & Accessoires', 'mode-et-accessoires', NULL, 0, 'de');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('chaussures', 'Schuhe', 'chaussures', 'mode-et-accessoires', 1, 'de'),
('bijoux-montres', 'Schmuck & Uhren', 'bijoux-montres', 'mode-et-accessoires', 1, 'de'),
('sacs-main', 'Handtaschen', 'sacs-main', 'mode-et-accessoires', 1, 'de'),
('accessoires-mode', 'Mode-Accessoires', 'accessoires-mode', 'mode-et-accessoires', 1, 'de');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('baskets', 'Sneaker', 'baskets', 'chaussures', 2, 'de'),
('sneakers', 'Turnschuhe', 'sneakers', 'chaussures', 2, 'de'),
('chaussures-ville', 'Stadtschuhe', 'chaussures-ville', 'chaussures', 2, 'de'),
('chaussures-sport', 'Sportschuhe', 'chaussures-sport', 'chaussures', 2, 'de'),
('chaussures-running', 'Laufschuhe', 'chaussures-running', 'chaussures', 2, 'de'),
('chaussures-trekking', 'Trekking-Schuhe', 'chaussures-trekking', 'chaussures', 2, 'de'),
('chaussures-randonnee', 'Wanderschuhe', 'chaussures-randonnee', 'chaussures', 2, 'de'),
('escarpins', 'Pumps', 'escarpins', 'chaussures', 2, 'de'),
('bottines', 'Stiefelchen', 'bottines', 'chaussures', 2, 'de'),
('bottes', 'Stiefel', 'bottes', 'chaussures', 2, 'de'),
('sandales', 'Sandalen', 'sandales', 'chaussures', 2, 'de'),
('tongs', 'Flip-Flops', 'tongs', 'chaussures', 2, 'de'),
('chaussures-plates', 'Flache Schuhe', 'chaussures-plates', 'chaussures', 2, 'de'),
('mocassins', 'Mokassins', 'mocassins', 'chaussures', 2, 'de'),
('loafers', 'Loafer', 'loafers', 'chaussures', 2, 'de'),
('derbies', 'Derbys', 'derbies', 'chaussures', 2, 'de'),
('oxfords', 'Oxfords', 'oxfords', 'chaussures', 2, 'de'),
('richelieu', 'Richelieus', 'richelieu', 'chaussures', 2, 'de'),
('chaussures-securite', 'Sicherheitsschuhe', 'chaussures-securite', 'chaussures', 2, 'de'),
('chaussures-travail', 'Arbeitsschuhe', 'chaussures-travail', 'chaussures', 2, 'de'),
('chaussures-ceremonie', 'Festliche Schuhe', 'chaussures-ceremonie', 'chaussures', 2, 'de'),
('chaussures-mariage', 'Hochzeitsschuhe', 'chaussures-mariage', 'chaussures', 2, 'de'),
('ballerines', 'Ballerinas', 'ballerines', 'chaussures', 2, 'de'),
('chaussures-bebe', 'Baby-Schuhe', 'chaussures-bebe', 'chaussures', 2, 'de'),
('chaussures-enfant', 'Kinderschuhe', 'chaussures-enfant', 'chaussures', 2, 'de'),
('chaussures-fille', 'Mädchenschuhe', 'chaussures-fille', 'chaussures', 2, 'de'),
('chaussures-garcon', 'Jungen-Schuhe', 'chaussures-garcon', 'chaussures', 2, 'de'),
('chaussures-adolescent', 'Jugend-Schuhe', 'chaussures-adolescent', 'chaussures', 2, 'de'),
('semelles-interieures', 'Einlegesohlen', 'semelles-interieures', 'chaussures', 2, 'de'),
('lacets', 'Schnürsenkel', 'lacets', 'chaussures', 2, 'de'),
('chausse-pieds', 'Schuhlöffel', 'chausse-pieds', 'chaussures', 2, 'de'),
('embauchoirs', 'Schuhspanner', 'embauchoirs', 'chaussures', 2, 'de'),
('cires-produits-entretien', 'Pflegeprodukte', 'cires-produits-entretien', 'chaussures', 2, 'de'),
('brosses-chaussures', 'Schuhbürsten', 'brosses-chaussures', 'chaussures', 2, 'de'),
('impermeabilisants', 'Imprägniermittel', 'impermeabilisants', 'chaussures', 2, 'de'),
('deodorants-chaussures', 'Schuh-Deos', 'deodorants-chaussures', 'chaussures', 2, 'de'),
('sechoirs-chaussures', 'Schuh-Trockner', 'sechoirs-chaussures', 'chaussures', 2, 'de'),
('bagues', 'Ringe', 'bagues', 'bijoux-montres', 2, 'de'),
('bagues-fantaisie', 'Fantasie-Ringe', 'bagues-fantaisie', 'bijoux-montres', 2, 'de'),
('bagues-argent', 'Silberringe', 'bagues-argent', 'bijoux-montres', 2, 'de'),
('bagues-or', 'Goldringe', 'bagues-or', 'bijoux-montres', 2, 'de'),
('bagues-diamant', 'Diamantringe', 'bagues-diamant', 'bijoux-montres', 2, 'de'),
('bagues-mariage', 'Eheringe', 'bagues-mariage', 'bijoux-montres', 2, 'de'),
('bagues-alliance', 'Allianz-Ringe', 'bagues-alliance', 'bijoux-montres', 2, 'de'),
('bagues-fiancailles', 'Verlobungsringe', 'bagues-fiancailles', 'bijoux-montres', 2, 'de'),
('colliers', 'Halsketten', 'colliers', 'bijoux-montres', 2, 'de'),
('colliers-fantaisie', 'Fantasie-Ketten', 'colliers-fantaisie', 'bijoux-montres', 2, 'de'),
('colliers-argent', 'Silberketten', 'colliers-argent', 'bijoux-montres', 2, 'de'),
('colliers-or', 'Goldketten', 'colliers-or', 'bijoux-montres', 2, 'de'),
('colliers-diamant', 'Diamant-Ketten', 'colliers-diamant', 'bijoux-montres', 2, 'de'),
('colliers-perles', 'Perlenketten', 'colliers-perles', 'bijoux-montres', 2, 'de'),
('bracelets', 'Armbänder', 'bracelets', 'bijoux-montres', 2, 'de'),
('bracelets-fantaisie', 'Fantasie-Armbänder', 'bracelets-fantaisie', 'bijoux-montres', 2, 'de'),
('bracelets-argent', 'Silberarmbänder', 'bracelets-argent', 'bijoux-montres', 2, 'de'),
('bracelets-or', 'Goldarmbänder', 'bracelets-or', 'bijoux-montres', 2, 'de'),
('bracelets-diamant', 'Diamant-Armbänder', 'bracelets-diamant', 'bijoux-montres', 2, 'de'),
('bracelets-cuir', 'Lederarmbänder', 'bracelets-cuir', 'bijoux-montres', 2, 'de'),
('bracelets-perles', 'Perlenarmbänder', 'bracelets-perles', 'bijoux-montres', 2, 'de'),
('boucles-doreilles', 'Ohrringe', 'boucles-doreilles', 'bijoux-montres', 2, 'de'),
('boucles-doreilles-fantaisie', 'Fantasie-Ohrringe', 'boucles-doreilles-fantaisie', 'bijoux-montres', 2, 'de'),
('boucles-doreilles-argent', 'Silberohrringe', 'boucles-doreilles-argent', 'bijoux-montres', 2, 'de'),
('boucles-doreilles-or', 'Goldohrringe', 'boucles-doreilles-or', 'bijoux-montres', 2, 'de'),
('boucles-doreilles-diamant', 'Diamant-Ohrringe', 'boucles-doreilles-diamant', 'bijoux-montres', 2, 'de'),
('boucles-doreilles-perles', 'Perlenohrringe', 'boucles-doreilles-perles', 'bijoux-montres', 2, 'de'),
('pendentifs', 'Anhänger', 'pendentifs', 'bijoux-montres', 2, 'de'),
('pendentifs-argent', 'Silberanhänger', 'pendentifs-argent', 'bijoux-montres', 2, 'de'),
('pendentifs-or', 'Goldanhänger', 'pendentifs-or', 'bijoux-montres', 2, 'de'),
('broches', 'Broschen', 'broches', 'bijoux-montres', 2, 'de'),
('broches-fantaisie', 'Fantasie-Broschen', 'broches-fantaisie', 'bijoux-montres', 2, 'de'),
('broches-argent', 'Silberbroschen', 'broches-argent', 'bijoux-montres', 2, 'de'),
('broches-or', 'Goldbroschen', 'broches-or', 'bijoux-montres', 2, 'de'),
('chaines', 'Ketten', 'chaines', 'bijoux-montres', 2, 'de'),
('chaines-argent', 'Silberketten', 'chaines-argent', 'bijoux-montres', 2, 'de'),
('chaines-or', 'Goldketten', 'chaines-or', 'bijoux-montres', 2, 'de'),
('gourmettes', 'Panzerketten', 'gourmettes', 'bijoux-montres', 2, 'de'),
('gourmettes-argent', 'Silberpanzerketten', 'gourmettes-argent', 'bijoux-montres', 2, 'de'),
('gourmettes-or', 'Goldpanzerketten', 'gourmettes-or', 'bijoux-montres', 2, 'de'),
('parures', 'Schmucksets', 'parures', 'bijoux-montres', 2, 'de');

-- Level 3 - Handtaschen (Handbags)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('sacs-a-bandouliere', 'Schultertaschen', 'sacs-a-bandouliere', 'sacs-main', 3, 'de'),
('sacs-a-dos-mode', 'Modische Rucksäcke', 'sacs-a-dos-mode', 'sacs-main', 3, 'de'),
('sacs-de-voyage', 'Reisetaschen', 'sacs-de-voyage', 'sacs-main', 3, 'de'),
('porte-documents', 'Aktentaschen', 'porte-documents', 'sacs-main', 3, 'de'),
('sacs-de-sport', 'Sporttaschen', 'sacs-de-sport', 'sacs-main', 3, 'de'),
('sacs-de-plage', 'Strandtaschen', 'sacs-de-plage', 'sacs-main', 3, 'de'),
('pochettes', 'Clutches', 'pochettes', 'sacs-main', 3, 'de'),
('cartables', 'Schulranzen', 'cartables', 'sacs-main', 3, 'de'),
('sacs-a-main-luxe', 'Luxus-Handtaschen', 'sacs-a-main-luxe', 'sacs-main', 3, 'de');

-- Level 3 - Mode-Accessoires (Fashion Accessories)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('ceintures', 'Gürtel', 'ceintures', 'accessoires-mode', 3, 'de'),
('portefeuilles', 'Geldbörsen', 'portefeuilles', 'accessoires-mode', 3, 'de'),
('lunettes-de-soleil', 'Sonnenbrillen', 'lunettes-de-soleil', 'accessoires-mode', 3, 'de'),
('montres', 'Uhren', 'montres', 'accessoires-mode', 3, 'de'),
('bijoux', 'Schmuck', 'bijoux', 'accessoires-mode', 3, 'de'),
('cravates', 'Krawatten', 'cravates', 'accessoires-mode', 3, 'de'),
('echarpes', 'Schals', 'echarpes', 'accessoires-mode', 3, 'de'),
('chapeaux', 'Hüte', 'chapeaux', 'accessoires-mode', 3, 'de'),
('casquettes', 'Kappen', 'casquettes', 'accessoires-mode', 3, 'de'),
('gants-mode', 'Handschuhe', 'gants-mode', 'accessoires-mode', 3, 'de');

-- Italian
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('mode-et-accessoires', 'Moda e Accessori', 'mode-et-accessoires', NULL, 0, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('chaussures', 'Scarpe', 'chaussures', 'mode-et-accessoires', 1, 'it'),
('bijoux-montres', 'Gioielli & Orologi', 'bijoux-montres', 'mode-et-accessoires', 1, 'it'),
('sacs-main', 'Borse', 'sacs-main', 'mode-et-accessoires', 1, 'it'),
('accessoires-mode', 'Accessori moda', 'accessoires-mode', 'mode-et-accessoires', 1, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('baskets', 'Scarpe da ginnastica', 'baskets', 'chaussures', 2, 'it'),
('sneakers', 'Sneakers', 'sneakers', 'chaussures', 2, 'it'),
('running', 'Scarpe da corsa', 'running', 'chaussures', 2, 'it'),
('lifestyle', 'Lifestyle', 'lifestyle', 'chaussures', 2, 'it'),
('montantes', 'Alte', 'montantes', 'chaussures', 2, 'it'),
('basses', 'Basse', 'basses', 'chaussures', 2, 'it'),
('slip-on', 'Slip-on', 'slip-on', 'chaussures', 2, 'it'),
('derbies', 'Derby', 'derbies', 'chaussures', 2, 'it'),
('richelieu', 'Oxford', 'richelieu', 'chaussures', 2, 'it'),
('mocassins', 'Mocassini', 'mocassins', 'chaussures', 2, 'it'),
('escarpins', 'Décolleté', 'escarpins', 'chaussures', 2, 'it'),
('ballerines', 'Ballerine', 'ballerines', 'chaussures', 2, 'it'),
('salomes', 'Mary Jane', 'salomes', 'chaussures', 2, 'it'),
('mules', 'Mules', 'mules', 'chaussures', 2, 'it'),
('chelsea', 'Chelsea', 'chelsea', 'chaussures', 2, 'it'),
('monk', 'Monk strap', 'monk', 'chaussures', 2, 'it'),
('bottes', 'Stivali', 'bottes', 'chaussures', 2, 'it'),
('bottines', 'Stivaletti', 'bottines', 'chaussures', 2, 'it'),
('cuissardes', 'Cuissardes', 'cuissardes', 'chaussures', 2, 'it'),
('cavalieres', 'Stivali da equitazione', 'cavalieres', 'chaussures', 2, 'it'),
('pluie', 'Stivali da pioggia', 'pluie', 'chaussures', 2, 'it'),
('fourrees', 'Foderati in pelliccia', 'fourrees', 'chaussures', 2, 'it'),
('motardes', 'Stivali da moto', 'motardes', 'chaussures', 2, 'it'),
('sandales-plates', 'Sandali bassi', 'sandales-plates', 'chaussures', 2, 'it'),
('sandales-compensees', 'Sandali con zeppa', 'sandales-compensees', 'chaussures', 2, 'it'),
('tongs', 'Infradito', 'tongs', 'chaussures', 2, 'it'),
('nu-pieds', 'Sandali aperti', 'nu-pieds', 'chaussures', 2, 'it'),
('claquettes', 'Ciabatte', 'claquettes', 'chaussures', 2, 'it'),
('espadrilles', 'Espadrillas', 'espadrilles', 'chaussures', 2, 'it'),
('football', 'Calcio', 'football', 'chaussures', 2, 'it'),
('futsal', 'Futsal', 'futsal', 'chaussures', 2, 'it'),
('basketball', 'Basket', 'basketball', 'chaussures', 2, 'it'),
('tennis-chaussures', 'Tennis', 'tennis-chaussures', 'chaussures', 2, 'it'),
('golf-chaussures', 'Golf', 'golf-chaussures', 'chaussures', 2, 'it'),
('running-trail', 'Trail running', 'running-trail', 'chaussures', 2, 'it'),
('skateboard', 'Skateboard', 'skateboard', 'chaussures', 2, 'it'),
('fitness', 'Fitness', 'fitness', 'chaussures', 2, 'it'),
('premiers-pas', 'Primi passi', 'premiers-pas', 'chaussures', 2, 'it'),
('ecole', 'Scuola', 'ecole', 'chaussures', 2, 'it'),
('lumineuses-led', 'LED luminosi', 'lumineuses-led', 'chaussures', 2, 'it'),
('automatique', 'Automatico', 'automatique', 'bijoux-montres', 2, 'it'),
('quartz', 'Quarzo', 'quartz', 'bijoux-montres', 2, 'it'),
('connectee', 'Smartwatch', 'connectee', 'bijoux-montres', 2, 'it'),
('chronographe', 'Cronografo', 'chronographe', 'bijoux-montres', 2, 'it'),
('plongee', 'Subacqueo', 'plongee', 'bijoux-montres', 2, 'it'),
('sport-gps', 'Sport GPS', 'sport-gps', 'bijoux-montres', 2, 'it'),
('bracelet-cuir', 'Cinturino in pelle', 'bracelet-cuir', 'bijoux-montres', 2, 'it'),
('bracelet-acier', 'Cinturino in acciaio', 'bracelet-acier', 'bijoux-montres', 2, 'it'),
('bracelet-silicone', 'Cinturino in silicone', 'bracelet-silicone', 'bijoux-montres', 2, 'it'),
('chaines-fines', 'Catene sottili', 'chaines-fines', 'bijoux-montres', 2, 'it'),
('ras-de-cou', 'Choker', 'ras-de-cou', 'bijoux-montres', 2, 'it'),
('sautoirs', 'Collane lunghe', 'sautoirs', 'bijoux-montres', 2, 'it'),
('multi-rangs', 'Multi-strato', 'multi-rangs', 'bijoux-montres', 2, 'it'),
('medailles', 'Medaglie', 'medailles', 'bijoux-montres', 2, 'it'),
('croix', 'Croci', 'croix', 'bijoux-montres', 2, 'it'),
('initiales', 'Iniziali', 'initiales', 'bijoux-montres', 2, 'it'),
('pierres-precieuses', 'Pietre preziose', 'pierres-precieuses', 'bijoux-montres', 2, 'it'),
('pierres-semi-precieuses', 'Pietre semi-preziose', 'pierres-semi-precieuses', 'bijoux-montres', 2, 'it'),
('perles', 'Perle', 'perles', 'bijoux-montres', 2, 'it'),
('or', 'Oro', 'or', 'bijoux-montres', 2, 'it'),
('argent', 'Argento', 'argent', 'bijoux-montres', 2, 'it'),
('vermeil', 'Vermeil', 'vermeil', 'bijoux-montres', 2, 'it'),
('puces', 'Orecchini a perno', 'puces', 'bijoux-montres', 2, 'it'),
('creoles', 'Cerchi', 'creoles', 'bijoux-montres', 2, 'it'),
('pendantes', 'Pendenti', 'pendantes', 'bijoux-montres', 2, 'it'),
('clips-boucles', 'Clip', 'clips-boucles', 'bijoux-montres', 2, 'it'),
('bracelets-chaine', 'Bracciali a catena', 'bracelets-chaine', 'bijoux-montres', 2, 'it'),
('gourmette', 'Gourmette', 'gourmette', 'bijoux-montres', 2, 'it'),
('joncs', 'Bracciali rigidi', 'joncs', 'bijoux-montres', 2, 'it'),
('manchettes', 'Cuff', 'manchettes', 'bijoux-montres', 2, 'it'),
('tennis-bijoux', 'Bracciali tennis', 'tennis-bijoux', 'bijoux-montres', 2, 'it'),
('perles-bracelets', 'Bracciali di perle', 'perles-bracelets', 'bijoux-montres', 2, 'it'),
('cuir-tresse', 'Cuoio intrecciato', 'cuir-tresse', 'bijoux-montres', 2, 'it'),
('charms', 'Charm', 'charms', 'bijoux-montres', 2, 'it'),
('alliance', 'Fede nuziale', 'alliance', 'bijoux-montres', 2, 'it'),
('solitaire', 'Solitaire', 'solitaire', 'bijoux-montres', 2, 'it'),
('chevaliere', 'Anello con sigillo', 'chevaliere', 'bijoux-montres', 2, 'it'),
('empilables', 'Impilabili', 'empilables', 'bijoux-montres', 2, 'it');

-- Level 3 - Borse (Handbags)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('sacs-a-bandouliere', 'Borse a spalla', 'sacs-a-bandouliere', 'sacs-main', 3, 'it'),
('sacs-a-dos-mode', 'Zaini moda', 'sacs-a-dos-mode', 'sacs-main', 3, 'it'),
('sacs-de-voyage', 'Borse da viaggio', 'sacs-de-voyage', 'sacs-main', 3, 'it'),
('porte-documents', 'Portadocumenti', 'porte-documents', 'sacs-main', 3, 'it'),
('sacs-de-sport', 'Borse sportive', 'sacs-de-sport', 'sacs-main', 3, 'it'),
('sacs-de-plage', 'Borse da spiaggia', 'sacs-de-plage', 'sacs-main', 3, 'it'),
('pochettes', 'Clutch', 'pochettes', 'sacs-main', 3, 'it'),
('cartables', 'Cartelle', 'cartables', 'sacs-main', 3, 'it'),
('sacs-a-main-luxe', 'Borse di lusso', 'sacs-a-main-luxe', 'sacs-main', 3, 'it');

-- Level 3 - Accessori moda (Fashion Accessories)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('ceintures', 'Cinture', 'ceintures', 'accessoires-mode', 3, 'it'),
('portefeuilles', 'Portafogli', 'portefeuilles', 'accessoires-mode', 3, 'it'),
('lunettes-de-soleil', 'Occhiali da sole', 'lunettes-de-soleil', 'accessoires-mode', 3, 'it'),
('montres', 'Orologi', 'montres', 'accessoires-mode', 3, 'it'),
('bijoux', 'Gioielli', 'bijoux', 'accessoires-mode', 3, 'it'),
('cravates', 'Cravatte', 'cravates', 'accessoires-mode', 3, 'it'),
('echarpes', 'Sciarpe', 'echarpes', 'accessoires-mode', 3, 'it'),
('chapeaux', 'Cappelli', 'chapeaux', 'accessoires-mode', 3, 'it'),
('casquettes', 'Cappellini', 'casquettes', 'accessoires-mode', 3, 'it'),
('gants-mode', 'Guanti', 'gants-mode', 'accessoires-mode', 3, 'it');

*** End Patch