-- Migration pour la catégorie Animaux & Accessoires (toutes langues)

-- FRANÇAIS
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('animaux-accessoires', 'Animaux & Accessoires', 'animaux-accessoires', NULL, 0, 'fr');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
-- Animaux Domestiques
('animaux-domestiques', 'Animaux Domestiques', 'animaux-domestiques', 'animaux-accessoires', 1, 'fr'),
('chiens', 'Chiens', 'chiens', 'animaux-domestiques', 2, 'fr'),
('chiots-races', 'chiots de race', 'chiots-races', 'chiens', 3, 'fr'),
('chiens-adultes', 'chiens adultes', 'chiens-adultes', 'chiens', 3, 'fr'),
('chiens-dresses', 'chiens dressés', 'chiens-dresses', 'chiens', 3, 'fr'),
('chats', 'Chats', 'chats', 'animaux-domestiques', 2, 'fr'),
('chatons-races', 'chatons de race', 'chatons-races', 'chats', 3, 'fr'),
('chats-adultes', 'chats adultes', 'chats-adultes', 'chats', 3, 'fr'),
('oiseaux', 'oiseaux', 'oiseaux', 'animaux-domestiques', 2, 'fr'),
('oiseaux-rares', 'oiseaux rares', 'oiseaux-rares', 'oiseaux', 3, 'fr'),
('canaris', 'canaris', 'canaris', 'oiseaux', 3, 'fr'),
('poissons', 'poissons', 'poissons', 'animaux-domestiques', 2, 'fr'),
('poissons-aquarium', 'poissons d\'aquarium', 'poissons-aquarium', 'poissons', 3, 'fr'),
('rongeurs', 'rongeurs', 'rongeurs', 'animaux-domestiques', 2, 'fr'),
('lapins', 'lapins', 'lapins', 'rongeurs', 3, 'fr'),
('hamsters', 'hamsters', 'hamsters', 'rongeurs', 3, 'fr'),
('reptiles', 'reptiles', 'reptiles', 'animaux-domestiques', 2, 'fr'),
('tortues', 'tortues', 'tortues', 'reptiles', 3, 'fr'),

-- Animaux d'Élevage
('animaux-elevage', 'Animaux d\'Élevage', 'animaux-elevage', 'animaux-accessoires', 1, 'fr'),
('ovins', 'ovins', 'ovins', 'animaux-elevage', 2, 'fr'),
('bovins', 'bovins', 'bovins', 'animaux-elevage', 2, 'fr'),
('caprins', 'caprins', 'caprins', 'animaux-elevage', 2, 'fr'),
('volailles', 'volailles', 'volailles', 'animaux-elevage', 2, 'fr'),
('equides', 'équidés', 'equides', 'animaux-elevage', 2, 'fr'),

-- Nourriture & Soins Animaliers
('nourriture-soins', 'Nourriture & Soins Animaliers', 'nourriture-soins', 'animaux-accessoires', 1, 'fr'),
('alimentation-chiens-chats', 'Alimentation Chiens & Chats', 'alimentation-chiens-chats', 'nourriture-soins', 2, 'fr'),
('croquettes', 'croquettes', 'croquettes', 'alimentation-chiens-chats', 3, 'fr'),
('patees', 'pâtées', 'patees', 'alimentation-chiens-chats', 3, 'fr'),
('friandises', 'friandises', 'friandises', 'alimentation-chiens-chats', 3, 'fr'),
('alimentation-oiseaux', 'Alimentation Oiseaux', 'alimentation-oiseaux', 'nourriture-soins', 2, 'fr'),
('melanges-oiseaux', 'mélanges pour oiseaux', 'melanges-oiseaux', 'alimentation-oiseaux', 3, 'fr'),
('alimentation-poissons', 'Alimentation Poissons', 'alimentation-poissons', 'nourriture-soins', 2, 'fr'),
('aliments-poissons', 'aliments pour poissons', 'aliments-poissons', 'alimentation-poissons', 3, 'fr'),
('soins-hygiene', 'Soins & Hygiène', 'soins-hygiene', 'nourriture-soins', 2, 'fr'),
('produits-hygiene', 'produits d\'hygiène', 'produits-hygiene', 'soins-hygiene', 3, 'fr'),
('shampoings', 'shampoings', 'shampoings', 'soins-hygiene', 3, 'fr'),
('antiparasitaires', 'antiparasitaires', 'antiparasitaires', 'soins-hygiene', 3, 'fr'),
('anti-tiques', 'anti-tiques', 'anti-tiques', 'soins-hygiene', 3, 'fr'),
('produits-veterinaires', 'produits vétérinaires', 'produits-veterinaires', 'soins-hygiene', 3, 'fr'),
('complements-alimentaires', 'Compléments Alimentaires', 'complements-alimentaires', 'nourriture-soins', 2, 'fr'),
('vitamines', 'vitamines', 'vitamines', 'complements-alimentaires', 3, 'fr'),

-- Accessoires & Équipements
('accessoires-equipements', 'Accessoires & Équipements', 'accessoires-equipements', 'animaux-accessoires', 1, 'fr'),
('accessoires-promenade', 'Accessoires de Promenade', 'accessoires-promenade', 'accessoires-equipements', 2, 'fr'),
('laisses', 'laisses', 'laisses', 'accessoires-promenade', 3, 'fr'),
('colliers', 'colliers', 'colliers', 'accessoires-promenade', 3, 'fr'),
('harnais', 'harnais', 'harnais', 'accessoires-promenade', 3, 'fr'),
('habitats', 'Habitats', 'habitats', 'accessoires-equipements', 2, 'fr'),
('cages', 'cages', 'cages', 'habitats', 3, 'fr'),
('volières', 'volières', 'volières', 'habitats', 3, 'fr'),
('niches', 'niches', 'niches', 'habitats', 3, 'fr'),
('aquariums', 'aquariums', 'aquariums', 'habitats', 3, 'fr'),
('terrariums', 'terrariums', 'terrariums', 'habitats', 3, 'fr'),
('confort-dodo', 'Confort & Dodo', 'confort-dodo', 'accessoires-equipements', 2, 'fr'),
('paniers', 'paniers', 'paniers', 'confort-dodo', 3, 'fr'),
('coussins', 'coussins', 'coussins', 'confort-dodo', 3, 'fr'),
('arbres-chat', 'arbres à chat', 'arbres-chat', 'confort-dodo', 3, 'fr'),
('alimentation-accessoires', 'Alimentation & Accessoires', 'alimentation-accessoires', 'accessoires-equipements', 2, 'fr'),
('gamelles', 'gamelles', 'gamelles', 'alimentation-accessoires', 3, 'fr'),
('distributeurs-auto', 'distributeurs automatiques', 'distributeurs-auto', 'alimentation-accessoires', 3, 'fr'),
('fontaines-eau', 'fontaines d\'eau', 'fontaines-eau', 'alimentation-accessoires', 3, 'fr'),
('litières-hygiene', 'Litières & Hygiène', 'litières-hygiene', 'accessoires-equipements', 2, 'fr'),
('litières', 'litières', 'litières', 'litières-hygiene', 3, 'fr'),
('bacs-litiere', 'bacs à litière', 'bacs-litiere', 'litières-hygiene', 3, 'fr'),
('jouets-loisirs', 'Jouets & Loisirs', 'jouets-loisirs', 'accessoires-equipements', 2, 'fr'),
('jouets', 'jouets', 'jouets', 'jouets-loisirs', 3, 'fr'),
('transport', 'Transport', 'transport', 'accessoires-equipements', 2, 'fr'),
('paniers-transport', 'paniers de transport', 'paniers-transport', 'transport', 3, 'fr'),

-- Élevage & Reproduction
('elevage-reproduction', 'Élevage & Reproduction', 'elevage-reproduction', 'animaux-accessoires', 1, 'fr'),
('materiel-elevage', 'Matériel d\'Élevage', 'materiel-elevage', 'elevage-reproduction', 2, 'fr'),
('incubateurs', 'incubateurs', 'incubateurs', 'materiel-elevage', 3, 'fr'),
('couveuses', 'couveuses', 'couveuses', 'materiel-elevage', 3, 'fr'),
('cages-elevage', 'cages d\'élevage', 'cages-elevage', 'materiel-elevage', 3, 'fr'),
('accessoires-reproduction', 'Accessoires de Reproduction', 'accessoires-reproduction', 'elevage-reproduction', 2, 'fr'),
('accessoires-accouplement', 'accessoires d\'accouplement', 'accessoires-accouplement', 'accessoires-reproduction', 3, 'fr'),
('reproducteurs-selectionnes', 'Reproducteurs Sélectionnés', 'reproducteurs-selectionnes', 'elevage-reproduction', 2, 'fr'),
('reproducteurs', 'reproducteurs sélectionnés', 'reproducteurs', 'reproducteurs-selectionnes', 3, 'fr'),
('jeunes-animaux', 'Jeunes Animaux', 'jeunes-animaux', 'elevage-reproduction', 2, 'fr'),
('poussins', 'poussins', 'poussins', 'jeunes-animaux', 3, 'fr'),
('agneaux', 'agneaux', 'agneaux', 'jeunes-animaux', 3, 'fr'),
('chevreaux', 'chevreaux', 'chevreaux', 'jeunes-animaux', 3, 'fr'),
('services-elevage', 'Services d\'Élevage', 'services-elevage', 'elevage-reproduction', 2, 'fr'),
('assistance-elevage', 'services d\'assistance à l\'élevage', 'assistance-elevage', 'services-elevage', 3, 'fr'),
('conseils-specialises', 'conseils spécialisés', 'conseils-specialises', 'services-elevage', 3, 'fr'),
('genetique-selection', 'génétique & sélection', 'genetique-selection', 'services-elevage', 3, 'fr'),

-- Services Animaliers
('services-animaliers', 'Services Animaliers', 'services-animaliers', 'animaux-accessoires', 1, 'fr'),
('toilettage', 'Toilettage', 'toilettage', 'services-animaliers', 2, 'fr'),
('toilettage-chiens', 'toilettage chiens', 'toilettage-chiens', 'toilettage', 3, 'fr'),
('toilettage-chats', 'toilettage chats', 'toilettage-chats', 'toilettage', 3, 'fr'),
('dressage-education', 'Dressage & Éducation', 'dressage-education', 'services-animaliers', 2, 'fr'),
('dressage-canin', 'dressage canin', 'dressage-canin', 'dressage-education', 3, 'fr'),
('education-canine', 'éducation canine', 'education-canine', 'dressage-education', 3, 'fr'),
('pension-garde', 'Pension & Garde', 'pension-garde', 'services-animaliers', 2, 'fr'),
('pension-animaux', 'pension & garde d\'animaux', 'pension-animaux', 'pension-garde', 3, 'fr'),
('promenades-soins', 'Promenades & Soins', 'promenades-soins', 'services-animaliers', 2, 'fr'),
('promenades', 'promenades', 'promenades', 'promenades-soins', 3, 'fr'),
('soins-domicile', 'soins à domicile', 'soins-domicile', 'promenades-soins', 3, 'fr'),
('comportement-adoption', 'Comportement & Adoption', 'comportement-adoption', 'services-animaliers', 2, 'fr'),
('consultation-comportementaliste', 'consultation comportementaliste', 'consultation-comportementaliste', 'comportement-adoption', 3, 'fr'),
('adoption', 'adoption', 'adoption', 'comportement-adoption', 3, 'fr'),
('services-speciaux', 'Services Spéciaux', 'services-speciaux', 'services-animaliers', 2, 'fr'),
('photographie-animaliere', 'photographie animalière', 'photographie-animaliere', 'services-speciaux', 3, 'fr'),
('transport-animaux', 'transport d\'animaux', 'transport-animaux', 'services-speciaux', 3, 'fr'),
('services-veterinaires', 'services vétérinaires privés', 'services-veterinaires', 'services-speciaux', 3, 'fr'),

-- Produits & Accessoires Extérieurs
('produits-exterieurs', 'Produits & Accessoires Extérieurs', 'produits-exterieurs', 'animaux-accessoires', 1, 'fr'),
('clotures-enclos', 'Clôtures & Enclos', 'clotures-enclos', 'produits-exterieurs', 2, 'fr'),
('clotures-animaux', 'clôtures pour animaux', 'clotures-animaux', 'clotures-enclos', 3, 'fr'),
('enclos', 'enclos', 'enclos', 'clotures-enclos', 3, 'fr'),
('abris-exterieurs', 'Abris Extérieurs', 'abris-exterieurs', 'produits-exterieurs', 2, 'fr'),
('abris-exterieurs-animaux', 'abris extérieurs', 'abris-exterieurs-animaux', 'abris-exterieurs', 3, 'fr'),
('alimentation-automatique', 'Alimentation Automatique', 'alimentation-automatique', 'produits-exterieurs', 2, 'fr'),
('mangeoires-auto', 'mangeoires automatiques', 'mangeoires-auto', 'alimentation-automatique', 3, 'fr'),
('systemes-abreuvement', 'systèmes d\'abreuvement', 'systemes-abreuvement', 'alimentation-automatique', 3, 'fr'),
('equipements-elevage-exterieur', 'Équipements Élevage Extérieur', 'equipements-elevage-exterieur', 'produits-exterieurs', 2, 'fr'),
('materiel-plein-air', 'matériel pour élevage en plein air', 'materiel-plein-air', 'equipements-elevage-exterieur', 3, 'fr'),
('confort-thermique', 'Confort Thermique', 'confort-thermique', 'produits-exterieurs', 2, 'fr'),
('lampes-chauffantes', 'lampes chauffantes', 'lampes-chauffantes', 'confort-thermique', 3, 'fr'),
('accessoires-volières', 'Accessoires Volières & Basse-Cour', 'accessoires-volières', 'produits-exterieurs', 2, 'fr'),
('materiel-volières', 'matériel pour volières & basses-cour', 'materiel-volières', 'accessoires-volières', 3, 'fr');

-- ENGLISH
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('animaux-accessoires', 'Animals & Accessories', 'animaux-accessoires', NULL, 0, 'en');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
-- Pets
('animaux-domestiques', 'Pets', 'animaux-domestiques', 'animaux-accessoires', 1, 'en'),
('chiens', 'Dogs', 'chiens', 'animaux-domestiques', 2, 'en'),
('chiots-races', 'pedigree puppies', 'chiots-races', 'chiens', 3, 'en'),
('chiens-adultes', 'adult dogs', 'chiens-adultes', 'chiens', 3, 'en'),
('chiens-dresses', 'trained dogs', 'chiens-dresses', 'chiens', 3, 'en'),
('chats', 'Cats', 'chats', 'animaux-domestiques', 2, 'en'),
('chatons-races', 'pedigree kittens', 'chatons-races', 'chats', 3, 'en'),
('chats-adultes', 'adult cats', 'chats-adultes', 'chats', 3, 'en'),
('oiseaux', 'birds', 'oiseaux', 'animaux-domestiques', 2, 'en'),
('oiseaux-rares', 'rare birds', 'oiseaux-rares', 'oiseaux', 3, 'en'),
('canaris', 'canaries', 'canaris', 'oiseaux', 3, 'en'),
('poissons', 'fish', 'poissons', 'animaux-domestiques', 2, 'en'),
('poissons-aquarium', 'aquarium fish', 'poissons-aquarium', 'poissons', 3, 'en'),
('rongeurs', 'rodents', 'rongeurs', 'animaux-domestiques', 2, 'en'),
('lapins', 'rabbits', 'lapins', 'rongeurs', 3, 'en'),
('hamsters', 'hamsters', 'hamsters', 'rongeurs', 3, 'en'),
('reptiles', 'reptiles', 'reptiles', 'animaux-domestiques', 2, 'en'),
('tortues', 'turtles', 'tortues', 'reptiles', 3, 'en'),

-- Farm Animals
('animaux-elevage', 'Farm Animals', 'animaux-elevage', 'animaux-accessoires', 1, 'en'),
('ovins', 'sheep', 'ovins', 'animaux-elevage', 2, 'en'),
('bovins', 'cattle', 'bovins', 'animaux-elevage', 2, 'en'),
('caprins', 'goats', 'caprins', 'animaux-elevage', 2, 'en'),
('volailles', 'poultry', 'volailles', 'animaux-elevage', 2, 'en'),
('equides', 'equines', 'equides', 'animaux-elevage', 2, 'en'),

-- Food & Animal Care
('nourriture-soins', 'Food & Animal Care', 'nourriture-soins', 'animaux-accessoires', 1, 'en'),
('alimentation-chiens-chats', 'Dog & Cat Food', 'alimentation-chiens-chats', 'nourriture-soins', 2, 'en'),
('croquettes', 'kibble', 'croquettes', 'alimentation-chiens-chats', 3, 'en'),
('patees', 'wet food', 'patees', 'alimentation-chiens-chats', 3, 'en'),
('friandises', 'treats', 'friandises', 'alimentation-chiens-chats', 3, 'en'),
('alimentation-oiseaux', 'Bird Food', 'alimentation-oiseaux', 'nourriture-soins', 2, 'en'),
('melanges-oiseaux', 'bird seed mixes', 'melanges-oiseaux', 'alimentation-oiseaux', 3, 'en'),
('alimentation-poissons', 'Fish Food', 'alimentation-poissons', 'nourriture-soins', 2, 'en'),
('aliments-poissons', 'fish food', 'aliments-poissons', 'alimentation-poissons', 3, 'en'),
('soins-hygiene', 'Care & Hygiene', 'soins-hygiene', 'nourriture-soins', 2, 'en'),
('produits-hygiene', 'hygiene products', 'produits-hygiene', 'soins-hygiene', 3, 'en'),
('shampoings', 'shampoos', 'shampoings', 'soins-hygiene', 3, 'en'),
('antiparasitaires', 'antiparasitics', 'antiparasitaires', 'soins-hygiene', 3, 'en'),
('anti-tiques', 'anti-tick products', 'anti-tiques', 'soins-hygiene', 3, 'en'),
('produits-veterinaires', 'veterinary products', 'produits-veterinaires', 'soins-hygiene', 3, 'en'),
('complements-alimentaires', 'Food Supplements', 'complements-alimentaires', 'nourriture-soins', 2, 'en'),
('vitamines', 'vitamins', 'vitamines', 'complements-alimentaires', 3, 'en'),

-- Accessories & Equipment
('accessoires-equipements', 'Accessories & Equipment', 'accessoires-equipements', 'animaux-accessoires', 1, 'en'),
('accessoires-promenade', 'Walking Accessories', 'accessoires-promenade', 'accessoires-equipements', 2, 'en'),
('laisses', 'leashes', 'laisses', 'accessoires-promenade', 3, 'en'),
('colliers', 'collars', 'colliers', 'accessoires-promenade', 3, 'en'),
('harnais', 'harnesses', 'harnais', 'accessoires-promenade', 3, 'en'),
('habitats', 'Habitats', 'habitats', 'accessoires-equipements', 2, 'en'),
('cages', 'cages', 'cages', 'habitats', 3, 'en'),
('volières', 'aviaries', 'volières', 'habitats', 3, 'en'),
('niches', 'dog houses', 'niches', 'habitats', 3, 'en'),
('aquariums', 'aquariums', 'aquariums', 'habitats', 3, 'en'),
('terrariums', 'terrariums', 'terrariums', 'habitats', 3, 'en'),
('confort-dodo', 'Comfort & Sleep', 'confort-dodo', 'accessoires-equipements', 2, 'en'),
('paniers', 'baskets', 'paniers', 'confort-dodo', 3, 'en'),
('coussins', 'cushions', 'coussins', 'confort-dodo', 3, 'en'),
('arbres-chat', 'cat trees', 'arbres-chat', 'confort-dodo', 3, 'en'),
('alimentation-accessoires', 'Feeding Accessories', 'alimentation-accessoires', 'accessoires-equipements', 2, 'en'),
('gamelles', 'bowls', 'gamelles', 'alimentation-accessoires', 3, 'en'),
('distributeurs-auto', 'automatic feeders', 'distributeurs-auto', 'alimentation-accessoires', 3, 'en'),
('fontaines-eau', 'water fountains', 'fontaines-eau', 'alimentation-accessoires', 3, 'en'),
('litières-hygiene', 'Litter & Hygiene', 'litières-hygiene', 'accessoires-equipements', 2, 'en'),
('litières', 'litter', 'litières', 'litières-hygiene', 3, 'en'),
('bacs-litiere', 'litter boxes', 'bacs-litiere', 'litières-hygiene', 3, 'en'),
('jouets-loisirs', 'Toys & Leisure', 'jouets-loisirs', 'accessoires-equipements', 2, 'en'),
('jouets', 'toys', 'jouets', 'jouets-loisirs', 3, 'en'),
('transport', 'Transport', 'transport', 'accessoires-equipements', 2, 'en'),
('paniers-transport', 'transport baskets', 'paniers-transport', 'transport', 3, 'en'),

-- Breeding & Reproduction
('elevage-reproduction', 'Breeding & Reproduction', 'elevage-reproduction', 'animaux-accessoires', 1, 'en'),
('materiel-elevage', 'Breeding Equipment', 'materiel-elevage', 'elevage-reproduction', 2, 'en'),
('incubateurs', 'incubators', 'incubateurs', 'materiel-elevage', 3, 'en'),
('couveuses', 'brooders', 'couveuses', 'materiel-elevage', 3, 'en'),
('cages-elevage', 'breeding cages', 'cages-elevage', 'materiel-elevage', 3, 'en'),
('accessoires-reproduction', 'Reproduction Accessories', 'accessoires-reproduction', 'elevage-reproduction', 2, 'en'),
('accessoires-accouplement', 'mating accessories', 'accessoires-accouplement', 'accessoires-reproduction', 3, 'en'),
('reproducteurs-selectionnes', 'Selected Breeders', 'reproducteurs-selectionnes', 'elevage-reproduction', 2, 'en'),
('reproducteurs', 'selected breeders', 'reproducteurs', 'reproducteurs-selectionnes', 3, 'en'),
('jeunes-animaux', 'Young Animals', 'jeunes-animaux', 'elevage-reproduction', 2, 'en'),
('poussins', 'chicks', 'poussins', 'jeunes-animaux', 3, 'en'),
('agneaux', 'lambs', 'agneaux', 'jeunes-animaux', 3, 'en'),
('chevreaux', 'kids', 'chevreaux', 'jeunes-animaux', 3, 'en'),
('services-elevage', 'Breeding Services', 'services-elevage', 'elevage-reproduction', 2, 'en'),
('assistance-elevage', 'breeding assistance services', 'assistance-elevage', 'services-elevage', 3, 'en'),
('conseils-specialises', 'specialized advice', 'conseils-specialises', 'services-elevage', 3, 'en'),
('genetique-selection', 'genetics & selection', 'genetique-selection', 'services-elevage', 3, 'en'),

-- Animal Services
('services-animaliers', 'Animal Services', 'services-animaliers', 'animaux-accessoires', 1, 'en'),
('toilettage', 'Grooming', 'toilettage', 'services-animaliers', 2, 'en'),
('toilettage-chiens', 'dog grooming', 'toilettage-chiens', 'toilettage', 3, 'en'),
('toilettage-chats', 'cat grooming', 'toilettage-chats', 'toilettage', 3, 'en'),
('dressage-education', 'Training & Education', 'dressage-education', 'services-animaliers', 2, 'en'),
('dressage-canin', 'dog training', 'dressage-canin', 'dressage-education', 3, 'en'),
('education-canine', 'canine education', 'education-canine', 'dressage-education', 3, 'en'),
('pension-garde', 'Boarding & Care', 'pension-garde', 'services-animaliers', 2, 'en'),
('pension-animaux', 'animal boarding & care', 'pension-animaux', 'pension-garde', 3, 'en'),
('promenades-soins', 'Walks & Care', 'promenades-soins', 'services-animaliers', 2, 'en'),
('promenades', 'walks', 'promenades', 'promenades-soins', 3, 'en'),
('soins-domicile', 'home care', 'soins-domicile', 'promenades-soins', 3, 'en'),
('comportement-adoption', 'Behavior & Adoption', 'comportement-adoption', 'services-animaliers', 2, 'en'),
('consultation-comportementaliste', 'behaviorist consultation', 'consultation-comportementaliste', 'comportement-adoption', 3, 'en'),
('adoption', 'adoption', 'adoption', 'comportement-adoption', 3, 'en'),
('services-speciaux', 'Special Services', 'services-speciaux', 'services-animaliers', 2, 'en'),
('photographie-animaliere', 'animal photography', 'photographie-animaliere', 'services-speciaux', 3, 'en'),
('transport-animaux', 'animal transport', 'transport-animaux', 'services-speciaux', 3, 'en'),
('services-veterinaires', 'private veterinary services', 'services-veterinaires', 'services-speciaux', 3, 'en'),

-- Outdoor Products
('produits-exterieurs', 'Outdoor Products', 'produits-exterieurs', 'animaux-accessoires', 1, 'en'),
('clotures-enclos', 'Fences & Enclosures', 'clotures-enclos', 'produits-exterieurs', 2, 'en'),
('clotures-animaux', 'animal fences', 'clotures-animaux', 'clotures-enclos', 3, 'en'),
('enclos', 'enclosures', 'enclos', 'clotures-enclos', 3, 'en'),
('abris-exterieurs', 'Outdoor Shelters', 'abris-exterieurs', 'produits-exterieurs', 2, 'en'),
('abris-exterieurs-animaux', 'outdoor shelters', 'abris-exterieurs-animaux', 'abris-exterieurs', 3, 'en'),
('alimentation-automatique', 'Automatic Feeding', 'alimentation-automatique', 'produits-exterieurs', 2, 'en'),
('mangeoires-auto', 'automatic feeders', 'mangeoires-auto', 'alimentation-automatique', 3, 'en'),
('systemes-abreuvement', 'watering systems', 'systemes-abreuvement', 'alimentation-automatique', 3, 'en'),
('equipements-elevage-exterieur', 'Outdoor Farming Equipment', 'equipements-elevage-exterieur', 'produits-exterieurs', 2, 'en'),
('materiel-plein-air', 'outdoor farming equipment', 'materiel-plein-air', 'equipements-elevage-exterieur', 3, 'en'),
('confort-thermique', 'Thermal Comfort', 'confort-thermique', 'produits-exterieurs', 2, 'en'),
('lampes-chauffantes', 'heating lamps', 'lampes-chauffantes', 'confort-thermique', 3, 'en'),
('accessoires-volières', 'Aviary & Coop Accessories', 'accessoires-volières', 'produits-exterieurs', 2, 'en'),
('materiel-volières', 'aviary & coop equipment', 'materiel-volières', 'accessoires-volières', 3, 'en'),

-- ESPAGNOL
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('animaux-accessoires', 'Animales y Accesorios', 'animaux-accessoires', NULL, 0, 'es');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
-- Animales Domésticos
('animaux-domestiques', 'Animales Domésticos', 'animaux-domestiques', 'animaux-accessoires', 1, 'es'),
('chiens', 'Perros', 'chiens', 'animaux-domestiques', 2, 'es'),
('chiots-races', 'cachorros de raza', 'chiots-races', 'chiens', 3, 'es'),
('chiens-adultes', 'perros adultos', 'chiens-adultes', 'chiens', 3, 'es'),
('chiens-dresses', 'perros entrenados', 'chiens-dresses', 'chiens', 3, 'es'),
('chats', 'Gatos', 'chats', 'animaux-domestiques', 2, 'es'),
('chatons-races', 'gatitos de raza', 'chatons-races', 'chats', 3, 'es'),
('chats-adultes', 'gatos adultos', 'chats-adultes', 'chats', 3, 'es'),
('oiseaux', 'aves', 'oiseaux', 'animaux-domestiques', 2, 'es'),
('oiseaux-rares', 'aves raras', 'oiseaux-rares', 'oiseaux', 3, 'es'),
('canaris', 'canarios', 'canaris', 'oiseaux', 3, 'es'),
('poissons', 'peces', 'poissons', 'animaux-domestiques', 2, 'es'),
('poissons-aquarium', 'peces de acuario', 'poissons-aquarium', 'poissons', 3, 'es'),
('rongeurs', 'roedores', 'rongeurs', 'animaux-domestiques', 2, 'es'),
('lapins', 'conejos', 'lapins', 'rongeurs', 3, 'es'),
('hamsters', 'hámsters', 'hamsters', 'rongeurs', 3, 'es'),
('reptiles', 'reptiles', 'reptiles', 'animaux-domestiques', 2, 'es'),
('tortues', 'tortugas', 'tortues', 'reptiles', 3, 'es'),

-- Animales de Cría
('animaux-elevage', 'Animales de Cría', 'animaux-elevage', 'animaux-accessoires', 1, 'es'),
('ovins', 'ovinos', 'ovins', 'animaux-elevage', 2, 'es'),
('bovins', 'bovinos', 'bovins', 'animaux-elevage', 2, 'es'),
('caprins', 'caprinos', 'caprins', 'animaux-elevage', 2, 'es'),
('volailles', 'aves de corral', 'volailles', 'animaux-elevage', 2, 'es'),
('equides', 'equinos', 'equides', 'animaux-elevage', 2, 'es'),

-- Alimentación & Cuidado Animal
('nourriture-soins', 'Alimentación & Cuidado Animal', 'nourriture-soins', 'animaux-accessoires', 1, 'es'),
('alimentation-chiens-chats', 'Alimentación Perros & Gatos', 'alimentation-chiens-chats', 'nourriture-soins', 2, 'es'),
('croquettes', 'croquetas', 'croquettes', 'alimentation-chiens-chats', 3, 'es'),
('patees', 'patés', 'patees', 'alimentation-chiens-chats', 3, 'es'),
('friandises', 'golosinas', 'friandises', 'alimentation-chiens-chats', 3, 'es'),
('alimentation-oiseaux', 'Alimentación Aves', 'alimentation-oiseaux', 'nourriture-soins', 2, 'es'),
('melanges-oiseaux', 'mezclas para aves', 'melanges-oiseaux', 'alimentation-oiseaux', 3, 'es'),
('alimentation-poissons', 'Alimentación Peces', 'alimentation-poissons', 'nourriture-soins', 2, 'es'),
('aliments-poissons', 'alimentos para peces', 'aliments-poissons', 'alimentation-poissons', 3, 'es'),
('soins-hygiene', 'Cuidado & Higiene', 'soins-hygiene', 'nourriture-soins', 2, 'es'),
('produits-hygiene', 'productos de higiene', 'produits-hygiene', 'soins-hygiene', 3, 'es'),
('shampoings', 'champús', 'shampoings', 'soins-hygiene', 3, 'es'),
('antiparasitaires', 'antiparasitarios', 'antiparasitaires', 'soins-hygiene', 3, 'es'),
('anti-tiques', 'anti-garrapatas', 'anti-tiques', 'soins-hygiene', 3, 'es'),
('produits-veterinaires', 'productos veterinarios', 'produits-veterinaires', 'soins-hygiene', 3, 'es'),
('complements-alimentaires', 'Complementos Alimenticios', 'complements-alimentaires', 'nourriture-soins', 2, 'es'),
('vitamines', 'vitaminas', 'vitamines', 'complements-alimentaires', 3, 'es'),

-- Accesorios & Equipos
('accessoires-equipements', 'Accesorios & Equipos', 'accessoires-equipements', 'animaux-accessoires', 1, 'es'),
('accessoires-promenade', 'Accesorios de Paseo', 'accessoires-promenade', 'accessoires-equipements', 2, 'es'),
('laisses', 'correas', 'laisses', 'accessoires-promenade', 3, 'es'),
('colliers', 'collares', 'colliers', 'accessoires-promenade', 3, 'es'),
('harnais', 'arneses', 'harnais', 'accessoires-promenade', 3, 'es'),
('habitats', 'Hábitats', 'habitats', 'accessoires-equipements', 2, 'es'),
('cages', 'jaulas', 'cages', 'habitats', 3, 'es'),
('volières', 'pajareras', 'volières', 'habitats', 3, 'es'),
('niches', 'casetas', 'niches', 'habitats', 3, 'es'),
('aquariums', 'acuarios', 'aquariums', 'habitats', 3, 'es'),
('terrariums', 'terrarios', 'terrariums', 'habitats', 3, 'es'),
('confort-dodo', 'Confort & Descanso', 'confort-dodo', 'accessoires-equipements', 2, 'es'),
('paniers', 'cestas', 'paniers', 'confort-dodo', 3, 'es'),
('coussins', 'cojines', 'coussins', 'confort-dodo', 3, 'es'),
('arbres-chat', 'árboles para gatos', 'arbres-chat', 'confort-dodo', 3, 'es'),
('alimentacion-accesorios', 'Alimentación & Accesorios', 'alimentation-accessoires', 'accessoires-equipements', 2, 'es'),
('gamelles', 'tazones', 'gamelles', 'alimentacion-accesorios', 3, 'es'),
('distributeurs-auto', 'dispensadores automáticos', 'distributeurs-auto', 'alimentacion-accesorios', 3, 'es'),
('fontaines-eau', 'fuentes de agua', 'fontaines-eau', 'alimentacion-accesorios', 3, 'es'),
('litiène-hygiene', 'Arena & Higiene', 'litières-hygiene', 'accessoires-equipements', 2, 'es'),
('litières', 'arenas', 'litières', 'litiène-hygiene', 3, 'es'),
('bacs-litiere', 'bandejas de arena', 'bacs-litiere', 'litiène-hygiene', 3, 'es'),
('jouets-loisirs', 'Juguetes & Ocio', 'jouets-loisirs', 'accessoires-equipements', 2, 'es'),
('jouets', 'juguetes', 'jouets', 'jouets-loisirs', 3, 'es'),
('transport', 'Transporte', 'transport', 'accessoires-equipements', 2, 'es'),
('paniers-transport', 'cestas de transporte', 'paniers-transport', 'transport', 3, 'es'),

-- Cría & Reproducción
('elevage-reproduction', 'Cría & Reproducción', 'elevage-reproduction', 'animaux-accessoires', 1, 'es'),
('materiel-elevage', 'Material de Cría', 'materiel-elevage', 'elevage-reproduction', 2, 'es'),
('incubateurs', 'incubadoras', 'incubateurs', 'materiel-elevage', 3, 'es'),
('couveuses', 'cobederas', 'couveuses', 'materiel-elevage', 3, 'es'),
('cages-elevage', 'jaulas de cría', 'cages-elevage', 'materiel-elevage', 3, 'es'),
('accessoires-reproduction', 'Accesorios de Reproducción', 'accessoires-reproduction', 'elevage-reproduction', 2, 'es'),
('accessoires-accouplement', 'accesorios de apareamiento', 'accessoires-accouplement', 'accessoires-reproduction', 3, 'es'),
('reproducteurs-selectionnes', 'Reproductores Seleccionados', 'reproducteurs-selectionnes', 'elevage-reproduction', 2, 'es'),
('reproducteurs', 'reproductores seleccionados', 'reproducteurs', 'reproducteurs-selectionnes', 3, 'es'),
('jeunes-animaux', 'Animales Jóvenes', 'jeunes-animaux', 'elevage-reproduction', 2, 'es'),
('poussins', 'polluelos', 'poussins', 'jeunes-animaux', 3, 'es'),
('agneaux', 'corderos', 'agneaux', 'jeunes-animaux', 3, 'es'),
('chevreaux', 'cabritos', 'chevreaux', 'jeunes-animaux', 3, 'es'),
('services-elevage', 'Servicios de Cría', 'services-elevage', 'elevage-reproduction', 2, 'es'),
('assistance-elevage', 'servicios de asistencia a la cría', 'assistance-elevage', 'services-elevage', 3, 'es'),
('conseils-specialises', 'asesoramiento especializado', 'conseils-specialises', 'services-elevage', 3, 'es'),
('genetique-selection', 'genética & selección', 'genetique-selection', 'services-elevage', 3, 'es'),

-- Servicios Animales
('services-animaliers', 'Servicios Animales', 'services-animaliers', 'animaux-accessoires', 1, 'es'),
('toilettage', 'Estética', 'toilettage', 'services-animaliers', 2, 'es'),
('toilettage-chiens', 'estética canina', 'toilettage-chiens', 'toilettage', 3, 'es'),
('toilettage-chats', 'estética felina', 'toilettage-chats', 'toilettage', 3, 'es'),
('dressage-education', 'Adiestramiento & Educación', 'dressage-education', 'services-animaliers', 2, 'es'),
('dressage-canin', 'adiestramiento canino', 'dressage-canin', 'dressage-education', 3, 'es'),
('education-canine', 'educación canina', 'education-canine', 'dressage-education', 3, 'es'),
('pension-garde', 'Pensión & Guardería', 'pension-garde', 'services-animaliers', 2, 'es'),
('pension-animaux', 'pensión & guardería de animales', 'pension-animaux', 'pension-garde', 3, 'es'),
('promenades-soins', 'Paseos & Cuidados', 'promenades-soins', 'services-animaliers', 2, 'es'),
('promenades', 'paseos', 'promenades', 'promenades-soins', 3, 'es'),
('soins-domicile', 'cuidados a domicilio', 'soins-domicile', 'promenades-soins', 3, 'es'),
('comportement-adoption', 'Comportamiento & Adopción', 'comportement-adoption', 'services-animaliers', 2, 'es'),
('consultation-comportementaliste', 'consulta etóloga', 'consultation-comportementaliste', 'comportement-adoption', 3, 'es'),
('adoption', 'adopción', 'adoption', 'comportement-adoption', 3, 'es'),
('services-speciaux', 'Servicios Especiales', 'services-speciaux', 'services-animaliers', 2, 'es'),
('photographie-animaliere', 'fotografía animal', 'photographie-animaliere', 'services-speciaux', 3, 'es'),
('transport-animaux', 'transporte de animales', 'transport-animaux', 'services-speciaux', 3, 'es'),
('services-veterinaires', 'servicios veterinarios privados', 'services-veterinaires', 'services-speciaux', 3, 'es'),

-- Productos & Accesorios Exteriores
('produits-exterieurs', 'Productos & Accesorios Exteriores', 'produits-exterieurs', 'animaux-accessoires', 1, 'es'),
('clotures-enclos', 'Cercas & Recintos', 'clotures-enclos', 'produits-exterieurs', 2, 'es'),
('clotures-animaux', 'cercas para animales', 'clotures-animaux', 'clotures-enclos', 3, 'es'),
('enclos', 'recintos', 'enclos', 'clotures-enclos', 3, 'es'),
('abris-exterieurs', 'Refugios Exteriores', 'abris-exterieurs', 'produits-exterieurs', 2, 'es'),
('abris-exterieurs-animaux', 'refugios exteriores', 'abris-exterieurs-animaux', 'abris-exterieurs', 3, 'es'),
('alimentation-automatique', 'Alimentación Automática', 'alimentation-automatique', 'produits-exterieurs', 2, 'es'),
('mangeoires-auto', 'comedores automáticos', 'mangeoires-auto', 'alimentation-automatique', 3, 'es'),
('systemes-abreuvement', 'sistemas de abrevadero', 'systemes-abreuvement', 'alimentation-automatique', 3, 'es'),
('equipements-elevage-exterieur', 'Equipos Cría Exterior', 'equipements-elevage-exterieur', 'produits-exterieurs', 2, 'es'),
('materiel-plein-air', 'material para cría al aire libre', 'materiel-plein-air', 'equipements-elevage-exterieur', 3, 'es'),
('confort-thermique', 'Confort Térmico', 'confort-thermique', 'produits-exterieurs', 2, 'es'),
('lampes-chauffantes', 'lámparas calefactoras', 'lampes-chauffantes', 'confort-thermique', 3, 'es'),
('accessoires-volières', 'Accesorios Volieras & Gallineros', 'accessoires-volières', 'produits-exterieurs', 2, 'es'),
('materiel-volières', 'material para volieras & gallineros', 'materiel-volières', 'accessoires-volières', 3, 'es'),

-- DEUTSCH
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('animaux-accessoires', 'Tiere & Zubehör', 'animaux-accessoires', NULL, 0, 'de');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
-- Haustiere
('animaux-domestiques', 'Haustiere', 'animaux-domestiques', 'animaux-accessoires', 1, 'de'),
('chiens', 'Hunde', 'chiens', 'animaux-domestiques', 2, 'de'),
('chiots-races', 'Rassenwelpen', 'chiots-races', 'chiens', 3, 'de'),
('chiens-adultes', 'Erwachsene Hunde', 'chiens-adultes', 'chiens', 3, 'de'),
('chiens-dresses', 'Abgerichtete Hunde', 'chiens-dresses', 'chiens', 3, 'de'),
('chats', 'Katzen', 'chats', 'animaux-domestiques', 2, 'de'),
('chatons-races', 'Rassenkätzchen', 'chatons-races', 'chats', 3, 'de'),
('chats-adultes', 'Erwachsene Katzen', 'chats-adultes', 'chats', 3, 'de'),
('oiseaux', 'Vögel', 'oiseaux', 'animaux-domestiques', 2, 'de'),
('oiseaux-rares', 'Seltene Vögel', 'oiseaux-rares', 'oiseaux', 3, 'de'),
('canaris', 'Kanarienvögel', 'canaris', 'oiseaux', 3, 'de'),
('poissons', 'Fische', 'poissons', 'animaux-domestiques', 2, 'de'),
('poissons-aquarium', 'Aquariumfische', 'poissons-aquarium', 'poissons', 3, 'de'),
('rongeurs', 'Nagetiere', 'rongeurs', 'animaux-domestiques', 2, 'de'),
('lapins', 'Kaninchen', 'lapins', 'rongeurs', 3, 'de'),
('hamsters', 'Hamster', 'hamsters', 'rongeurs', 3, 'de'),
('reptiles', 'Reptilien', 'reptiles', 'animaux-domestiques', 2, 'de'),
('tortues', 'Schildkröten', 'tortues', 'reptiles', 3, 'de'),

-- Nutztiere
('animaux-elevage', 'Nutztiere', 'animaux-elevage', 'animaux-accessoires', 1, 'de'),
('ovins', 'Schafe', 'ovins', 'animaux-elevage', 2, 'de'),
('bovins', 'Rinder', 'bovins', 'animaux-elevage', 2, 'de'),
('caprins', 'Ziegen', 'caprins', 'animaux-elevage', 2, 'de'),
('volailles', 'Geflügel', 'volailles', 'animaux-elevage', 2, 'de'),
('equides', 'Pferde', 'equides', 'animaux-elevage', 2, 'de'),

-- Tiernahrung & Pflege
('nourriture-soins', 'Tiernahrung & Pflege', 'nourriture-soins', 'animaux-accessoires', 1, 'de'),
('alimentation-chiens-chats', 'Hunde- & Katzenfutter', 'alimentation-chiens-chats', 'nourriture-soins', 2, 'de'),
('croquettes', 'Trockenfutter', 'croquettes', 'alimentation-chiens-chats', 3, 'de'),
('patees', 'Nassfutter', 'patees', 'alimentation-chiens-chats', 3, 'de'),
('friandises', 'Leckerli', 'friandises', 'alimentation-chiens-chats', 3, 'de'),
('alimentation-oiseaux', 'Vogelfutter', 'alimentation-oiseaux', 'nourriture-soins', 2, 'de'),
('melanges-oiseaux', 'Vogelsamenmischungen', 'melanges-oiseaux', 'alimentation-oiseaux', 3, 'de'),
('alimentation-poissons', 'Fischfutter', 'alimentation-poissons', 'nourriture-soins', 2, 'de'),
('aliments-poissons', 'Fischfutter', 'aliments-poissons', 'alimentation-poissons', 3, 'de'),
('soins-hygiene', 'Pflege & Hygiene', 'soins-hygiene', 'nourriture-soins', 2, 'de'),
('produits-hygiene', 'Hygieneprodukte', 'produits-hygiene', 'soins-hygiene', 3, 'de'),
('shampoings', 'Shampoos', 'shampoings', 'soins-hygiene', 3, 'de'),
('antiparasitaires', 'Antiparasitika', 'antiparasitaires', 'soins-hygiene', 3, 'de'),
('anti-tiques', 'Zeckenschutz', 'anti-tiques', 'soins-hygiene', 3, 'de'),
('produits-veterinaires', 'Veterinärprodukte', 'produits-veterinaires', 'soins-hygiene', 3, 'de'),
('complements-alimentaires', 'Nahrungsergänzungsmittel', 'complements-alimentaires', 'nourriture-soins', 2, 'de'),
('vitamines', 'Vitamine', 'vitamines', 'complements-alimentaires', 3, 'de'),

-- Zubehör & Ausstattung
('accessoires-equipements', 'Zubehör & Ausstattung', 'accessoires-equipements', 'animaux-accessoires', 1, 'de'),
('accessoires-promenade', 'Spaziergäng-Zubehör', 'accessoires-promenade', 'accessoires-equipements', 2, 'de'),
('laisses', 'Leinen', 'laisses', 'accessoires-promenade', 3, 'de'),
('colliers', 'Halsbänder', 'colliers', 'accessoires-promenade', 3, 'de'),
('harnais', 'Geschirre', 'harnais', 'accessoires-promenade', 3, 'de'),
('habitats', 'Unterkünfte', 'habitats', 'accessoires-equipements', 2, 'de'),
('cages', 'Käfige', 'cages', 'habitats', 3, 'de'),
('volières', 'Voliere', 'volières', 'habitats', 3, 'de'),
('niches', 'Hundehütten', 'niches', 'habitats', 3, 'de'),
('aquariums', 'Aquarien', 'aquariums', 'habitats', 3, 'de'),
('terrariums', 'Terrarien', 'terrariums', 'habitats', 3, 'de'),
('confort-dodo', 'Komfort & Schlaf', 'confort-dodo', 'accessoires-equipements', 2, 'de'),
('paniers', 'Körbe', 'paniers', 'confort-dodo', 3, 'de'),
('coussins', 'Kissen', 'coussins', 'confort-dodo', 3, 'de'),
('arbres-chat', 'Kratzbäume', 'arbres-chat', 'confort-dodo', 3, 'de'),
('alimentation-accessoires', 'Futter & Zubehör', 'alimentation-accessoires', 'accessoires-equipements', 2, 'de'),
('gamelles', 'Futternäpfe', 'gamelles', 'alimentation-accessoires', 3, 'de'),
('distributeurs-auto', 'Automatische Futterspender', 'distributeurs-auto', 'alimentation-accessoires', 3, 'de'),
('fontaines-eau', 'Wasserbrunnen', 'fontaines-eau', 'alimentation-accessoires', 3, 'de'),
('litières-hygiene', 'Katzenstreu & Hygiene', 'litières-hygiene', 'accessoires-equipements', 2, 'de'),
('litières', 'Katzenstreu', 'litières', 'litières-hygiene', 3, 'de'),
('bacs-litiere', 'Katzentoiletten', 'bacs-litiere', 'litières-hygiene', 3, 'de'),
('jouets-loisirs', 'Spielzeug & Freizeit', 'jouets-loisirs', 'accessoires-equipements', 2, 'de'),
('jouets', 'Spielzeug', 'jouets', 'jouets-loisirs', 3, 'de'),
('transport', 'Transport', 'transport', 'accessoires-equipements', 2, 'de'),
('paniers-transport', 'Transportkörbe', 'paniers-transport', 'transport', 3, 'de'),

-- Zucht & Fortpflanzung
('elevage-reproduction', 'Zucht & Fortpflanzung', 'elevage-reproduction', 'animaux-accessoires', 1, 'de'),
('materiel-elevage', 'Zuchtausrüstung', 'materiel-elevage', 'elevage-reproduction', 2, 'de'),
('incubateurs', 'Brutapparate', 'incubateurs', 'materiel-elevage', 3, 'de'),
('couveuses', 'Brutmaschinen', 'couveuses', 'materiel-elevage', 3, 'de'),
('cages-elevage', 'Zuchtkäfige', 'cages-elevage', 'materiel-elevage', 3, 'de'),
('accessoires-reproduction', 'Fortpflanzungszubehör', 'accessoires-reproduction', 'elevage-reproduction', 2, 'de'),
('accessoires-accouplement', 'Paarungszubehör', 'accessoires-accouplement', 'accessoires-reproduction', 3, 'de'),
('reproducteurs-selectionnes', 'Ausgewählte Zuchttiere', 'reproducteurs-selectionnes', 'elevage-reproduction', 2, 'de'),
('reproducteurs', 'Ausgewählte Zuchttiere', 'reproducteurs', 'reproducteurs-selectionnes', 3, 'de'),
('jeunes-animaux', 'Jungtiere', 'jeunes-animaux', 'elevage-reproduction', 2, 'de'),
('poussins', 'Küken', 'poussins', 'jeunes-animaux', 3, 'de'),
('agneaux', 'Lämmer', 'agneaux', 'jeunes-animaux', 3, 'de'),
('chevreaux', 'Zicklein', 'chevreaux', 'jeunes-animaux', 3, 'de'),
('services-elevage', 'Zuchtdienstleistungen', 'services-elevage', 'elevage-reproduction', 2, 'de'),
('assistance-elevage', 'Zuchtunterstützungsdienste', 'assistance-elevage', 'services-elevage', 3, 'de'),
('conseils-specialises', 'Spezialberatung', 'conseils-specialises', 'services-elevage', 3, 'de'),
('genetique-selection', 'Genetik & Selektion', 'genetique-selection', 'services-elevage', 3, 'de'),

-- Tierdienstleistungen
('services-animaliers', 'Tierdienstleistungen', 'services-animaliers', 'animaux-accessoires', 1, 'de'),
('toilettage', 'Tierpflege', 'toilettage', 'services-animaliers', 2, 'de'),
('toilettage-chiens', 'Hundepflege', 'toilettage-chiens', 'toilettage', 3, 'de'),
('toilettage-chats', 'Katzenpflege', 'toilettage-chats', 'toilettage', 3, 'de'),
('dressage-education', 'Abrichtung & Erziehung', 'dressage-education', 'services-animaliers', 2, 'de'),
('dressage-canin', 'Hundeabrichtung', 'dressage-canin', 'dressage-education', 3, 'de'),
('education-canine', 'Hundeerziehung', 'education-canine', 'dressage-education', 3, 'de'),
('pension-garde', 'Pension & Betreuung', 'pension-garde', 'services-animaliers', 2, 'de'),
('pension-animaux', 'Tierpension & -betreuung', 'pension-animaux', 'pension-garde', 3, 'de'),
('promenades-soins', 'Gassigehen & Pflege', 'promenades-soins', 'services-animaliers', 2, 'de'),
('promenades', 'Gassigehen', 'promenades', 'promenades-soins', 3, 'de'),
('soins-domicile', 'Hausbesuchspflege', 'soins-domicile', 'promenades-soins', 3, 'de'),
('comportement-adoption', 'Verhalten & Adoption', 'comportement-adoption', 'services-animaliers', 2, 'de'),
('consultation-comportementaliste', 'Verhaltenstherapie', 'consultation-comportementaliste', 'comportement-adoption', 3, 'de'),
('adoption', 'Adoption', 'adoption', 'comportement-adoption', 3, 'de'),
('services-speciaux', 'Spezialdienste', 'services-speciaux', 'services-animaliers', 2, 'de'),
('photographie-animaliere', 'Tierfotografie', 'photographie-animaliere', 'services-speciaux', 3, 'de'),
('transport-animaux', 'Tiertransport', 'transport-animaux', 'services-speciaux', 3, 'de'),
('services-veterinaires', 'Private Tierarztdienste', 'services-veterinaires', 'services-speciaux', 3, 'de'),

-- Produkte & Outdoor-Zubehör
('produits-exterieurs', 'Produkte & Outdoor-Zubehör', 'produits-exterieurs', 'animaux-accessoires', 1, 'de'),
('clotures-enclos', 'Zäune & Gehege', 'clotures-enclos', 'produits-exterieurs', 2, 'de'),
('clotures-animaux', 'Tierzäune', 'clotures-animaux', 'clotures-enclos', 3, 'de'),
('enclos', 'Gehege', 'enclos', 'clotures-enclos', 3, 'de'),
('abris-exterieurs', 'Outdoor-Unterstände', 'abris-exterieurs', 'produits-exterieurs', 2, 'de'),
('abris-exterieurs-animaux', 'Outdoor-Unterstände', 'abris-exterieurs-animaux', 'abris-exterieurs', 3, 'de'),
('alimentation-automatique', 'Automatische Fütterung', 'alimentation-automatique', 'produits-exterieurs', 2, 'de'),
('mangeoires-auto', 'Automatische Futterautomaten', 'mangeoires-auto', 'alimentation-automatique', 3, 'de'),
('systemes-abreuvement', 'Tränkesysteme', 'systemes-abreuvement', 'alimentation-automatique', 3, 'de'),
('equipements-elevage-exterieur', 'Outdoor-Zuchtausrüstung', 'equipements-elevage-exterieur', 'produits-exterieurs', 2, 'de'),
('materiel-plein-air', 'Outdoor-Zuchtausrüstung', 'materiel-plein-air', 'equipements-elevage-exterieur', 3, 'de'),
('confort-thermique', 'Thermischer Komfort', 'confort-thermique', 'produits-exterieurs', 2, 'de'),
('lampes-chauffantes', 'Wärmelampen', 'lampes-chauffantes', 'confort-thermique', 3, 'de'),
('accessoires-volières', 'Voliere- & Hühnerstall-Zubehör', 'accessoires-volières', 'produits-exterieurs', 2, 'de'),
('materiel-volières', 'Voliere- & Hühnerstall-Zubehör', 'materiel-volières', 'accessoires-volières', 3, 'de');

-- ITALIANO
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('animaux-accessoires', 'Animali e Accessori', 'animaux-accessoires', NULL, 0, 'it');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
-- Animali Domestici
('animaux-domestiques', 'Animali Domestici', 'animaux-domestiques', 'animaux-accessoires', 1, 'it'),
('chiens', 'Cani', 'chiens', 'animaux-domestiques', 2, 'it'),
('chiots-races', 'cuccioli di razza', 'chiots-races', 'chiens', 3, 'it'),
('chiens-adultes', 'cani adulti', 'chiens-adultes', 'chiens', 3, 'it'),
('chiens-dresses', 'cani addestrati', 'chiens-dresses', 'chiens', 3, 'it'),
('chats', 'Gatti', 'chats', 'animaux-domestiques', 2, 'it'),
('chatons-races', 'gattini di razza', 'chatons-races', 'chats', 3, 'it'),
('chats-adultes', 'gatti adulti', 'chats-adultes', 'chats', 3, 'it'),
('oiseaux', 'Uccelli', 'oiseaux', 'animaux-domestiques', 2, 'it'),
('oiseaux-rares', 'uccelli rari', 'oiseaux-rares', 'oiseaux', 3, 'it'),
('canaris', 'canarini', 'canaris', 'oiseaux', 3, 'it'),
('poissons', 'Pesci', 'poissons', 'animaux-domestiques', 2, 'it'),
('poissons-aquarium', 'pesci per acquario', 'poissons-aquarium', 'poissons', 3, 'it'),
('rongeurs', 'Roditori', 'rongeurs', 'animaux-domestiques', 2, 'it'),
('lapins', 'conigli', 'lapins', 'rongeurs', 3, 'it'),
('hamsters', 'criceti', 'hamsters', 'rongeurs', 3, 'it'),
('reptiles', 'Rettili', 'reptiles', 'animaux-domestiques', 2, 'it'),
('tortues', 'tartarughe', 'tortues', 'reptiles', 3, 'it'),

-- Animali da Allevamento
('animaux-elevage', 'Animali da Allevamento', 'animaux-elevage', 'animaux-accessoires', 1, 'it'),
('ovins', 'Ovini', 'ovins', 'animaux-elevage', 2, 'it'),
('bovins', 'Bovini', 'bovins', 'animaux-elevage', 2, 'it'),
('caprins', 'Caprini', 'caprins', 'animaux-elevage', 2, 'it'),
('volailles', 'Pollame', 'volailles', 'animaux-elevage', 2, 'it'),
('equides', 'Equini', 'equides', 'animaux-elevage', 2, 'it'),

-- Cibo & Cura degli Animali
('nourriture-soins', 'Cibo & Cura degli Animali', 'nourriture-soins', 'animaux-accessoires', 1, 'it'),
('alimentation-chiens-chats', 'Cibo per Cani & Gatti', 'alimentation-chiens-chats', 'nourriture-soins', 2, 'it'),
('croquettes', 'crocchette', 'croquettes', 'alimentation-chiens-chats', 3, 'it'),
('patees', 'pasta', 'patees', 'alimentation-chiens-chats', 3, 'it'),
('friandises', 'golosità', 'friandises', 'alimentation-chiens-chats', 3, 'it'),
('alimentation-oiseaux', 'Cibo per Uccelli', 'alimentation-oiseaux', 'nourriture-soins', 2, 'it'),
('melanges-oiseaux', 'miscugli per uccelli', 'melanges-oiseaux', 'alimentation-oiseaux', 3, 'it'),
('alimentation-poissons', 'Cibo per Pesci', 'alimentation-poissons', 'nourriture-soins', 2, 'it'),
('aliments-poissons', 'alimenti per pesci', 'aliments-poissons', 'alimentation-poissons', 3, 'it'),
('soins-hygiene', 'Cura e Igiene', 'soins-hygiene', 'nourriture-soins', 2, 'it'),
('produits-hygiene', 'prodotti per igiene', 'produits-hygiene', 'soins-hygiene', 3, 'it'),
('shampoings', 'shampoo', 'shampoings', 'soins-hygiene', 3, 'it'),
('antiparasitaires', 'antiparassitari', 'antiparasitaires', 'soins-hygiene', 3, 'it'),
('anti-tiques', 'anti-pulci', 'anti-tiques', 'soins-hygiene', 3, 'it'),
('produits-veterinaires', 'prodotti veterinari', 'produits-veterinaires', 'soins-hygiene', 3, 'it'),
('complements-alimentaires', 'Integratori Alimentari', 'complements-alimentaires', 'nourriture-soins', 2, 'it'),
('vitamines', 'vitamine', 'vitamines', 'complements-alimentaires', 3, 'it'),

-- Accessori & Equipaggiamenti
('accessoires-equipements', 'Accessori & Equipaggiamenti', 'accessoires-equipements', 'animaux-accessoires', 1, 'it'),
('accessoires-promenade', 'Accessori per Passeggiate', 'accessoires-promenade', 'accessoires-equipements', 2, 'it'),
('laisses', 'guinzagli', 'laisses', 'accessoires-promenade', 3, 'it'),
('colliers', 'collari', 'colliers', 'accessoires-promenade', 3, 'it'),
('harnais', 'imbracature', 'harnais', 'accessoires-promenade', 3, 'it'),
('habitats', 'Ambienti', 'habitats', 'accessoires-equipements', 2, 'it'),
('cages', 'gabbie', 'cages', 'habitats', 3, 'it'),
('volières', 'voliera', 'volières', 'habitats', 3, 'it'),
('niches', 'cuccette', 'niches', 'habitats', 3, 'it'),
('aquariums', 'acquari', 'aquariums', 'habitats', 3, 'it'),
('terrariums', 'terrari', 'terrariums', 'habitats', 3, 'it'),
('confort-dodo', 'Confort & Sonno', 'confort-dodo', 'accessoires-equipements', 2, 'it'),
('paniers', 'cestini', 'paniers', 'confort-dodo', 3, 'it'),
('coussins', 'cuscini', 'coussins', 'confort-dodo', 3, 'it'),
('arbres-chat', 'alberi per gatti', 'arbres-chat', 'confort-dodo', 3, 'it'),
('alimentation-accessoires', 'Alimentazione & Accessori', 'alimentation-accessoires', 'accessoires-equipements', 2, 'it'),
('gamelles', 'ciotole', 'gamelles', 'alimentation-accessoires', 3, 'it'),
('distributeurs-auto', 'distributori automatici', 'distributeurs-auto', 'alimentation-accessoires', 3, 'it'),
('fontaines-eau', 'fontane d\'acqua', 'fontaines-eau', 'alimentation-accessoires', 3, 'it'),
('litières-hygiene', 'Lettiere & Igiene', 'litières-hygiene', 'accessoires-equipements', 2, 'it'),
('litières', 'lettiere', 'litières', 'litières-hygiene', 3, 'it'),
('bacs-litiere', 'vaschette lettiera', 'bacs-litiere', 'litières-hygiene', 3, 'it'),
('jouets-loisirs', 'Giocattoli & Tempo Libero', 'jouets-loisirs', 'accessoires-equipements', 2, 'it'),
('jouets', 'giocattoli', 'jouets', 'jouets-loisirs', 3, 'it'),
('transport', 'Trasporto', 'transport', 'accessoires-equipements', 2, 'it'),
('paniers-transport', 'cestini da trasporto', 'paniers-transport', 'transport', 3, 'it'),

-- Allevamento & Riproduzione
('elevage-reproduction', 'Allevamento & Riproduzione', 'elevage-reproduction', 'animaux-accessoires', 1, 'it'),
('materiel-elevage', 'Attrezzature per Allevamento', 'materiel-elevage', 'elevage-reproduction', 2, 'it'),
('incubateurs', 'incubatrici', 'incubateurs', 'materiel-elevage', 3, 'it'),
('couveuses', 'covatrici', 'couveuses', 'materiel-elevage', 3, 'it'),
('cages-elevage', 'gabbie da allevamento', 'cages-elevage', 'materiel-elevage', 3, 'it'),
('accessoires-reproduction', 'Accessori per la Riproduzione', 'accessoires-reproduction', 'elevage-reproduction', 2, 'it'),
('accessoires-accouplement', 'accessori per l\'accoppiamento', 'accessoires-accouplement', 'accessoires-reproduction', 3, 'it'),
('reproducteurs-selectionnes', 'Riproduttori Selezionati', 'reproducteurs-selectionnes', 'elevage-reproduction', 2, 'it'),
('reproducteurs', 'riproduttori selezionati', 'reproducteurs', 'reproducteurs-selectionnes', 3, 'it'),
('jeunes-animaux', 'Giovani Animali', 'jeunes-animaux', 'elevage-reproduction', 2, 'it'),
('poussins', 'pulcini', 'poussins', 'jeunes-animaux', 3, 'it'),
('agneaux', 'agnelli', 'agneaux', 'jeunes-animaux', 3, 'it'),
('chevreaux', 'capretti', 'chevreaux', 'jeunes-animaux', 3, 'it'),
('services-elevage', 'Servizi per Allevamento', 'services-elevage', 'elevage-reproduction', 2, 'it'),
('assistance-elevage', 'servizi di assistenza allevamento', 'assistance-elevage', 'services-elevage', 3, 'it'),
('conseils-specialises', 'consigli specialistici', 'conseils-specialises', 'services-elevage', 3, 'it'),
('genetique-selection', 'genetica e selezione', 'genetique-selection', 'services-elevage', 3, 'it'),

-- Servizi per Animali
('services-animaliers', 'Servizi per Animali', 'services-animaliers', 'animaux-accessoires', 1, 'it'),
('toilettage', 'Toelettatura', 'toilettage', 'services-animaliers', 2, 'it'),
('toilettage-chiens', 'toelettatura cani', 'toilettage-chiens', 'toilettage', 3, 'it'),
('toilettage-chats', 'toelettatura gatti', 'toilettage-chats', 'toilettage', 3, 'it'),
('dressage-education', 'Addestramento & Educazione', 'dressage-education', 'services-animaliers', 2, 'it'),
('dressage-canin', 'addestramento cani', 'dressage-canin', 'dressage-education', 3, 'it'),
('education-canine', 'educazione canina', 'education-canine', 'dressage-education', 3, 'it'),
('pension-garde', 'Pensione & Guardia', 'pension-garde', 'services-animaliers', 2, 'it'),
('pension-animaux', 'pensione e guardia animali', 'pension-animaux', 'pension-garde', 3, 'it'),
('promenades-soins', 'Passeggiate & Cure', 'promenades-soins', 'services-animaliers', 2, 'it'),
('promenades', 'passeggiate', 'promenades', 'promenades-soins', 3, 'it'),
('soins-domicile', 'cure a domicilio', 'soins-domicile', 'promenades-soins', 3, 'it'),
('comportement-adoption', 'Comportamento & Adozione', 'comportement-adoption', 'services-animaliers', 2, 'it'),
('consultation-comportementaliste', 'consultazione comportamentalista', 'consultation-comportementaliste', 'comportement-adoption', 3, 'it'),
('adoption', 'adozione', 'adoption', 'comportement-adoption', 3, 'it'),
('services-speciaux', 'Servizi Speciali', 'services-speciaux', 'services-animaliers', 2, 'it'),
('photographie-animaliere', 'fotografia di animali', 'photographie-animaliere', 'services-speciaux', 3, 'it'),
('transport-animaux', 'trasporto animali', 'transport-animaux', 'services-speciaux', 3, 'it'),
('services-veterinaires', 'servizi veterinari privati', 'services-veterinaires', 'services-speciaux', 3, 'it'),

-- Prodotti per Esterni
('produits-exterieurs', 'Prodotti per Esterni', 'produits-exterieurs', 'animaux-accessoires', 1, 'it'),
('clotures-enclos', 'Recinzioni & Recinti', 'clotures-enclos', 'produits-exterieurs', 2, 'it'),
('clotures-animaux', 'recinzioni per animali', 'clotures-animaux', 'clotures-enclos', 3, 'it'),
('enclos', 'recinti', 'enclos', 'clotures-enclos', 3, 'it'),
('abris-exterieurs', 'Rifugi per Esterni', 'abris-exterieurs', 'produits-exterieurs', 2, 'it'),
('abris-exterieurs-animaux', 'rifugi per animali esterni', 'abris-exterieurs-animaux', 'abris-exterieurs', 3, 'it'),
('alimentation-automatique', 'Alimentazione Automatica', 'alimentation-automatique', 'produits-exterieurs', 2, 'it'),
('mangeoires-auto', 'mangimi automatici', 'mangeoires-auto', 'alimentation-automatique', 3, 'it'),
('systemes-abreuvement', 'sistemi di abbeverata', 'systemes-abreuvement', 'alimentation-automatique', 3, 'it'),
('equipements-elevage-exterieur', 'Equipaggiamento Allevamento Esterno', 'equipements-elevage-exterieur', 'produits-exterieurs', 2, 'it'),
('materiel-plein-air', 'attrezzatura per allevamento all\'aperto', 'materiel-plein-air', 'equipements-elevage-exterieur', 3, 'it'),
('confort-thermique', 'Confort Termico', 'confort-thermique', 'produits-exterieurs', 2, 'it'),
('lampes-chauffantes', 'lampade riscaldanti', 'lampes-chauffantes', 'confort-thermique', 3, 'it'),
('accessoires-volières', 'Accessori Voliere & Pollaio', 'accessoires-volières', 'produits-exterieurs', 2, 'it'),
('materiel-volières', 'accessori per voliere e pollai', 'materiel-volières', 'accessoires-volières', 3, 'it');

-- ARABE
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('animaux-accessoires', 'الحيوانات والإكسسوارات', 'animaux-accessoires', NULL, 0, 'ar');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
-- الحيوانات الأليفة
('animaux-domestiques', 'الحيوانات الأليفة', 'animaux-domestiques', 'animaux-accessoires', 1, 'ar'),
('chiens', 'الكلاب', 'chiens', 'animaux-domestiques', 2, 'ar'),
('chiots-races', 'جروات عرقية', 'chiots-races', 'chiens', 3, 'ar'),
('chiens-adultes', 'كلاب بالغة', 'chiens-adultes', 'chiens', 3, 'ar'),
('chiens-dresses', 'كلاب مدربة', 'chiens-dresses', 'chiens', 3, 'ar'),
('chats', 'القطط', 'chats', 'animaux-domestiques', 2, 'ar'),
('chatons-races', 'قطط صغيرة عرقية', 'chatons-races', 'chats', 3, 'ar'),
('chats-adultes', 'قطط بالغة', 'chats-adultes', 'chats', 3, 'ar'),
('chats-exotiques', 'قطط غريبة', 'chats-exotiques', 'chats', 3, 'ar'),
('oiseaux', 'الطيور', 'oiseaux', 'animaux-domestiques', 2, 'ar'),
('oiseaux-domestiques', 'طيور منزلية', 'oiseaux-domestiques', 'oiseaux', 3, 'ar'),
('canaris', 'كناري', 'canaris', 'oiseaux', 3, 'ar'),
('perruches', 'ببغاوات', 'perruches', 'oiseaux', 3, 'ar'),
('poissons', 'الأسماك', 'poissons', 'animaux-domestiques', 2, 'ar'),
('poissons-aquarium', 'أسماك أحواض', 'poissons-aquarium', 'poissons', 3, 'ar'),
('poissons-exotiques', 'أسماك غريبة', 'poissons-exotiques', 'poissons', 3, 'ar'),
('poissons-rouges', 'أسماك ذهبية', 'poissons-rouges', 'poissons', 3, 'ar'),
('rongeurs', 'القوارض', 'rongeurs', 'animaux-domestiques', 2, 'ar'),
('lapins', 'أرانب', 'lapins', 'rongeurs', 3, 'ar'),
('hamsters', 'هامستر', 'hamsters', 'rongeurs', 3, 'ar'),
('cochons-inde', 'خنازير غينيا', 'cochons-inde', 'rongeurs', 3, 'ar'),
('reptiles', 'الزواحف', 'reptiles', 'animaux-domestiques', 2, 'ar'),
('tortues', 'سلاحف', 'tortues', 'reptiles', 3, 'ar'),
('lezards', 'سحالي', 'lezards', 'reptiles', 3, 'ar'),
('serpents', 'ثعابين', 'serpents', 'reptiles', 3, 'ar'),

-- حيوانات التربية
('animaux-elevage', 'حيوانات التربية', 'animaux-elevage', 'animaux-accessoires', 1, 'ar'),
('ovins', 'الأغنام', 'ovins', 'animaux-elevage', 2, 'ar'),
('moutons-elevage', 'أغنام تربية', 'moutons-elevage', 'ovins', 3, 'ar'),
('agneaux', 'حملان', 'agneaux', 'ovins', 3, 'ar'),
('brebis-lait', 'نعاج حلوب', 'brebis-lait', 'ovins', 3, 'ar'),
('bovins', 'الأبقار', 'bovins', 'animaux-elevage', 2, 'ar'),
('vaches-lait', 'أبقار حلوب', 'vaches-lait', 'bovins', 3, 'ar'),
('taureaux', 'ثيران', 'taureaux', 'bovins', 3, 'ar'),
('veau-elevage', 'عجول تربية', 'veau-elevage', 'bovins', 3, 'ar'),
('caprins', 'الماعز', 'caprins', 'animaux-elevage', 2, 'ar'),
('chevres-elevage', 'ماعز تربية', 'chevres-elevage', 'caprins', 3, 'ar'),
('chevreaux', 'جدي', 'chevreaux', 'caprins', 3, 'ar'),
('chevres-lait', 'ماعز حلوب', 'chevres-lait', 'caprins', 3, 'ar'),
('volailles', 'الدواجن', 'volailles', 'animaux-elevage', 2, 'ar'),
('poules-pondreuses', 'دجاج بياض', 'poules-pondreuses', 'volailles', 3, 'ar'),
('poulets-chair', 'دجاج لحم', 'poulets-chair', 'volailles', 3, 'ar'),
('dindons', 'ديك رومي', 'dindons', 'volailles', 3, 'ar'),
('equides', 'الخيول', 'equides', 'animaux-elevage', 2, 'ar'),
('chevaux-elevage', 'خيول تربية', 'chevaux-elevage', 'equides', 3, 'ar'),
('poneys', 'بوني', 'poneys', 'equides', 3, 'ar'),
('anes', 'حمير', 'anes', 'equides', 3, 'ar'),

-- الطعام والعناية بالحيوانات
('nourriture-soins', 'الطعام والعناية بالحيوانات', 'nourriture-soins', 'animaux-accessoires', 1, 'ar'),
('alimentation-chiens', 'طعام الكلاب', 'alimentation-chiens', 'nourriture-soins', 2, 'ar'),
('croquettes', 'كرواسان', 'croquettes', 'alimentation-chiens', 3, 'ar'),
('pates', 'معجون', 'pates', 'alimentation-chiens', 3, 'ar'),
('friandises-chien', 'حلويات للكلاب', 'friandises-chien', 'alimentation-chiens', 3, 'ar'),
('alimentation-chats', 'طعام القطط', 'alimentation-chats', 'nourriture-soins', 2, 'ar'),
('croquettes-chat', 'كرواسان للقطط', 'croquettes-chat', 'alimentation-chats', 3, 'ar'),
('pates-chat', 'معجون للقطط', 'pates-chat', 'alimentation-chats', 3, 'ar'),
('friandises-chat', 'حلويات للقطط', 'friandises-chat', 'alimentation-chats', 3, 'ar'),
('alimentation-oiseaux', 'طعام الطيور', 'alimentation-oiseaux', 'nourriture-soins', 2, 'ar'),
('melanges-oiseaux', 'خلطات طيور', 'melanges-oiseaux', 'alimentation-oiseaux', 3, 'ar'),
('graines', 'بذور', 'graines', 'alimentation-oiseaux', 3, 'ar'),
('friandises-oiseaux', 'حلويات للطيور', 'friandises-oiseaux', 'alimentation-oiseaux', 3, 'ar'),
('alimentation-poissons', 'طعام الأسماك', 'alimentation-poissons', 'nourriture-soins', 2, 'ar'),
('flocons-poissons', 'رقائق أسماك', 'flocons-poissons', 'alimentation-poissons', 3, 'ar'),
('granules', 'حبيبات', 'granules', 'alimentation-poissons', 3, 'ar'),
('aliments-congeles', 'أطعمة مجمدة', 'aliments-congeles', 'alimentation-poissons', 3, 'ar'),
('soins-hygiene', 'العناية والنظافة', 'soins-hygiene', 'nourriture-soins', 2, 'ar'),
('shampooings', 'شامبو', 'shampooings', 'soins-hygiene', 3, 'ar'),
('antiparasitaires', 'مضادات الطفيليات', 'antiparasitaires', 'soins-hygiene', 3, 'ar'),
('anti-tiques', 'مضاد للقراد', 'anti-tiques', 'soins-hygiene', 3, 'ar'),
('complements-vitamines', 'المكملات والفيتامينات', 'complements-vitamines', 'nourriture-soins', 2, 'ar'),
('vitamines-mineraux', 'فيتامينات ومعادن', 'vitamines-mineraux', 'complements-vitamines', 3, 'ar'),
('supplements-articulations', 'مكملات المفاصل', 'supplements-articulations', 'complements-vitamines', 3, 'ar'),
('probiotiques', 'بروبيوتيك', 'probiotiques', 'complements-vitamines', 3, 'ar'),

-- الإكسسوارات والمعدات
('accessoires-equipements', 'الإكسسوارات والمعدات', 'accessoires-equipements', 'animaux-accessoires', 1, 'ar'),
('laisses-collier', 'المقاود والأطواق', 'laisses-collier', 'accessoires-equipements', 2, 'ar'),
('laisses-classiques', 'مقاود تقليدية', 'laisses-classiques', 'laisses-collier', 3, 'ar'),
('laisses-retractables', 'مقاود قابلة للسحب', 'laisses-retractables', 'laisses-collier', 3, 'ar'),
('colliers-cuir', 'أطواق جلد', 'colliers-cuir', 'laisses-collier', 3, 'ar'),
('harnais', 'الأحزمة', 'harnais', 'accessoires-equipements', 2, 'ar'),
('harnais-chiens', 'أحزمة للكلاب', 'harnais-chiens', 'harnais', 3, 'ar'),
('harnais-chats', 'أحزمة للقطط', 'harnais-chats', 'harnais', 3, 'ar'),
('harnais-anti-traction', 'أحزمة مضادة للشد', 'harnais-anti-traction', 'harnais', 3, 'ar'),
('cages-transport', 'الأقفاص والنقل', 'cages-transport', 'accessoires-equipements', 2, 'ar'),
('cages-transport', 'أقفاص نقل', 'cages-transport', 'cages-transport', 3, 'ar'),
('paniers-transport', 'سلال نقل', 'paniers-transport', 'cages-transport', 3, 'ar'),
('sac-transport', 'حقائب نقل', 'sac-transport', 'cages-transport', 3, 'ar'),
('niches-paniers', 'البيوت والسلال', 'niches-paniers', 'accessoires-equipements', 2, 'ar'),
('niches-exterieures', 'بيوت خارجية', 'niches-exterieures', 'niches-paniers', 3, 'ar'),
('paniers-interieur', 'سلال داخلية', 'paniers-interieur', 'niches-paniers', 3, 'ar'),
('coussins-lit', 'وسادات وأسرة', 'coussins-lit', 'niches-paniers', 3, 'ar'),
('arbres-chat', 'أشجار القطط', 'arbres-chat', 'accessoires-equipements', 2, 'ar'),
('arbres-griffade', 'أشجار الخدش', 'arbres-griffade', 'arbres-chat', 3, 'ar'),
('tours-activite', 'أبراج نشاط', 'tours-activite', 'arbres-chat', 3, 'ar'),
('hamacs-chat', 'هاموك للقطط', 'hamacs-chat', 'arbres-chat', 3, 'ar'),
('aquariums-terrariums', 'أحواض السمك والزواحف', 'aquariums-terrariums', 'accessoires-equipements', 2, 'ar'),
('aquariums-verre', 'أحواض زجاج', 'aquariums-verre', 'aquariums-terrariums', 3, 'ar'),
('terrariums-reptiles', 'أحواض زواحف', 'terrariums-reptiles', 'aquariums-terrariums', 3, 'ar'),
('accessoires-aquarium', 'إكسسوارات أحواض', 'accessoires-aquarium', 'aquariums-terrariums', 3, 'ar'),
('distributeurs-gamelles', 'الموزعات وأوعية الطعام', 'distributeurs-gamelles', 'accessoires-equipements', 2, 'ar'),
('distributeurs-automatiques', 'موزعات أوتوماتيكية', 'distributeurs-automatiques', 'distributeurs-gamelles', 3, 'ar'),
('gamelles-classiques', 'أوعية تقليدية', 'gamelles-classiques', 'distributeurs-gamelles', 3, 'ar'),
('fontaines-eau', 'نوافير مياه', 'fontaines-eau', 'distributeurs-gamelles', 3, 'ar'),
('litiere-accessoires', 'الرمال والإكسسوارات', 'litiere-accessoires', 'accessoires-equipements', 2, 'ar'),
('litiere-minerale', 'رمال معدنية', 'litiere-minerale', 'litiere-accessoires', 3, 'ar'),
('litiere-vegetale', 'رمال نباتية', 'litiere-vegetale', 'litiere-accessoires', 3, 'ar'),
('bacs-litiere', 'أوعية رمال', 'bacs-litiere', 'litiere-accessoires', 3, 'ar'),
('jouets-animaux', 'ألعاب الحيوانات', 'jouets-animaux', 'accessoires-equipements', 2, 'ar'),
('jouets-chiens', 'ألعاب للكلاب', 'jouets-chiens', 'jouets-animaux', 3, 'ar'),
('jouets-chats', 'ألعاب للقطط', 'jouets-chats', 'jouets-animaux', 3, 'ar'),
('jouets-oiseaux', 'ألعاب للطيور', 'jouets-oiseaux', 'jouets-animaux', 3, 'ar'),

-- التربية والتكاثر
('elevage-reproduction', 'التربية والتكاثر', 'elevage-reproduction', 'animaux-accessoires', 1, 'ar'),
('materiel-elevage', 'معدات التربية', 'materiel-elevage', 'elevage-reproduction', 2, 'ar'),
('incubateurs', 'حاضنات', 'incubateurs', 'materiel-elevage', 3, 'ar'),
('couveuses', 'فراخات', 'couveuses', 'materiel-elevage', 3, 'ar'),
('cages-elevage', 'أقفاص تربية', 'cages-elevage', 'materiel-elevage', 3, 'ar'),
('accessoires-accouplement', 'إكسسوارات التزاوج', 'accessoires-accouplement', 'elevage-reproduction', 2, 'ar'),
('box-accouplement', 'صناديق تزاوج', 'box-accouplement', 'accessoires-accouplement', 3, 'ar'),
('detecteurs-chaleur', 'كاشفات الشبق', 'detecteurs-chaleur', 'accessoires-accouplement', 3, 'ar'),
('support-reproduction', 'دعامات تكاثر', 'support-reproduction', 'accessoires-accouplement', 3, 'ar'),
('reproducteurs-selectionnes', 'المنتخبين للتكاثر', 'reproducteurs-selectionnes', 'elevage-reproduction', 2, 'ar'),
('etalons', 'فحول', 'etalons', 'reproducteurs-selectionnes', 3, 'ar'),
('reproducteurs-bovins', 'مكاثر أبقار', 'reproducteurs-bovins', 'reproducteurs-selectionnes', 3, 'ar'),
('reproducteurs-ovins', 'مكاثر أغنام', 'reproducteurs-ovins', 'reproducteurs-selectionnes', 3, 'ar'),
('volailles-pondre', 'الدواجن الجاهزة للبيض', 'volailles-pondre', 'elevage-reproduction', 2, 'ar'),
('poules-pondreuses-selection', 'دجاج بياض منتخب', 'poules-pondreuses-selection', 'volailles-pondre', 3, 'ar'),
('poussins-reproducteurs', 'كتكوت مكاثر', 'poussins-reproducteurs', 'volailles-pondre', 3, 'ar'),
('dindes-reproductrices', 'ديك رومي مكاثر', 'dindes-reproductrices', 'volailles-pondre', 3, 'ar'),
('jeunes-animaux', 'الحيوانات الصغيرة', 'jeunes-animaux', 'elevage-reproduction', 2, 'ar'),
('agneaux-veau', 'حملان وعجول', 'agneaux-veau', 'jeunes-animaux', 3, 'ar'),
('chevreaux-porcelets', 'جدي وخنازير صغيرة', 'chevreaux-porcelets', 'jeunes-animaux', 3, 'ar'),
('poulains', 'مهور', 'poulains', 'jeunes-animaux', 3, 'ar'),
('services-elevage', 'خدمات التربية', 'services-elevage', 'elevage-reproduction', 2, 'ar'),
('conseils-elevage', 'نصائح تربية', 'conseils-elevage', 'services-elevage', 3, 'ar'),
('assistance-velage', 'مساعدة الولادة', 'assistance-velage', 'services-elevage', 3, 'ar'),
('genetique-selection', 'جينات وانتخاب', 'genetique-selection', 'services-elevage', 3, 'ar'),

-- الخدمات الحيوانية
('services-animaliers', 'الخدمات الحيوانية', 'services-animaliers', 'animaux-accessoires', 1, 'ar'),
('toilettage', 'العناية بالمظهر', 'toilettage', 'services-animaliers', 2, 'ar'),
('toilettage-chiens', 'تزيين الكلاب', 'toilettage-chiens', 'toilettage', 3, 'ar'),
('toilettage-chats', 'تزيين القطط', 'toilettage-chats', 'toilettage', 3, 'ar'),
('coupe-griffes', 'قص الأظافر', 'coupe-griffes', 'toilettage', 3, 'ar'),
('dressage-education', 'التدريب والتعليم', 'dressage-education', 'services-animaliers', 2, 'ar'),
('dressage-chiens', 'تدريب الكلاب', 'dressage-chiens', 'dressage-education', 3, 'ar'),
('education-chiot', 'تعليم الجروات', 'education-chiot', 'dressage-education', 3, 'ar'),
('comportementaliste', 'أخصائي سلوك', 'comportementaliste', 'dressage-education', 3, 'ar'),
('pension-garde', 'النزل والم guardianship', 'pension-garde', 'services-animaliers', 2, 'ar'),
('pension-chiens', 'نزل كلاب', 'pension-chiens', 'pension-garde', 3, 'ar'),
('garde-chats', 'حراسة قطط', 'garde-chats', 'pension-garde', 3, 'ar'),
('pension-oiseaux', 'نزل طيور', 'pension-oiseaux', 'pension-garde', 3, 'ar'),
('promenades', 'الجولات', 'promenades', 'services-animaliers', 2, 'ar'),
('promeneur-chiens', 'ماشي الكلاب', 'promeneur-chiens', 'promenades', 3, 'ar'),
('group-promenades', 'جولات جماعية', 'group-promenades', 'promenades', 3, 'ar'),
('sport-canin', 'رياضة الكلاب', 'sport-canin', 'promenades', 3, 'ar'),
('soins-domicile', 'العناية المنزلية', 'soins-domicile', 'services-animaliers', 2, 'ar'),
('visites-domicile', 'زيارات منزلية', 'visites-domicile', 'soins-domicile', 3, 'ar'),
('administration-medicaments', 'إعطاء أدوية', 'administration-medicaments', 'soins-domicile', 3, 'ar'),
('soins-blessures', 'عناية الجروح', 'soins-blessures', 'soins-domicile', 3, 'ar'),
('photographie-animaliere', 'تصوير الحيوانات', 'photographie-animaliere', 'services-animaliers', 2, 'ar'),
('seances-photo', 'جلسات تصوير', 'seances-photo', 'photographie-animaliere', 3, 'ar'),
('photos-studio', 'صور استديو', 'photos-studio', 'photographie-animaliere', 3, 'ar'),
('photos-exterieur', 'صور خارجية', 'photos-exterieur', 'photographie-animaliere', 3, 'ar'),
('transport-animaux', 'نقل الحيوانات', 'transport-animaux', 'services-animaliers', 2, 'ar'),
('transport-national', 'نقل وطني', 'transport-national', 'transport-animaux', 3, 'ar'),
('transport-international', 'نقل دولي', 'transport-international', 'transport-animaux', 3, 'ar'),
('taxi-animalier', 'تاكسي حيوانات', 'taxi-animalier', 'transport-animaux', 3, 'ar'),
('adoption-animaux', 'تبني الحيوانات', 'adoption-animaux', 'services-animaliers', 2, 'ar'),
('adoption-chiens', 'تبني الكلاب', 'adoption-chiens', 'adoption-animaux', 3, 'ar'),
('adoption-chats', 'تبني القطط', 'adoption-chats', 'adoption-animaux', 3, 'ar'),
('adoption-autres', 'تبني حيوانات أخرى', 'adoption-autres', 'adoption-animaux', 3, 'ar'),
('services-veterinaires', 'الخدمات البيطرية', 'services-veterinaires', 'services-animaliers', 2, 'ar'),
('consultations-veterinaires', 'استشارات بيطرية', 'consultations-veterinaires', 'services-veterinaires', 3, 'ar'),
('vaccinations', 'تطعيمات', 'vaccinations', 'services-veterinaires', 3, 'ar'),
('chirurgie-veterinaire', 'جراحة بيطرية', 'chirurgie-veterinaire', 'services-veterinaires', 3, 'ar'),

-- منتجات خارجية
('produits-exterieurs', 'منتجات خارجية', 'produits-exterieurs', 'animaux-accessoires', 1, 'ar'),
('clotures-animaux', 'أسيجة الحيوانات', 'clotures-animaux', 'produits-exterieurs', 2, 'ar'),
('clotures-electriques', 'أسيجة كهربائية', 'clotures-electriques', 'clotures-animaux', 3, 'ar'),
('clotures-mailles', 'أسيجة شبكية', 'clotures-mailles', 'clotures-animaux', 3, 'ar'),
('poteaux-cloture', 'أعمدة سياج', 'poteaux-cloture', 'clotures-animaux', 3, 'ar'),
('abris-exterieurs', 'المآوي الخارجية', 'abris-exterieurs', 'produits-exterieurs', 2, 'ar'),
('abris-exterieurs-animaux', 'مآوي للحيوانات الخارجية', 'abris-exterieurs-animaux', 'abris-exterieurs', 3, 'ar'),
('alimentation-automatique', 'التغذية الأوتوماتيكية', 'alimentation-automatique', 'produits-exterieurs', 2, 'ar'),
('mangeoires-auto', 'مغذيات أوتوماتيكية', 'mangeoires-auto', 'alimentation-automatique', 3, 'ar'),
('systemes-abreuvement', 'أنظمة الشرب', 'systemes-abreuvement', 'alimentation-automatique', 3, 'ar'),
('equipements-elevage-exterieur', 'معدات تربية خارجية', 'equipements-elevage-exterieur', 'produits-exterieurs', 2, 'ar'),
('materiel-plein-air', 'معدات في الهواء الطلق', 'materiel-plein-air', 'equipements-elevage-exterieur', 3, 'ar'),
('confort-thermique', 'الراحة الحرارية', 'confort-thermique', 'produits-exterieurs', 2, 'ar'),
('lampes-chauffantes', 'مصابيح تدفئة', 'lampes-chauffantes', 'confort-thermique', 3, 'ar'),
('accessoires-volières', 'إكسسوارات الأقفاص', 'accessoires-volières', 'produits-exterieurs', 2, 'ar'),
('materiel-volières', 'معدات الأقفاص', 'materiel-volières', 'accessoires-volières', 3, 'ar');