INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('nautisme', 'Nautisme & Bateaux', 'nautisme', NULL, 0, 'fr');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('types-de-bateaux', 'Types de bateaux', 'types-de-bateaux', 'nautisme', 1, 'fr'),
('moteurs-propulsion', 'Moteurs & propulsion', 'moteurs-propulsion', 'nautisme', 1, 'fr'),
('equipements-de-navigation', 'Équipements de navigation', 'equipements-de-navigation', 'nautisme', 1, 'fr'),
('securite-sauvetage', 'Sécurité & sauvetage', 'securite-sauvetage', 'nautisme', 1, 'fr'),
('accastillage-pieces-detachees', 'Accastillage & pièces détachées', 'accastillage-pieces-detachees', 'nautisme', 1, 'fr'),
('confort-amenagement-interieur', 'Confort & aménagement intérieur', 'confort-amenagement-interieur', 'nautisme', 1, 'fr'),
('accessoires-entretien', 'Accessoires & entretien', 'accessoires-entretien', 'nautisme', 1, 'fr'),
('transport-stockage', 'Transport & stockage', 'transport-stockage', 'nautisme', 1, 'fr'),
('sports-nautiques-associes', 'Sports nautiques associés', 'sports-nautiques-associes', 'nautisme', 1, 'fr');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('bateaux-a-moteur', 'Bateaux à moteur', 'bateaux-a-moteur', 'types-de-bateaux', 2, 'fr'),
('voiliers', 'Voiliers', 'voiliers', 'types-de-bateaux', 2, 'fr'),
('yachts', 'Yachts', 'yachts', 'types-de-bateaux', 2, 'fr'),
('semi-rigides', 'Semi-rigides', 'semi-rigides', 'types-de-bateaux', 2, 'fr'),
('zodiacs-pneumatiques', 'Zodiacs & pneumatiques', 'zodiacs-pneumatiques', 'types-de-bateaux', 2, 'fr'),
('jet-skis-scooters-mer', 'Jet-skis & scooters des mers', 'jet-skis-scooters-mer', 'types-de-bateaux', 2, 'fr'),
('barques-chaloupes', 'Barques & chaloupes', 'barques-chaloupes', 'types-de-bateaux', 2, 'fr'),
('kayaks', 'Kayaks', 'kayaks', 'types-de-bateaux', 2, 'fr'),
('canoes', 'Canoës', 'canoes', 'types-de-bateaux', 2, 'fr'),
('bateaux-de-peche', 'Bateaux de pêche', 'bateaux-de-peche', 'types-de-bateaux', 2, 'fr'),
('pedalos', 'Pédalos', 'pedalos', 'types-de-bateaux', 2, 'fr'),
('catamarans', 'Catamarans', 'catamarans', 'types-de-bateaux', 2, 'fr'),
('planches-a-voile-windsurf', 'Planches à voile & windsurf', 'planches-a-voile-windsurf', 'types-de-bateaux', 2, 'fr'),
('moteurs-hors-bord', 'Moteurs hors-bord', 'moteurs-hors-bord', 'moteurs-propulsion', 2, 'fr'),
('moteurs-in-bord', 'Moteurs in-bord', 'moteurs-in-bord', 'moteurs-propulsion', 2, 'fr'),
('moteurs-electriques', 'Moteurs électriques', 'moteurs-electriques', 'moteurs-propulsion', 2, 'fr'),
('helices', 'Hélices', 'helices', 'moteurs-propulsion', 2, 'fr'),
('propulsion-auxiliaire', 'Systèmes de propulsion auxiliaire', 'propulsion-auxiliaire', 'moteurs-propulsion', 2, 'fr'),
('batteries-marine', 'Batteries marine', 'batteries-marine', 'moteurs-propulsion', 2, 'fr'),
('reservoirs-carburant-nautique', 'Réservoirs & carburant nautique', 'reservoirs-carburant-nautique', 'moteurs-propulsion', 2, 'fr'),
('gps-nautiques', 'GPS nautiques', 'gps-nautiques', 'equipements-de-navigation', 2, 'fr'),
('sondeurs-echosondeurs', 'Sondeurs & échosondeurs', 'sondeurs-echosondeurs', 'equipements-de-navigation', 2, 'fr'),
('radars', 'Radars', 'radars', 'equipements-de-navigation', 2, 'fr'),
('cartes-instruments-marins', 'Cartes & instruments marins', 'cartes-instruments-marins', 'equipements-de-navigation', 2, 'fr'),
('compas', 'Compas', 'compas', 'equipements-de-navigation', 2, 'fr'),
('pilotes-automatiques', 'Pilotes automatiques', 'pilotes-automatiques', 'equipements-de-navigation', 2, 'fr'),
('radios-vhf', 'Radios VHF', 'radios-vhf', 'equipements-de-navigation', 2, 'fr'),
('traceurs-de-cartes', 'Traceurs de cartes', 'traceurs-de-cartes', 'equipements-de-navigation', 2, 'fr'),
('jumelles-marines', 'Jumelles marines', 'jumelles-marines', 'equipements-de-navigation', 2, 'fr'),
('gilets-de-sauvetage', 'Gilets de sauvetage', 'gilets-de-sauvetage', 'securite-sauvetage', 2, 'fr'),
('bouees', 'Bouées', 'bouees', 'securite-sauvetage', 2, 'fr'),
('harnais-lignes-de-vie', 'Harnais & lignes de vie', 'harnais-lignes-de-vie', 'securite-sauvetage', 2, 'fr'),
('extincteurs-marine', 'Extincteurs marine', 'extincteurs-marine', 'securite-sauvetage', 2, 'fr'),
('trousses-de-secours', 'Trousses de secours', 'trousses-de-secours', 'securite-sauvetage', 2, 'fr'),
('fusees-signalisations', 'Fusées & signalisations', 'fusees-signalisations', 'securite-sauvetage', 2, 'fr'),
('kits-d-urgence', 'Kits d’urgence', 'kits-d-urgence', 'securite-sauvetage', 2, 'fr'),
('pompes-de-cale', 'Pompes de cale', 'pompes-de-cale', 'securite-sauvetage', 2, 'fr'),
('cordages', 'Cordages', 'cordages', 'accastillage-pieces-detachees', 2, 'fr'),
('amarres', 'Amarres', 'amarres', 'accastillage-pieces-detachees', 2, 'fr'),
('ancres-chaines', 'Ancres & chaînes', 'ancres-chaines', 'accastillage-pieces-detachees', 2, 'fr'),
('poulies', 'Poulies', 'poulies', 'accastillage-pieces-detachees', 2, 'fr'),
('taquets', 'Taquets', 'taquets', 'accastillage-pieces-detachees', 2, 'fr'),
('mousquetons', 'Mousquetons', 'mousquetons', 'accastillage-pieces-detachees', 2, 'fr'),
('winchs', 'Winchs', 'winchs', 'accastillage-pieces-detachees', 2, 'fr'),
('voiles-greements', 'Voiles & gréements', 'voiles-greements', 'accastillage-pieces-detachees', 2, 'fr'),
('chandeliers-balcons', 'Chandeliers & balcons', 'chandeliers-balcons', 'accastillage-pieces-detachees', 2, 'fr'),
('echelles-de-bain', 'Échelles de bain', 'echelles-de-bain', 'accastillage-pieces-detachees', 2, 'fr'),
('pare-battages', 'Pare-battages', 'pare-battages', 'accastillage-pieces-detachees', 2, 'fr'),
('hublots-ecoutilles', 'Hublots & écoutilles', 'hublots-ecoutilles', 'accastillage-pieces-detachees', 2, 'fr'),
('sieges-banquettes', 'Sièges & banquettes', 'sieges-banquettes', 'confort-amenagement-interieur', 2, 'fr'),
('cabines-couchettes', 'Cabines & couchettes', 'cabines-couchettes', 'confort-amenagement-interieur', 2, 'fr'),
('eclairage-interieur', 'Éclairage intérieur', 'eclairage-interieur', 'confort-amenagement-interieur', 2, 'fr'),
('cuisine-marine', 'Équipements de cuisine marine', 'cuisine-marine', 'confort-amenagement-interieur', 2, 'fr'),
('refrigerateurs-glacieres-nautiques', 'Réfrigérateurs & glacières nautiques', 'refrigerateurs-glacieres-nautiques', 'confort-amenagement-interieur', 2, 'fr'),
('wc-nautiques', 'WC nautiques', 'wc-nautiques', 'confort-amenagement-interieur', 2, 'fr'),
('douches-sanitaires', 'Douches & sanitaires', 'douches-sanitaires', 'confort-amenagement-interieur', 2, 'fr'),
('rangements-coffres', 'Rangements & coffres', 'rangements-coffres', 'confort-amenagement-interieur', 2, 'fr'),
('housses-protection', 'Housses de protection', 'housses-protection', 'accessoires-entretien', 2, 'fr'),
('nettoyants-entretien', 'Nettoyants & produits d’entretien', 'nettoyants-entretien', 'accessoires-entretien', 2, 'fr'),
('peintures-antifouling', 'Peintures & antifouling', 'peintures-antifouling', 'accessoires-entretien', 2, 'fr'),
('kits-reparation-coque', 'Kits de réparation coque', 'kits-reparation-coque', 'accessoires-entretien', 2, 'fr'),
('batteries-chargeurs', 'Batteries & chargeurs', 'batteries-chargeurs', 'accessoires-entretien', 2, 'fr'),
('outils-nautiques', 'Outils nautiques', 'outils-nautiques', 'accessoires-entretien', 2, 'fr'),
('pompes-manuelles', 'Pompes manuelles', 'pompes-manuelles', 'accessoires-entretien', 2, 'fr'),
('rames-pagaies', 'Rames & pagaies', 'rames-pagaies', 'accessoires-entretien', 2, 'fr'),
('remorques-bateau', 'Remorques bateau', 'remorques-bateau', 'transport-stockage', 2, 'fr'),
('treuils-sangles', 'Treuils & sangles', 'treuils-sangles', 'transport-stockage', 2, 'fr'),
('chariots-mise-a-leau', 'Chariots de mise à l’eau', 'chariots-mise-a-leau', 'transport-stockage', 2, 'fr'),
('supports-stockage', 'Supports de stockage', 'supports-stockage', 'transport-stockage', 2, 'fr'),
('garages-nautiques', 'Garages nautiques', 'garages-nautiques', 'transport-stockage', 2, 'fr'),
('portiques-palans', 'Portiques & palans', 'portiques-palans', 'transport-stockage', 2, 'fr'),
('wakeboard', 'Wakeboard', 'wakeboard', 'sports-nautiques-associes', 2, 'fr'),
('ski-nautique', 'Ski nautique', 'ski-nautique', 'sports-nautiques-associes', 2, 'fr'),
('kneeboard', 'Kneeboard', 'kneeboard', 'sports-nautiques-associes', 2, 'fr'),
('bouees-tractees', 'Bouées tractées', 'bouees-tractees', 'sports-nautiques-associes', 2, 'fr'),
('paddle-sup', 'Paddle (SUP)', 'paddle-sup', 'sports-nautiques-associes', 2, 'fr'),
('kitesurf', 'Kitesurf', 'kitesurf', 'sports-nautiques-associes', 2, 'fr'),
('plongee-snorkeling', 'Plongée & snorkeling', 'plongee-snorkeling', 'sports-nautiques-associes', 2, 'fr'),
('peche-en-mer-equipements', 'Équipements de pêche en mer', 'peche-en-mer-equipements', 'sports-nautiques-associes', 2, 'fr');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('nautisme', 'Boating & Marine', 'nautisme', NULL, 0, 'en');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('types-de-bateaux', 'Boat Types', 'types-de-bateaux', 'nautisme', 1, 'en'),
('moteurs-propulsion', 'Engines & Propulsion', 'moteurs-propulsion', 'nautisme', 1, 'en'),
('equipements-de-navigation', 'Navigation Equipment', 'equipements-de-navigation', 'nautisme', 1, 'en'),
('securite-sauvetage', 'Safety & Rescue', 'securite-sauvetage', 'nautisme', 1, 'en'),
('accastillage-pieces-detachees', 'Deck Fittings & Spare Parts', 'accastillage-pieces-detachees', 'nautisme', 1, 'en'),
('confort-amenagement-interieur', 'Comfort & Interior', 'confort-amenagement-interieur', 'nautisme', 1, 'en'),
('accessoires-entretien', 'Accessories & Maintenance', 'accessoires-entretien', 'nautisme', 1, 'en'),
('transport-stockage', 'Transport & Storage', 'transport-stockage', 'nautisme', 1, 'en'),
('sports-nautiques-associes', 'Water Sports', 'sports-nautiques-associes', 'nautisme', 1, 'en');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('bateaux-a-moteur', 'Powerboats', 'bateaux-a-moteur', 'types-de-bateaux', 2, 'en'),
('voiliers', 'Sailboats', 'voiliers', 'types-de-bateaux', 2, 'en'),
('yachts', 'Yachts', 'yachts', 'types-de-bateaux', 2, 'en'),
('semi-rigides', 'RIBs', 'semi-rigides', 'types-de-bateaux', 2, 'en'),
('zodiacs-pneumatiques', 'Inflatables & Zodiacs', 'zodiacs-pneumatiques', 'types-de-bateaux', 2, 'en'),
('jet-skis-scooters-mer', 'Jet skis & PWCs', 'jet-skis-scooters-mer', 'types-de-bateaux', 2, 'en'),
('barques-chaloupes', 'Rowboats & skiffs', 'barques-chaloupes', 'types-de-bateaux', 2, 'en'),
('kayaks', 'Kayaks', 'kayaks', 'types-de-bateaux', 2, 'en'),
('canoes', 'Canoes', 'canoes', 'types-de-bateaux', 2, 'en'),
('bateaux-de-peche', 'Fishing boats', 'bateaux-de-peche', 'types-de-bateaux', 2, 'en'),
('pedalos', 'Pedal boats', 'pedalos', 'types-de-bateaux', 2, 'en'),
('catamarans', 'Catamarans', 'catamarans', 'types-de-bateaux', 2, 'en'),
('planches-a-voile-windsurf', 'Windsurf boards', 'planches-a-voile-windsurf', 'types-de-bateaux', 2, 'en'),
('moteurs-hors-bord', 'Outboard engines', 'moteurs-hors-bord', 'moteurs-propulsion', 2, 'en'),
('moteurs-in-bord', 'Inboard engines', 'moteurs-in-bord', 'moteurs-propulsion', 2, 'en'),
('moteurs-electriques', 'Electric motors', 'moteurs-electriques', 'moteurs-propulsion', 2, 'en'),
('helices', 'Propellers', 'helices', 'moteurs-propulsion', 2, 'en'),
('propulsion-auxiliaire', 'Auxiliary propulsion', 'propulsion-auxiliaire', 'moteurs-propulsion', 2, 'en'),
('batteries-marine', 'Marine batteries', 'batteries-marine', 'moteurs-propulsion', 2, 'en'),
('reservoirs-carburant-nautique', 'Fuel tanks & marine fuel', 'reservoirs-carburant-nautique', 'moteurs-propulsion', 2, 'en'),
('gps-nautiques', 'Marine GPS', 'gps-nautiques', 'equipements-de-navigation', 2, 'en'),
('sondeurs-echosondeurs', 'Fishfinders & echo sounders', 'sondeurs-echosondeurs', 'equipements-de-navigation', 2, 'en'),
('radars', 'Radars', 'radars', 'equipements-de-navigation', 2, 'en'),
('cartes-instruments-marins', 'Charts & marine instruments', 'cartes-instruments-marins', 'equipements-de-navigation', 2, 'en'),
('compas', 'Compasses', 'compas', 'equipements-de-navigation', 2, 'en'),
('pilotes-automatiques', 'Autopilots', 'pilotes-automatiques', 'equipements-de-navigation', 2, 'en'),
('radios-vhf', 'VHF radios', 'radios-vhf', 'equipements-de-navigation', 2, 'en'),
('traceurs-de-cartes', 'Chartplotters', 'traceurs-de-cartes', 'equipements-de-navigation', 2, 'en'),
('jumelles-marines', 'Marine binoculars', 'jumelles-marines', 'equipements-de-navigation', 2, 'en'),
('gilets-de-sauvetage', 'Life jackets', 'gilets-de-sauvetage', 'securite-sauvetage', 2, 'en'),
('bouees', 'Buoys', 'bouees', 'securite-sauvetage', 2, 'en'),
('harnais-lignes-de-vie', 'Harnesses & lifelines', 'harnais-lignes-de-vie', 'securite-sauvetage', 2, 'en'),
('extincteurs-marine', 'Marine fire extinguishers', 'extincteurs-marine', 'securite-sauvetage', 2, 'en'),
('trousses-de-secours', 'First aid kits', 'trousses-de-secours', 'securite-sauvetage', 2, 'en'),
('fusees-signalisations', 'Flares & signaling', 'fusees-signalisations', 'securite-sauvetage', 2, 'en'),
('kits-d-urgence', 'Emergency kits', 'kits-d-urgence', 'securite-sauvetage', 2, 'en'),
('pompes-de-cale', 'Bilge pumps', 'pompes-de-cale', 'securite-sauvetage', 2, 'en'),
('cordages', 'Ropes', 'cordages', 'accastillage-pieces-detachees', 2, 'en'),
('amarres', 'Dock lines', 'amarres', 'accastillage-pieces-detachees', 2, 'en'),
('ancres-chaines', 'Anchors & chains', 'ancres-chaines', 'accastillage-pieces-detachees', 2, 'en'),
('poulies', 'Pulleys', 'poulies', 'accastillage-pieces-detachees', 2, 'en'),
('taquets', 'Cleats', 'taquets', 'accastillage-pieces-detachees', 2, 'en'),
('mousquetons', 'Carabiners', 'mousquetons', 'accastillage-pieces-detachees', 2, 'en'),
('winchs', 'Winches', 'winchs', 'accastillage-pieces-detachees', 2, 'en'),
('voiles-greements', 'Sails & rigging', 'voiles-greements', 'accastillage-pieces-detachees', 2, 'en'),
('chandeliers-balcons', 'Stanchions & rails', 'chandeliers-balcons', 'accastillage-pieces-detachees', 2, 'en'),
('echelles-de-bain', 'Swim ladders', 'echelles-de-bain', 'accastillage-pieces-detachees', 2, 'en'),
('pare-battages', 'Fenders', 'pare-battages', 'accastillage-pieces-detachees', 2, 'en'),
('hublots-ecoutilles', 'Hatches & portholes', 'hublots-ecoutilles', 'accastillage-pieces-detachees', 2, 'en'),
('sieges-banquettes', 'Seats & benches', 'sieges-banquettes', 'confort-amenagement-interieur', 2, 'en'),
('cabines-couchettes', 'Cabins & berths', 'cabines-couchettes', 'confort-amenagement-interieur', 2, 'en'),
('eclairage-interieur', 'Interior lighting', 'eclairage-interieur', 'confort-amenagement-interieur', 2, 'en'),
('cuisine-marine', 'Marine galley equipment', 'cuisine-marine', 'confort-amenagement-interieur', 2, 'en'),
('refrigerateurs-glacieres-nautiques', 'Marine fridges & coolers', 'refrigerateurs-glacieres-nautiques', 'confort-amenagement-interieur', 2, 'en'),
('wc-nautiques', 'Marine toilets', 'wc-nautiques', 'confort-amenagement-interieur', 2, 'en'),
('douches-sanitaires', 'Showers & sanitation', 'douches-sanitaires', 'confort-amenagement-interieur', 2, 'en'),
('rangements-coffres', 'Storage & lockers', 'rangements-coffres', 'confort-amenagement-interieur', 2, 'en'),
('housses-protection', 'Protective covers', 'housses-protection', 'accessoires-entretien', 2, 'en'),
('nettoyants-entretien', 'Cleaners & care products', 'nettoyants-entretien', 'accessoires-entretien', 2, 'en'),
('peintures-antifouling', 'Paints & antifouling', 'peintures-antifouling', 'accessoires-entretien', 2, 'en'),
('kits-reparation-coque', 'Hull repair kits', 'kits-reparation-coque', 'accessoires-entretien', 2, 'en'),
('batteries-chargeurs', 'Batteries & chargers', 'batteries-chargeurs', 'accessoires-entretien', 2, 'en'),
('outils-nautiques', 'Marine tools', 'outils-nautiques', 'accessoires-entretien', 2, 'en'),
('pompes-manuelles', 'Hand pumps', 'pompes-manuelles', 'accessoires-entretien', 2, 'en'),
('rames-pagaies', 'Oars & paddles', 'rames-pagaies', 'accessoires-entretien', 2, 'en'),
('remorques-bateau', 'Boat trailers', 'remorques-bateau', 'transport-stockage', 2, 'en'),
('treuils-sangles', 'Winches & straps', 'treuils-sangles', 'transport-stockage', 2, 'en'),
('chariots-mise-a-leau', 'Launching trolleys', 'chariots-mise-a-leau', 'transport-stockage', 2, 'en'),
('supports-stockage', 'Storage racks', 'supports-stockage', 'transport-stockage', 2, 'en'),
('garages-nautiques', 'Boat garages', 'garages-nautiques', 'transport-stockage', 2, 'en'),
('portiques-palans', 'Davits & hoists', 'portiques-palans', 'transport-stockage', 2, 'en'),
('wakeboard', 'Wakeboard', 'wakeboard', 'sports-nautiques-associes', 2, 'en'),
('ski-nautique', 'Water skiing', 'ski-nautique', 'sports-nautiques-associes', 2, 'en'),
('kneeboard', 'Kneeboard', 'kneeboard', 'sports-nautiques-associes', 2, 'en'),
('bouees-tractees', 'Towable tubes', 'bouees-tractees', 'sports-nautiques-associes', 2, 'en'),
('paddle-sup', 'Paddle (SUP)', 'paddle-sup', 'sports-nautiques-associes', 2, 'en'),
('kitesurf', 'Kitesurf', 'kitesurf', 'sports-nautiques-associes', 2, 'en'),
('plongee-snorkeling', 'Diving & snorkeling', 'plongee-snorkeling', 'sports-nautiques-associes', 2, 'en'),
('peche-en-mer-equipements', 'Sea fishing gear', 'peche-en-mer-equipements', 'sports-nautiques-associes', 2, 'en');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('nautisme', 'Náutica & Embarcaciones', 'nautisme', NULL, 0, 'es');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('types-de-bateaux', 'Tipos de embarcaciones', 'types-de-bateaux', 'nautisme', 1, 'es'),
('moteurs-propulsion', 'Motores & Propulsión', 'moteurs-propulsion', 'nautisme', 1, 'es'),
('equipements-de-navigation', 'Equipos de navegación', 'equipements-de-navigation', 'nautisme', 1, 'es'),
('securite-sauvetage', 'Seguridad & Salvamento', 'securite-sauvetage', 'nautisme', 1, 'es'),
('accastillage-pieces-detachees', 'Accesorios de cubierta & repuestos', 'accastillage-pieces-detachees', 'nautisme', 1, 'es'),
('confort-amenagement-interieur', 'Confort & interior', 'confort-amenagement-interieur', 'nautisme', 1, 'es'),
('accessoires-entretien', 'Accesorios & mantenimiento', 'accessoires-entretien', 'nautisme', 1, 'es'),
('transport-stockage', 'Transporte & almacenamiento', 'transport-stockage', 'nautisme', 1, 'es'),
('sports-nautiques-associes', 'Deportes acuáticos', 'sports-nautiques-associes', 'nautisme', 1, 'es');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('bateaux-a-moteur', 'Lanchas a motor', 'bateaux-a-moteur', 'types-de-bateaux', 2, 'es'),
('voiliers', 'Veleros', 'voiliers', 'types-de-bateaux', 2, 'es'),
('yachts', 'Yates', 'yachts', 'types-de-bateaux', 2, 'es'),
('semi-rigides', 'Semirrígidos', 'semi-rigides', 'types-de-bateaux', 2, 'es'),
('zodiacs-pneumatiques', 'Zodiacs & neumáticas', 'zodiacs-pneumatiques', 'types-de-bateaux', 2, 'es'),
('jet-skis-scooters-mer', 'Motos de agua', 'jet-skis-scooters-mer', 'types-de-bateaux', 2, 'es'),
('barques-chaloupes', 'Botes & chalupas', 'barques-chaloupes', 'types-de-bateaux', 2, 'es'),
('kayaks', 'Kayaks', 'kayaks', 'types-de-bateaux', 2, 'es'),
('canoes', 'Canoas', 'canoes', 'types-de-bateaux', 2, 'es'),
('bateaux-de-peche', 'Barcos de pesca', 'bateaux-de-peche', 'types-de-bateaux', 2, 'es'),
('pedalos', 'Hidropedales', 'pedalos', 'types-de-bateaux', 2, 'es'),
('catamarans', 'Catamaranes', 'catamarans', 'types-de-bateaux', 2, 'es'),
('planches-a-voile-windsurf', 'Tablas de windsurf', 'planches-a-voile-windsurf', 'types-de-bateaux', 2, 'es'),
('moteurs-hors-bord', 'Motores fueraborda', 'moteurs-hors-bord', 'moteurs-propulsion', 2, 'es'),
('moteurs-in-bord', 'Motores intraborda', 'moteurs-in-bord', 'moteurs-propulsion', 2, 'es'),
('moteurs-electriques', 'Motores eléctricos', 'moteurs-electriques', 'moteurs-propulsion', 2, 'es'),
('helices', 'Hélices', 'helices', 'moteurs-propulsion', 2, 'es'),
('propulsion-auxiliaire', 'Propulsión auxiliar', 'propulsion-auxiliaire', 'moteurs-propulsion', 2, 'es'),
('batteries-marine', 'Baterías marinas', 'batteries-marine', 'moteurs-propulsion', 2, 'es'),
('reservoirs-carburant-nautique', 'Depósitos & combustible marino', 'reservoirs-carburant-nautique', 'moteurs-propulsion', 2, 'es'),
('gps-nautiques', 'GPS marinos', 'gps-nautiques', 'equipements-de-navigation', 2, 'es'),
('sondeurs-echosondeurs', 'Sondas & ecosondas', 'sondeurs-echosondeurs', 'equipements-de-navigation', 2, 'es'),
('radars', 'Radares', 'radars', 'equipements-de-navigation', 2, 'es'),
('cartes-instruments-marins', 'Cartas & instrumentos marinos', 'cartes-instruments-marins', 'equipements-de-navigation', 2, 'es'),
('compas', 'Brújulas', 'compas', 'equipements-de-navigation', 2, 'es'),
('pilotes-automatiques', 'Pilotos automáticos', 'pilotes-automatiques', 'equipements-de-navigation', 2, 'es'),
('radios-vhf', 'Radios VHF', 'radios-vhf', 'equipements-de-navigation', 2, 'es'),
('traceurs-de-cartes', 'Plotters de cartas', 'traceurs-de-cartes', 'equipements-de-navigation', 2, 'es'),
('jumelles-marines', 'Binoculares marinos', 'jumelles-marines', 'equipements-de-navigation', 2, 'es'),
('gilets-de-sauvetage', 'Chalecos salvavidas', 'gilets-de-sauvetage', 'securite-sauvetage', 2, 'es'),
('bouees', 'Boyas', 'bouees', 'securite-sauvetage', 2, 'es'),
('harnais-lignes-de-vie', 'Arneses & líneas de vida', 'harnais-lignes-de-vie', 'securite-sauvetage', 2, 'es'),
('extincteurs-marine', 'Extintores marinos', 'extincteurs-marine', 'securite-sauvetage', 2, 'es'),
('trousses-de-secours', 'Kits de primeros auxilios', 'trousses-de-secours', 'securite-sauvetage', 2, 'es'),
('fusees-signalisations', 'Bengalas & señalización', 'fusees-signalisations', 'securite-sauvetage', 2, 'es'),
('kits-d-urgence', 'Kits de emergencia', 'kits-d-urgence', 'securite-sauvetage', 2, 'es'),
('pompes-de-cale', 'Bombas de achique', 'pompes-de-cale', 'securite-sauvetage', 2, 'es'),
('cordages', 'Cuerdas', 'cordages', 'accastillage-pieces-detachees', 2, 'es'),
('amarres', 'Amarras', 'amarres', 'accastillage-pieces-detachees', 2, 'es'),
('ancres-chaines', 'Anclas & cadenas', 'ancres-chaines', 'accastillage-pieces-detachees', 2, 'es'),
('poulies', 'Poleas', 'poulies', 'accastillage-pieces-detachees', 2, 'es'),
('taquets', 'Cornamusas', 'taquets', 'accastillage-pieces-detachees', 2, 'es'),
('mousquetons', 'Mosquetones', 'mousquetons', 'accastillage-pieces-detachees', 2, 'es'),
('winchs', 'Molinillos', 'winchs', 'accastillage-pieces-detachees', 2, 'es'),
('voiles-greements', 'Velas & jarcia', 'voiles-greements', 'accastillage-pieces-detachees', 2, 'es'),
('chandeliers-balcons', 'Candeleros & barandillas', 'chandeliers-balcons', 'accastillage-pieces-detachees', 2, 'es'),
('echelles-de-bain', 'Escaleras de baño', 'echelles-de-bain', 'accastillage-pieces-detachees', 2, 'es'),
('pare-battages', 'Defensas', 'pare-battages', 'accastillage-pieces-detachees', 2, 'es'),
('hublots-ecoutilles', 'Escotillas & portillos', 'hublots-ecoutilles', 'accastillage-pieces-detachees', 2, 'es'),
('sieges-banquettes', 'Asientos & bancos', 'sieges-banquettes', 'confort-amenagement-interieur', 2, 'es'),
('cabines-couchettes', 'Camarotes & literas', 'cabines-couchettes', 'confort-amenagement-interieur', 2, 'es'),
('eclairage-interieur', 'Iluminación interior', 'eclairage-interieur', 'confort-amenagement-interieur', 2, 'es'),
('cuisine-marine', 'Equipos de cocina marina', 'cuisine-marine', 'confort-amenagement-interieur', 2, 'es'),
('refrigerateurs-glacieres-nautiques', 'Frigoríficos & neveras marinas', 'refrigerateurs-glacieres-nautiques', 'confort-amenagement-interieur', 2, 'es'),
('wc-nautiques', 'WC náuticos', 'wc-nautiques', 'confort-amenagement-interieur', 2, 'es'),
('douches-sanitaires', 'Duchas & sanitarios', 'douches-sanitaires', 'confort-amenagement-interieur', 2, 'es'),
('rangements-coffres', 'Almacenaje & cofres', 'rangements-coffres', 'confort-amenagement-interieur', 2, 'es'),
('housses-protection', 'Fundas de protección', 'housses-protection', 'accessoires-entretien', 2, 'es'),
('nettoyants-entretien', 'Limpiadores & mantenimiento', 'nettoyants-entretien', 'accessoires-entretien', 2, 'es'),
('peintures-antifouling', 'Pinturas & antifouling', 'peintures-antifouling', 'accessoires-entretien', 2, 'es'),
('kits-reparation-coque', 'Kits de reparación de casco', 'kits-reparation-coque', 'accessoires-entretien', 2, 'es'),
('batteries-chargeurs', 'Baterías & cargadores', 'batteries-chargeurs', 'accessoires-entretien', 2, 'es'),
('outils-nautiques', 'Herramientas náuticas', 'outils-nautiques', 'accessoires-entretien', 2, 'es'),
('pompes-manuelles', 'Bombas manuales', 'pompes-manuelles', 'accessoires-entretien', 2, 'es'),
('rames-pagaies', 'Remos & palas', 'rames-pagaies', 'accessoires-entretien', 2, 'es'),
('remorques-bateau', 'Remolques para barcos', 'remorques-bateau', 'transport-stockage', 2, 'es'),
('treuils-sangles', 'Cabrestantes & cinchas', 'treuils-sangles', 'transport-stockage', 2, 'es'),
('chariots-mise-a-leau', 'Carros de botadura', 'chariots-mise-a-leau', 'transport-stockage', 2, 'es'),
('supports-stockage', 'Soportes de almacenamiento', 'supports-stockage', 'transport-stockage', 2, 'es'),
('garages-nautiques', 'Garajes náuticos', 'garages-nautiques', 'transport-stockage', 2, 'es'),
('portiques-palans', 'Pórticos & polipastos', 'portiques-palans', 'transport-stockage', 2, 'es'),
('wakeboard', 'Wakeboard', 'wakeboard', 'sports-nautiques-associes', 2, 'es'),
('ski-nautique', 'Esquí acuático', 'ski-nautique', 'sports-nautiques-associes', 2, 'es'),
('kneeboard', 'Kneeboard', 'kneeboard', 'sports-nautiques-associes', 2, 'es'),
('bouees-tractees', 'Boyas remolcadas', 'bouees-tractees', 'sports-nautiques-associes', 2, 'es'),
('paddle-sup', 'Paddle (SUP)', 'paddle-sup', 'sports-nautiques-associes', 2, 'es'),
('kitesurf', 'Kitesurf', 'kitesurf', 'sports-nautiques-associes', 2, 'es'),
('plongee-snorkeling', 'Buceo & snorkel', 'plongee-snorkeling', 'sports-nautiques-associes', 2, 'es'),
('peche-en-mer-equipements', 'Equipos de pesca en mar', 'peche-en-mer-equipements', 'sports-nautiques-associes', 2, 'es');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('nautisme', 'قوارب وبحرية', 'nautisme', NULL, 0, 'ar');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('types-de-bateaux', 'أنواع القوارب', 'types-de-bateaux', 'nautisme', 1, 'ar'),
('moteurs-propulsion', 'المحركات والدفع', 'moteurs-propulsion', 'nautisme', 1, 'ar'),
('equipements-de-navigation', 'معدات الملاحة', 'equipements-de-navigation', 'nautisme', 1, 'ar'),
('securite-sauvetage', 'السلامة والإنقاذ', 'securite-sauvetage', 'nautisme', 1, 'ar'),
('accastillage-pieces-detachees', 'تجهيزات السطح وقطع غيار', 'accastillage-pieces-detachees', 'nautisme', 1, 'ar'),
('confort-amenagement-interieur', 'راحة وتجهيز داخلي', 'confort-amenagement-interieur', 'nautisme', 1, 'ar'),
('accessoires-entretien', 'إكسسوارات وصيانة', 'accessoires-entretien', 'nautisme', 1, 'ar'),
('transport-stockage', 'نقل وتخزين', 'transport-stockage', 'nautisme', 1, 'ar'),
('sports-nautiques-associes', 'رياضات مائية', 'sports-nautiques-associes', 'nautisme', 1, 'ar');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('bateaux-a-moteur', 'قوارب بمحرك', 'bateaux-a-moteur', 'types-de-bateaux', 2, 'ar'),
('voiliers', 'قوارب شراعية', 'voiliers', 'types-de-bateaux', 2, 'ar'),
('yachts', 'يخوت', 'yachts', 'types-de-bateaux', 2, 'ar'),
('semi-rigides', 'قوارب شبه صلبة', 'semi-rigides', 'types-de-bateaux', 2, 'ar'),
('zodiacs-pneumatiques', 'زودياك وقوارب مطاطية', 'zodiacs-pneumatiques', 'types-de-bateaux', 2, 'ar'),
('jet-skis-scooters-mer', 'دراجات مائية', 'jet-skis-scooters-mer', 'types-de-bateaux', 2, 'ar'),
('barques-chaloupes', 'مراكب تجديف وشالوبيات', 'barques-chaloupes', 'types-de-bateaux', 2, 'ar'),
('kayaks', 'كاياك', 'kayaks', 'types-de-bateaux', 2, 'ar'),
('canoes', 'كانو', 'canoes', 'types-de-bateaux', 2, 'ar'),
('bateaux-de-peche', 'قوارب صيد', 'bateaux-de-peche', 'types-de-bateaux', 2, 'ar'),
('pedalos', 'قوارب بدالات', 'pedalos', 'types-de-bateaux', 2, 'ar'),
('catamarans', 'كاتاماران', 'catamarans', 'types-de-bateaux', 2, 'ar'),
('planches-a-voile-windsurf', 'ألواح ويندسيرف', 'planches-a-voile-windsurf', 'types-de-bateaux', 2, 'ar'),
('moteurs-hors-bord', 'محركات خارجية', 'moteurs-hors-bord', 'moteurs-propulsion', 2, 'ar'),
('moteurs-in-bord', 'محركات داخلية', 'moteurs-in-bord', 'moteurs-propulsion', 2, 'ar'),
('moteurs-electriques', 'محركات كهربائية', 'moteurs-electriques', 'moteurs-propulsion', 2, 'ar'),
('helices', 'مراوح', 'helices', 'moteurs-propulsion', 2, 'ar'),
('propulsion-auxiliaire', 'دفع مساعد', 'propulsion-auxiliaire', 'moteurs-propulsion', 2, 'ar'),
('batteries-marine', 'بطاريات بحرية', 'batteries-marine', 'moteurs-propulsion', 2, 'ar'),
('reservoirs-carburant-nautique', 'خزانات ووقود بحري', 'reservoirs-carburant-nautique', 'moteurs-propulsion', 2, 'ar'),
('gps-nautiques', 'GPS بحري', 'gps-nautiques', 'equipements-de-navigation', 2, 'ar'),
('sondeurs-echosondeurs', 'مجسات وصدى', 'sondeurs-echosondeurs', 'equipements-de-navigation', 2, 'ar'),
('radars', 'رادارات', 'radars', 'equipements-de-navigation', 2, 'ar'),
('cartes-instruments-marins', 'خرائط وأدوات بحرية', 'cartes-instruments-marins', 'equipements-de-navigation', 2, 'ar'),
('compas', 'بوصلة', 'compas', 'equipements-de-navigation', 2, 'ar'),
('pilotes-automatiques', 'طيار آلي', 'pilotes-automatiques', 'equipements-de-navigation', 2, 'ar'),
('radios-vhf', 'راديو VHF', 'radios-vhf', 'equipements-de-navigation', 2, 'ar'),
('traceurs-de-cartes', 'راسم خرائط', 'traceurs-de-cartes', 'equipements-de-navigation', 2, 'ar'),
('jumelles-marines', 'مناظير بحرية', 'jumelles-marines', 'equipements-de-navigation', 2, 'ar'),
('gilets-de-sauvetage', 'سترات نجاة', 'gilets-de-sauvetage', 'securite-sauvetage', 2, 'ar'),
('bouees', 'عوامات', 'bouees', 'securite-sauvetage', 2, 'ar'),
('harnais-lignes-de-vie', 'أحزمة وخطوط حياة', 'harnais-lignes-de-vie', 'securite-sauvetage', 2, 'ar'),
('extincteurs-marine', 'طفايات بحرية', 'extincteurs-marine', 'securite-sauvetage', 2, 'ar'),
('trousses-de-secours', 'حقائب إسعاف أولي', 'trousses-de-secours', 'securite-sauvetage', 2, 'ar'),
('fusees-signalisations', 'مشاعل وإشارات', 'fusees-signalisations', 'securite-sauvetage', 2, 'ar'),
('kits-d-urgence', 'مجموعات طوارئ', 'kits-d-urgence', 'securite-sauvetage', 2, 'ar'),
('pompes-de-cale', 'مضخات تجفيف القاع', 'pompes-de-cale', 'securite-sauvetage', 2, 'ar'),
('cordages', 'حبال', 'cordages', 'accastillage-pieces-detachees', 2, 'ar'),
('amarres', 'حبال ربط', 'amarres', 'accastillage-pieces-detachees', 2, 'ar'),
('ancres-chaines', 'مراسي وسلاسل', 'ancres-chaines', 'accastillage-pieces-detachees', 2, 'ar'),
('poulies', 'بكرات', 'poulies', 'accastillage-pieces-detachees', 2, 'ar'),
('taquets', 'مراسي تثبيت', 'taquets', 'accastillage-pieces-detachees', 2, 'ar'),
('mousquetons', 'مشابك', 'mousquetons', 'accastillage-pieces-detachees', 2, 'ar'),
('winchs', 'ونشات', 'winchs', 'accastillage-pieces-detachees', 2, 'ar'),
('voiles-greements', 'أشرعة وتجهيزات', 'voiles-greements', 'accastillage-pieces-detachees', 2, 'ar'),
('chandeliers-balcons', 'حواجز ومساند', 'chandeliers-balcons', 'accastillage-pieces-detachees', 2, 'ar'),
('echelles-de-bain', 'سلالم سباحة', 'echelles-de-bain', 'accastillage-pieces-detachees', 2, 'ar'),
('pare-battages', 'مصدات', 'pare-battages', 'accastillage-pieces-detachees', 2, 'ar'),
('hublots-ecoutilles', 'نوافذ وفتحات', 'hublots-ecoutilles', 'accastillage-pieces-detachees', 2, 'ar'),
('sieges-banquettes', 'مقاعد ومصاطب', 'sieges-banquettes', 'confort-amenagement-interieur', 2, 'ar'),
('cabines-couchettes', 'كبائن وأسرّة', 'cabines-couchettes', 'confort-amenagement-interieur', 2, 'ar'),
('eclairage-interieur', 'إضاءة داخلية', 'eclairage-interieur', 'confort-amenagement-interieur', 2, 'ar'),
('cuisine-marine', 'معدات مطبخ بحري', 'cuisine-marine', 'confort-amenagement-interieur', 2, 'ar'),
('refrigerateurs-glacieres-nautiques', 'ثلاجات ومبردات بحرية', 'refrigerateurs-glacieres-nautiques', 'confort-amenagement-interieur', 2, 'ar'),
('wc-nautiques', 'دورات مياه بحرية', 'wc-nautiques', 'confort-amenagement-interieur', 2, 'ar'),
('douches-sanitaires', 'دشوص وصحيات', 'douches-sanitaires', 'confort-amenagement-interieur', 2, 'ar'),
('rangements-coffres', 'تخزين وخزائن', 'rangements-coffres', 'confort-amenagement-interieur', 2, 'ar'),
('housses-protection', 'أغطية حماية', 'housses-protection', 'accessoires-entretien', 2, 'ar'),
('nettoyants-entretien', 'منظفات ومنتجات عناية', 'nettoyants-entretien', 'accessoires-entretien', 2, 'ar'),
('peintures-antifouling', 'دهانات ومضادات التلوث البحري', 'peintures-antifouling', 'accessoires-entretien', 2, 'ar'),
('kits-reparation-coque', 'عدة إصلاح الهيكل', 'kits-reparation-coque', 'accessoires-entretien', 2, 'ar'),
('batteries-chargeurs', 'بطاريات وشواحن', 'batteries-chargeurs', 'accessoires-entretien', 2, 'ar'),
('outils-nautiques', 'أدوات بحرية', 'outils-nautiques', 'accessoires-entretien', 2, 'ar'),
('pompes-manuelles', 'مضخات يدوية', 'pompes-manuelles', 'accessoires-entretien', 2, 'ar'),
('rames-pagaies', 'مجاديف', 'rames-pagaies', 'accessoires-entretien', 2, 'ar'),
('remorques-bateau', 'مقطورات القوارب', 'remorques-bateau', 'transport-stockage', 2, 'ar'),
('treuils-sangles', 'ونشات وأحزمة', 'treuils-sangles', 'transport-stockage', 2, 'ar'),
('chariots-mise-a-leau', 'عربات إنزال للماء', 'chariots-mise-a-leau', 'transport-stockage', 2, 'ar'),
('supports-stockage', 'حوامل تخزين', 'supports-stockage', 'transport-stockage', 2, 'ar'),
('garages-nautiques', 'كارجات بحرية', 'garages-nautiques', 'transport-stockage', 2, 'ar'),
('portiques-palans', 'مرافع ورافعات', 'portiques-palans', 'transport-stockage', 2, 'ar'),
('wakeboard', 'ويكبورد', 'wakeboard', 'sports-nautiques-associes', 2, 'ar'),
('ski-nautique', 'تزلج مائي', 'ski-nautique', 'sports-nautiques-associes', 2, 'ar'),
('kneeboard', 'كني بورد', 'kneeboard', 'sports-nautiques-associes', 2, 'ar'),
('bouees-tractees', 'عوامات مسحوبة', 'bouees-tractees', 'sports-nautiques-associes', 2, 'ar'),
('paddle-sup', 'بادل (SUP)', 'paddle-sup', 'sports-nautiques-associes', 2, 'ar'),
('kitesurf', 'كايت سيرف', 'kitesurf', 'sports-nautiques-associes', 2, 'ar'),
('plongee-snorkeling', 'غوص وسنوركلينغ', 'plongee-snorkeling', 'sports-nautiques-associes', 2, 'ar'),
('peche-en-mer-equipements', 'معدات صيد بحري', 'peche-en-mer-equipements', 'sports-nautiques-associes', 2, 'ar');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('nautisme', 'Boote & Nautik', 'nautisme', NULL, 0, 'de');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('types-de-bateaux', 'Bootstypen', 'types-de-bateaux', 'nautisme', 1, 'de'),
('moteurs-propulsion', 'Motoren & Antrieb', 'moteurs-propulsion', 'nautisme', 1, 'de'),
('equipements-de-navigation', 'Navigationsausrüstung', 'equipements-de-navigation', 'nautisme', 1, 'de'),
('securite-sauvetage', 'Sicherheit & Rettung', 'securite-sauvetage', 'nautisme', 1, 'de'),
('accastillage-pieces-detachees', 'Beschläge & Ersatzteile', 'accastillage-pieces-detachees', 'nautisme', 1, 'de'),
('confort-amenagement-interieur', 'Komfort & Innenausbau', 'confort-amenagement-interieur', 'nautisme', 1, 'de'),
('accessoires-entretien', 'Zubehör & Pflege', 'accessoires-entretien', 'nautisme', 1, 'de'),
('transport-stockage', 'Transport & Lagerung', 'transport-stockage', 'nautisme', 1, 'de'),
('sports-nautiques-associes', 'Wassersport', 'sports-nautiques-associes', 'nautisme', 1, 'de');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('bateaux-a-moteur', 'Motorboote', 'bateaux-a-moteur', 'types-de-bateaux', 2, 'de'),
('voiliers', 'Segelboote', 'voiliers', 'types-de-bateaux', 2, 'de'),
('yachts', 'Yachten', 'yachts', 'types-de-bateaux', 2, 'de'),
('semi-rigides', 'Schlauchboote (RIB)', 'semi-rigides', 'types-de-bateaux', 2, 'de'),
('zodiacs-pneumatiques', 'Schlauchboote & Zodiacs', 'zodiacs-pneumatiques', 'types-de-bateaux', 2, 'de'),
('jet-skis-scooters-mer', 'Jetskis & Wasserroller', 'jet-skis-scooters-mer', 'types-de-bateaux', 2, 'de'),
('barques-chaloupes', 'Ruderboote & Schaluppen', 'barques-chaloupes', 'types-de-bateaux', 2, 'de'),
('kayaks', 'Kajaks', 'kayaks', 'types-de-bateaux', 2, 'de'),
('canoes', 'Kanus', 'canoes', 'types-de-bateaux', 2, 'de'),
('bateaux-de-peche', 'Fischerboote', 'bateaux-de-peche', 'types-de-bateaux', 2, 'de'),
('pedalos', 'Tretboote', 'pedalos', 'types-de-bateaux', 2, 'de'),
('catamarans', 'Katamarane', 'catamarans', 'types-de-bateaux', 2, 'de'),
('planches-a-voile-windsurf', 'Windsurf-Bretter', 'planches-a-voile-windsurf', 'types-de-bateaux', 2, 'de'),
('moteurs-hors-bord', 'Außenbordmotoren', 'moteurs-hors-bord', 'moteurs-propulsion', 2, 'de'),
('moteurs-in-bord', 'Innenbordmotoren', 'moteurs-in-bord', 'moteurs-propulsion', 2, 'de'),
('moteurs-electriques', 'Elektromotoren', 'moteurs-electriques', 'moteurs-propulsion', 2, 'de'),
('helices', 'Propeller', 'helices', 'moteurs-propulsion', 2, 'de'),
('propulsion-auxiliaire', 'Hilfsantrieb', 'propulsion-auxiliaire', 'moteurs-propulsion', 2, 'de'),
('batteries-marine', 'Bootsbatterien', 'batteries-marine', 'moteurs-propulsion', 2, 'de'),
('reservoirs-carburant-nautique', 'Kraftstofftanks & Bootskraftstoff', 'reservoirs-carburant-nautique', 'moteurs-propulsion', 2, 'de'),
('gps-nautiques', 'Marine-GPS', 'gps-nautiques', 'equipements-de-navigation', 2, 'de'),
('sondeurs-echosondeurs', 'Echolote & Fischfinder', 'sondeurs-echosondeurs', 'equipements-de-navigation', 2, 'de'),
('radars', 'Radare', 'radars', 'equipements-de-navigation', 2, 'de'),
('cartes-instruments-marins', 'Seekarten & Marineinstrumente', 'cartes-instruments-marins', 'equipements-de-navigation', 2, 'de'),
('compas', 'Kompass', 'compas', 'equipements-de-navigation', 2, 'de'),
('pilotes-automatiques', 'Autopiloten', 'pilotes-automatiques', 'equipements-de-navigation', 2, 'de'),
('radios-vhf', 'UKW-Funkgeräte', 'radios-vhf', 'equipements-de-navigation', 2, 'de'),
('traceurs-de-cartes', 'Kartenplotter', 'traceurs-de-cartes', 'equipements-de-navigation', 2, 'de'),
('jumelles-marines', 'Marine-Ferngläser', 'jumelles-marines', 'equipements-de-navigation', 2, 'de'),
('gilets-de-sauvetage', 'Rettungswesten', 'gilets-de-sauvetage', 'securite-sauvetage', 2, 'de'),
('bouees', 'Bojen', 'bouees', 'securite-sauvetage', 2, 'de'),
('harnais-lignes-de-vie', 'Sicherheitsgurte & Lifelines', 'harnais-lignes-de-vie', 'securite-sauvetage', 2, 'de'),
('extincteurs-marine', 'Feuerlöscher für Boote', 'extincteurs-marine', 'securite-sauvetage', 2, 'de'),
('trousses-de-secours', 'Erste-Hilfe-Sets', 'trousses-de-secours', 'securite-sauvetage', 2, 'de'),
('fusees-signalisations', 'Leuchtraketen & Signale', 'fusees-signalisations', 'securite-sauvetage', 2, 'de'),
('kits-d-urgence', 'Notfallsets', 'kits-d-urgence', 'securite-sauvetage', 2, 'de'),
('pompes-de-cale', 'Bilgenpumpen', 'pompes-de-cale', 'securite-sauvetage', 2, 'de'),
('cordages', 'Leinen & Seile', 'cordages', 'accastillage-pieces-detachees', 2, 'de'),
('amarres', 'Festmacherleinen', 'amarres', 'accastillage-pieces-detachees', 2, 'de'),
('ancres-chaines', 'Anker & Ketten', 'ancres-chaines', 'accastillage-pieces-detachees', 2, 'de'),
('poulies', 'Rollen & Blöcke', 'poulies', 'accastillage-pieces-detachees', 2, 'de'),
('taquets', 'Klampen', 'taquets', 'accastillage-pieces-detachees', 2, 'de'),
('mousquetons', 'Karabiner', 'mousquetons', 'accastillage-pieces-detachees', 2, 'de'),
('winchs', 'Winschen', 'winchs', 'accastillage-pieces-detachees', 2, 'de'),
('voiles-greements', 'Segel & Takelage', 'voiles-greements', 'accastillage-pieces-detachees', 2, 'de'),
('chandeliers-balcons', 'Relings & Pfosten', 'chandeliers-balcons', 'accastillage-pieces-detachees', 2, 'de'),
('echelles-de-bain', 'Badeleitern', 'echelles-de-bain', 'accastillage-pieces-detachees', 2, 'de'),
('pare-battages', 'Fender', 'pare-battages', 'accastillage-pieces-detachees', 2, 'de'),
('hublots-ecoutilles', 'Luken & Bullaugen', 'hublots-ecoutilles', 'accastillage-pieces-detachees', 2, 'de'),
('sieges-banquettes', 'Sitze & Bänke', 'sieges-banquettes', 'confort-amenagement-interieur', 2, 'de'),
('cabines-couchettes', 'Kabinen & Kojen', 'cabines-couchettes', 'confort-amenagement-interieur', 2, 'de'),
('eclairage-interieur', 'Innenbeleuchtung', 'eclairage-interieur', 'confort-amenagement-interieur', 2, 'de'),
('cuisine-marine', 'Küchenausstattung (Marine)', 'cuisine-marine', 'confort-amenagement-interieur', 2, 'de'),
('refrigerateurs-glacieres-nautiques', 'Kühlschränke & Kühlboxen (Marine)', 'refrigerateurs-glacieres-nautiques', 'confort-amenagement-interieur', 2, 'de'),
('wc-nautiques', 'Boots-WCs', 'wc-nautiques', 'confort-amenagement-interieur', 2, 'de'),
('douches-sanitaires', 'Duschen & Sanitär', 'douches-sanitaires', 'confort-amenagement-interieur', 2, 'de'),
('rangements-coffres', 'Stauräume & Schränke', 'rangements-coffres', 'confort-amenagement-interieur', 2, 'de'),
('housses-protection', 'Schutzabdeckungen', 'housses-protection', 'accessoires-entretien', 2, 'de'),
('nettoyants-entretien', 'Reiniger & Pflegeprodukte', 'nettoyants-entretien', 'accessoires-entretien', 2, 'de'),
('peintures-antifouling', 'Farben & Antifouling', 'peintures-antifouling', 'accessoires-entretien', 2, 'de'),
('kits-reparation-coque', 'Rumpfreparatur-Kits', 'kits-reparation-coque', 'accessoires-entretien', 2, 'de'),
('batteries-chargeurs', 'Batterien & Ladegeräte', 'batteries-chargeurs', 'accessoires-entretien', 2, 'de'),
('outils-nautiques', 'Bootswerkzeuge', 'outils-nautiques', 'accessoires-entretien', 2, 'de'),
('pompes-manuelles', 'Handpumpen', 'pompes-manuelles', 'accessoires-entretien', 2, 'de'),
('rames-pagaies', 'Ruder & Paddel', 'rames-pagaies', 'accessoires-entretien', 2, 'de'),
('remorques-bateau', 'Bootsanhänger', 'remorques-bateau', 'transport-stockage', 2, 'de'),
('treuils-sangles', 'Winden & Gurte', 'treuils-sangles', 'transport-stockage', 2, 'de'),
('chariots-mise-a-leau', 'Slipwagen', 'chariots-mise-a-leau', 'transport-stockage', 2, 'de'),
('supports-stockage', 'Lagergestelle', 'supports-stockage', 'transport-stockage', 2, 'de'),
('garages-nautiques', 'Bootsgaragen', 'garages-nautiques', 'transport-stockage', 2, 'de'),
('portiques-palans', 'Davits & Kräne', 'portiques-palans', 'transport-stockage', 2, 'de'),
('wakeboard', 'Wakeboard', 'wakeboard', 'sports-nautiques-associes', 2, 'de'),
('ski-nautique', 'Wasserski', 'ski-nautique', 'sports-nautiques-associes', 2, 'de'),
('kneeboard', 'Kneeboard', 'kneeboard', 'sports-nautiques-associes', 2, 'de'),
('bouees-tractees', 'Zugbojen', 'bouees-tractees', 'sports-nautiques-associes', 2, 'de'),
('paddle-sup', 'Paddle (SUP)', 'paddle-sup', 'sports-nautiques-associes', 2, 'de'),
('kitesurf', 'Kitesurfen', 'kitesurf', 'sports-nautiques-associes', 2, 'de'),
('plongee-snorkeling', 'Tauchen & Schnorcheln', 'plongee-snorkeling', 'sports-nautiques-associes', 2, 'de'),
('peche-en-mer-equipements', 'Meeresangeln-Ausrüstung', 'peche-en-mer-equipements', 'sports-nautiques-associes', 2, 'de');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('nautisme', 'Nautica & Imbarcazioni', 'nautisme', NULL, 0, 'it');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('types-de-bateaux', 'Tipi di imbarcazioni', 'types-de-bateaux', 'nautisme', 1, 'it'),
('moteurs-propulsion', 'Motori & Propulsione', 'moteurs-propulsion', 'nautisme', 1, 'it'),
('equipements-de-navigation', 'Strumenti di navigazione', 'equipements-de-navigation', 'nautisme', 1, 'it'),
('securite-sauvetage', 'Sicurezza & salvataggio', 'securite-sauvetage', 'nautisme', 1, 'it'),
('accastillage-pieces-detachees', 'Accessori ponte & ricambi', 'accastillage-pieces-detachees', 'nautisme', 1, 'it'),
('confort-amenagement-interieur', 'Comfort & interni', 'confort-amenagement-interieur', 'nautisme', 1, 'it'),
('accessoires-entretien', 'Accessori & manutenzione', 'accessoires-entretien', 'nautisme', 1, 'it'),
('transport-stockage', 'Trasporto & stoccaggio', 'transport-stockage', 'nautisme', 1, 'it'),
('sports-nautiques-associes', 'Sport acquatici', 'sports-nautiques-associes', 'nautisme', 1, 'it');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('bateaux-a-moteur', 'Barche a motore', 'bateaux-a-moteur', 'types-de-bateaux', 2, 'it'),
('voiliers', 'Barche a vela', 'voiliers', 'types-de-bateaux', 2, 'it'),
('yachts', 'Yacht', 'yachts', 'types-de-bateaux', 2, 'it'),
('semi-rigides', 'Gommoni (RIB)', 'semi-rigides', 'types-de-bateaux', 2, 'it'),
('zodiacs-pneumatiques', 'Gommoni & Zodiacs', 'zodiacs-pneumatiques', 'types-de-bateaux', 2, 'it'),
('jet-skis-scooters-mer', 'Moto d’acqua', 'jet-skis-scooters-mer', 'types-de-bateaux', 2, 'it'),
('barques-chaloupes', 'Barche a remi & lance', 'barques-chaloupes', 'types-de-bateaux', 2, 'it'),
('kayaks', 'Kayak', 'kayaks', 'types-de-bateaux', 2, 'it'),
('canoes', 'Canoe', 'canoes', 'types-de-bateaux', 2, 'it'),
('bateaux-de-peche', 'Barche da pesca', 'bateaux-de-peche', 'types-de-bateaux', 2, 'it'),
('pedalos', 'Pedalò', 'pedalos', 'types-de-bateaux', 2, 'it'),
('catamarans', 'Catamarani', 'catamarans', 'types-de-bateaux', 2, 'it'),
('planches-a-voile-windsurf', 'Tavole windsurf', 'planches-a-voile-windsurf', 'types-de-bateaux', 2, 'it'),
('moteurs-hors-bord', 'Motori fuoribordo', 'moteurs-hors-bord', 'moteurs-propulsion', 2, 'it'),
('moteurs-in-bord', 'Motori entrobordo', 'moteurs-in-bord', 'moteurs-propulsion', 2, 'it'),
('moteurs-electriques', 'Motori elettrici', 'moteurs-electriques', 'moteurs-propulsion', 2, 'it'),
('helices', 'Eliche', 'helices', 'moteurs-propulsion', 2, 'it'),
('propulsion-auxiliaire', 'Propulsione ausiliaria', 'propulsion-auxiliaire', 'moteurs-propulsion', 2, 'it'),
('batteries-marine', 'Batterie marine', 'batteries-marine', 'moteurs-propulsion', 2, 'it'),
('reservoirs-carburant-nautique', 'Serbatoi & carburante marino', 'reservoirs-carburant-nautique', 'moteurs-propulsion', 2, 'it'),
('gps-nautiques', 'GPS marini', 'gps-nautiques', 'equipements-de-navigation', 2, 'it'),
('sondeurs-echosondeurs', 'Ecoscandagli & fishfinder', 'sondeurs-echosondeurs', 'equipements-de-navigation', 2, 'it'),
('radars', 'Radar', 'radars', 'equipements-de-navigation', 2, 'it'),
('cartes-instruments-marins', 'Carte & strumenti marini', 'cartes-instruments-marins', 'equipements-de-navigation', 2, 'it'),
('compas', 'Bussole', 'compas', 'equipements-de-navigation', 2, 'it'),
('pilotes-automatiques', 'Piloti automatici', 'pilotes-automatiques', 'equipements-de-navigation', 2, 'it'),
('radios-vhf', 'Radio VHF', 'radios-vhf', 'equipements-de-navigation', 2, 'it'),
('traceurs-de-cartes', 'Chartplotter', 'traceurs-de-cartes', 'equipements-de-navigation', 2, 'it'),
('jumelles-marines', 'Binocoli marini', 'jumelles-marines', 'equipements-de-navigation', 2, 'it'),
('gilets-de-sauvetage', 'Gilet salvagente', 'gilets-de-sauvetage', 'securite-sauvetage', 2, 'it'),
('bouees', 'Boe', 'bouees', 'securite-sauvetage', 2, 'it'),
('harnais-lignes-de-vie', 'Imbracature & lifeline', 'harnais-lignes-de-vie', 'securite-sauvetage', 2, 'it'),
('extincteurs-marine', 'Estintori marini', 'extincteurs-marine', 'securite-sauvetage', 2, 'it'),
('trousses-de-secours', 'Kit di pronto soccorso', 'trousses-de-secours', 'securite-sauvetage', 2, 'it'),
('fusees-signalisations', 'Razzi & segnalazioni', 'fusees-signalisations', 'securite-sauvetage', 2, 'it'),
('kits-d-urgence', 'Kit di emergenza', 'kits-d-urgence', 'securite-sauvetage', 2, 'it'),
('pompes-de-cale', 'Pompe di sentina', 'pompes-de-cale', 'securite-sauvetage', 2, 'it'),
('cordages', 'Cime', 'cordages', 'accastillage-pieces-detachees', 2, 'it'),
('amarres', 'Ormeggi', 'amarres', 'accastillage-pieces-detachees', 2, 'it'),
('ancres-chaines', 'Ancora & catene', 'ancres-chaines', 'accastillage-pieces-detachees', 2, 'it'),
('poulies', 'Carrucole', 'poulies', 'accastillage-pieces-detachees', 2, 'it'),
('taquets', 'Gallocce', 'taquets', 'accastillage-pieces-detachees', 2, 'it'),
('mousquetons', 'Moschettoni', 'mousquetons', 'accastillage-pieces-detachees', 2, 'it'),
('winchs', 'Winch', 'winchs', 'accastillage-pieces-detachees', 2, 'it'),
('voiles-greements', 'Vele & rigging', 'voiles-greements', 'accastillage-pieces-detachees', 2, 'it'),
('chandeliers-balcons', 'Pulpiti & battagliole', 'chandeliers-balcons', 'accastillage-pieces-detachees', 2, 'it'),
('echelles-de-bain', 'Scale bagno', 'echelles-de-bain', 'accastillage-pieces-detachees', 2, 'it'),
('pare-battages', 'Parabordi', 'pare-battages', 'accastillage-pieces-detachees', 2, 'it'),
('hublots-ecoutilles', 'Oblò & boccaporti', 'hublots-ecoutilles', 'accastillage-pieces-detachees', 2, 'it'),
('sieges-banquettes', 'Sedute & panche', 'sieges-banquettes', 'confort-amenagement-interieur', 2, 'it'),
('cabines-couchettes', 'Cabine & cuccette', 'cabines-couchettes', 'confort-amenagement-interieur', 2, 'it'),
('eclairage-interieur', 'Illuminazione interna', 'eclairage-interieur', 'confort-amenagement-interieur', 2, 'it'),
('cuisine-marine', 'Cucina di bordo', 'cuisine-marine', 'confort-amenagement-interieur', 2, 'it'),
('refrigerateurs-glacieres-nautiques', 'Frigoriferi & ghiacciaie marine', 'refrigerateurs-glacieres-nautiques', 'confort-amenagement-interieur', 2, 'it'),
('wc-nautiques', 'WC marini', 'wc-nautiques', 'confort-amenagement-interieur', 2, 'it'),
('douches-sanitaires', 'Docce & sanitari', 'douches-sanitaires', 'confort-amenagement-interieur', 2, 'it'),
('rangements-coffres', 'Stivaggi & gavoni', 'rangements-coffres', 'confort-amenagement-interieur', 2, 'it'),
('housses-protection', 'Coperture protettive', 'housses-protection', 'accessoires-entretien', 2, 'it'),
('nettoyants-entretien', 'Detergenti & cura', 'nettoyants-entretien', 'accessoires-entretien', 2, 'it'),
('peintures-antifouling', 'Vernici & antifouling', 'peintures-antifouling', 'accessoires-entretien', 2, 'it'),
('kits-reparation-coque', 'Kit riparazione scafo', 'kits-reparation-coque', 'accessoires-entretien', 2, 'it'),
('batteries-chargeurs', 'Batterie & caricabatterie', 'batteries-chargeurs', 'accessoires-entretien', 2, 'it'),
('outils-nautiques', 'Attrezzi nautici', 'outils-nautiques', 'accessoires-entretien', 2, 'it'),
('pompes-manuelles', 'Pompe manuali', 'pompes-manuelles', 'accessoires-entretien', 2, 'it'),
('rames-pagaies', 'Remi & pagaie', 'rames-pagaies', 'accessoires-entretien', 2, 'it'),
('remorques-bateau', 'Rimorchi barca', 'remorques-bateau', 'transport-stockage', 2, 'it'),
('treuils-sangles', 'Argani & cinghie', 'treuils-sangles', 'transport-stockage', 2, 'it'),
('chariots-mise-a-leau', 'Carrelli varo', 'chariots-mise-a-leau', 'transport-stockage', 2, 'it'),
('supports-stockage', 'Supporti stoccaggio', 'supports-stockage', 'transport-stockage', 2, 'it'),
('garages-nautiques', 'Garage nautici', 'garages-nautiques', 'transport-stockage', 2, 'it'),
('portiques-palans', 'Paranchi & gru', 'portiques-palans', 'transport-stockage', 2, 'it'),
('wakeboard', 'Wakeboard', 'wakeboard', 'sports-nautiques-associes', 2, 'it'),
('ski-nautique', 'Sci nautico', 'ski-nautique', 'sports-nautiques-associes', 2, 'it'),
('kneeboard', 'Kneeboard', 'kneeboard', 'sports-nautiques-associes', 2, 'it'),
('bouees-tractees', 'Ciambelle trainate', 'bouees-tractees', 'sports-nautiques-associes', 2, 'it'),
('paddle-sup', 'Paddle (SUP)', 'paddle-sup', 'sports-nautiques-associes', 2, 'it'),
('kitesurf', 'Kitesurf', 'kitesurf', 'sports-nautiques-associes', 2, 'it'),
('plongee-snorkeling', 'Immersione & snorkeling', 'plongee-snorkeling', 'sports-nautiques-associes', 2, 'it'),
('peche-en-mer-equipements', 'Attrezzatura pesca in mare', 'peche-en-mer-equipements', 'sports-nautiques-associes', 2, 'it');