-- Migration Immobilier & Maison - Toutes les langues
-- Catégorie principale et sous-catégories pour AR, FR, EN, ES, DE, IT

-- ARABE
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('immobilier-maison', 'العقارات والمنزل', 'immobilier-maison', NULL, 0, 'ar');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('ventes-immobilieres', 'مبيعات العقارات', 'ventes-immobilieres', 'immobilier-maison', 1, 'ar'),
('appartements-a-vendre', 'شقق للبيع', 'appartements-a-vendre', 'ventes-immobilieres', 2, 'ar'),
('studios', 'استوديوهات', 'studios', 'ventes-immobilieres', 2, 'ar'),
('f2', 'F2', 'f2', 'ventes-immobilieres', 2, 'ar'),
('f3', 'F3', 'f3', 'ventes-immobilieres', 2, 'ar'),
('f4', 'F4', 'f4', 'ventes-immobilieres', 2, 'ar'),
('f5-plus', 'F5+', 'f5-plus', 'ventes-immobilieres', 2, 'ar'),
('appartements-neufs', 'شقق جديدة', 'appartements-neufs', 'ventes-immobilieres', 2, 'ar'),
('appartements-promotion-immobiliere', 'شقق ترويج عقاري', 'appartements-promotion-immobiliere', 'ventes-immobilieres', 2, 'ar'),
('maisons-a-vendre', 'منازل للبيع', 'maisons-a-vendre', 'ventes-immobilieres', 2, 'ar'),
('villas', 'فلل', 'villas', 'ventes-immobilieres', 2, 'ar'),
('duplex', 'ديوبلكس', 'duplex', 'ventes-immobilieres', 2, 'ar'),
('triplex', 'تريبلكس', 'triplex', 'ventes-immobilieres', 2, 'ar'),
('maisons-plain-pied', 'منازل بطابق واحد', 'maisons-plain-pied', 'ventes-immobilieres', 2, 'ar'),
('fermes-proprietes-rurales', 'مزارع وعقارات ريفية', 'fermes-proprietes-rurales', 'ventes-immobilieres', 2, 'ar'),
('terrains-constructibles', 'أراضٍ قابلة للبناء', 'terrains-constructibles', 'ventes-immobilieres', 2, 'ar'),
('terrains-agricoles', 'أراضٍ زراعية', 'terrains-agricoles', 'ventes-immobilieres', 2, 'ar'),
('locaux-commerciaux', 'محلات تجارية', 'locaux-commerciaux', 'ventes-immobilieres', 2, 'ar'),
('bureaux', 'مكاتب', 'bureaux', 'ventes-immobilieres', 2, 'ar'),
('immeubles', 'عمارات', 'immeubles', 'ventes-immobilieres', 2, 'ar'),
('garages-a-vendre', 'كراجات للبيع', 'garages-a-vendre', 'ventes-immobilieres', 2, 'ar'),
('locations-immobilieres', 'إيجارات العقارات', 'locations-immobilieres', 'immobilier-maison', 1, 'ar'),
('appartements-en-location', 'شقق للإيجار', 'appartements-en-location', 'locations-immobilieres', 2, 'ar'),
('studios-location', 'استوديوهات', 'studios', 'locations-immobilieres', 2, 'ar'),
('f2-location', 'F2', 'f2', 'locations-immobilieres', 2, 'ar'),
('f3-location', 'F3', 'f3', 'locations-immobilieres', 2, 'ar'),
('f4-location', 'F4', 'f4', 'locations-immobilieres', 2, 'ar'),
('maisons-en-location', 'منازل للإيجار', 'maisons-en-location', 'locations-immobilieres', 2, 'ar'),
('villas-location', 'فلل', 'villas', 'locations-immobilieres', 2, 'ar'),
('duplex-location', 'ديوبلكس', 'duplex', 'locations-immobilieres', 2, 'ar'),
('triplex-location', 'تريبلكس', 'triplex', 'locations-immobilieres', 2, 'ar'),
('chambres-en-location', 'غرف للإيجار', 'chambres-en-location', 'locations-immobilieres', 2, 'ar'),
('colocation', 'سكن مشترك', 'colocation', 'locations-immobilieres', 2, 'ar'),
('locations-meublees', 'إيجارات مفروشة', 'locations-meublees', 'locations-immobilieres', 2, 'ar'),
('locations-non-meublees', 'إيجارات غير مفروشة', 'locations-non-meublees', 'locations-immobilieres', 2, 'ar'),
('locations-saisonnieres', 'إيجارات موسمية', 'locations-saisonnieres', 'locations-immobilieres', 2, 'ar'),
('locations-vacances', 'إيجارات عطلات', 'locations-vacances', 'locations-immobilieres', 2, 'ar'),
('bureaux-a-louer', 'مكاتب للإيجار', 'bureaux-a-louer', 'locations-immobilieres', 2, 'ar'),
('locaux-commerciaux-a-louer', 'محلات تجارية للإيجار', 'locaux-commerciaux-a-louer', 'locations-immobilieres', 2, 'ar'),
('garages-parkings-a-louer', 'كراجات ومواقف للإيجار', 'garages-parkings-a-louer', 'locations-immobilieres', 2, 'ar'),
('immobilier-professionnel', 'عقار مهني', 'immobilier-professionnel', 'immobilier-maison', 1, 'ar'),
('entrepots', 'مستودعات', 'entrepots', 'immobilier-professionnel', 2, 'ar'),
('hangars', 'هنغارات', 'hangars', 'immobilier-professionnel', 2, 'ar'),
('locaux-industriels', 'محلات صناعية', 'locaux-industriels', 'immobilier-professionnel', 2, 'ar'),
('ateliers', 'ورش', 'ateliers', 'immobilier-professionnel', 2, 'ar'),
('zones-logistiques', 'مناطق لوجستية', 'zones-logistiques', 'immobilier-professionnel', 2, 'ar'),
('bureaux-professionnels', 'مكاتب مهنية', 'bureaux-professionnels', 'immobilier-professionnel', 2, 'ar'),
('open-spaces', 'مساحات مفتوحة', 'open-spaces', 'immobilier-professionnel', 2, 'ar'),
('magasins', 'متاجر', 'magasins', 'immobilier-professionnel', 2, 'ar'),
('restaurants-cafes', 'مطاعم ومقاهي', 'restaurants-cafes', 'immobilier-professionnel', 2, 'ar'),
('pharmacies', 'صيدليات', 'pharmacies', 'immobilier-professionnel', 2, 'ar'),
('cabinets-medicaux', 'عيادات طبية', 'cabinets-medicaux', 'immobilier-professionnel', 2, 'ar'),
('investissement-immobilier', 'استثمار عقاري', 'investissement-immobilier', 'immobilier-maison', 1, 'ar'),
('programmes-neufs', 'برامج جديدة', 'programmes-neufs', 'investissement-immobilier', 2, 'ar'),
('logements-promotionnels', 'سكن ترويجي', 'logements-promotionnels', 'investissement-immobilier', 2, 'ar'),
('immobiliers-lpp', 'عقارات LPP', 'immobiliers-lpp', 'investissement-immobilier', 2, 'ar'),
('logements-sociaux', 'سكن اجتماعي', 'logements-sociaux', 'investissement-immobilier', 2, 'ar'),
('residences-etudiantes', 'إقامات طلابية', 'residences-etudiantes', 'investissement-immobilier', 2, 'ar'),
('residences-seniors', 'إقامات لكبار السن', 'residences-seniors', 'investissement-immobilier', 2, 'ar'),
('biens-locatifs', 'عقارات للإيجار', 'biens-locatifs', 'investissement-immobilier', 2, 'ar'),
('immeubles-de-rapport', 'عمارات دخل', 'immeubles-de-rapport', 'investissement-immobilier', 2, 'ar'),
('terrains-promotionnels', 'أراضٍ ترويجية', 'terrains-promotionnels', 'investissement-immobilier', 2, 'ar'),
('maison-mobilier-interieur', 'المنزل والأثاث الداخلي', 'maison-mobilier-interieur', 'immobilier-maison', 1, 'ar'),
('salons-canapes', 'صالات وجلوس', 'salons-canapes', 'maison-mobilier-interieur', 2, 'ar'),
('tables-chaises', 'طاولات وكراسي', 'tables-chaises', 'maison-mobilier-interieur', 2, 'ar'),
('armoires', 'خزائن', 'armoires', 'maison-mobilier-interieur', 2, 'ar'),
('dressings', 'غرف تبديل الملابس', 'dressings', 'maison-mobilier-interieur', 2, 'ar'),
('lits-matelas', 'أسرة ومراتب', 'lits-matelas', 'maison-mobilier-interieur', 2, 'ar'),
('meubles-tv', 'أثاث التلفاز', 'meubles-tv', 'maison-mobilier-interieur', 2, 'ar'),
('buffets-commodes', 'بوفيهات وكمود', 'buffets-commodes', 'maison-mobilier-interieur', 2, 'ar'),
('bibliotheques', 'مكتبات', 'bibliotheques', 'maison-mobilier-interieur', 2, 'ar'),
('meubles-enfants', 'أثاث الأطفال', 'meubles-enfants', 'maison-mobilier-interieur', 2, 'ar'),
('petits-meubles', 'أثاث صغير', 'petits-meubles', 'maison-mobilier-interieur', 2, 'ar'),
('rangements', 'تخزين وتنظيم', 'rangements', 'maison-mobilier-interieur', 2, 'ar'),
('decoration-accessoires-maison', 'ديكور وإكسسوارات المنزل', 'decoration-accessoires-maison', 'immobilier-maison', 1, 'ar'),
('tapis', 'سجاد', 'tapis', 'decoration-accessoires-maison', 2, 'ar'),
('rideaux-voilages', 'ستائر وحواجز', 'rideaux-voilages', 'decoration-accessoires-maison', 2, 'ar'),
('luminaires', 'إضاءة', 'luminaires', 'decoration-accessoires-maison', 2, 'ar'),
('cadres-tableaux', 'إطارات ولوحات', 'cadres-tableaux', 'decoration-accessoires-maison', 2, 'ar'),
('miroirs', 'مرايا', 'miroirs', 'decoration-accessoires-maison', 2, 'ar'),
('horloges', 'ساعات', 'horloges', 'decoration-accessoires-maison', 2, 'ar'),
('accessoires-decoratifs', 'إكسسوارات ديكور', 'accessoires-decoratifs', 'decoration-accessoires-maison', 2, 'ar'),
('stickers-muraux', 'ملصقات جدارية', 'stickers-muraux', 'decoration-accessoires-maison', 2, 'ar'),
('coussins-textiles', 'وسائد ومنسوجات', 'coussins-textiles', 'decoration-accessoires-maison', 2, 'ar'),
('vases-decor-floral', 'مزهريات وديكور زهري', 'vases-decor-floral', 'decoration-accessoires-maison', 2, 'ar'),
('cuisine-salle-de-bain', 'المطبخ والحمام', 'cuisine-salle-de-bain', 'immobilier-maison', 1, 'ar'),
('ustensiles-de-cuisine', 'أدوات المطبخ', 'ustensiles-de-cuisine', 'cuisine-salle-de-bain', 2, 'ar'),
('casseroles-poeles', 'قدور ومقالي', 'casseroles-poeles', 'cuisine-salle-de-bain', 2, 'ar'),
('vaisselle', 'أواني', 'vaisselle', 'cuisine-salle-de-bain', 2, 'ar'),
('couverts', 'أدوات المائدة', 'couverts', 'cuisine-salle-de-bain', 2, 'ar'),
('robots-de-cuisine', 'أجهزة المطبخ', 'robots-de-cuisine', 'cuisine-salle-de-bain', 2, 'ar'),
('plaques-fours', 'مواقد وأفران', 'plaques-fours', 'cuisine-salle-de-bain', 2, 'ar'),
('equipements-sanitaires', 'معدات صحية', 'equipements-sanitaires', 'cuisine-salle-de-bain', 2, 'ar'),
('baignoires', 'أحواض استحمام', 'baignoires', 'cuisine-salle-de-bain', 2, 'ar'),
('douches', 'دش', 'douches', 'cuisine-salle-de-bain', 2, 'ar'),
('lavabos', 'مغاسل', 'lavabos', 'cuisine-salle-de-bain', 2, 'ar'),
('robinetterie', 'خلاطات ومحابس', 'robinetterie', 'cuisine-salle-de-bain', 2, 'ar'),
('meubles-de-salle-de-bain', 'أثاث الحمام', 'meubles-de-salle-de-bain', 'cuisine-salle-de-bain', 2, 'ar'),
('jardin-exterieur', 'الحديقة والخارج', 'jardin-exterieur', 'immobilier-maison', 1, 'ar'),
('mobilier-de-jardin', 'أثاث الحديقة', 'mobilier-de-jardin', 'jardin-exterieur', 2, 'ar'),
('salons-exterieurs', 'جلسات خارجية', 'salons-exterieurs', 'jardin-exterieur', 2, 'ar'),
('parasols', 'مظلات', 'parasols', 'jardin-exterieur', 2, 'ar'),
('barbecues', 'شوايات', 'barbecues', 'jardin-exterieur', 2, 'ar'),
('tondeuses', 'جزازات عشب', 'tondeuses', 'jardin-exterieur', 2, 'ar'),
('debroussailleuses', 'مزيلات أعشاب', 'debroussailleuses', 'jardin-exterieur', 2, 'ar'),
('tronconneuses', 'مناشير', 'tronconneuses', 'jardin-exterieur', 2, 'ar'),
('outils-de-jardinage', 'أدوات البستنة', 'outils-de-jardinage', 'jardin-exterieur', 2, 'ar'),
('pots-jardinieres', 'أصص وزروع', 'pots-jardinieres', 'jardin-exterieur', 2, 'ar'),
('serres', 'بيوت زجاجية', 'serres', 'jardin-exterieur', 2, 'ar'),
('piscines-accessoires', 'مسابح وإكسسوارات', 'piscines-accessoires', 'jardin-exterieur', 2, 'ar'),
('eclairage-exterieur', 'إضاءة خارجية', 'eclairage-exterieur', 'jardin-exterieur', 2, 'ar'),
('bricolage-amelioration-maison', 'أعمال منزلية وتحسين المسكن', 'bricolage-amelioration-maison', 'immobilier-maison', 1, 'ar'),
('outils-electroportatifs', 'أدوات كهربائية (مثاقب، مفكات، جلاخات)', 'outils-electroportatifs', 'bricolage-amelioration-maison', 2, 'ar'),
('outils-a-main', 'أدوات يدوية', 'outils-a-main', 'bricolage-amelioration-maison', 2, 'ar'),
('peinture', 'دهان', 'peinture', 'bricolage-amelioration-maison', 2, 'ar'),
('revetements-murs-sols', 'كسوة الجدران والأرضيات', 'revetements-murs-sols', 'bricolage-amelioration-maison', 2, 'ar'),
('parquet', 'باركيه', 'parquet', 'bricolage-amelioration-maison', 2, 'ar'),
('carrelage', 'بلاط', 'carrelage', 'bricolage-amelioration-maison', 2, 'ar'),
('plomberie', 'سباكة', 'plomberie', 'bricolage-amelioration-maison', 2, 'ar'),
('electricite', 'كهرباء', 'electricite', 'bricolage-amelioration-maison', 2, 'ar'),
('isolation', 'عزل', 'isolation', 'bricolage-amelioration-maison', 2, 'ar'),
('materiaux-de-construction', 'مواد البناء', 'materiaux-de-construction', 'bricolage-amelioration-maison', 2, 'ar'),
('portes-fenetres', 'أبواب ونوافذ', 'portes-fenetres', 'bricolage-amelioration-maison', 2, 'ar'),
('securite-maison', 'أمن المنزل', 'securite-maison', 'immobilier-maison', 1, 'ar'),
('cameras-de-surveillance', 'كاميرات مراقبة', 'cameras-de-surveillance', 'securite-maison', 2, 'ar'),
('alarmes-connectees', 'إنذارات متصلة', 'alarmes-connectees', 'securite-maison', 2, 'ar'),
('detecteurs-de-fumee', 'كاشفات دخان', 'detecteurs-de-fumee', 'securite-maison', 2, 'ar'),
('serrures-cadenas', 'أقفال وسلاسل', 'serrures-cadenas', 'securite-maison', 2, 'ar'),
('portails-automatiques', 'بوابات آلية', 'portails-automatiques', 'securite-maison', 2, 'ar'),
('visiophones', 'أنظمة اتصال مرئي', 'visiophones', 'securite-maison', 2, 'ar'),
('coffres-forts', 'خزائن آمنة', 'coffres-forts', 'securite-maison', 2, 'ar'),
('services-maison-immobilier', 'خدمات المنزل والعقار', 'services-maison-immobilier', 'immobilier-maison', 1, 'ar'),
('agences-immobilieres', 'وكالات عقارية', 'agences-immobilieres', 'services-maison-immobilier', 2, 'ar'),
('services-architecture', 'خدمات الهندسة المعمارية', 'services-architecture', 'services-maison-immobilier', 2, 'ar'),
('artisans-plomberie-electricite-peinture', 'حرفيون (سباكة، كهرباء، طلاء)', 'artisans-plomberie-electricite-peinture', 'services-maison-immobilier', 2, 'ar'),
('demenagement', 'نقل', 'demenagement', 'services-maison-immobilier', 2, 'ar'),
('nettoyage', 'تنظيف', 'nettoyage', 'services-maison-immobilier', 2, 'ar'),
('entretien-jardin', 'صيانة الحدائق', 'entretien-jardin', 'services-maison-immobilier', 2, 'ar'),
('renovation', 'ترميم', 'renovation', 'services-maison-immobilier', 2, 'ar'),
('gestion-locative', 'إدارة الإيجارات', 'gestion-locative', 'services-maison-immobilier', 2, 'ar'),
('diagnostics-immobiliers', 'تشخيصات عقارية', 'diagnostics-immobiliers', 'services-maison-immobilier', 2, 'ar'),
('marques-materiel-populaire', 'ماركات ومعدات شائعة', 'marques-materiel-populaire', 'immobilier-maison', 1, 'ar'),
('ikea', 'Ikea', 'ikea', 'marques-materiel-populaire', 2, 'ar'),
('samsung-home', 'Samsung Home', 'samsung-home', 'marques-materiel-populaire', 2, 'ar'),
('lg', 'LG', 'lg', 'marques-materiel-populaire', 2, 'ar'),
('bosch', 'Bosch', 'bosch', 'marques-materiel-populaire', 2, 'ar'),
('beko', 'Beko', 'beko', 'marques-materiel-populaire', 2, 'ar'),
('whirlpool', 'Whirlpool', 'whirlpool', 'marques-materiel-populaire', 2, 'ar'),
('philips-lighting', 'Philips Lighting', 'philips-lighting', 'marques-materiel-populaire', 2, 'ar'),
('schneider-electric', 'Schneider Electric', 'schneider-electric', 'marques-materiel-populaire', 2, 'ar'),
('karcher', 'Kärcher', 'karcher', 'marques-materiel-populaire', 2, 'ar'),
('ariston', 'Ariston', 'ariston', 'marques-materiel-populaire', 2, 'ar'),
('moulinex', 'Moulinex', 'moulinex', 'marques-materiel-populaire', 2, 'ar'),
('tefal', 'Tefal', 'tefal', 'marques-materiel-populaire', 2, 'ar'),
('jaga', 'Jaga', 'jaga', 'marques-materiel-populaire', 2, 'ar'),
('daikin', 'Daikin', 'daikin', 'marques-materiel-populaire', 2, 'ar'),
('hitachi', 'Hitachi', 'hitachi', 'marques-materiel-populaire', 2, 'ar');

-- FRANÇAIS
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('immobilier-maison', 'Immobilier & Maison', 'immobilier-maison', NULL, 0, 'fr');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('ventes-immobilieres', 'Ventes Immobilières', 'ventes-immobilieres', 'immobilier-maison', 1, 'fr'),
('appartements-a-vendre', 'Appartements à vendre', 'appartements-a-vendre', 'ventes-immobilieres', 2, 'fr'),
('studios', 'Studios', 'studios', 'ventes-immobilieres', 2, 'fr'),
('f2', 'F2', 'f2', 'ventes-immobilieres', 2, 'fr'),
('f3', 'F3', 'f3', 'ventes-immobilieres', 2, 'fr'),
('f4', 'F4', 'f4', 'ventes-immobilieres', 2, 'fr'),
('f5-plus', 'F5+', 'f5-plus', 'ventes-immobilieres', 2, 'fr'),
('appartements-neufs', 'Appartements neufs', 'appartements-neufs', 'ventes-immobilieres', 2, 'fr'),
('appartements-promotion-immobiliere', 'Appartements promotion immobilière', 'appartements-promotion-immobiliere', 'ventes-immobilieres', 2, 'fr'),
('maisons-a-vendre', 'Maisons à vendre', 'maisons-a-vendre', 'ventes-immobilieres', 2, 'fr'),
('villas', 'Villas', 'villas', 'ventes-immobilieres', 2, 'fr'),
('duplex', 'Duplex', 'duplex', 'ventes-immobilieres', 2, 'fr'),
('triplex', 'Triplex', 'triplex', 'ventes-immobilieres', 2, 'fr'),
('maisons-plain-pied', 'Maisons plain-pied', 'maisons-plain-pied', 'ventes-immobilieres', 2, 'fr'),
('fermes-proprietes-rurales', 'Fermes & propriétés rurales', 'fermes-proprietes-rurales', 'ventes-immobilieres', 2, 'fr'),
('terrains-constructibles', 'Terrains constructibles', 'terrains-constructibles', 'ventes-immobilieres', 2, 'fr'),
('terrains-agricoles', 'Terrains agricoles', 'terrains-agricoles', 'ventes-immobilieres', 2, 'fr'),
('locaux-commerciaux', 'Locaux commerciaux', 'locaux-commerciaux', 'ventes-immobilieres', 2, 'fr'),
('bureaux', 'Bureaux', 'bureaux', 'ventes-immobilieres', 2, 'fr'),
('immeubles', 'Immeubles', 'immeubles', 'ventes-immobilieres', 2, 'fr'),
('garages-a-vendre', 'Garages à vendre', 'garages-a-vendre', 'ventes-immobilieres', 2, 'fr'),
('locations-immobilieres', 'Locations Immobilières', 'locations-immobilieres', 'immobilier-maison', 1, 'fr'),
('appartements-en-location', 'Appartements en location', 'appartements-en-location', 'locations-immobilieres', 2, 'fr'),
('studios-location', 'Studios', 'studios', 'locations-immobilieres', 2, 'fr'),
('f2-location', 'F2', 'f2', 'locations-immobilieres', 2, 'fr'),
('f3-location', 'F3', 'f3', 'locations-immobilieres', 2, 'fr'),
('f4-location', 'F4', 'f4', 'locations-immobilieres', 2, 'fr'),
('maisons-en-location', 'Maisons en location', 'maisons-en-location', 'locations-immobilieres', 2, 'fr'),
('villas-location', 'Villas', 'villas', 'locations-immobilieres', 2, 'fr'),
('duplex-location', 'Duplex', 'duplex', 'locations-immobilieres', 2, 'fr'),
('triplex-location', 'Triplex', 'triplex', 'locations-immobilieres', 2, 'fr'),
('chambres-en-location', 'Chambres en location', 'chambres-en-location', 'locations-immobilieres', 2, 'fr'),
('colocation', 'Colocation', 'colocation', 'locations-immobilieres', 2, 'fr'),
('locations-meublees', 'Locations meublées', 'locations-meublees', 'locations-immobilieres', 2, 'fr'),
('locations-non-meublees', 'Locations non meublées', 'locations-non-meublees', 'locations-immobilieres', 2, 'fr'),
('locations-saisonnieres', 'Locations saisonnières', 'locations-saisonnieres', 'locations-immobilieres', 2, 'fr'),
('locations-vacances', 'Locations vacances', 'locations-vacances', 'locations-immobilieres', 2, 'fr'),
('bureaux-a-louer', 'Bureaux à louer', 'bureaux-a-louer', 'locations-immobilieres', 2, 'fr'),
('locaux-commerciaux-a-louer', 'Locaux commerciaux à louer', 'locaux-commerciaux-a-louer', 'locations-immobilieres', 2, 'fr'),
('garages-parkings-a-louer', 'Garages & parkings à louer', 'garages-parkings-a-louer', 'locations-immobilieres', 2, 'fr'),
('immobilier-professionnel', 'Immobilier Professionnel', 'immobilier-professionnel', 'immobilier-maison', 1, 'fr'),
('entrepots', 'Entrepôts', 'entrepots', 'immobilier-professionnel', 2, 'fr'),
('hangars', 'Hangars', 'hangars', 'immobilier-professionnel', 2, 'fr'),
('locaux-industriels', 'Locaux industriels', 'locaux-industriels', 'immobilier-professionnel', 2, 'fr'),
('ateliers', 'Ateliers', 'ateliers', 'immobilier-professionnel', 2, 'fr'),
('zones-logistiques', 'Zones logistiques', 'zones-logistiques', 'immobilier-professionnel', 2, 'fr'),
('bureaux-professionnels', 'Bureaux professionnels', 'bureaux-professionnels', 'immobilier-professionnel', 2, 'fr'),
('open-spaces', 'Open-spaces', 'open-spaces', 'immobilier-professionnel', 2, 'fr'),
('magasins', 'Magasins', 'magasins', 'immobilier-professionnel', 2, 'fr'),
('restaurants-cafes', 'Restaurants & cafés', 'restaurants-cafes', 'immobilier-professionnel', 2, 'fr'),
('pharmacies', 'Pharmacies', 'pharmacies', 'immobilier-professionnel', 2, 'fr'),
('cabinets-medicaux', 'Cabinets médicaux', 'cabinets-medicaux', 'immobilier-professionnel', 2, 'fr'),
('investissement-immobilier', 'Investissement Immobilier', 'investissement-immobilier', 'immobilier-maison', 1, 'fr'),
('programmes-neufs', 'Programmes neufs', 'programmes-neufs', 'investissement-immobilier', 2, 'fr'),
('logements-promotionnels', 'Logements promotionnels', 'logements-promotionnels', 'investissement-immobilier', 2, 'fr'),
('immobiliers-lpp', 'Immobiliers LPP', 'immobiliers-lpp', 'investissement-immobilier', 2, 'fr'),
('logements-sociaux', 'Logements sociaux', 'logements-sociaux', 'investissement-immobilier', 2, 'fr'),
('residences-etudiantes', 'Résidences étudiantes', 'residences-etudiantes', 'investissement-immobilier', 2, 'fr'),
('residences-seniors', 'Résidences seniors', 'residences-seniors', 'investissement-immobilier', 2, 'fr'),
('biens-locatifs', 'Biens locatifs', 'biens-locatifs', 'investissement-immobilier', 2, 'fr'),
('immeubles-de-rapport', 'Immeubles de rapport', 'immeubles-de-rapport', 'investissement-immobilier', 2, 'fr'),
('terrains-promotionnels', 'Terrains promotionnels', 'terrains-promotionnels', 'investissement-immobilier', 2, 'fr'),
('maison-mobilier-interieur', 'Maison & Mobilier Intérieur', 'maison-mobilier-interieur', 'immobilier-maison', 1, 'fr'),
('salons-canapes', 'Salons & canapés', 'salons-canapes', 'maison-mobilier-interieur', 2, 'fr'),
('tables-chaises', 'Tables & chaises', 'tables-chaises', 'maison-mobilier-interieur', 2, 'fr'),
('armoires', 'Armoires', 'armoires', 'maison-mobilier-interieur', 2, 'fr'),
('dressings', 'Dressings', 'dressings', 'maison-mobilier-interieur', 2, 'fr'),
('lits-matelas', 'Lits & matelas', 'lits-matelas', 'maison-mobilier-interieur', 2, 'fr'),
('meubles-tv', 'Meubles TV', 'meubles-tv', 'maison-mobilier-interieur', 2, 'fr'),
('buffets-commodes', 'Buffets & commodes', 'buffets-commodes', 'maison-mobilier-interieur', 2, 'fr'),
('bibliotheques', 'Bibliothèques', 'bibliotheques', 'maison-mobilier-interieur', 2, 'fr'),
('meubles-enfants', 'Meubles enfants', 'meubles-enfants', 'maison-mobilier-interieur', 2, 'fr'),
('petits-meubles', 'Petits meubles', 'petits-meubles', 'maison-mobilier-interieur', 2, 'fr'),
('rangements', 'Rangements', 'rangements', 'maison-mobilier-interieur', 2, 'fr'),
('decoration-accessoires-maison', 'Décoration & Accessoires Maison', 'decoration-accessoires-maison', 'immobilier-maison', 1, 'fr'),
('tapis', 'Tapis', 'tapis', 'decoration-accessoires-maison', 2, 'fr'),
('rideaux-voilages', 'Rideaux & voilages', 'rideaux-voilages', 'decoration-accessoires-maison', 2, 'fr'),
('luminaires', 'Luminaires', 'luminaires', 'decoration-accessoires-maison', 2, 'fr'),
('cadres-tableaux', 'Cadres & tableaux', 'cadres-tableaux', 'decoration-accessoires-maison', 2, 'fr'),
('miroirs', 'Miroirs', 'miroirs', 'decoration-accessoires-maison', 2, 'fr'),
('horloges', 'Horloges', 'horloges', 'decoration-accessoires-maison', 2, 'fr'),
('accessoires-decoratifs', 'Accessoires décoratifs', 'accessoires-decoratifs', 'decoration-accessoires-maison', 2, 'fr'),
('stickers-muraux', 'Stickers muraux', 'stickers-muraux', 'decoration-accessoires-maison', 2, 'fr'),
('coussins-textiles', 'Coussins & textiles', 'coussins-textiles', 'decoration-accessoires-maison', 2, 'fr'),
('vases-decor-floral', 'Vases & décor floral', 'vases-decor-floral', 'decoration-accessoires-maison', 2, 'fr'),
('cuisine-salle-de-bain', 'Cuisine & Salle de Bain', 'cuisine-salle-de-bain', 'immobilier-maison', 1, 'fr'),
('ustensiles-de-cuisine', 'Ustensiles de cuisine', 'ustensiles-de-cuisine', 'cuisine-salle-de-bain', 2, 'fr'),
('casseroles-poeles', 'Casseroles & poêles', 'casseroles-poeles', 'cuisine-salle-de-bain', 2, 'fr'),
('vaisselle', 'Vaisselle', 'vaisselle', 'cuisine-salle-de-bain', 2, 'fr'),
('couverts', 'Couverts', 'couverts', 'cuisine-salle-de-bain', 2, 'fr'),
('robots-de-cuisine', 'Robots de cuisine', 'robots-de-cuisine', 'cuisine-salle-de-bain', 2, 'fr'),
('plaques-fours', 'Plaques & fours', 'plaques-fours', 'cuisine-salle-de-bain', 2, 'fr'),
('equipements-sanitaires', 'Équipements sanitaires', 'equipements-sanitaires', 'cuisine-salle-de-bain', 2, 'fr'),
('baignoires', 'Baignoires', 'baignoires', 'cuisine-salle-de-bain', 2, 'fr'),
('douches', 'Douches', 'douches', 'cuisine-salle-de-bain', 2, 'fr'),
('lavabos', 'Lavabos', 'lavabos', 'cuisine-salle-de-bain', 2, 'fr'),
('robinetterie', 'Robinetterie', 'robinetterie', 'cuisine-salle-de-bain', 2, 'fr'),
('meubles-de-salle-de-bain', 'Meubles de salle de bain', 'meubles-de-salle-de-bain', 'cuisine-salle-de-bain', 2, 'fr'),
('jardin-exterieur', 'Jardin & Extérieur', 'jardin-exterieur', 'immobilier-maison', 1, 'fr'),
('mobilier-de-jardin', 'Mobilier de jardin', 'mobilier-de-jardin', 'jardin-exterieur', 2, 'fr'),
('salons-exterieurs', 'Salons extérieurs', 'salons-exterieurs', 'jardin-exterieur', 2, 'fr'),
('parasols', 'Parasols', 'parasols', 'jardin-exterieur', 2, 'fr'),
('barbecues', 'Barbecues', 'barbecues', 'jardin-exterieur', 2, 'fr'),
('tondeuses', 'Tondeuses', 'tondeuses', 'jardin-exterieur', 2, 'fr'),
('debroussailleuses', 'Débroussailleuses', 'debroussailleuses', 'jardin-exterieur', 2, 'fr'),
('tronconneuses', 'Tronçonneuses', 'tronconneuses', 'jardin-exterieur', 2, 'fr'),
('outils-de-jardinage', 'Outils de jardinage', 'outils-de-jardinage', 'jardin-exterieur', 2, 'fr'),
('pots-jardinieres', 'Pots & jardinières', 'pots-jardinieres', 'jardin-exterieur', 2, 'fr'),
('serres', 'Serres', 'serres', 'jardin-exterieur', 2, 'fr'),
('piscines-accessoires', 'Piscines & accessoires', 'piscines-accessoires', 'jardin-exterieur', 2, 'fr'),
('eclairage-exterieur', 'Éclairage extérieur', 'eclairage-exterieur', 'jardin-exterieur', 2, 'fr'),
('bricolage-amelioration-maison', 'Bricolage & Amélioration Maison', 'bricolage-amelioration-maison', 'immobilier-maison', 1, 'fr'),
('outils-electroportatifs', 'Outils électroportatifs (perceuses, visseuses, meuleuses)', 'outils-electroportatifs', 'bricolage-amelioration-maison', 2, 'fr'),
('outils-a-main', 'Outils à main', 'outils-a-main', 'bricolage-amelioration-maison', 2, 'fr'),
('peinture', 'Peinture', 'peinture', 'bricolage-amelioration-maison', 2, 'fr'),
('revetements-murs-sols', 'Revêtements murs & sols', 'revetements-murs-sols', 'bricolage-amelioration-maison', 2, 'fr'),
('parquet', 'Parquet', 'parquet', 'bricolage-amelioration-maison', 2, 'fr'),
('carrelage', 'Carrelage', 'carrelage', 'bricolage-amelioration-maison', 2, 'fr'),
('plomberie', 'Plomberie', 'plomberie', 'bricolage-amelioration-maison', 2, 'fr'),
('electricite', 'Électricité', 'electricite', 'bricolage-amelioration-maison', 2, 'fr'),
('isolation', 'Isolation', 'isolation', 'bricolage-amelioration-maison', 2, 'fr'),
('materiaux-de-construction', 'Matériaux de construction', 'materiaux-de-construction', 'bricolage-amelioration-maison', 2, 'fr'),
('portes-fenetres', 'Portes & fenêtres', 'portes-fenetres', 'bricolage-amelioration-maison', 2, 'fr'),
('securite-maison', 'Sécurité Maison', 'securite-maison', 'immobilier-maison', 1, 'fr'),
('cameras-de-surveillance', 'Caméras de surveillance', 'cameras-de-surveillance', 'securite-maison', 2, 'fr'),
('alarmes-connectees', 'Alarmes connectées', 'alarmes-connectees', 'securite-maison', 2, 'fr'),
('detecteurs-de-fumee', 'Détecteurs de fumée', 'detecteurs-de-fumee', 'securite-maison', 2, 'fr'),
('serrures-cadenas', 'Serrures & cadenas', 'serrures-cadenas', 'securite-maison', 2, 'fr'),
('portails-automatiques', 'Portails automatiques', 'portails-automatiques', 'securite-maison', 2, 'fr'),
('visiophones', 'Visiophones', 'visiophones', 'securite-maison', 2, 'fr'),
('coffres-forts', 'Coffres-forts', 'coffres-forts', 'securite-maison', 2, 'fr'),
('services-maison-immobilier', 'Services Maison & Immobilier', 'services-maison-immobilier', 'immobilier-maison', 1, 'fr'),
('agences-immobilieres', 'Agences immobilières', 'agences-immobilieres', 'services-maison-immobilier', 2, 'fr'),
('services-architecture', 'Services d’architecture', 'services-architecture', 'services-maison-immobilier', 2, 'fr'),
('artisans-plomberie-electricite-peinture', 'Artisans (plomberie, électricité, peinture)', 'artisans-plomberie-electricite-peinture', 'services-maison-immobilier', 2, 'fr'),
('demenagement', 'Déménagement', 'demenagement', 'services-maison-immobilier', 2, 'fr'),
('nettoyage', 'Nettoyage', 'nettoyage', 'services-maison-immobilier', 2, 'fr'),
('entretien-jardin', 'Entretien jardin', 'entretien-jardin', 'services-maison-immobilier', 2, 'fr'),
('renovation', 'Rénovation', 'renovation', 'services-maison-immobilier', 2, 'fr'),
('gestion-locative', 'Gestion locative', 'gestion-locative', 'services-maison-immobilier', 2, 'fr'),
('diagnostics-immobiliers', 'Diagnostics immobiliers', 'diagnostics-immobiliers', 'services-maison-immobilier', 2, 'fr'),
('marques-materiel-populaire', 'Marques & Matériel Populaire', 'marques-materiel-populaire', 'immobilier-maison', 1, 'fr'),
('ikea', 'Ikea', 'ikea', 'marques-materiel-populaire', 2, 'fr'),
('samsung-home', 'Samsung Home', 'samsung-home', 'marques-materiel-populaire', 2, 'fr'),
('lg', 'LG', 'lg', 'marques-materiel-populaire', 2, 'fr'),
('bosch', 'Bosch', 'bosch', 'marques-materiel-populaire', 2, 'fr'),
('beko', 'Beko', 'beko', 'marques-materiel-populaire', 2, 'fr'),
('whirlpool', 'Whirlpool', 'whirlpool', 'marques-materiel-populaire', 2, 'fr'),
('philips-lighting', 'Philips Lighting', 'philips-lighting', 'marques-materiel-populaire', 2, 'fr'),
('schneider-electric', 'Schneider Electric', 'schneider-electric', 'marques-materiel-populaire', 2, 'fr'),
('karcher', 'Kärcher', 'karcher', 'marques-materiel-populaire', 2, 'fr'),
('ariston', 'Ariston', 'ariston', 'marques-materiel-populaire', 2, 'fr'),
('moulinex', 'Moulinex', 'moulinex', 'marques-materiel-populaire', 2, 'fr'),
('tefal', 'Tefal', 'tefal', 'marques-materiel-populaire', 2, 'fr'),
('jaga', 'Jaga', 'jaga', 'marques-materiel-populaire', 2, 'fr'),
('daikin', 'Daikin', 'daikin', 'marques-materiel-populaire', 2, 'fr'),
('hitachi', 'Hitachi', 'hitachi', 'marques-materiel-populaire', 2, 'fr');

-- ANGLAIS
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('immobilier-maison', 'Real Estate & Home', 'immobilier-maison', NULL, 0, 'en');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('ventes-immobilieres', 'Property Sales', 'ventes-immobilieres', 'immobilier-maison', 1, 'en'),
('appartements-a-vendre', 'Apartments for sale', 'appartements-a-vendre', 'ventes-immobilieres', 2, 'en'),
('studios', 'Studios', 'studios', 'ventes-immobilieres', 2, 'en'),
('f2', 'F2', 'f2', 'ventes-immobilieres', 2, 'en'),
('f3', 'F3', 'f3', 'ventes-immobilieres', 2, 'en'),
('f4', 'F4', 'f4', 'ventes-immobilieres', 2, 'en'),
('f5-plus', 'F5+', 'f5-plus', 'ventes-immobilieres', 2, 'en'),
('appartements-neufs', 'New apartments', 'appartements-neufs', 'ventes-immobilieres', 2, 'en'),
('appartements-promotion-immobiliere', 'Promotional apartments', 'appartements-promotion-immobiliere', 'ventes-immobilieres', 2, 'en'),
('maisons-a-vendre', 'Houses for sale', 'maisons-a-vendre', 'ventes-immobilieres', 2, 'en'),
('villas', 'Villas', 'villas', 'ventes-immobilieres', 2, 'en'),
('duplex', 'Duplexes', 'duplex', 'ventes-immobilieres', 2, 'en'),
('triplex', 'Triplexes', 'triplex', 'ventes-immobilieres', 2, 'en'),
('maisons-plain-pied', 'Bungalows', 'maisons-plain-pied', 'ventes-immobilieres', 2, 'en'),
('fermes-proprietes-rurales', 'Farms & rural properties', 'fermes-proprietes-rurales', 'ventes-immobilieres', 2, 'en'),
('terrains-constructibles', 'Building plots', 'terrains-constructibles', 'ventes-immobilieres', 2, 'en'),
('terrains-agricoles', 'Farmland', 'terrains-agricoles', 'ventes-immobilieres', 2, 'en'),
('locaux-commerciaux', 'Commercial premises', 'locaux-commerciaux', 'ventes-immobilieres', 2, 'en'),
('bureaux', 'Offices', 'bureaux', 'ventes-immobilieres', 2, 'en'),
('immeubles', 'Buildings', 'immeubles', 'ventes-immobilieres', 2, 'en'),
('garages-a-vendre', 'Garages for sale', 'garages-a-vendre', 'ventes-immobilieres', 2, 'en'),
('locations-immobilieres', 'Property Rentals', 'locations-immobilieres', 'immobilier-maison', 1, 'en'),
('appartements-en-location', 'Apartments for rent', 'appartements-en-location', 'locations-immobilieres', 2, 'en'),
('studios-location', 'Studios', 'studios', 'locations-immobilieres', 2, 'en'),
('f2-location', 'F2', 'f2', 'locations-immobilieres', 2, 'en'),
('f3-location', 'F3', 'f3', 'locations-immobilieres', 2, 'en'),
('f4-location', 'F4', 'f4', 'locations-immobilieres', 2, 'en'),
('maisons-en-location', 'Houses for rent', 'maisons-en-location', 'locations-immobilieres', 2, 'en'),
('villas-location', 'Villas', 'villas', 'locations-immobilieres', 2, 'en'),
('duplex-location', 'Duplexes', 'duplex', 'locations-immobilieres', 2, 'en'),
('triplex-location', 'Triplexes', 'triplex', 'locations-immobilieres', 2, 'en'),
('chambres-en-location', 'Rooms for rent', 'chambres-en-location', 'locations-immobilieres', 2, 'en'),
('colocation', 'Flatsharing', 'colocation', 'locations-immobilieres', 2, 'en'),
('locations-meublees', 'Furnished rentals', 'locations-meublees', 'locations-immobilieres', 2, 'en'),
('locations-non-meublees', 'Unfurnished rentals', 'locations-non-meublees', 'locations-immobilieres', 2, 'en'),
('locations-saisonnieres', 'Seasonal rentals', 'locations-saisonnieres', 'locations-immobilieres', 2, 'en'),
('locations-vacances', 'Holiday rentals', 'locations-vacances', 'locations-immobilieres', 2, 'en'),
('bureaux-a-louer', 'Offices for rent', 'bureaux-a-louer', 'locations-immobilieres', 2, 'en'),
('locaux-commerciaux-a-louer', 'Commercial premises for rent', 'locaux-commerciaux-a-louer', 'locations-immobilieres', 2, 'en'),
('garages-parkings-a-louer', 'Garages & parking for rent', 'garages-parkings-a-louer', 'locations-immobilieres', 2, 'en'),
('immobilier-professionnel', 'Professional Real Estate', 'immobilier-professionnel', 'immobilier-maison', 1, 'en'),
('entrepots', 'Warehouses', 'entrepots', 'immobilier-professionnel', 2, 'en'),
('hangars', 'Hangars', 'hangars', 'immobilier-professionnel', 2, 'en'),
('locaux-industriels', 'Industrial premises', 'locaux-industriels', 'immobilier-professionnel', 2, 'en'),
('ateliers', 'Workshops', 'ateliers', 'immobilier-professionnel', 2, 'en'),
('zones-logistiques', 'Logistics zones', 'zones-logistiques', 'immobilier-professionnel', 2, 'en'),
('bureaux-professionnels', 'Professional offices', 'bureaux-professionnels', 'immobilier-professionnel', 2, 'en'),
('open-spaces', 'Open spaces', 'open-spaces', 'immobilier-professionnel', 2, 'en'),
('magasins', 'Shops', 'magasins', 'immobilier-professionnel', 2, 'en'),
('restaurants-cafes', 'Restaurants & cafés', 'restaurants-cafes', 'immobilier-professionnel', 2, 'en'),
('pharmacies', 'Pharmacies', 'pharmacies', 'immobilier-professionnel', 2, 'en'),
('cabinets-medicaux', 'Medical practices', 'cabinets-medicaux', 'immobilier-professionnel', 2, 'en'),
('investissement-immobilier', 'Real Estate Investment', 'investissement-immobilier', 'immobilier-maison', 1, 'en'),
('programmes-neufs', 'New developments', 'programmes-neufs', 'investissement-immobilier', 2, 'en'),
('logements-promotionnels', 'Promotional housing', 'logements-promotionnels', 'investissement-immobilier', 2, 'en'),
('immobiliers-lpp', 'LPP housing', 'immobiliers-lpp', 'investissement-immobilier', 2, 'en'),
('logements-sociaux', 'Social housing', 'logements-sociaux', 'investissement-immobilier', 2, 'en'),
('residences-etudiantes', 'Student residences', 'residences-etudiantes', 'investissement-immobilier', 2, 'en'),
('residences-seniors', 'Senior residences', 'residences-seniors', 'investissement-immobilier', 2, 'en'),
('biens-locatifs', 'Rental properties', 'biens-locatifs', 'investissement-immobilier', 2, 'en'),
('immeubles-de-rapport', 'Yield buildings', 'immeubles-de-rapport', 'investissement-immobilier', 2, 'en'),
('terrains-promotionnels', 'Promotional land', 'terrains-promotionnels', 'investissement-immobilier', 2, 'en'),
('maison-mobilier-interieur', 'Home & Interior Furniture', 'maison-mobilier-interieur', 'immobilier-maison', 1, 'en'),
('salons-canapes', 'Living rooms & sofas', 'salons-canapes', 'maison-mobilier-interieur', 2, 'en'),
('tables-chaises', 'Tables & chairs', 'tables-chaises', 'maison-mobilier-interieur', 2, 'en'),
('armoires', 'Wardrobes', 'armoires', 'maison-mobilier-interieur', 2, 'en'),
('dressings', 'Closets', 'dressings', 'maison-mobilier-interieur', 2, 'en'),
('lits-matelas', 'Beds & mattresses', 'lits-matelas', 'maison-mobilier-interieur', 2, 'en'),
('meubles-tv', 'TV furniture', 'meubles-tv', 'maison-mobilier-interieur', 2, 'en'),
('buffets-commodes', 'Sideboards & dressers', 'buffets-commodes', 'maison-mobilier-interieur', 2, 'en'),
('bibliotheques', 'Bookcases', 'bibliotheques', 'maison-mobilier-interieur', 2, 'en'),
('meubles-enfants', 'Kids’ furniture', 'meubles-enfants', 'maison-mobilier-interieur', 2, 'en'),
('petits-meubles', 'Small furniture', 'petits-meubles', 'maison-mobilier-interieur', 2, 'en'),
('rangements', 'Storage', 'rangements', 'maison-mobilier-interieur', 2, 'en'),
('decoration-accessoires-maison', 'Home Decor & Accessories', 'decoration-accessoires-maison', 'immobilier-maison', 1, 'en'),
('tapis', 'Rugs', 'tapis', 'decoration-accessoires-maison', 2, 'en'),
('rideaux-voilages', 'Curtains & sheers', 'rideaux-voilages', 'decoration-accessoires-maison', 2, 'en'),
('luminaires', 'Lighting', 'luminaires', 'decoration-accessoires-maison', 2, 'en'),
('cadres-tableaux', 'Frames & paintings', 'cadres-tableaux', 'decoration-accessoires-maison', 2, 'en'),
('miroirs', 'Mirrors', 'miroirs', 'decoration-accessoires-maison', 2, 'en'),
('horloges', 'Clocks', 'horloges', 'decoration-accessoires-maison', 2, 'en'),
('accessoires-decoratifs', 'Decorative accessories', 'accessoires-decoratifs', 'decoration-accessoires-maison', 2, 'en'),
('stickers-muraux', 'Wall stickers', 'stickers-muraux', 'decoration-accessoires-maison', 2, 'en'),
('coussins-textiles', 'Cushions & textiles', 'coussins-textiles', 'decoration-accessoires-maison', 2, 'en'),
('vases-decor-floral', 'Vases & floral decor', 'vases-decor-floral', 'decoration-accessoires-maison', 2, 'en'),
('cuisine-salle-de-bain', 'Kitchen & Bathroom', 'cuisine-salle-de-bain', 'immobilier-maison', 1, 'en'),
('ustensiles-de-cuisine', 'Kitchen utensils', 'ustensiles-de-cuisine', 'cuisine-salle-de-bain', 2, 'en'),
('casseroles-poeles', 'Pots & pans', 'casseroles-poeles', 'cuisine-salle-de-bain', 2, 'en'),
('vaisselle', 'Tableware', 'vaisselle', 'cuisine-salle-de-bain', 2, 'en'),
('couverts', 'Cutlery', 'couverts', 'cuisine-salle-de-bain', 2, 'en'),
('robots-de-cuisine', 'Kitchen robots', 'robots-de-cuisine', 'cuisine-salle-de-bain', 2, 'en'),
('plaques-fours', 'Cooktops & ovens', 'plaques-fours', 'cuisine-salle-de-bain', 2, 'en'),
('equipements-sanitaires', 'Sanitary equipment', 'equipements-sanitaires', 'cuisine-salle-de-bain', 2, 'en'),
('baignoires', 'Bathtubs', 'baignoires', 'cuisine-salle-de-bain', 2, 'en'),
('douches', 'Showers', 'douches', 'cuisine-salle-de-bain', 2, 'en'),
('lavabos', 'Sinks', 'lavabos', 'cuisine-salle-de-bain', 2, 'en'),
('robinetterie', 'Faucets', 'robinetterie', 'cuisine-salle-de-bain', 2, 'en'),
('meubles-de-salle-de-bain', 'Bathroom furniture', 'meubles-de-salle-de-bain', 'cuisine-salle-de-bain', 2, 'en'),
('jardin-exterieur', 'Garden & Outdoor', 'jardin-exterieur', 'immobilier-maison', 1, 'en'),
('mobilier-de-jardin', 'Garden furniture', 'mobilier-de-jardin', 'jardin-exterieur', 2, 'en'),
('salons-exterieurs', 'Outdoor lounges', 'salons-exterieurs', 'jardin-exterieur', 2, 'en'),
('parasols', 'Parasols', 'parasols', 'jardin-exterieur', 2, 'en'),
('barbecues', 'Barbecues', 'barbecues', 'jardin-exterieur', 2, 'en'),
('tondeuses', 'Lawn mowers', 'tondeuses', 'jardin-exterieur', 2, 'en'),
('debroussailleuses', 'Brushcutters', 'debroussailleuses', 'jardin-exterieur', 2, 'en'),
('tronconneuses', 'Chainsaws', 'tronconneuses', 'jardin-exterieur', 2, 'en'),
('outils-de-jardinage', 'Gardening tools', 'outils-de-jardinage', 'jardin-exterieur', 2, 'en'),
('pots-jardinieres', 'Pots & planters', 'pots-jardinieres', 'jardin-exterieur', 2, 'en'),
('serres', 'Greenhouses', 'serres', 'jardin-exterieur', 2, 'en'),
('piscines-accessoires', 'Pools & accessories', 'piscines-accessoires', 'jardin-exterieur', 2, 'en'),
('eclairage-exterieur', 'Outdoor lighting', 'eclairage-exterieur', 'jardin-exterieur', 2, 'en'),
('bricolage-amelioration-maison', 'DIY & Home Improvement', 'bricolage-amelioration-maison', 'immobilier-maison', 1, 'en'),
('outils-electroportatifs', 'Power tools (drills, screwdrivers, grinders)', 'outils-electroportatifs', 'bricolage-amelioration-maison', 2, 'en'),
('outils-a-main', 'Hand tools', 'outils-a-main', 'bricolage-amelioration-maison', 2, 'en'),
('peinture', 'Paint', 'peinture', 'bricolage-amelioration-maison', 2, 'en'),
('revetements-murs-sols', 'Wall & floor coverings', 'revetements-murs-sols', 'bricolage-amelioration-maison', 2, 'en'),
('parquet', 'Parquet', 'parquet', 'bricolage-amelioration-maison', 2, 'en'),
('carrelage', 'Tiles', 'carrelage', 'bricolage-amelioration-maison', 2, 'en'),
('plomberie', 'Plumbing', 'plomberie', 'bricolage-amelioration-maison', 2, 'en'),
('electricite', 'Electricity', 'electricite', 'bricolage-amelioration-maison', 2, 'en'),
('isolation', 'Insulation', 'isolation', 'bricolage-amelioration-maison', 2, 'en'),
('materiaux-de-construction', 'Building materials', 'materiaux-de-construction', 'bricolage-amelioration-maison', 2, 'en'),
('portes-fenetres', 'Doors & windows', 'portes-fenetres', 'bricolage-amelioration-maison', 2, 'en'),
('securite-maison', 'Home Security', 'securite-maison', 'immobilier-maison', 1, 'en'),
('cameras-de-surveillance', 'Surveillance cameras', 'cameras-de-surveillance', 'securite-maison', 2, 'en'),
('alarmes-connectees', 'Connected alarms', 'alarmes-connectees', 'securite-maison', 2, 'en'),
('detecteurs-de-fumee', 'Smoke detectors', 'detecteurs-de-fumee', 'securite-maison', 2, 'en'),
('serrures-cadenas', 'Locks & padlocks', 'serrures-cadenas', 'securite-maison', 2, 'en'),
('portails-automatiques', 'Automatic gates', 'portails-automatiques', 'securite-maison', 2, 'en'),
('visiophones', 'Video intercoms', 'visiophones', 'securite-maison', 2, 'en'),
('coffres-forts', 'Safes', 'coffres-forts', 'securite-maison', 2, 'en'),
('services-maison-immobilier', 'Home & Real Estate Services', 'services-maison-immobilier', 'immobilier-maison', 1, 'en'),
('agences-immobilieres', 'Real estate agencies', 'agences-immobilieres', 'services-maison-immobilier', 2, 'en'),
('services-architecture', 'Architecture services', 'services-architecture', 'services-maison-immobilier', 2, 'en'),
('artisans-plomberie-electricite-peinture', 'Trades (plumbing, electricity, painting)', 'artisans-plomberie-electricite-peinture', 'services-maison-immobilier', 2, 'en'),
('demenagement', 'Moving', 'demenagement', 'services-maison-immobilier', 2, 'en'),
('nettoyage', 'Cleaning', 'nettoyage', 'services-maison-immobilier', 2, 'en'),
('entretien-jardin', 'Garden maintenance', 'entretien-jardin', 'services-maison-immobilier', 2, 'en'),
('renovation', 'Renovation', 'renovation', 'services-maison-immobilier', 2, 'en'),
('gestion-locative', 'Property management', 'gestion-locative', 'services-maison-immobilier', 2, 'en'),
('diagnostics-immobiliers', 'Real estate diagnostics', 'diagnostics-immobiliers', 'services-maison-immobilier', 2, 'en'),
('marques-materiel-populaire', 'Popular Brands & Equipment', 'marques-materiel-populaire', 'immobilier-maison', 1, 'en'),
('ikea', 'Ikea', 'ikea', 'marques-materiel-populaire', 2, 'en'),
('samsung-home', 'Samsung Home', 'samsung-home', 'marques-materiel-populaire', 2, 'en'),
('lg', 'LG', 'lg', 'marques-materiel-populaire', 2, 'en'),
('bosch', 'Bosch', 'bosch', 'marques-materiel-populaire', 2, 'en'),
('beko', 'Beko', 'beko', 'marques-materiel-populaire', 2, 'en'),
('whirlpool', 'Whirlpool', 'whirlpool', 'marques-materiel-populaire', 2, 'en'),
('philips-lighting', 'Philips Lighting', 'philips-lighting', 'marques-materiel-populaire', 2, 'en'),
('schneider-electric', 'Schneider Electric', 'schneider-electric', 'marques-materiel-populaire', 2, 'en'),
('karcher', 'Kärcher', 'karcher', 'marques-materiel-populaire', 2, 'en'),
('ariston', 'Ariston', 'ariston', 'marques-materiel-populaire', 2, 'en'),
('moulinex', 'Moulinex', 'moulinex', 'marques-materiel-populaire', 2, 'en'),
('tefal', 'Tefal', 'tefal', 'marques-materiel-populaire', 2, 'en'),
('jaga', 'Jaga', 'jaga', 'marques-materiel-populaire', 2, 'en'),
('daikin', 'Daikin', 'daikin', 'marques-materiel-populaire', 2, 'en');

-- ESPAGNOL
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('immobilier-maison', 'Inmobiliaria & Hogar', 'immobilier-maison', NULL, 0, 'es');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('ventes-immobilieres', 'Ventas Inmobiliarias', 'ventes-immobilieres', 'immobilier-maison', 1, 'es'),
('appartements-a-vendre', 'Apartamentos en venta', 'appartements-a-vendre', 'ventes-immobilieres', 2, 'es'),
('studios', 'Estudios', 'studios', 'ventes-immobilieres', 2, 'es'),
('f2', 'F2', 'f2', 'ventes-immobilieres', 2, 'es'),
('f3', 'F3', 'f3', 'ventes-immobilieres', 2, 'es'),
('f4', 'F4', 'f4', 'ventes-immobilieres', 2, 'es'),
('f5-plus', 'F5+', 'f5-plus', 'ventes-immobilieres', 2, 'es'),
('appartements-neufs', 'Apartamentos nuevos', 'appartements-neufs', 'ventes-immobilieres', 2, 'es'),
('appartements-promotion-immobiliere', 'Apartamentos promoción inmobiliaria', 'appartements-promotion-immobiliere', 'ventes-immobilieres', 2, 'es'),
('maisons-a-vendre', 'Casas en venta', 'maisons-a-vendre', 'ventes-immobilieres', 2, 'es'),
('villas', 'Villas', 'villas', 'ventes-immobilieres', 2, 'es'),
('duplex', 'Dúplex', 'duplex', 'ventes-immobilieres', 2, 'es'),
('triplex', 'Tríplex', 'triplex', 'ventes-immobilieres', 2, 'es'),
('maisons-plain-pied', 'Casas de una planta', 'maisons-plain-pied', 'ventes-immobilieres', 2, 'es'),
('fermes-proprietes-rurales', 'Granjas & propiedades rurales', 'fermes-proprietes-rurales', 'ventes-immobilieres', 2, 'es'),
('terrains-constructibles', 'Terrenos edificables', 'terrains-constructibles', 'ventes-immobilieres', 2, 'es'),
('terrains-agricoles', 'Terrenos agrícolas', 'terrains-agricoles', 'ventes-immobilieres', 2, 'es'),
('locaux-commerciaux', 'Locales comerciales', 'locaux-commerciaux', 'ventes-immobilieres', 2, 'es'),
('bureaux', 'Oficinas', 'bureaux', 'ventes-immobilieres', 2, 'es'),
('immeubles', 'Edificios', 'immeubles', 'ventes-immobilieres', 2, 'es'),
('garages-a-vendre', 'Garajes en venta', 'garages-a-vendre', 'ventes-immobilieres', 2, 'es'),
('locations-immobilieres', 'Alquileres Inmobiliarios', 'locations-immobilieres', 'immobilier-maison', 1, 'es'),
('appartements-en-location', 'Apartamentos en alquiler', 'appartements-en-location', 'locations-immobilieres', 2, 'es'),
('studios-location', 'Estudios', 'studios', 'locations-immobilieres', 2, 'es'),
('f2-location', 'F2', 'f2', 'locations-immobilieres', 2, 'es'),
('f3-location', 'F3', 'f3', 'locations-immobilieres', 2, 'es'),
('f4-location', 'F4', 'f4', 'locations-immobilieres', 2, 'es'),
('maisons-en-location', 'Casas en alquiler', 'maisons-en-location', 'locations-immobilieres', 2, 'es'),
('villas-location', 'Villas', 'villas', 'locations-immobilieres', 2, 'es'),
('duplex-location', 'Dúplex', 'duplex', 'locations-immobilieres', 2, 'es'),
('triplex-location', 'Tríplex', 'triplex', 'locations-immobilieres', 2, 'es'),
('chambres-en-location', 'Habitaciones en alquiler', 'chambres-en-location', 'locations-immobilieres', 2, 'es'),
('colocation', 'Compañeros de piso', 'colocation', 'locations-immobilieres', 2, 'es'),
('locations-meublees', 'Alquileres amueblados', 'locations-meublees', 'locations-immobilieres', 2, 'es'),
('locations-non-meublees', 'Alquileres sin amueblar', 'locations-non-meublees', 'locations-immobilieres', 2, 'es'),
('locations-saisonnieres', 'Alquileres temporales', 'locations-saisonnieres', 'locations-immobilieres', 2, 'es'),
('locations-vacances', 'Alquileres vacacionales', 'locations-vacances', 'locations-immobilieres', 2, 'es'),
('bureaux-a-louer', 'Oficinas en alquiler', 'bureaux-a-louer', 'locations-immobilieres', 2, 'es'),
('locaux-commerciaux-a-louer', 'Locales comerciales en alquiler', 'locaux-commerciaux-a-louer', 'locations-immobilieres', 2, 'es'),
('garages-parkings-a-louer', 'Garajes & aparcamientos en alquiler', 'garages-parkings-a-louer', 'locations-immobilieres', 2, 'es'),
('immobilier-professionnel', 'Inmobiliaria Profesional', 'immobilier-professionnel', 'immobilier-maison', 1, 'es'),
('entrepots', 'Almacenes', 'entrepots', 'immobilier-professionnel', 2, 'es'),
('hangars', 'Hangares', 'hangars', 'immobilier-professionnel', 2, 'es'),
('locaux-industriels', 'Locales industriales', 'locaux-industriels', 'immobilier-professionnel', 2, 'es'),
('ateliers', 'Talleres', 'ateliers', 'immobilier-professionnel', 2, 'es'),
('zones-logistiques', 'Zonas logísticas', 'zones-logistiques', 'immobilier-professionnel', 2, 'es'),
('bureaux-professionnels', 'Oficinas profesionales', 'bureaux-professionnels', 'immobilier-professionnel', 2, 'es'),
('open-spaces', 'Open-spaces', 'open-spaces', 'immobilier-professionnel', 2, 'es'),
('magasins', 'Tiendas', 'magasins', 'immobilier-professionnel', 2, 'es'),
('restaurants-cafes', 'Restaurantes & cafés', 'restaurants-cafes', 'immobilier-professionnel', 2, 'es'),
('pharmacies', 'Farmacias', 'pharmacies', 'immobilier-professionnel', 2, 'es'),
('cabinets-medicaux', 'Consultorios médicos', 'cabinets-medicaux', 'immobilier-professionnel', 2, 'es'),
('investissement-immobilier', 'Inversión Inmobiliaria', 'investissement-immobilier', 'immobilier-maison', 1, 'es'),
('programmes-neufs', 'Programas nuevos', 'programmes-neufs', 'investissement-immobilier', 2, 'es'),
('logements-promotionnels', 'Viviendas promocionales', 'logements-promotionnels', 'investissement-immobilier', 2, 'es'),
('immobiliers-lpp', 'Inmuebles LPP', 'immobiliers-lpp', 'investissement-immobilier', 2, 'es'),
('logements-sociaux', 'Viviendas sociales', 'logements-sociaux', 'investissement-immobilier', 2, 'es'),
('residences-etudiantes', 'Residencias de estudiantes', 'residences-etudiantes', 'investissement-immobilier', 2, 'es'),
('residences-seniors', 'Residencias para mayores', 'residences-seniors', 'investissement-immobilier', 2, 'es'),
('biens-locatifs', 'Bienes de alquiler', 'biens-locatifs', 'investissement-immobilier', 2, 'es'),
('immeubles-de-rapport', 'Edificios de inversión', 'immeubles-de-rapport', 'investissement-immobilier', 2, 'es'),
('terrains-promotionnels', 'Terrenos promocionales', 'terrains-promotionnels', 'investissement-immobilier', 2, 'es'),
('maison-mobilier-interieur', 'Hogar & Muebles Interior', 'maison-mobilier-interieur', 'immobilier-maison', 1, 'es'),
('salons-canapes', 'Salones & sofás', 'salons-canapes', 'maison-mobilier-interieur', 2, 'es'),
('tables-chaises', 'Mesas & sillas', 'tables-chaises', 'maison-mobilier-interieur', 2, 'es'),
('armoires', 'Armarios', 'armoires', 'maison-mobilier-interieur', 2, 'es'),
('dressings', 'Vestidores', 'dressings', 'maison-mobilier-interieur', 2, 'es'),
('lits-matelas', 'Camas & colchones', 'lits-matelas', 'maison-mobilier-interieur', 2, 'es'),
('meubles-tv', 'Muebles TV', 'meubles-tv', 'maison-mobilier-interieur', 2, 'es'),
('buffets-commodes', 'Apadores & cómodas', 'buffets-commodes', 'maison-mobilier-interieur', 2, 'es'),
('bibliotheques', 'Bibliotecas', 'bibliotheques', 'maison-mobilier-interieur', 2, 'es'),
('meubles-enfants', 'Muebles infantiles', 'meubles-enfants', 'maison-mobilier-interieur', 2, 'es'),
('petits-meubles', 'Muebles pequeños', 'petits-meubles', 'maison-mobilier-interieur', 2, 'es'),
('rangements', 'Almacenamiento', 'rangements', 'maison-mobilier-interieur', 2, 'es'),
('decoration-accessoires-maison', 'Decoración & Accesorios Hogar', 'decoration-accessoires-maison', 'immobilier-maison', 1, 'es'),
('tapis', 'Alfombras', 'tapis', 'decoration-accessoires-maison', 2, 'es'),
('rideaux-voilages', 'Cortinas & visillos', 'rideaux-voilages', 'decoration-accessoires-maison', 2, 'es'),
('luminaires', 'Iluminación', 'luminaires', 'decoration-accessoires-maison', 2, 'es'),
('cadres-tableaux', 'Marcos & cuadros', 'cadres-tableaux', 'decoration-accessoires-maison', 2, 'es'),
('miroirs', 'Espejos', 'miroirs', 'decoration-accessoires-maison', 2, 'es'),
('horloges', 'Relojes', 'horloges', 'decoration-accessoires-maison', 2, 'es'),
('accessoires-decoratifs', 'Accesorios decorativos', 'accessoires-decoratifs', 'decoration-accessoires-maison', 2, 'es'),
('stickers-muraux', 'Calcomanías murales', 'stickers-muraux', 'decoration-accessoires-maison', 2, 'es'),
('coussins-textiles', 'Cojines & textiles', 'coussins-textiles', 'decoration-accessoires-maison', 2, 'es'),
('vases-decor-floral', 'Jarrones & decoración floral', 'vases-decor-floral', 'decoration-accessoires-maison', 2, 'es'),
('cuisine-salle-de-bain', 'Cocina & Baño', 'cuisine-salle-de-bain', 'immobilier-maison', 1, 'es'),
('ustensiles-de-cuisine', 'Utensilios de cocina', 'ustensiles-de-cuisine', 'cuisine-salle-de-bain', 2, 'es'),
('casseroles-poeles', 'Cacerolas & sartenes', 'casseroles-poeles', 'cuisine-salle-de-bain', 2, 'es'),
('vaisselle', 'Vajilla', 'vaisselle', 'cuisine-salle-de-bain', 2, 'es'),
('couverts', 'Cubiertos', 'couverts', 'cuisine-salle-de-bain', 2, 'es'),
('robots-de-cuisine', 'Robots de cocina', 'robots-de-cuisine', 'cuisine-salle-de-bain', 2, 'es'),
('plaques-fours', 'Placas & hornos', 'plaques-fours', 'cuisine-salle-de-bain', 2, 'es'),
('equipements-sanitaires', 'Equipos sanitarios', 'equipements-sanitaires', 'cuisine-salle-de-bain', 2, 'es'),
('baignoires', 'Bañeras', 'baignoires', 'cuisine-salle-de-bain', 2, 'es'),
('douches', 'Duchas', 'douches', 'cuisine-salle-de-bain', 2, 'es'),
('lavabos', 'Lavabos', 'lavabos', 'cuisine-salle-de-bain', 2, 'es'),
('robinetterie', 'Grifería', 'robinetterie', 'cuisine-salle-de-bain', 2, 'es'),
('meubles-de-salle-de-bain', 'Muebles de baño', 'meubles-de-salle-de-bain', 'cuisine-salle-de-bain', 2, 'es'),
('jardin-exterieur', 'Jardín & Exterior', 'jardin-exterieur', 'immobilier-maison', 1, 'es'),
('mobilier-de-jardin', 'Muebles de jardín', 'mobilier-de-jardin', 'jardin-exterieur', 2, 'es'),
('salons-exterieurs', 'Salones exteriores', 'salons-exterieurs', 'jardin-exterieur', 2, 'es'),
('parasols', 'Sombrillas', 'parasols', 'jardin-exterieur', 2, 'es'),
('barbecues', 'Barbacoas', 'barbecues', 'jardin-exterieur', 2, 'es'),
('tondeuses', 'Cortacésped', 'tondeuses', 'jardin-exterieur', 2, 'es'),
('debroussailleuses', 'Desbrozadoras', 'debroussailleuses', 'jardin-exterieur', 2, 'es'),
('tronconneuses', 'Motosierras', 'tronconneuses', 'jardin-exterieur', 2, 'es'),
('outils-de-jardinage', 'Herramientas de jardinería', 'outils-de-jardinage', 'jardin-exterieur', 2, 'es'),
('pots-jardinieres', 'Macetas & jardineras', 'pots-jardinieres', 'jardin-exterieur', 2, 'es'),
('serres', 'Invernaderos', 'serres', 'jardin-exterieur', 2, 'es'),
('piscines-accessoires', 'Piscinas & accesorios', 'piscines-accessoires', 'jardin-exterieur', 2, 'es'),
('eclairage-exterieur', 'Iluminación exterior', 'eclairage-exterieur', 'jardin-exterieur', 2, 'es'),
('bricolage-amelioration-maison', 'Bricolaje & Mejora Hogar', 'bricolage-amelioration-maison', 'immobilier-maison', 1, 'es'),
('outils-electroportatifs', 'Herramientas eléctricas (taladros, destornilladores, amoladoras)', 'outils-electroportatifs', 'bricolage-amelioration-maison', 2, 'es'),
('outils-a-main', 'Herramientas manuales', 'outils-a-main', 'bricolage-amelioration-maison', 2, 'es'),
('peinture', 'Pintura', 'peinture', 'bricolage-amelioration-maison', 2, 'es'),
('revetements-murs-sols', 'Revestimientos paredes & suelos', 'revetements-murs-sols', 'bricolage-amelioration-maison', 2, 'es'),
('parquet', 'Parquet', 'parquet', 'bricolage-amelioration-maison', 2, 'es'),
('carrelage', 'Azulejos', 'carrelage', 'bricolage-amelioration-maison', 2, 'es'),
('plomberie', 'Fontanería', 'plomberie', 'bricolage-amelioration-maison', 2, 'es'),
('electricite', 'Electricidad', 'electricite', 'bricolage-amelioration-maison', 2, 'es'),
('isolation', 'Aislamiento', 'isolation', 'bricolage-amelioration-maison', 2, 'es'),
('materiaux-de-construction', 'Materiales de construcción', 'materiaux-de-construction', 'bricolage-amelioration-maison', 2, 'es'),
('portes-fenetres', 'Puertas & ventanas', 'portes-fenetres', 'bricolage-amelioration-maison', 2, 'es'),
('securite-maison', 'Seguridad Hogar', 'securite-maison', 'immobilier-maison', 1, 'es'),
('cameras-de-surveillance', 'Cámaras de vigilancia', 'cameras-de-surveillance', 'securite-maison', 2, 'es'),
('alarmes-connectees', 'Alarmas conectadas', 'alarmes-connectees', 'securite-maison', 2, 'es'),
('detecteurs-de-fumee', 'Detectores de humo', 'detecteurs-de-fumee', 'securite-maison', 2, 'es'),
('serrures-cadenas', 'Cerraduras & candados', 'serrures-cadenas', 'securite-maison', 2, 'es'),
('portails-automatiques', 'Portones automáticos', 'portails-automatiques', 'securite-maison', 2, 'es'),
('visiophones', 'Videoporteros', 'visiophones', 'securite-maison', 2, 'es'),
('coffres-forts', 'Cajas fuertes', 'coffres-forts', 'securite-maison', 2, 'es'),
('services-maison-immobilier', 'Servicios Hogar & Inmobiliaria', 'services-maison-immobilier', 'immobilier-maison', 1, 'es'),
('agences-immobilieres', 'Agencias inmobiliarias', 'agences-immobilieres', 'services-maison-immobilier', 2, 'es'),
('services-architecture', 'Servicios de arquitectura', 'services-architecture', 'services-maison-immobilier', 2, 'es'),
('artisans-plomberie-electricite-peinture', 'Artesanos (fontanería, electricidad, pintura)', 'artisans-plomberie-electricite-peinture', 'services-maison-immobilier', 2, 'es'),
('demenagement', 'Mudanzas', 'demenagement', 'services-maison-immobilier', 2, 'es'),
('nettoyage', 'Limpieza', 'nettoyage', 'services-maison-immobilier', 2, 'es'),
('entretien-jardin', 'Mantenimiento jardín', 'entretien-jardin', 'services-maison-immobilier', 2, 'es'),
('renovation', 'Renovación', 'renovation', 'services-maison-immobilier', 2, 'es'),
('gestion-locative', 'Gestión de alquileres', 'gestion-locative', 'services-maison-immobilier', 2, 'es'),
('diagnostics-immobiliers', 'Diagnósticos inmobiliarios', 'diagnostics-immobiliers', 'services-maison-immobilier', 2, 'es'),
('marques-materiel-populaire', 'Marcas & Equipamiento Popular', 'marques-materiel-populaire', 'immobilier-maison', 1, 'es'),
('ikea', 'Ikea', 'ikea', 'marques-materiel-populaire', 2, 'es'),
('samsung-home', 'Samsung Home', 'samsung-home', 'marques-materiel-populaire', 2, 'es'),
('lg', 'LG', 'lg', 'marques-materiel-populaire', 2, 'es'),
('bosch', 'Bosch', 'bosch', 'marques-materiel-populaire', 2, 'es'),
('beko', 'Beko', 'beko', 'marques-materiel-populaire', 2, 'es'),
('whirlpool', 'Whirlpool', 'whirlpool', 'marques-materiel-populaire', 2, 'es'),
('philips-lighting', 'Philips Lighting', 'philips-lighting', 'marques-materiel-populaire', 2, 'es'),
('schneider-electric', 'Schneider Electric', 'schneider-electric', 'marques-materiel-populaire', 2, 'es'),
('karcher', 'Kärcher', 'karcher', 'marques-materiel-populaire', 2, 'es'),
('ariston', 'Ariston', 'ariston', 'marques-materiel-populaire', 2, 'es'),
('moulinex', 'Moulinex', 'moulinex', 'marques-materiel-populaire', 2, 'es'),
('tefal', 'Tefal', 'tefal', 'marques-materiel-populaire', 2, 'es'),
('jaga', 'Jaga', 'jaga', 'marques-materiel-populaire', 2, 'es'),
('daikin', 'Daikin', 'daikin', 'marques-materiel-populaire', 2, 'es');

-- ALLEMAND
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('immobilier-maison', 'Immobilien & Haus', 'immobilier-maison', NULL, 0, 'de');

INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('ventes-immobilieres', 'Immobilienverkäufe', 'ventes-immobilieres', 'immobilier-maison', 1, 'de'),
('appartements-a-vendre', 'Wohnungen zum Verkauf', 'appartements-a-vendre', 'ventes-immobilieres', 2, 'de'),
('studios', 'Studios', 'studios', 'ventes-immobilieres', 2, 'de'),
('f2', 'F2', 'f2', 'ventes-immobilieres', 2, 'de'),
('f3', 'F3', 'f3', 'ventes-immobilieres', 2, 'de'),
('f4', 'F4', 'f4', 'ventes-immobilieres', 2, 'de'),
('f5-plus', 'F5+', 'f5-plus', 'ventes-immobilieres', 2, 'de'),
('appartements-neufs', 'Neue Wohnungen', 'appartements-neufs', 'ventes-immobilieres', 2, 'de'),
('appartements-promotion-immobiliere', 'Wohnungen Immobilienförderung', 'appartements-promotion-immobiliere', 'ventes-immobilieres', 2, 'de'),
('maisons-a-vendre', 'Häuser zum Verkauf', 'maisons-a-vendre', 'ventes-immobilieres', 2, 'de'),
('villas', 'Villen', 'villas', 'ventes-immobilieres', 2, 'de'),
('duplex', 'Duplex', 'duplex', 'ventes-immobilieres', 2, 'de'),
('triplex', 'Triplex', 'triplex', 'ventes-immobilieres', 2, 'de'),
('maisons-plain-pied', 'Einstöckige Häuser', 'maisons-plain-pied', 'ventes-immobilieres', 2, 'de'),
('fermes-proprietes-rurales', 'Bauernhöfe & ländliche Grundstücke', 'fermes-proprietes-rurales', 'ventes-immobilieres', 2, 'de'),
('terrains-constructibles', 'Bebaubare Grundstücke', 'terrains-constructibles', 'ventes-immobilieres', 2, 'de'),
('terrains-agricoles', 'Landwirtschaftliche Grundstücke', 'terrains-agricoles', 'ventes-immobilieres', 2, 'de'),
('locaux-commerciaux', 'Gewerberäume', 'locaux-commerciaux', 'ventes-immobilieres', 2, 'de'),
('bureaux', 'Büros', 'bureaux', 'ventes-immobilieres', 2, 'de'),
('immeubles', 'Gebäude', 'immeubles', 'ventes-immobilieres', 2, 'de'),
('garages-a-vendre', 'Garagen zum Verkauf', 'garages-a-vendre', 'ventes-immobilieres', 2, 'de'),
('locations-immobilieres', 'Immobilienvermietungen', 'locations-immobilieres', 'immobilier-maison', 1, 'de'),
('appartements-en-location', 'Wohnungen zur Miete', 'appartements-en-location', 'locations-immobilieres', 2, 'de'),
('studios-location', 'Studios', 'studios', 'locations-immobilieres', 2, 'de'),
('f2-location', 'F2', 'f2', 'locations-immobilieres', 2, 'de'),
('f3-location', 'F3', 'f3', 'locations-immobilieres', 2, 'de'),
('f4-location', 'F4', 'f4', 'locations-immobilieres', 2, 'de'),
('maisons-en-location', 'Häuser zur Miete', 'maisons-en-location', 'locations-immobilieres', 2, 'de'),
('villas-location', 'Villen', 'villas', 'locations-immobilieres', 2, 'de'),
('duplex-location', 'Duplex', 'duplex', 'locations-immobilieres', 2, 'de'),
('triplex-location', 'Triplex', 'triplex', 'locations-immobilieres', 2, 'de'),
('chambres-en-location', 'Zimmer zur Miete', 'chambres-en-location', 'locations-immobilieres', 2, 'de'),
('colocation', 'Wohngemeinschaft', 'colocation', 'locations-immobilieres', 2, 'de'),
('locations-meublees', 'Möblierte Vermietungen', 'locations-meublees', 'locations-immobilieres', 2, 'de'),
('locations-non-meublees', 'Unmöblierte Vermietungen', 'locations-non-meublees', 'locations-immobilieres', 2, 'de'),
('locations-saisonnieres', 'Saisonvermietungen', 'locations-saisonnieres', 'locations-immobilieres', 2, 'de'),
('locations-vacances', 'Ferienvermietungen', 'locations-vacances', 'locations-immobilieres', 2, 'de'),
('bureaux-a-louer', 'Büros zur Miete', 'bureaux-a-louer', 'locations-immobilieres', 2, 'de'),
('locaux-commerciaux-a-louer', 'Gewerberäume zur Miete', 'locaux-commerciaux-a-louer', 'locations-immobilieres', 2, 'de'),
('garages-parkings-a-louer', 'Garagen & Parkplätze zur Miete', 'garages-parkings-a-louer', 'locations-immobilieres', 2, 'de'),
('immobilier-professionnel', 'Gewerbeimmobilien', 'immobilier-professionnel', 'immobilier-maison', 1, 'de'),
('entrepots', 'Lagerhallen', 'entrepots', 'immobilier-professionnel', 2, 'de'),
('hangars', 'Hallenschuppen', 'hangars', 'immobilier-professionnel', 2, 'de'),
('locaux-industriels', 'Industrieräume', 'locaux-industriels', 'immobilier-professionnel', 2, 'de'),
('ateliers', 'Werkstätten', 'ateliers', 'immobilier-professionnel', 2, 'de'),
('zones-logistiques', 'Logistikzonen', 'zones-logistiques', 'immobilier-professionnel', 2, 'de'),
('bureaux-professionnels', 'Professionelle Büros', 'bureaux-professionnels', 'immobilier-professionnel', 2, 'de'),
('open-spaces', 'Open-Spaces', 'open-spaces', 'immobilier-professionnel', 2, 'de'),
('magasins', 'Geschäfte', 'magasins', 'immobilier-professionnel', 2, 'de'),
('restaurants-cafes', 'Restaurants & Cafés', 'restaurants-cafes', 'immobilier-professionnel', 2, 'de'),
('pharmacies', 'Apotheken', 'pharmacies', 'immobilier-professionnel', 2, 'de'),
('cabinets-medicaux', 'Medizinische Praxen', 'cabinets-medicaux', 'immobilier-professionnel', 2, 'de'),
('investissement-immobilier', 'Immobilieninvestition', 'investissement-immobilier', 'immobilier-maison', 1, 'de'),
('programmes-neufs', 'Neue Programme', 'programmes-neufs', 'investissement-immobilier', 2, 'de'),
('logements-promotionnels', 'Förderungswohnungen', 'logements-promotionnels', 'investissement-immobilier', 2, 'de'),
('immobiliers-lpp', 'Immobilien LPP', 'immobiliers-lpp', 'investissement-immobilier', 2, 'de'),
('logements-sociaux', 'Sozialwohnungen', 'logements-sociaux', 'investissement-immobilier', 2, 'de'),
('residences-etudiantes', 'Studentenwohnheime', 'residences-etudiantes', 'investissement-immobilier', 2, 'de'),
('residences-seniors', 'Seniorenresidenzen', 'residences-seniors', 'investissement-immobilier', 2, 'de'),
('biens-locatifs', 'Vermietungsobjekte', 'biens-locatifs', 'investissement-immobilier', 2, 'de'),
('immeubles-de-rapport', 'Renditehäuser', 'immeubles-de-rapport', 'investissement-immobilier', 2, 'de'),
('terrains-promotionnels', 'Förderungsgrundstücke', 'terrains-promotionnels', 'investissement-immobilier', 2, 'de'),
('maison-mobilier-interieur', 'Haus & Inneneinrichtung', 'maison-mobilier-interieur', 'immobilier-maison', 1, 'de'),
('salons-canapes', 'Wohnzimmer & Sofas', 'salons-canapes', 'maison-mobilier-interieur', 2, 'de'),
('tables-chaises', 'Tische & Stühle', 'tables-chaises', 'maison-mobilier-interieur', 2, 'de'),
('armoires', 'Schränke', 'armoires', 'maison-mobilier-interieur', 2, 'de'),
('dressings', 'Ankleidezimmer', 'dressings', 'maison-mobilier-interieur', 2, 'de'),
('lits-matelas', 'Betten & Matratzen', 'lits-matelas', 'maison-mobilier-interieur', 2, 'de'),
('meubles-tv', 'TV-Möbel', 'meubles-tv', 'maison-mobilier-interieur', 2, 'de'),
('buffets-commodes', 'Sideboards & Kommoden', 'buffets-commodes', 'maison-mobilier-interieur', 2, 'de'),
('bibliotheques', 'Bücherregale', 'bibliotheques', 'maison-mobilier-interieur', 2, 'de'),
('meubles-enfants', 'Kinderzimmermöbel', 'meubles-enfants', 'maison-mobilier-interieur', 2, 'de'),
('petits-meubles', 'Kleine Möbel', 'petits-meubles', 'maison-mobilier-interieur', 2, 'de'),
('rangements', 'Aufbewahrung', 'rangements', 'maison-mobilier-interieur', 2, 'de'),
('decoration-accessoires-maison', 'Dekoration & Zubehör', 'decoration-accessoires-maison', 'immobilier-maison', 1, 'de'),
('tapis', 'Teppiche', 'tapis', 'decoration-accessoires-maison', 2, 'de'),
('rideaux-voilages', 'Vorhänge & Gardinen', 'rideaux-voilages', 'decoration-accessoires-maison', 2, 'de'),
('luminaires', 'Beleuchtung', 'luminaires', 'decoration-accessoires-maison', 2, 'de'),
('cadres-tableaux', 'Rahmen & Gemälde', 'cadres-tableaux', 'decoration-accessoires-maison', 2, 'de'),
('miroirs', 'Spiegel', 'miroirs', 'decoration-accessoires-maison', 2, 'de'),
('horloges', 'Uhren', 'horloges', 'decoration-accessoires-maison', 2, 'de'),
('accessoires-decoratifs', 'Dekorative Zubehör', 'accessoires-decoratifs', 'decoration-accessoires-maison', 2, 'de'),
('stickers-muraux', 'Wandaufkleber', 'stickers-muraux', 'decoration-accessoires-maison', 2, 'de'),
('coussins-textiles', 'Kissen & Textilien', 'coussins-textiles', 'decoration-accessoires-maison', 2, 'de'),
('vases-decor-floral', 'Vasen & florale Dekoration', 'vases-decor-floral', 'decoration-accessoires-maison', 2, 'de'),
('cuisine-salle-de-bain', 'Küche & Badezimmer', 'cuisine-salle-de-bain', 'immobilier-maison', 1, 'de'),
('ustensiles-de-cuisine', 'Küchenutensilien', 'ustensiles-de-cuisine', 'cuisine-salle-de-bain', 2, 'de'),
('casseroles-poeles', 'Töpfe & Pfannen', 'casseroles-poeles', 'cuisine-salle-de-bain', 2, 'de'),
('vaisselle', 'Geschirr', 'vaisselle', 'cuisine-salle-de-bain', 2, 'de'),
('couverts', 'Besteck', 'couverts', 'cuisine-salle-de-bain', 2, 'de'),
('robots-de-cuisine', 'Küchenmaschinen', 'robots-de-cuisine', 'cuisine-salle-de-bain', 2, 'de'),
('plaques-fours', 'Kochfelder & Öfen', 'plaques-fours', 'cuisine-salle-de-bain', 2, 'de'),
('equipements-sanitaires', 'Sanitäreinrichtungen', 'equipements-sanitaires', 'cuisine-salle-de-bain', 2, 'de'),
('baignoires', 'Badewannen', 'baignoires', 'cuisine-salle-de-bain', 2, 'de'),
('douches', 'Duschen', 'douches', 'cuisine-salle-de-bain', 2, 'de'),
('lavabos', 'Waschbecken', 'lavabos', 'cuisine-salle-de-bain', 2, 'de'),
('robinetterie', 'Armaturen', 'robinetterie', 'cuisine-salle-de-bain', 2, 'de'),
('meubles-de-salle-de-bain', 'Badezimmermöbel', 'meubles-de-salle-de-bain', 'cuisine-salle-de-bain', 2, 'de'),
('jardin-exterieur', 'Garten & Außenbereich', 'jardin-exterieur', 'immobilier-maison', 1, 'de'),
('mobilier-de-jardin', 'Gartenmöbel', 'mobilier-de-jardin', 'jardin-exterieur', 2, 'de'),
('salons-exterieurs', 'Außenlounges', 'salons-exterieurs', 'jardin-exterieur', 2, 'de'),
('parasols', 'Sonnenschirme', 'parasols', 'jardin-exterieur', 2, 'de'),
('barbecues', 'Grills', 'barbecues', 'jardin-exterieur', 2, 'de'),
('tondeuses', 'Rasenmäher', 'tondeuses', 'jardin-exterieur', 2, 'de'),
('debroussailleuses', 'Freischneider', 'debroussailleuses', 'jardin-exterieur', 2, 'de'),
('tronconneuses', 'Kettensägen', 'tronconneuses', 'jardin-exterieur', 2, 'de'),
('outils-de-jardinage', 'Gartenwerkzeuge', 'outils-de-jardinage', 'jardin-exterieur', 2, 'de'),
('pots-jardinieres', 'Töpfe & Blumenkästen', 'pots-jardinieres', 'jardin-exterieur', 2, 'de'),
('serres', 'Gewächshäuser', 'serres', 'jardin-exterieur', 2, 'de'),
('piscines-accessoires', 'Pools & Zubehör', 'piscines-accessoires', 'jardin-exterieur', 2, 'de'),
('eclairage-exterieur', 'Außenbeleuchtung', 'eclairage-exterieur', 'jardin-exterieur', 2, 'de'),
('bricolage-amelioration-maison', 'Heimwerken & Hausverbesserung', 'bricolage-amelioration-maison', 'immobilier-maison', 1, 'de'),
('outils-electroportatifs', 'Elektrowerkzeuge (Bohrer, Schrauber, Schleifer)', 'outils-electroportatifs', 'bricolage-amelioration-maison', 2, 'de'),
('outils-a-main', 'Handwerkzeuge', 'outils-a-main', 'bricolage-amelioration-maison', 2, 'de'),
('peinture', 'Farbe', 'peinture', 'bricolage-amelioration-maison', 2, 'de'),
('revetements-murs-sols', 'Wand- & Bodenbeläge', 'revetements-murs-sols', 'bricolage-amelioration-maison', 2, 'de'),
('parquet', 'Parkett', 'parquet', 'bricolage-amelioration-maison', 2, 'de'),
('carrelage', 'Fliesen', 'carrelage', 'bricolage-amelioration-maison', 2, 'de'),
('plomberie', 'Sanitär', 'plomberie', 'bricolage-amelioration-maison', 2, 'de'),
('electricite', 'Elektrik', 'electricite', 'bricolage-amelioration-maison', 2, 'de'),
('isolation', 'Isolierung', 'isolation', 'bricolage-amelioration-maison', 2, 'de'),
('materiaux-de-construction', 'Baumaterialien', 'materiaux-de-construction', 'bricolage-amelioration-maison', 2, 'de'),
('portes-fenetres', 'Türen & Fenster', 'portes-fenetres', 'bricolage-amelioration-maison', 2, 'de'),
('securite-maison', 'Haussicherheit', 'securite-maison', 'immobilier-maison', 1, 'de'),
('cameras-de-surveillance', 'Überwachungskameras', 'cameras-de-surveillance', 'securite-maison', 2, 'de'),
('alarmes-connectees', 'Verbundene Alarme', 'alarmes-connectees', 'securite-maison', 2, 'de'),
('detecteurs-de-fumee', 'Rauchmelder', 'detecteurs-de-fumee', 'securite-maison', 2, 'de'),
('serrures-cadenas', 'Schlösser & Vorhängeschlösser', 'serrures-cadenas', 'securite-maison', 2, 'de'),
('portails-automatiques', 'Automatische Tore', 'portails-automatiques', 'securite-maison', 2, 'de'),
('visiophones', 'Videogegensprechanlagen', 'visiophones', 'securite-maison', 2, 'de'),
('coffres-forts', 'Tresore', 'coffres-forts', 'securite-maison', 2, 'de'),
('services-maison-immobilier', 'Haus & Immobiliendienste', 'services-maison-immobilier', 'immobilier-maison', 1, 'de'),
('agences-immobilieres', 'Immobilienagenturen', 'agences-immobilieres', 'services-maison-immobilier', 2, 'de'),
('services-architecture', 'Architekturdienstleistungen', 'services-architecture', 'services-maison-immobilier', 2, 'de'),
('artisans-plomberie-electricite-peinture', 'Handwerker (Sanitär, Elektrik, Maler)', 'artisans-plomberie-electricite-peinture', 'services-maison-immobilier', 2, 'de'),
('demenagement', 'Umzug', 'demenagement', 'services-maison-immobilier', 2, 'de'),
('nettoyage', 'Reinigung', 'nettoyage', 'services-maison-immobilier', 2, 'de'),
('entretien-jardin', 'Gartenpflege', 'entretien-jardin', 'services-maison-immobilier', 2, 'de'),
('renovation', 'Renovierung', 'renovation', 'services-maison-immobilier', 2, 'de'),
('gestion-locative', 'Vermietungsmanagement', 'gestion-locative', 'services-maison-immobilier', 2, 'de'),
('diagnostics-immobiliers', 'Immobiliendiagnostik', 'diagnostics-immobiliers', 'services-maison-immobilier', 2, 'de'),
('marques-materiel-populaire', 'Beliebte Marken & Ausrüstung', 'marques-materiel-populaire', 'immobilier-maison', 1, 'de'),
('ikea', 'Ikea', 'ikea', 'marques-materiel-populaire', 2, 'de'),
('samsung-home', 'Samsung Home', 'samsung-home', 'marques-materiel-populaire', 2, 'de'),
('lg', 'LG', 'lg', 'marques-materiel-populaire', 2, 'de'),
('bosch', 'Bosch', 'bosch', 'marques-materiel-populaire', 2, 'de'),
('beko', 'Beko', 'beko', 'marques-materiel-populaire', 2, 'de'),
('whirlpool', 'Whirlpool', 'whirlpool', 'marques-materiel-populaire', 2, 'de'),
('philips-lighting', 'Philips Lighting', 'philips-lighting', 'marques-materiel-populaire', 2, 'de'),
('schneider-electric', 'Schneider Electric', 'schneider-electric', 'marques-materiel-populaire', 2, 'de'),
('karcher', 'Kärcher', 'karcher', 'marques-materiel-populaire', 2, 'de'),
('ariston', 'Ariston', 'ariston', 'marques-materiel-populaire', 2, 'de'),
('moulinex', 'Moulinex', 'moulinex', 'marques-materiel-populaire', 2, 'de'),
('tefal', 'Tefal', 'tefal', 'marques-materiel-populaire', 2, 'de'),
('jaga', 'Jaga', 'jaga', 'marques-materiel-populaire', 2, 'de'),
('daikin', 'Daikin', 'daikin', 'marques-materiel-populaire', 2, 'de');

-- ITALIEN
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('immobilier-maison', 'Immobili & Casa', 'immobilier-maison', NULL, 0, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('ventes-immobilieres', 'Vendite Immobiliari', 'ventes-immobilieres', 'immobilier-maison', 1, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('appartement', 'Appartamento', 'appartement', 'ventes-immobilieres', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('maison-villa', 'Casa/Villa', 'maison-villa', 'ventes-immobilieres', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('terrain', 'Terreno', 'terrain', 'ventes-immobilieres', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('commerce', 'Commercio', 'commerce', 'ventes-immobilieres', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('bureaux', 'Uffici', 'bureaux', 'ventes-immobilieres', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('garage-parking-box', 'Garage/Parcheggio/Box', 'garage-parking-box', 'ventes-immobilieres', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('programme-neuf', 'Programma Nuovo', 'programme-neuf', 'ventes-immobilieres', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('autre-vente-immobiliere', 'Altra Vendita Immobiliare', 'autre-vente-immobiliere', 'ventes-immobilieres', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('locations-immobilieres', 'Affitti Immobiliari', 'locations-immobilieres', 'immobilier-maison', 1, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('location-appartement', 'Affitto Appartamento', 'location-appartement', 'locations-immobilieres', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('location-maison-villa', 'Affitto Casa/Villa', 'location-maison-villa', 'locations-immobilieres', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('location-studio', 'Affitto Monolocale', 'location-studio', 'locations-immobilieres', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('location-chambre', 'Affitto Camera', 'location-chambre', 'locations-immobilieres', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('location-commerce', 'Affitto Commercio', 'location-commerce', 'locations-immobilieres', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('location-bureau', 'Affitto Ufficio', 'location-bureau', 'locations-immobilieres', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('location-garage-parking-box', 'Affitto Garage/Parcheggio/Box', 'location-garage-parking-box', 'locations-immobilieres', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('autre-location-immobiliere', 'Altro Affitto Immobiliare', 'autre-location-immobiliere', 'locations-immobilieres', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('colocation', 'Coinquilino', 'colocation', 'immobilier-maison', 1, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('colocation-appartement', 'Coinquilino Appartamento', 'colocation-appartement', 'colocation', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('colocation-maison-villa', 'Coinquilino Casa/Villa', 'colocation-maison-villa', 'colocation', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('colocation-studio', 'Coinquilino Monolocale', 'colocation-studio', 'colocation', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('colocation-chambre', 'Coinquilino Camera', 'colocation-chambre', 'colocation', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('autre-colocation', 'Altro Coinquilino', 'autre-colocation', 'colocation', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('viager', 'Vitaio', 'viager', 'immobilier-maison', 1, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('viager-appartement', 'Vitaio Appartamento', 'viager-appartement', 'viager', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('viager-maison-villa', 'Vitaio Casa/Villa', 'viager-maison-villa', 'viager', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('viager-commerce', 'Vitaio Commercio', 'viager-commerce', 'viager', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('autre-viager', 'Altro Vitaio', 'autre-viager', 'viager', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('location-saisonniere', 'Affitto Stagionale', 'location-saisonniere', 'immobilier-maison', 1, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('location-saisonniere-appartement', 'Affitto Stagionale Appartamento', 'location-saisonniere-appartement', 'location-saisonniere', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('location-saisonniere-maison-villa', 'Affitto Stagionale Casa/Villa', 'location-saisonniere-maison-villa', 'location-saisonniere', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('location-saisonniere-studio', 'Affitto Stagionale Monolocale', 'location-saisonniere-studio', 'location-saisonniere', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('autre-location-saisonniere', 'Altro Affitto Stagionale', 'autre-location-saisonniere', 'location-saisonniere', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('recherche-immobiliere', 'Ricerca Immobiliare', 'recherche-immobiliere', 'immobilier-maison', 1, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('recherche-appartement', 'Ricerca Appartamento', 'recherche-appartement', 'recherche-immobiliere', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('recherche-maison-villa', 'Ricerca Casa/Villa', 'recherche-maison-villa', 'recherche-immobiliere', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('recherche-studio', 'Ricerca Monolocale', 'recherche-studio', 'recherche-immobiliere', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('recherche-chambre', 'Ricerca Camera', 'recherche-chambre', 'recherche-immobiliere', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('recherche-terrain', 'Ricerca Terreno', 'recherche-terrain', 'recherche-immobiliere', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('recherche-commerce', 'Ricerca Commercio', 'recherche-commerce', 'recherche-immobiliere', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('recherche-bureau', 'Ricerca Ufficio', 'recherche-bureau', 'recherche-immobiliere', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('recherche-garage-parking-box', 'Ricerca Garage/Parcheggio/Box', 'recherche-garage-parking-box', 'recherche-immobiliere', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('autre-recherche-immobiliere', 'Altra Ricerca Immobiliare', 'autre-recherche-immobiliere', 'recherche-immobiliere', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('services-immobiliers', 'Servizi Immobiliari', 'services-immobiliers', 'immobilier-maison', 1, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('estimation-immobiliere', 'Stima Immobiliare', 'estimation-immobiliere', 'services-immobiliers', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('gestion-immobiliere', 'Gestione Immobiliare', 'gestion-immobiliere', 'services-immobiliers', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('transaction-immobiliere', 'Transazione Immobiliare', 'transaction-immobiliere', 'services-immobiliers', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('conseil-immobilier', 'Consulenza Immobiliare', 'conseil-immobilier', 'services-immobiliers', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('amenagement-immobilier', 'Arredamento Immobiliare', 'amenagement-immobilier', 'services-immobiliers', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('promotion-immobiliere', 'Promozione Immobiliare', 'promotion-immobiliere', 'services-immobiliers', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('marques-materiel-populaire', 'Marche Materiale Popolare', 'marques-materiel-populaire', 'immobilier-maison', 1, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('samsung', 'Samsung', 'samsung', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('lg', 'LG', 'lg', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('sony', 'Sony', 'sony', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('philips', 'Philips', 'philips', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('bosch', 'Bosch', 'bosch', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('siemens', 'Siemens', 'siemens', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('electrolux', 'Electrolux', 'electrolux', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('daikin', 'Daikin', 'daikin', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('atlantic', 'Atlantic', 'atlantic', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('candy', 'Candy', 'candy', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('indesit', 'Indesit', 'indesit', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('ariston', 'Ariston', 'ariston', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('beko', 'Beko', 'beko', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('whirlpool', 'Whirlpool', 'whirlpool', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('philips-lighting', 'Philips Lighting', 'philips-lighting', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('schneider-electric', 'Schneider Electric', 'schneider-electric', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('karcher', 'Kärcher', 'karcher', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('ariston', 'Ariston', 'ariston', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('moulinex', 'Moulinex', 'moulinex', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('tefal', 'Tefal', 'tefal', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('jaga', 'Jaga', 'jaga', 'marques-materiel-populaire', 2, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('daikin', 'Daikin', 'daikin', 'marques-materiel-populaire', 2, 'it');