*** Begin Patch
-- French
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('sacs-et-bagages', 'Sacs & Bagages', 'sacs-et-bagages', NULL, 0, 'fr');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('sacs-a-main', 'Sacs à main (femme & unisexe)', 'sacs-a-main', 'sacs-et-bagages', 1, 'fr'),
('sacs-a-dos', 'Sacs à dos', 'sacs-a-dos', 'sacs-et-bagages', 1, 'fr'),
('sacs-voyage-week-end', 'Sacs de voyage & Week-end', 'sacs-voyage-week-end', 'sacs-et-bagages', 1, 'fr'),
('valises-bagages', 'Valises & Bagages', 'valises-bagages', 'sacs-et-bagages', 1, 'fr'),
('maroquinerie', 'Maroquinerie', 'maroquinerie', 'sacs-et-bagages', 1, 'fr');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('cabas-grand', 'Cabas grand', 'cabas-grand', 'sacs-a-main', 2, 'fr'),
('cabas-moyen', 'Cabas moyen', 'cabas-moyen', 'sacs-a-main', 2, 'fr'),
('cabas-rigide', 'Cabas rigide', 'cabas-rigide', 'sacs-a-main', 2, 'fr'),
('cabas-souple', 'Cabas souple', 'cabas-souple', 'sacs-a-main', 2, 'fr'),
('bandouliere-mini', 'Bandoulière mini', 'bandouliere-mini', 'sacs-a-main', 2, 'fr'),
('bandouliere-moyen', 'Bandoulière moyen', 'bandouliere-moyen', 'sacs-a-main', 2, 'fr'),
('bandouliere-matelasse', 'Bandoulière matelassée', 'bandouliere-matelasse', 'sacs-a-main', 2, 'fr'),
('bandouliere-sport', 'Bandoulière sport', 'bandouliere-sport', 'sacs-a-main', 2, 'fr'),
('sacs-seau', 'Sacs seau', 'sacs-seau', 'sacs-a-main', 2, 'fr'),
('sacs-tote', 'Sacs tote', 'sacs-tote', 'sacs-a-main', 2, 'fr'),
('sacs-hobo', 'Sacs hobo', 'sacs-hobo', 'sacs-a-main', 2, 'fr'),
('sacs-bowling', 'Sacs bowling', 'sacs-bowling', 'sacs-a-main', 2, 'fr'),
('pochettes-soiree', 'Pochettes soirée', 'pochettes-soiree', 'sacs-a-main', 2, 'fr'),
('pochettes-mariage', 'Pochettes mariage', 'pochettes-mariage', 'sacs-a-main', 2, 'fr'),
('pochettes-minimalistes', 'Pochettes minimalistes', 'pochettes-minimalistes', 'sacs-a-main', 2, 'fr'),
('mini-bags-ville', 'Mini bags ville', 'mini-bags-ville', 'sacs-a-main', 2, 'fr'),
('mini-bags-luxe', 'Mini bags luxe', 'mini-bags-luxe', 'sacs-a-main', 2, 'fr'),
('sacs-demi-lune', 'Sacs demi-lune', 'sacs-demi-lune', 'sacs-a-main', 2, 'fr'),
('sacs-en-cuir-veritable', 'Sacs en cuir véritable', 'sacs-en-cuir-veritable', 'sacs-a-main', 2, 'fr'),
('sacs-en-cuir-synthetique', 'Sacs en cuir synthétique', 'sacs-en-cuir-synthetique', 'sacs-a-main', 2, 'fr'),
('sacs-en-cuir-artisanal', 'Sacs en cuir artisanal', 'sacs-en-cuir-artisanal', 'sacs-a-main', 2, 'fr'),
('sacs-en-toile-tissu', 'Sacs en toile & tissu', 'sacs-en-toile-tissu', 'sacs-a-main', 2, 'fr'),
('urbains', 'Urbains', 'urbains', 'sacs-a-dos', 2, 'fr'),
('antivol', 'Antivol', 'antivol', 'sacs-a-dos', 2, 'fr'),
('business-porte-pc', 'Business (porte PC)', 'business-porte-pc', 'sacs-a-dos', 2, 'fr'),
('sport', 'Sport', 'sport', 'sacs-a-dos', 2, 'fr'),
('randonnee-20l', 'Randonnée 20L', 'randonnee-20l', 'sacs-a-dos', 2, 'fr'),
('randonnee-30l', 'Randonnée 30L', 'randonnee-30l', 'sacs-a-dos', 2, 'fr'),
('randonnee-50l-plus', 'Randonnée 50L+', 'randonnee-50l-plus', 'sacs-a-dos', 2, 'fr'),
('tactiques-militaires', 'Tactiques & militaires', 'tactiques-militaires', 'sacs-a-dos', 2, 'fr'),
('scolaires-enfant-ado', 'Scolaires enfant & ado', 'scolaires-enfant-ado', 'sacs-a-dos', 2, 'fr'),
('minimalistes', 'Minimalistes', 'minimalistes', 'sacs-a-dos', 2, 'fr'),
('voyage-cabine', 'Voyage cabine', 'voyage-cabine', 'sacs-a-dos', 2, 'fr'),
('voyage-souples', 'Voyage souples', 'voyage-souples', 'sacs-voyage-week-end', 2, 'fr'),
('voyage-semi-rigides', 'Voyage semi-rigides', 'voyage-semi-rigides', 'sacs-voyage-week-end', 2, 'fr'),
('duffle-bags', 'Duffle bags', 'duffle-bags', 'sacs-voyage-week-end', 2, 'fr'),
('polochon', 'Polochon', 'polochon', 'sacs-voyage-week-end', 2, 'fr'),
('week-end', 'Week-end', 'week-end', 'sacs-voyage-week-end', 2, 'fr'),
('pliables', 'Pliables', 'pliables', 'sacs-voyage-week-end', 2, 'fr'),
('transport-longue-distance', 'Transport longue distance', 'transport-longue-distance', 'sacs-voyage-week-end', 2, 'fr'),
('multi-poches', 'Multi-poches', 'multi-poches', 'sacs-voyage-week-end', 2, 'fr'),
('compartiment-chaussures', 'Compartiment chaussures', 'compartiment-chaussures', 'sacs-voyage-week-end', 2, 'fr'),
('cabine-rigides', 'Cabine rigides', 'cabine-rigides', 'valises-bagages', 2, 'fr'),
('cabine-souples', 'Cabine souples', 'cabine-souples', 'valises-bagages', 2, 'fr'),
('cabine-extensibles', 'Cabine extensibles', 'cabine-extensibles', 'valises-bagages', 2, 'fr'),
('valises-medium', 'Valises medium', 'valises-medium', 'valises-bagages', 2, 'fr'),
('valises-grandes', 'Valises grandes', 'valises-grandes', 'valises-bagages', 2, 'fr'),
('valises-aluminium', 'Valises aluminium', 'valises-aluminium', 'valises-bagages', 2, 'fr'),
('sets-valises', 'Sets valises', 'sets-valises', 'valises-bagages', 2, 'fr'),
('valises-enfants', 'Valises enfants', 'valises-enfants', 'valises-bagages', 2, 'fr'),
('valises-connectees', 'Valises connectées', 'valises-connectees', 'valises-bagages', 2, 'fr'),
('valises-professionnelles', 'Valises professionnelles', 'valises-professionnelles', 'valises-bagages', 2, 'fr'),
('bagages-certifies-iata', 'Bagages certifiés IATA', 'bagages-certifies-iata', 'valises-bagages', 2, 'fr'),
('valises-securisees-tsa', 'Valises sécurisées TSA', 'valises-securisees-tsa', 'valises-bagages', 2, 'fr'),
('portefeuilles-zippe', 'Portefeuilles zippé', 'portefeuilles-zippe', 'maroquinerie', 2, 'fr'),
('portefeuilles-pliable', 'Portefeuilles pliable', 'portefeuilles-pliable', 'maroquinerie', 2, 'fr'),
('portefeuilles-compact', 'Portefeuilles compact', 'portefeuilles-compact', 'maroquinerie', 2, 'fr');

-- Level 3 - Catégories principales pour Bagages de voyage (French)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('valises-souples', 'Valises souples', 'valises-souples', 'valises-bagages', 3, 'fr'),
('valises-rigides', 'Valises rigides', 'valises-rigides', 'valises-bagages', 3, 'fr'),
('cabines-bagages', 'Cabines bagages', 'cabines-bagages', 'valises-bagages', 3, 'fr'),
('sacs-de-voyage-roulants', 'Sacs de voyage roulants', 'sacs-de-voyage-roulants', 'sacs-voyage-week-end', 3, 'fr'),
('sacs-de-sport-voyage', 'Sacs de sport voyage', 'sacs-de-sport-voyage', 'sacs-voyage-week-end', 3, 'fr'),
('trousses-de-toilette', 'Trousses de toilette', 'trousses-de-toilette', 'sacs-voyage-week-end', 3, 'fr'),
('housses-bagages', 'Housses bagages', 'housses-bagages', 'valises-bagages', 3, 'fr'),
('etiquettes-bagages', 'Étiquettes bagages', 'etiquettes-bagages', 'valises-bagages', 3, 'fr'),
('cadenas-bagages', 'Cadenas bagages', 'cadenas-bagages', 'valises-bagages', 3, 'fr');

-- Arabic
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('sacs-et-bagages', 'حقائب وأمتعة', 'sacs-et-bagages', NULL, 0, 'ar');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('sacs-a-main', 'حقائب يد (نساء & للجنسين)', 'sacs-a-main', 'sacs-et-bagages', 1, 'ar'),
('sacs-a-dos', 'حقائب ظهر', 'sacs-a-dos', 'sacs-et-bagages', 1, 'ar'),
('sacs-voyage-week-end', 'حقائب سفر ونهاية الأسبوع', 'sacs-voyage-week-end', 'sacs-et-bagages', 1, 'ar'),
('valises-bagages', 'حقائب سفر وأمتعة', 'valises-bagages', 'sacs-et-bagages', 1, 'ar'),
('maroquinerie', 'الجلود', 'maroquinerie', 'sacs-et-bagages', 1, 'ar');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('cabas-grand', 'حقائب تسوق كبيرة', 'cabas-grand', 'sacs-a-main', 2, 'ar'),
('cabas-moyen', 'حقائب تسوق متوسطة', 'cabas-moyen', 'sacs-a-main', 2, 'ar'),
('cabas-rigide', 'حقائب تسوق صلبة', 'cabas-rigide', 'sacs-a-main', 2, 'ar'),
('cabas-souple', 'حقائب تسوق ناعمة', 'cabas-souple', 'sacs-a-main', 2, 'ar'),
('bandouliere-mini', 'حقائب كتف صغيرة', 'bandouliere-mini', 'sacs-a-main', 2, 'ar'),
('bandouliere-moyen', 'حقائب كتف متوسطة', 'bandouliere-moyen', 'sacs-a-main', 2, 'ar'),
('bandouliere-matelasse', 'حقائب كتف مبطنة', 'bandouliere-matelasse', 'sacs-a-main', 2, 'ar'),
('bandouliere-sport', 'حقائب كتف رياضية', 'bandouliere-sport', 'sacs-a-main', 2, 'ar'),
('sacs-seau', 'حقائب دلو', 'sacs-seau', 'sacs-a-main', 2, 'ar'),
('sacs-tote', 'حقائب حمل', 'sacs-tote', 'sacs-a-main', 2, 'ar'),
('sacs-hobo', 'حقائب هوبو', 'sacs-hobo', 'sacs-a-main', 2, 'ar'),
('sacs-bowling', 'حقائب بولينغ', 'sacs-bowling', 'sacs-a-main', 2, 'ar'),
('pochettes-soiree', 'محافل سهرة', 'pochettes-soiree', 'sacs-a-main', 2, 'ar'),
('pochettes-mariage', 'محافل زفاف', 'pochettes-mariage', 'sacs-a-main', 2, 'ar'),
('pochettes-minimalistes', 'محافل بسيطة', 'pochettes-minimalistes', 'sacs-a-main', 2, 'ar'),
('mini-bags-ville', 'حقائب صغيرة للمدينة', 'mini-bags-ville', 'sacs-a-main', 2, 'ar'),
('mini-bags-luxe', 'حقائب صغيرة فاخرة', 'mini-bags-luxe', 'sacs-a-main', 2, 'ar'),
('sacs-demi-lune', 'حقائب هلال', 'sacs-demi-lune', 'sacs-a-main', 2, 'ar'),
('sacs-en-cuir-veritable', 'حقائب جلد طبيعي', 'sacs-en-cuir-veritable', 'sacs-a-main', 2, 'ar'),
('sacs-en-cuir-synthetique', 'حقائب جلد صناعي', 'sacs-en-cuir-synthetique', 'sacs-a-main', 2, 'ar'),
('sacs-en-cuir-artisanal', 'حقائب جلد حرفي', 'sacs-en-cuir-artisanal', 'sacs-a-main', 2, 'ar'),
('sacs-en-toile-tissu', 'حقائب قماش ونسيج', 'sacs-en-toile-tissu', 'sacs-a-main', 2, 'ar'),
('urbains', 'حقائب حضرية', 'urbains', 'sacs-a-dos', 2, 'ar'),
('antivol', 'حقائب مضادة للسرقة', 'antivol', 'sacs-a-dos', 2, 'ar'),
('business-porte-pc', 'حقائب عمل (للكمبيوتر)', 'business-porte-pc', 'sacs-a-dos', 2, 'ar'),
('sport', 'رياضية', 'sport', 'sacs-a-dos', 2, 'ar'),
('randonnee-20l', 'مشي لمسافات طويلة 20 لتر', 'randonnee-20l', 'sacs-a-dos', 2, 'ar'),
('randonnee-30l', 'مشي لمسافات طويلة 30 لتر', 'randonnee-30l', 'sacs-a-dos', 2, 'ar'),
('randonnee-50l-plus', 'مشي لمسافات طويلة 50 لتر+', 'randonnee-50l-plus', 'sacs-a-dos', 2, 'ar'),
('tactiques-militaires', 'تكتيكية وعسكرية', 'tactiques-militaires', 'sacs-a-dos', 2, 'ar'),
('scolaires-enfant-ado', 'حقائب مدرسية (أطفال/مراهقين)', 'scolaires-enfant-ado', 'sacs-a-dos', 2, 'ar'),
('minimalistes', 'بسيطة', 'minimalistes', 'sacs-a-dos', 2, 'ar'),
('voyage-cabine', 'سفر مقصورة', 'voyage-cabine', 'sacs-a-dos', 2, 'ar'),
('voyage-souples', 'سفر ناعمة', 'voyage-souples', 'sacs-voyage-week-end', 2, 'ar'),
('voyage-semi-rigides', 'سفر شبه صلبة', 'voyage-semi-rigides', 'sacs-voyage-week-end', 2, 'ar'),
('duffle-bags', 'حقائب دفل', 'duffle-bags', 'sacs-voyage-week-end', 2, 'ar'),
('polochon', 'حقائب اسطوانية', 'polochon', 'sacs-voyage-week-end', 2, 'ar'),
('week-end', 'نهاية الأسبوع', 'week-end', 'sacs-voyage-week-end', 2, 'ar'),
('pliables', 'قابلة للطي', 'pliables', 'sacs-voyage-week-end', 2, 'ar'),
('transport-longue-distance', 'نقل مسافات طويلة', 'transport-longue-distance', 'sacs-voyage-week-end', 2, 'ar'),
('multi-poches', 'متعددة الجيوب', 'multi-poches', 'sacs-voyage-week-end', 2, 'ar'),
('compartiment-chaussures', 'مقصورة أحذية', 'compartiment-chaussures', 'sacs-voyage-week-end', 2, 'ar'),
('cabine-rigides', 'مقصورة صلبة', 'cabine-rigides', 'valises-bagages', 2, 'ar'),
('cabine-souples', 'مقصورة ناعمة', 'cabine-souples', 'valises-bagages', 2, 'ar'),
('cabine-extensibles', 'مقصورة قابلة للتوسيع', 'cabine-extensibles', 'valises-bagages', 2, 'ar'),
('valises-medium', 'حقائب متوسطة', 'valises-medium', 'valises-bagages', 2, 'ar'),
('valises-grandes', 'حقائب كبيرة', 'valises-grandes', 'valises-bagages', 2, 'ar'),
('valises-aluminium', 'حقائب ألمنيوم', 'valises-aluminium', 'valises-bagages', 2, 'ar'),
('sets-valises', 'مجموعات حقائب', 'sets-valises', 'valises-bagages', 2, 'ar'),
('valises-enfants', 'حقائب أطفال', 'valises-enfants', 'valises-bagages', 2, 'ar'),
('valises-connectees', 'حقائب ذكية', 'valises-connectees', 'valises-bagages', 2, 'ar'),
('valises-professionnelles', 'حقائب مهنية', 'valises-professionnelles', 'valises-bagages', 2, 'ar'),
('bagages-certifies-iata', 'أمتعة معتمدة IATA', 'bagages-certifies-iata', 'valises-bagages', 2, 'ar'),
('valises-securisees-tsa', 'حقائب آمنة TSA', 'valises-securisees-tsa', 'valises-bagages', 2, 'ar'),
('portefeuilles-zippe', 'محافل بسحاب', 'portefeuilles-zippe', 'maroquinerie', 2, 'ar'),
('portefeuilles-pliable', 'محافل قابلة للطي', 'portefeuilles-pliable', 'maroquinerie', 2, 'ar'),
('portefeuilles-compact', 'محافل مدمجة', 'portefeuilles-compact', 'maroquinerie', 2, 'ar');

-- Level 3 - Catégories principales pour Bagages de voyage (Arabic)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('valises-souples', 'حقائب سفر مرنة', 'valises-souples', 'valises-bagages', 3, 'ar'),
('valises-rigides', 'حقائب سفر صلبة', 'valises-rigides', 'valises-bagages', 3, 'ar'),
('cabines-bagages', 'حقائب مقصورة', 'cabines-bagages', 'valises-bagages', 3, 'ar'),
('sacs-de-voyage-roulants', 'حقائب سفر بعجلات', 'sacs-de-voyage-roulants', 'sacs-voyage-week-end', 3, 'ar'),
('sacs-de-sport-voyage', 'حقائب رياضية للسفر', 'sacs-de-sport-voyage', 'sacs-voyage-week-end', 3, 'ar'),
('trousses-de-toilette', 'حقائب تجميل', 'trousses-de-toilette', 'sacs-voyage-week-end', 3, 'ar'),
('housses-bagages', 'أغطية الأمتعة', 'housses-bagages', 'valises-bagages', 3, 'ar'),
('etiquettes-bagages', 'ملصقات الأمتعة', 'etiquettes-bagages', 'valises-bagages', 3, 'ar'),
('cadenas-bagages', 'أقفال الأمتعة', 'cadenas-bagages', 'valises-bagages', 3, 'ar');

-- English
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('sacs-et-bagages', 'Bags & Luggage', 'sacs-et-bagages', NULL, 0, 'en');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('sacs-a-main', 'Handbags (women & unisex)', 'sacs-a-main', 'sacs-et-bagages', 1, 'en'),
('sacs-a-dos', 'Backpacks', 'sacs-a-dos', 'sacs-et-bagages', 1, 'en'),
('sacs-voyage-week-end', 'Travel & Weekend bags', 'sacs-voyage-week-end', 'sacs-et-bagages', 1, 'en'),
('valises-bagages', 'Suitcases & Luggage', 'valises-bagages', 'sacs-et-bagages', 1, 'en'),
('maroquinerie', 'Leather goods', 'maroquinerie', 'sacs-et-bagages', 1, 'en');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('cabas-grand', 'Large tote bags', 'cabas-grand', 'sacs-a-main', 2, 'en'),
('cabas-moyen', 'Medium tote bags', 'cabas-moyen', 'sacs-a-main', 2, 'en'),
('cabas-rigide', 'Rigid tote bags', 'cabas-rigide', 'sacs-a-main', 2, 'en'),
('cabas-souple', 'Soft tote bags', 'cabas-souple', 'sacs-a-main', 2, 'en'),
('bandouliere-mini', 'Mini shoulder bags', 'bandouliere-mini', 'sacs-a-main', 2, 'en'),
('bandouliere-moyen', 'Medium shoulder bags', 'bandouliere-moyen', 'sacs-a-main', 2, 'en'),
('bandouliere-matelasse', 'Quilted shoulder bags', 'bandouliere-matelasse', 'sacs-a-main', 2, 'en'),
('bandouliere-sport', 'Sport shoulder bags', 'bandouliere-sport', 'sacs-a-main', 2, 'en'),
('sacs-seau', 'Bucket bags', 'sacs-seau', 'sacs-a-main', 2, 'en'),
('sacs-tote', 'Tote bags', 'sacs-tote', 'sacs-a-main', 2, 'en'),
('sacs-hobo', 'Hobo bags', 'sacs-hobo', 'sacs-a-main', 2, 'en'),
('sacs-bowling', 'Bowling bags', 'sacs-bowling', 'sacs-a-main', 2, 'en'),
('pochettes-soiree', 'Evening clutches', 'pochettes-soiree', 'sacs-a-main', 2, 'en'),
('pochettes-mariage', 'Wedding clutches', 'pochettes-mariage', 'sacs-a-main', 2, 'en'),
('pochettes-minimalistes', 'Minimalist clutches', 'pochettes-minimalistes', 'sacs-a-main', 2, 'en'),
('mini-bags-ville', 'City mini bags', 'mini-bags-ville', 'sacs-a-main', 2, 'en'),
('mini-bags-luxe', 'Luxury mini bags', 'mini-bags-luxe', 'sacs-a-main', 2, 'en'),
('sacs-demi-lune', 'Half-moon bags', 'sacs-demi-lune', 'sacs-a-main', 2, 'en'),
('sacs-en-cuir-veritable', 'Genuine leather bags', 'sacs-en-cuir-veritable', 'sacs-a-main', 2, 'en'),
('sacs-en-cuir-synthetique', 'Synthetic leather bags', 'sacs-en-cuir-synthetique', 'sacs-a-main', 2, 'en'),
('sacs-en-cuir-artisanal', 'Artisanal leather bags', 'sacs-en-cuir-artisanal', 'sacs-a-main', 2, 'en'),
('sacs-en-toile-tissu', 'Canvas & fabric bags', 'sacs-en-toile-tissu', 'sacs-a-main', 2, 'en'),
('urbains', 'Urban backpacks', 'urbains', 'sacs-a-dos', 2, 'en'),
('antivol', 'Anti-theft backpacks', 'antivol', 'sacs-a-dos', 2, 'en'),
('business-porte-pc', 'Business backpacks (laptop)', 'business-porte-pc', 'sacs-a-dos', 2, 'en'),
('sport', 'Sports backpacks', 'sport', 'sacs-a-dos', 2, 'en'),
('randonnee-20l', 'Hiking & trekking 20L', 'randonnee-20l', 'sacs-a-dos', 2, 'en'),
('randonnee-30l', 'Hiking & trekking 30L', 'randonnee-30l', 'sacs-a-dos', 2, 'en'),
('randonnee-50l-plus', 'Hiking & trekking 50L+', 'randonnee-50l-plus', 'sacs-a-dos', 2, 'en'),
('tactiques-militaires', 'Tactical & military', 'tactiques-militaires', 'sacs-a-dos', 2, 'en'),
('scolaires-enfant-ado', 'School backpacks (kids/teens)', 'scolaires-enfant-ado', 'sacs-a-dos', 2, 'en'),
('minimalistes', 'Minimalist backpacks', 'minimalistes', 'sacs-a-dos', 2, 'en'),
('voyage-cabine', 'Carry-on travel backpacks', 'voyage-cabine', 'sacs-a-dos', 2, 'en'),
('voyage-souples', 'Soft travel bags', 'voyage-souples', 'sacs-voyage-week-end', 2, 'en'),
('voyage-semi-rigides', 'Semi-rigid travel bags', 'voyage-semi-rigides', 'sacs-voyage-week-end', 2, 'en'),
('duffle-bags', 'Duffle bags', 'duffle-bags', 'sacs-voyage-week-end', 2, 'en'),
('polochon', 'Barrel bags', 'polochon', 'sacs-voyage-week-end', 2, 'en'),
('week-end', 'Weekender bags', 'week-end', 'sacs-voyage-week-end', 2, 'en'),
('pliables', 'Foldable bags', 'pliables', 'sacs-voyage-week-end', 2, 'en'),
('transport-longue-distance', 'Long-distance transport bags', 'transport-longue-distance', 'sacs-voyage-week-end', 2, 'en'),
('multi-poches', 'Multi-pocket bags', 'multi-poches', 'sacs-voyage-week-end', 2, 'en'),
('compartiment-chaussures', 'Shoe compartment bags', 'compartiment-chaussures', 'sacs-voyage-week-end', 2, 'en'),
('cabine-rigides', 'Cabin suitcases (hard)', 'cabine-rigides', 'valises-bagages', 2, 'en'),
('cabine-souples', 'Cabin suitcases (soft)', 'cabine-souples', 'valises-bagages', 2, 'en'),
('cabine-extensibles', 'Expandable cabin suitcases', 'cabine-extensibles', 'valises-bagages', 2, 'en'),
('valises-medium', 'Medium suitcases', 'valises-medium', 'valises-bagages', 2, 'en'),
('valises-grandes', 'Large suitcases', 'valises-grandes', 'valises-bagages', 2, 'en'),
('valises-aluminium', 'Aluminium suitcases', 'valises-aluminium', 'valises-bagages', 2, 'en'),
('sets-valises', 'Luggage sets', 'sets-valises', 'valises-bagages', 2, 'en'),
('valises-enfants', 'Kids suitcases', 'valises-enfants', 'valises-bagages', 2, 'en'),
('valises-connectees', 'Smart suitcases', 'valises-connectees', 'valises-bagages', 2, 'en'),
('valises-professionnelles', 'Professional suitcases', 'valises-professionnelles', 'valises-bagages', 2, 'en'),
('bagages-certifies-iata', 'IATA certified luggage', 'bagages-certifies-iata', 'valises-bagages', 2, 'en'),
('valises-securisees-tsa', 'TSA secure suitcases', 'valises-securisees-tsa', 'valises-bagages', 2, 'en'),
('portefeuilles-zippe', 'Zipped wallets', 'portefeuilles-zippe', 'maroquinerie', 2, 'en'),
('portefeuilles-pliable', 'Foldable wallets', 'portefeuilles-pliable', 'maroquinerie', 2, 'en'),
('portefeuilles-compact', 'Compact wallets', 'portefeuilles-compact', 'maroquinerie', 2, 'en');

-- Level 3 - Main Categories for Travel Luggage (English)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('valises-souples', 'Soft suitcases', 'valises-souples', 'valises-bagages', 3, 'en'),
('valises-rigides', 'Hard suitcases', 'valises-rigides', 'valises-bagages', 3, 'en'),
('cabines-bagages', 'Cabin luggage', 'cabines-bagages', 'valises-bagages', 3, 'en'),
('sacs-de-voyage-roulants', 'Rolling travel bags', 'sacs-de-voyage-roulants', 'sacs-voyage-week-end', 3, 'en'),
('sacs-de-sport-voyage', 'Travel sports bags', 'sacs-de-sport-voyage', 'sacs-voyage-week-end', 3, 'en'),
('trousses-de-toilette', 'Toiletry bags', 'trousses-de-toilette', 'sacs-voyage-week-end', 3, 'en'),
('housses-bagages', 'Luggage covers', 'housses-bagages', 'valises-bagages', 3, 'en'),
('etiquettes-bagages', 'Luggage tags', 'etiquettes-bagages', 'valises-bagages', 3, 'en'),
('cadenas-bagages', 'Luggage locks', 'cadenas-bagages', 'valises-bagages', 3, 'en');

-- Spanish
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('sacs-et-bagages', 'Bolsos y Equipaje', 'sacs-et-bagages', NULL, 0, 'es');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('sacs-a-main', 'Bolsos de mano (mujer & unisex)', 'sacs-a-main', 'sacs-et-bagages', 1, 'es'),
('sacs-a-dos', 'Mochilas', 'sacs-a-dos', 'sacs-et-bagages', 1, 'es'),
('sacs-voyage-week-end', 'Bolsas de viaje y fin de semana', 'sacs-voyage-week-end', 'sacs-et-bagages', 1, 'es'),
('valises-bagages', 'Maletas y equipaje', 'valises-bagages', 'sacs-et-bagages', 1, 'es'),
('maroquinerie', 'Marroquinería', 'maroquinerie', 'sacs-et-bagages', 1, 'es');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('cabas-grand', 'Shopper grandes', 'cabas-grand', 'sacs-a-main', 2, 'es'),
('cabas-moyen', 'Shopper medianos', 'cabas-moyen', 'sacs-a-main', 2, 'es'),
('cabas-rigide', 'Shopper rígidos', 'cabas-rigide', 'sacs-a-main', 2, 'es'),
('cabas-souple', 'Shopper flexibles', 'cabas-souple', 'sacs-a-main', 2, 'es'),
('bandouliere-mini', 'Bolsos bandolera mini', 'bandouliere-mini', 'sacs-a-main', 2, 'es'),
('bandouliere-moyen', 'Bolsos bandolera medianos', 'bandouliere-moyen', 'sacs-a-main', 2, 'es'),
('bandouliere-matelasse', 'Bolsos bandolera acolchados', 'bandouliere-matelasse', 'sacs-a-main', 2, 'es'),
('bandouliere-sport', 'Bolsos bandolera deportivos', 'bandouliere-sport', 'sacs-a-main', 2, 'es'),
('sacs-seau', 'Bolsos saco', 'sacs-seau', 'sacs-a-main', 2, 'es'),
('sacs-tote', 'Bolsos tote', 'sacs-tote', 'sacs-a-main', 2, 'es'),
('sacs-hobo', 'Bolsos hobo', 'sacs-hobo', 'sacs-a-main', 2, 'es'),
('sacs-bowling', 'Bolsos bowling', 'sacs-bowling', 'sacs-a-main', 2, 'es'),
('pochettes-soiree', 'Clutches de noche', 'pochettes-soiree', 'sacs-a-main', 2, 'es'),
('pochettes-mariage', 'Clutches de boda', 'pochettes-mariage', 'sacs-a-main', 2, 'es'),
('pochettes-minimalistes', 'Clutches minimalistas', 'pochettes-minimalistes', 'sacs-a-main', 2, 'es'),
('mini-bags-ville', 'Mini bolsos urbanos', 'mini-bags-ville', 'sacs-a-main', 2, 'es'),
('mini-bags-luxe', 'Mini bolsos de lujo', 'mini-bags-luxe', 'sacs-a-main', 2, 'es'),
('sacs-demi-lune', 'Bolsos media luna', 'sacs-demi-lune', 'sacs-a-main', 2, 'es'),
('sacs-en-cuir-veritable', 'Bolsos de cuero auténtico', 'sacs-en-cuir-veritable', 'sacs-a-main', 2, 'es'),
('sacs-en-cuir-synthetique', 'Bolsos de cuero sintético', 'sacs-en-cuir-synthetique', 'sacs-a-main', 2, 'es'),
('sacs-en-cuir-artisanal', 'Bolsos de cuero artesanal', 'sacs-en-cuir-artisanal', 'sacs-a-main', 2, 'es'),
('sacs-en-toile-tissu', 'Bolsos de lona y tela', 'sacs-en-toile-tissu', 'sacs-a-main', 2, 'es'),
('urbains', 'Mochilas urbanas', 'urbains', 'sacs-a-dos', 2, 'es'),
('antivol', 'Mochilas antirrobo', 'antivol', 'sacs-a-dos', 2, 'es'),
('business-porte-pc', 'Mochilas de negocios (para portátil)', 'business-porte-pc', 'sacs-a-dos', 2, 'es'),
('sport', 'Mochilas deportivas', 'sport', 'sacs-a-dos', 2, 'es'),
('randonnee-20l', 'Senderismo y trekking 20L', 'randonnee-20l', 'sacs-a-dos', 2, 'es'),
('randonnee-30l', 'Senderismo y trekking 30L', 'randonnee-30l', 'sacs-a-dos', 2, 'es'),
('randonnee-50l-plus', 'Senderismo y trekking 50L+', 'randonnee-50l-plus', 'sacs-a-dos', 2, 'es'),
('tactiques-militaires', 'Mochilas tácticas y militares', 'tactiques-militaires', 'sacs-a-dos', 2, 'es'),
('scolaires-enfant-ado', 'Mochilas escolares (niños/adolescentes)', 'scolaires-enfant-ado', 'sacs-a-dos', 2, 'es'),
('minimalistes', 'Mochilas minimalistas', 'minimalistes', 'sacs-a-dos', 2, 'es'),
('voyage-cabine', 'Mochilas de cabina para viaje', 'voyage-cabine', 'sacs-a-dos', 2, 'es'),
('voyage-souples', 'Bolsas de viaje blandas', 'voyage-souples', 'sacs-voyage-week-end', 2, 'es'),
('voyage-semi-rigides', 'Bolsas de viaje semirrígidas', 'voyage-semi-rigides', 'sacs-voyage-week-end', 2, 'es'),
('duffle-bags', 'Bolsas duffle', 'duffle-bags', 'sacs-voyage-week-end', 2, 'es'),
('polochon', 'Bolsas barril', 'polochon', 'sacs-voyage-week-end', 2, 'es'),
('week-end', 'Bolsas de fin de semana', 'week-end', 'sacs-voyage-week-end', 2, 'es'),
('pliables', 'Bolsas plegables', 'pliables', 'sacs-voyage-week-end', 2, 'es'),
('transport-longue-distance', 'Bolsas de transporte de larga distancia', 'transport-longue-distance', 'sacs-voyage-week-end', 2, 'es'),
('multi-poches', 'Bolsas multi-bolsillos', 'multi-poches', 'sacs-voyage-week-end', 2, 'es'),
('compartiment-chaussures', 'Bolsas con compartimento para zapatos', 'compartiment-chaussures', 'sacs-voyage-week-end', 2, 'es'),
('cabine-rigides', 'Maletas de cabina rígidas', 'cabine-rigides', 'valises-bagages', 2, 'es'),
('cabine-souples', 'Maletas de cabina blandas', 'cabine-souples', 'valises-bagages', 2, 'es'),
('cabine-extensibles', 'Maletas de cabina expandibles', 'cabine-extensibles', 'valises-bagages', 2, 'es'),
('valises-medium', 'Maletas medianas', 'valises-medium', 'valises-bagages', 2, 'es'),
('valises-grandes', 'Maletas grandes', 'valises-grandes', 'valises-bagages', 2, 'es'),
('valises-aluminium', 'Maletas de aluminio', 'valises-aluminium', 'valises-bagages', 2, 'es'),
('sets-valises', 'Sets de maletas', 'sets-valises', 'valises-bagages', 2, 'es'),
('valises-enfants', 'Maletas infantiles', 'valises-enfants', 'valises-bagages', 2, 'es'),
('valises-connectees', 'Maletas inteligentes', 'valises-connectees', 'valises-bagages', 2, 'es'),
('valises-professionnelles', 'Maletas profesionales', 'valises-professionnelles', 'valises-bagages', 2, 'es'),
('bagages-certifies-iata', 'Equipaje certificado por IATA', 'bagages-certifies-iata', 'valises-bagages', 2, 'es'),
('valises-securisees-tsa', 'Maletas con seguridad TSA', 'valises-securisees-tsa', 'valises-bagages', 2, 'es'),
('portefeuilles-zippe', 'Carteras con cremallera', 'portefeuilles-zippe', 'maroquinerie', 2, 'es'),
('portefeuilles-pliable', 'Carteras plegables', 'portefeuilles-pliable', 'maroquinerie', 2, 'es'),
('portefeuilles-compact', 'Carteras compactas', 'portefeuilles-compact', 'maroquinerie', 2, 'es');

-- Level 3 - Categorías principales para Equipaje de Viaje (Spanish)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('valises-souples', 'Maletas blandas', 'valises-souples', 'valises-bagages', 3, 'es'),
('valises-rigides', 'Maletas rígidas', 'valises-rigides', 'valises-bagages', 3, 'es'),
('cabines-bagages', 'Equipaje de cabina', 'cabines-bagages', 'valises-bagages', 3, 'es'),
('sacs-de-voyage-roulants', 'Bolsas de viaje con ruedas', 'sacs-de-voyage-roulants', 'sacs-voyage-week-end', 3, 'es'),
('sacs-de-sport-voyage', 'Bolsas de deporte para viaje', 'sacs-de-sport-voyage', 'sacs-voyage-week-end', 3, 'es'),
('trousses-de-toilette', 'Neceseres', 'trousses-de-toilette', 'sacs-voyage-week-end', 3, 'es'),
('housses-bagages', 'Fundas para equipaje', 'housses-bagages', 'valises-bagages', 3, 'es'),
('etiquettes-bagages', 'Etiquetas para equipaje', 'etiquettes-bagages', 'valises-bagages', 3, 'es'),
('cadenas-bagages', 'Cerraduras para equipaje', 'cadenas-bagages', 'valises-bagages', 3, 'es');

-- German
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('sacs-et-bagages', 'Taschen & Gepäck', 'sacs-et-bagages', NULL, 0, 'de');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('sacs-a-main', 'Handtaschen (Damen & Unisex)', 'sacs-a-main', 'sacs-et-bagages', 1, 'de'),
('sacs-a-dos', 'Rucksäcke', 'sacs-a-dos', 'sacs-et-bagages', 1, 'de'),
('sacs-voyage-week-end', 'Reise- & Weekender-Taschen', 'sacs-voyage-week-end', 'sacs-et-bagages', 1, 'de'),
('valises-bagages', 'Koffer & Gepäck', 'valises-bagages', 'sacs-et-bagages', 1, 'de'),
('maroquinerie', 'Lederwaren', 'maroquinerie', 'sacs-et-bagages', 1, 'de');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('cabas-grand', 'Große Shopper-Taschen', 'cabas-grand', 'sacs-a-main', 2, 'de'),
('cabas-moyen', 'Mittlere Shopper-Taschen', 'cabas-moyen', 'sacs-a-main', 2, 'de'),
('cabas-rigide', 'Shopper, hart', 'cabas-rigide', 'sacs-a-main', 2, 'de'),
('cabas-souple', 'Shopper, weich', 'cabas-souple', 'sacs-a-main', 2, 'de'),
('bandouliere-mini', 'Mini-Schultertaschen', 'bandouliere-mini', 'sacs-a-main', 2, 'de'),
('bandouliere-moyen', 'Schultertaschen mittel', 'bandouliere-moyen', 'sacs-a-main', 2, 'de'),
('bandouliere-matelasse', 'Gesteppten Schultertaschen', 'bandouliere-matelasse', 'sacs-a-main', 2, 'de'),
('bandouliere-sport', 'Sport-Schultertaschen', 'bandouliere-sport', 'sacs-a-main', 2, 'de'),
('sacs-seau', 'Beuteltaschen', 'sacs-seau', 'sacs-a-main', 2, 'de'),
('sacs-tote', 'Tote Bags', 'sacs-tote', 'sacs-a-main', 2, 'de'),
('sacs-hobo', 'Hobo-Taschen', 'sacs-hobo', 'sacs-a-main', 2, 'de'),
('sacs-bowling', 'Bowling-Taschen', 'sacs-bowling', 'sacs-a-main', 2, 'de'),
('pochettes-soiree', 'Abendclutches', 'pochettes-soiree', 'sacs-a-main', 2, 'de'),
('pochettes-mariage', 'Hochzeitsclutches', 'pochettes-mariage', 'sacs-a-main', 2, 'de'),
('pochettes-minimalistes', 'Minimalistische Clutches', 'pochettes-minimalistes', 'sacs-a-main', 2, 'de'),
('mini-bags-ville', 'City Mini-Bags', 'mini-bags-ville', 'sacs-a-main', 2, 'de'),
('mini-bags-luxe', 'Luxus Mini-Bags', 'mini-bags-luxe', 'sacs-a-main', 2, 'de'),
('sacs-demi-lune', 'Halbmond-Taschen', 'sacs-demi-lune', 'sacs-a-main', 2, 'de'),
('sacs-en-cuir-veritable', 'Taschen aus Echtleder', 'sacs-en-cuir-veritable', 'sacs-a-main', 2, 'de'),
('sacs-en-cuir-synthetique', 'Taschen aus Kunstleder', 'sacs-en-cuir-synthetique', 'sacs-a-main', 2, 'de'),
('sacs-en-cuir-artisanal', 'Handgefertigte Ledertaschen', 'sacs-en-cuir-artisanal', 'sacs-a-main', 2, 'de'),
('sacs-en-toile-tissu', 'Canvas- & Stofftaschen', 'sacs-en-toile-tissu', 'sacs-a-main', 2, 'de'),
('urbains', 'Urbane Rucksäcke', 'urbains', 'sacs-a-dos', 2, 'de'),
('antivol', 'Anti-Diebstahl-Rucksäcke', 'antivol', 'sacs-a-dos', 2, 'de'),
('business-porte-pc', 'Business-Rucksäcke (Laptop)', 'business-porte-pc', 'sacs-a-dos', 2, 'de'),
('sport', 'Sport-Rucksäcke', 'sport', 'sacs-a-dos', 2, 'de'),
('randonnee-20l', 'Wandern & Trekking 20L', 'randonnee-20l', 'sacs-a-dos', 2, 'de'),
('randonnee-30l', 'Wandern & Trekking 30L', 'randonnee-30l', 'sacs-a-dos', 2, 'de'),
('randonnee-50l-plus', 'Wandern & Trekking 50L+', 'randonnee-50l-plus', 'sacs-a-dos', 2, 'de'),
('tactiques-militaires', 'Taktische & Militär', 'tactiques-militaires', 'sacs-a-dos', 2, 'de'),
('scolaires-enfant-ado', 'Schulrucksäcke (Kinder/Teenager)', 'scolaires-enfant-ado', 'sacs-a-dos', 2, 'de'),
('minimalistes', 'Minimalistische Rucksäcke', 'minimalistes', 'sacs-a-dos', 2, 'de'),
('voyage-cabine', 'Reise-Rucksäcke (Handgepäck)', 'voyage-cabine', 'sacs-a-dos', 2, 'de'),
('voyage-souples', 'Weiche Reisetaschen', 'voyage-souples', 'sacs-voyage-week-end', 2, 'de'),
('voyage-semi-rigides', 'Halbharte Reisetaschen', 'voyage-semi-rigides', 'sacs-voyage-week-end', 2, 'de'),
('duffle-bags', 'Duffle Bags', 'duffle-bags', 'sacs-voyage-week-end', 2, 'de'),
('polochon', 'Seesäcke', 'polochon', 'sacs-voyage-week-end', 2, 'de'),
('week-end', 'Weekender-Taschen', 'week-end', 'sacs-voyage-week-end', 2, 'de'),
('pliables', 'Faltbare Taschen', 'pliables', 'sacs-voyage-week-end', 2, 'de'),
('transport-longue-distance', 'Langstrecken-Transporttaschen', 'transport-longue-distance', 'sacs-voyage-week-end', 2, 'de'),
('multi-poches', 'Mehrfachtaschen', 'multi-poches', 'sacs-voyage-week-end', 2, 'de'),
('compartiment-chaussures', 'Taschen mit Schuhfach', 'compartiment-chaussures', 'sacs-voyage-week-end', 2, 'de'),
('cabine-rigides', 'Handgepäckkoffer (hart)', 'cabine-rigides', 'valises-bagages', 2, 'de'),
('cabine-souples', 'Handgepäckkoffer (weich)', 'cabine-souples', 'valises-bagages', 2, 'de'),
('cabine-extensibles', 'Erweiterbare Handgepäckkoffer', 'cabine-extensibles', 'valises-bagages', 2, 'de'),
('valises-medium', 'Mittlere Koffer', 'valises-medium', 'valises-bagages', 2, 'de'),
('valises-grandes', 'Große Koffer', 'valises-grandes', 'valises-bagages', 2, 'de'),
('valises-aluminium', 'Aluminiumkoffer', 'valises-aluminium', 'valises-bagages', 2, 'de'),
('sets-valises', 'Kofferset', 'sets-valises', 'valises-bagages', 2, 'de'),
('valises-enfants', 'Kinderkoffer', 'valises-enfants', 'valises-bagages', 2, 'de'),
('valises-connectees', 'Smarte Koffer', 'valises-connectees', 'valises-bagages', 2, 'de'),
('valises-professionnelles', 'Berufskoffer', 'valises-professionnelles', 'valises-bagages', 2, 'de'),
('bagages-certifies-iata', 'IATA-zertifiziertes Gepäck', 'bagages-certifies-iata', 'valises-bagages', 2, 'de'),
('valises-securisees-tsa', 'TSA-sichere Koffer', 'valises-securisees-tsa', 'valises-bagages', 2, 'de'),
('portefeuilles-zippe', 'Geldbörsen mit Reißverschluss', 'portefeuilles-zippe', 'maroquinerie', 2, 'de'),
('portefeuilles-pliable', 'Faltbare Geldbörsen', 'portefeuilles-pliable', 'maroquinerie', 2, 'de'),
('portefeuilles-compact', 'Kompakte Geldbörsen', 'portefeuilles-compact', 'maroquinerie', 2, 'de');

-- Level 3 - Hauptkategorien für Reisegepäck (German)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('valises-souples', 'Weiche Koffer', 'valises-souples', 'valises-bagages', 3, 'de'),
('valises-rigides', 'Harte Koffer', 'valises-rigides', 'valises-bagages', 3, 'de'),
('cabines-bagages', 'Kabinengepäck', 'cabines-bagages', 'valises-bagages', 3, 'de'),
('sacs-de-voyage-roulants', 'Rollende Reisetaschen', 'sacs-de-voyage-roulants', 'sacs-voyage-week-end', 3, 'de'),
('sacs-de-sport-voyage', 'Reisesporttaschen', 'sacs-de-sport-voyage', 'sacs-voyage-week-end', 3, 'de'),
('trousses-de-toilette', 'Toilettetaschen', 'trousses-de-toilette', 'sacs-voyage-week-end', 3, 'de'),
('housses-bagages', 'Gepäckhüllen', 'housses-bagages', 'valises-bagages', 3, 'de'),
('etiquettes-bagages', 'Gepäckanhänger', 'etiquettes-bagages', 'valises-bagages', 3, 'de'),
('cadenas-bagages', 'Gepäckschlösser', 'cadenas-bagages', 'valises-bagages', 3, 'de');

-- Italian
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('sacs-et-bagages', 'Borse & Bagagli', 'sacs-et-bagages', NULL, 0, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('sacs-a-main', 'Borse a mano (donna & unisex)', 'sacs-a-main', 'sacs-et-bagages', 1, 'it'),
('sacs-a-dos', 'Zaini', 'sacs-a-dos', 'sacs-et-bagages', 1, 'it'),
('sacs-voyage-week-end', 'Borse da viaggio & weekend', 'sacs-voyage-week-end', 'sacs-et-bagages', 1, 'it'),
('valises-bagages', 'Valigie & bagagli', 'valises-bagages', 'sacs-et-bagages', 1, 'it'),
('maroquinerie', 'Pelletteria', 'maroquinerie', 'sacs-et-bagages', 1, 'it');
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('cabas-grand', 'Shopper grande', 'cabas-grand', 'sacs-a-main', 2, 'it'),
('cabas-moyen', 'Shopper medio', 'cabas-moyen', 'sacs-a-main', 2, 'it'),
('cabas-rigide', 'Shopper rigido', 'cabas-rigide', 'sacs-a-main', 2, 'it'),
('cabas-souple', 'Shopper morbido', 'cabas-souple', 'sacs-a-main', 2, 'it'),
('bandouliere-mini', 'Borse a tracolla mini', 'bandouliere-mini', 'sacs-a-main', 2, 'it'),
('bandouliere-moyen', 'Borse a tracolla medie', 'bandouliere-moyen', 'sacs-a-main', 2, 'it'),
('bandouliere-matelasse', 'Borse a tracolla trapuntate', 'bandouliere-matelasse', 'sacs-a-main', 2, 'it'),
('bandouliere-sport', 'Borse a tracolla sportive', 'bandouliere-sport', 'sacs-a-main', 2, 'it'),
('sacs-seau', 'Borse secchiello', 'sacs-seau', 'sacs-a-main', 2, 'it'),
('sacs-tote', 'Borse tote', 'sacs-tote', 'sacs-a-main', 2, 'it'),
('sacs-hobo', 'Borse hobo', 'sacs-hobo', 'sacs-a-main', 2, 'it'),
('sacs-bowling', 'Borse bowling', 'sacs-bowling', 'sacs-a-main', 2, 'it'),
('pochettes-soiree', 'Clutch da sera', 'pochettes-soiree', 'sacs-a-main', 2, 'it'),
('pochettes-mariage', 'Clutch da matrimonio', 'pochettes-mariage', 'sacs-a-main', 2, 'it'),
('pochettes-minimalistes', 'Clutch minimaliste', 'pochettes-minimalistes', 'sacs-a-main', 2, 'it'),
('mini-bags-ville', 'Mini borse cittadine', 'mini-bags-ville', 'sacs-a-main', 2, 'it'),
('mini-bags-luxe', 'Mini borse di lusso', 'mini-bags-luxe', 'sacs-a-main', 2, 'it'),
('sacs-demi-lune', 'Borse mezzaluna', 'sacs-demi-lune', 'sacs-a-main', 2, 'it'),
('sacs-en-cuir-veritable', 'Borse in vera pelle', 'sacs-en-cuir-veritable', 'sacs-a-main', 2, 'it'),
('sacs-en-cuir-synthetique', 'Borse in pelle sintetica', 'sacs-en-cuir-synthetique', 'sacs-a-main', 2, 'it'),
('sacs-en-cuir-artisanal', 'Borse in pelle artigianale', 'sacs-en-cuir-artisanal', 'sacs-a-main', 2, 'it'),
('sacs-en-toile-tissu', 'Borse in tela e tessuto', 'sacs-en-toile-tissu', 'sacs-a-main', 2, 'it'),
('urbains', 'Zaini urbani', 'urbains', 'sacs-a-dos', 2, 'it'),
('antivol', 'Zaini antifurto', 'antivol', 'sacs-a-dos', 2, 'it'),
('business-porte-pc', 'Zaini business (per laptop)', 'business-porte-pc', 'sacs-a-dos', 2, 'it'),
('sport', 'Zaini sportivi', 'sport', 'sacs-a-dos', 2, 'it'),
('randonnee-20l', 'Escursionismo & trekking 20L', 'randonnee-20l', 'sacs-a-dos', 2, 'it'),
('randonnee-30l', 'Escursionismo & trekking 30L', 'randonnee-30l', 'sacs-a-dos', 2, 'it'),
('randonnee-50l-plus', 'Escursionismo & trekking 50L+', 'randonnee-50l-plus', 'sacs-a-dos', 2, 'it'),
('tactiques-militaires', 'Zaini tattici e militari', 'tactiques-militaires', 'sacs-a-dos', 2, 'it'),
('scolaires-enfant-ado', 'Zaini scolastici (bambini/adolescenti)', 'scolaires-enfant-ado', 'sacs-a-dos', 2, 'it'),
('minimalistes', 'Zaini minimalisti', 'minimalistes', 'sacs-a-dos', 2, 'it'),
('voyage-cabine', 'Zaini da viaggio cabina', 'voyage-cabine', 'sacs-a-dos', 2, 'it'),
('voyage-souples', 'Borse da viaggio morbide', 'voyage-souples', 'sacs-voyage-week-end', 2, 'it'),
('voyage-semi-rigides', 'Borse da viaggio semirigide', 'voyage-semi-rigides', 'sacs-voyage-week-end', 2, 'it'),
('duffle-bags', 'Borse duffle', 'duffle-bags', 'sacs-voyage-week-end', 2, 'it'),
('polochon', 'Borse a barile', 'polochon', 'sacs-voyage-week-end', 2, 'it'),
('week-end', 'Borse weekend', 'week-end', 'sacs-voyage-week-end', 2, 'it'),
('pliables', 'Borse pieghevoli', 'pliables', 'sacs-voyage-week-end', 2, 'it'),
('transport-longue-distance', 'Borse per trasporto a lunga distanza', 'transport-longue-distance', 'sacs-voyage-week-end', 2, 'it'),
('multi-poches', 'Borse multi-tasche', 'multi-poches', 'sacs-voyage-week-end', 2, 'it'),
('compartiment-chaussures', 'Borse con scomparto scarpe', 'compartiment-chaussures', 'sacs-voyage-week-end', 2, 'it'),
('cabine-rigides', 'Valigie da cabina rigide', 'cabine-rigides', 'valises-bagages', 2, 'it'),
('cabine-souples', 'Valigie da cabina morbide', 'cabine-souples', 'valises-bagages', 2, 'it'),
('cabine-extensibles', 'Valigie da cabina espandibili', 'cabine-extensibles', 'valises-bagages', 2, 'it'),
('valises-medium', 'Valigie medie', 'valises-medium', 'valises-bagages', 2, 'it'),
('valises-grandes', 'Valigie grandi', 'valises-grandes', 'valises-bagages', 2, 'it'),
('valises-aluminium', 'Valigie in alluminio', 'valises-aluminium', 'valises-bagages', 2, 'it'),
('sets-valises', 'Set di valigie', 'sets-valises', 'valises-bagages', 2, 'it'),
('valises-enfants', 'Valigie per bambini', 'valises-enfants', 'valises-bagages', 2, 'it'),
('valises-connectees', 'Valigie smart', 'valises-connectees', 'valises-bagages', 2, 'it'),
('valises-professionnelles', 'Valigie professionali', 'valises-professionnelles', 'valises-bagages', 2, 'it'),
('bagages-certifies-iata', 'Bagagli certificati IATA', 'bagages-certifies-iata', 'valises-bagages', 2, 'it'),
('valises-securisees-tsa', 'Valigie con sicurezza TSA', 'valises-securisees-tsa', 'valises-bagages', 2, 'it'),
('portefeuilles-zippe', 'Portafogli con cerniera', 'portefeuilles-zippe', 'maroquinerie', 2, 'it'),
('portefeuilles-pliable', 'Portafogli pieghevoli', 'portefeuilles-pliable', 'maroquinerie', 2, 'it'),
('portefeuilles-compact', 'Portafogli compatti', 'portefeuilles-compact', 'maroquinerie', 2, 'it');

-- Level 3 - Categorie principali per Bagagli da Viaggio (Italian)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('valises-souples', 'Valigie morbide', 'valises-souples', 'valises-bagages', 3, 'it'),
('valises-rigides', 'Valigie rigide', 'valises-rigides', 'valises-bagages', 3, 'it'),
('cabines-bagages', 'Bagagli a mano', 'cabines-bagages', 'valises-bagages', 3, 'it'),
('sacs-de-voyage-roulants', 'Borse da viaggio con rotelle', 'sacs-de-voyage-roulants', 'sacs-voyage-week-end', 3, 'it'),
('sacs-de-sport-voyage', 'Borse sportive da viaggio', 'sacs-de-sport-voyage', 'sacs-voyage-week-end', 3, 'it'),
('trousses-de-toilette', 'Necessari da viaggio', 'trousses-de-toilette', 'sacs-voyage-week-end', 3, 'it'),
('housses-bagages', 'Coperture per bagagli', 'housses-bagages', 'valises-bagages', 3, 'it'),
('etiquettes-bagages', 'Etichette per bagagli', 'etiquettes-bagages', 'valises-bagages', 3, 'it'),
('cadenas-bagages', 'Lucchetti per bagagli', 'cadenas-bagages', 'valises-bagages', 3, 'it');

*** End Patch