-- Migration pour la catégorie: Vêtement Homme, Femme & sous-vêtement
-- Toutes les langues: fr/ar/es/de/en/it

-- FRENCH
-- Level 0
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('mode-accessoires', 'Vêtement Homme, Femme & sous-vêtement', 'mode-accessoires', NULL, 0, 'fr');

-- Level 1
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('vetements-homme', 'Vêtements Homme', 'vetements-homme', 'mode-accessoires', 1, 'fr'),
('marques-vetements-homme', 'Marques vêtements homme', 'marques-vetements-homme', 'mode-accessoires', 1, 'fr'),
('accessoires-homme', 'Accessoires Homme', 'accessoires-homme', 'mode-accessoires', 1, 'fr'),
('vetements-femme', 'Vêtements Femme', 'vetements-femme', 'mode-accessoires', 1, 'fr'),
('marques-vetements-femme', 'Marques vêtements femme', 'marques-vetements-femme', 'mode-accessoires', 1, 'fr'),
('accessoires-femme', 'Accessoires Femme', 'accessoires-femme', 'mode-accessoires', 1, 'fr'),
('sous-vetements-homme', 'Sous-vêtements Homme', 'sous-vetements-homme', 'mode-accessoires', 1, 'fr'),
('lingerie-femme', 'Lingerie Femme', 'lingerie-femme', 'mode-accessoires', 1, 'fr'),
('nuit-interieur', 'Nuit & Intérieur', 'nuit-interieur', 'mode-accessoires', 1, 'fr'),
('sous-vetements-techniques', 'Sous-vêtements techniques', 'sous-vetements-techniques', 'mode-accessoires', 1, 'fr'),
('chaussures-homme-femme', 'Chaussures (Homme & Femme)', 'chaussures-homme-femme', 'mode-accessoires', 1, 'fr');

-- Level 2
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('t-shirts', 'T-shirts', 't-shirts', 'vetements-homme', 2, 'fr'),
('polos', 'Polos', 'polos', 'vetements-homme', 2, 'fr'),
('chemises', 'Chemises', 'chemises', 'vetements-homme', 2, 'fr'),
('pulls-gilets', 'Pulls & Gilets', 'pulls-gilets', 'vetements-homme', 2, 'fr'),
('sweats-hoodies', 'Sweats & Hoodies', 'sweats-hoodies', 'vetements-homme', 2, 'fr'),
('debardeurs', 'Débardeurs', 'debardeurs', 'vetements-homme', 2, 'fr'),
('jeans', 'Jeans', 'jeans', 'vetements-homme', 2, 'fr'),
('pantalons', 'Pantalons', 'pantalons', 'vetements-homme', 2, 'fr'),
('shorts', 'Shorts', 'shorts', 'vetements-homme', 2, 'fr'),
('survetements', 'Survêtements', 'survetements', 'vetements-homme', 2, 'fr'),
('vestes-legeres', 'Vestes légères', 'vestes-legeres', 'vetements-homme', 2, 'fr'),
('blousons', 'Blousons', 'blousons', 'vetements-homme', 2, 'fr'),
('manteaux', 'Manteaux', 'manteaux', 'vetements-homme', 2, 'fr'),
('parkas-coupe-vent', 'Parkas & Coupe-vent', 'parkas-coupe-vent', 'vetements-homme', 2, 'fr'),
('vestes-de-travail', 'Vestes de travail', 'vestes-de-travail', 'vetements-homme', 2, 'fr'),
('costumes-smokings', 'Costumes & Smokings', 'costumes-smokings', 'vetements-homme', 2, 'fr'),
('tenues-business', 'Tenues business', 'tenues-business', 'vetements-homme', 2, 'fr'),
('mode-urbaine', 'Mode urbaine', 'mode-urbaine', 'vetements-homme', 2, 'fr'),
('sportwear', 'Sportwear', 'sportwear', 'vetements-homme', 2, 'fr'),
('tenues-outdoor', 'Tenues outdoor', 'tenues-outdoor', 'vetements-homme', 2, 'fr'),
('vetements-traditionnels-homme', 'Vêtements traditionnels homme', 'vetements-traditionnels-homme', 'vetements-homme', 2, 'fr'),
('ceintures', 'Ceintures', 'ceintures', 'accessoires-homme', 2, 'fr'),
('cravates-noeuds-papillon', 'Cravates & Noeuds papillon', 'cravates-noeuds-papillon', 'accessoires-homme', 2, 'fr'),
('chapeaux-casquettes', 'Chapeaux & Casquettes', 'chapeaux-casquettes', 'accessoires-homme', 2, 'fr'),
('gants-echarpes', 'Gants & Echarpes', 'gants-echarpes', 'accessoires-homme', 2, 'fr'),
('lunettes-soleil', 'Lunettes de soleil', 'lunettes-soleil', 'accessoires-homme', 2, 'fr'),
('montres', 'Montres', 'montres', 'accessoires-homme', 2, 'fr'),
('bijoux-homme', 'Bijoux homme', 'bijoux-homme', 'accessoires-homme', 2, 'fr'),
('portefeuilles', 'Portefeuilles', 'portefeuilles', 'accessoires-homme', 2, 'fr'),
('porte-cartes', 'Porte-cartes', 'porte-cartes', 'accessoires-homme', 2, 'fr'),
('sacoches-besaces', 'Sacoches & Besaces', 'sacoches-besaces', 'accessoires-homme', 2, 'fr'),
('tops-t-shirts', 'Tops & T-shirts', 'tops-t-shirts', 'vetements-femme', 2, 'fr'),
('chemisiers-blouses', 'Chemisiers & Blouses', 'chemisiers-blouses', 'vetements-femme', 2, 'fr'),
('pulls-gilets-femme', 'Pulls & Gilets femme', 'pulls-gilets-femme', 'vetements-femme', 2, 'fr'),
('sweats-hoodies-femme', 'Sweats & Hoodies femme', 'sweats-hoodies-femme', 'vetements-femme', 2, 'fr'),
('debardeurs-bustiers', 'Débardeurs & Bustiers', 'debardeurs-bustiers', 'vetements-femme', 2, 'fr'),
('robes', 'Robes', 'robes', 'vetements-femme', 2, 'fr'),
('robes-evenements', 'Robes événements', 'robes-evenements', 'vetements-femme', 2, 'fr'),
('jupes', 'Jupes', 'jupes', 'vetements-femme', 2, 'fr'),
('jeans-femme', 'Jeans femme', 'jeans-femme', 'vetements-femme', 2, 'fr'),
('pantalons-femme', 'Pantalons femme', 'pantalons-femme', 'vetements-femme', 2, 'fr'),
('collants-leggings-thermiques', 'Collants & Leggings thermiques', 'collants-leggings-thermiques', 'vetements-femme', 2, 'fr'),
('vestes-femme', 'Vestes femme', 'vestes-femme', 'vetements-femme', 2, 'fr'),
('blousons-femme', 'Blousons femme', 'blousons-femme', 'vetements-femme', 2, 'fr'),
('manteaux-femme', 'Manteaux femme', 'manteaux-femme', 'vetements-femme', 2, 'fr'),
('doudounes-femme', 'Doudounes femme', 'doudounes-femme', 'vetements-femme', 2, 'fr'),
('capes-ponchos', 'Capes & Ponchos', 'capes-ponchos', 'vetements-femme', 2, 'fr'),
('mode-chic', 'Mode chic', 'mode-chic', 'vetements-femme', 2, 'fr'),
('mode-streetwear', 'Mode streetwear', 'mode-streetwear', 'vetements-femme', 2, 'fr'),
('sportwear-femme', 'Sportwear femme', 'sportwear-femme', 'vetements-femme', 2, 'fr'),
('beachwear', 'Beachwear', 'beachwear', 'vetements-femme', 2, 'fr'),
('mode-traditionnelle-femme', 'Mode traditionnelle femme', 'mode-traditionnelle-femme', 'vetements-femme', 2, 'fr'),
('sacs-main', 'Sacs main', 'sacs-main', 'accessoires-femme', 2, 'fr'),
('sacs-bandouliere', 'Sacs bandoulière', 'sacs-bandouliere', 'accessoires-femme', 2, 'fr'),
('pochettes', 'Pochettes', 'pochettes', 'accessoires-femme', 2, 'fr'),
('porte-monnaie', 'Porte-monnaie', 'porte-monnaie', 'accessoires-femme', 2, 'fr'),
('bijoux', 'Bijoux', 'bijoux', 'accessoires-femme', 2, 'fr'),
('ceintures', 'Ceintures', 'ceintures', 'accessoires-femme', 2, 'fr'),
('foulards-echarpes', 'Foulards & Echarpes', 'foulards-echarpes', 'accessoires-femme', 2, 'fr'),
('accessoires-cheveux', 'Accessoires cheveux', 'accessoires-cheveux', 'accessoires-femme', 2, 'fr'),
('lunettes-soleil-femme', 'Lunettes de soleil femme', 'lunettes-soleil-femme', 'accessoires-femme', 2, 'fr'),
('montres-femme', 'Montres femme', 'montres-femme', 'accessoires-femme', 2, 'fr'),
('boxers', 'Boxers', 'boxers', 'sous-vetements-homme', 2, 'fr'),
('slips', 'Slips', 'slips', 'sous-vetements-homme', 2, 'fr'),
('calecons', 'Caleçons', 'calecons', 'sous-vetements-homme', 2, 'fr'),
('debardeurs-sous-maillots-thermiques', 'Débardeurs & Sous-maillots thermiques', 'debardeurs-sous-maillots-thermiques', 'sous-vetements-homme', 2, 'fr'),
('soutiens-gorge', 'Soutiens-gorge', 'soutiens-gorge', 'lingerie-femme', 2, 'fr'),
('culottes', 'Culottes', 'culottes', 'lingerie-femme', 2, 'fr'),
('ensembles-lingerie', 'Ensembles lingerie', 'ensembles-lingerie', 'lingerie-femme', 2, 'fr'),
('body-combinaisons', 'Body & Combinaisons', 'body-combinaisons', 'lingerie-femme', 2, 'fr'),
('guepieres', 'Guêpières', 'guepieres', 'lingerie-femme', 2, 'fr'),
('lingerie-sculptante', 'Lingerie sculptante', 'lingerie-sculptante', 'lingerie-femme', 2, 'fr'),
('lingerie-sexy-dentelle', 'Lingerie sexy & dentelle', 'lingerie-sexy-dentelle', 'lingerie-femme', 2, 'fr'),
('pyjamas-homme-femme', 'Pyjamas homme & femme', 'pyjamas-homme-femme', 'nuit-interieur', 2, 'fr'),
('nuisettes', 'Nuisettes', 'nuisettes', 'nuit-interieur', 2, 'fr'),
('deshabilles', 'Déshabillés', 'deshabilles', 'nuit-interieur', 2, 'fr'),
('peignoirs', 'Peignoirs', 'peignoirs', 'nuit-interieur', 2, 'fr'),
('robes-de-chambre', 'Robes de chambre', 'robes-de-chambre', 'nuit-interieur', 2, 'fr'),
('homewear', 'Homewear', 'homewear', 'nuit-interieur', 2, 'fr'),
('sous-vetements-thermiques', 'Sous-vêtements thermiques', 'sous-vetements-thermiques', 'sous-vetements-techniques', 2, 'fr'),
('sous-couches-sport', 'Sous-couches sport', 'sous-couches-sport', 'sous-vetements-techniques', 2, 'fr'),
('chaussettes-techniques-compression', 'Chaussettes techniques & compression', 'chaussettes-techniques-compression', 'sous-vetements-techniques', 2, 'fr'),
('chaussures-habillees', 'Chaussures habillées', 'chaussures-habillees', 'chaussures-homme-femme', 2, 'fr'),
('mocassins', 'Mocassins', 'mocassins', 'chaussures-homme-femme', 2, 'fr'),
('chaussures-de-ville', 'Chaussures de ville', 'chaussures-de-ville', 'chaussures-homme-femme', 2, 'fr'),
('baskets', 'Baskets', 'baskets', 'chaussures-homme-femme', 2, 'fr');

-- Level 3
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('basiques', 'Basiques', 'basiques', 't-shirts', 3, 'fr'),
('imprimes', 'Imprimés', 'imprimes', 't-shirts', 3, 'fr'),
('oversize', 'Oversize', 'oversize', 't-shirts', 3, 'fr'),
('techniques', 'Techniques', 'techniques', 't-shirts', 3, 'fr'),
('manches-courtes', 'Manches courtes', 'manches-courtes', 'polos', 3, 'fr'),
('manches-longues', 'Manches longues', 'manches-longues', 'polos', 3, 'fr'),
('sport', 'Sport', 'sport', 'polos', 3, 'fr'),
('classiques', 'Classiques', 'classiques', 'chemises', 3, 'fr'),
('slim', 'Slim', 'slim', 'chemises', 3, 'fr'),
('decontractees', 'Décontractées', 'decontractees', 'chemises', 3, 'fr'),
('carreaux', 'Carreaux', 'carreaux', 'chemises', 3, 'fr'),
('denim', 'Denim', 'denim', 'chemises', 3, 'fr'),
('habillees', 'Habillées', 'habillees', 'chemises', 3, 'fr'),
('maille-fine', 'Maille fine', 'maille-fine', 'pulls-gilets', 3, 'fr'),
('laine', 'Laine', 'laine', 'pulls-gilets', 3, 'fr'),
('col-rond', 'Col rond', 'col-rond', 'pulls-gilets', 3, 'fr'),
('col-v', 'Col V', 'col-v', 'pulls-gilets', 3, 'fr'),
('col-roule', 'Col roulé', 'col-roule', 'pulls-gilets', 3, 'fr'),
('cardigan', 'Cardigan', 'cardigan', 'pulls-gilets', 3, 'fr'),
('a-capuche', 'À capuche', 'a-capuche', 'sweats-hoodies', 3, 'fr'),
('zippes', 'Zippés', 'zippes', 'sweats-hoodies', 3, 'fr'),
('oversize', 'Oversize', 'oversize', 'sweats-hoodies', 3, 'fr'),
('sportifs', 'Sportifs', 'sportifs', 'sweats-hoodies', 3, 'fr'),
('slim', 'Slim', 'slim', 'jeans', 3, 'fr'),
('straight', 'Straight', 'straight', 'jeans', 3, 'fr'),
('tapered', 'Tapered', 'tapered', 'jeans', 3, 'fr'),
('skinny', 'Skinny', 'skinny', 'jeans', 3, 'fr'),
('bootcut', 'Bootcut', 'bootcut', 'jeans', 3, 'fr'),
('chino', 'Chino', 'chino', 'pantalons', 3, 'fr'),
('costume', 'Costume', 'costume', 'pantalons', 3, 'fr'),
('cargo', 'Cargo', 'cargo', 'pantalons', 3, 'fr'),
('jogging', 'Jogging', 'jogging', 'pantalons', 3, 'fr'),
('urbain', 'Urbain', 'urbain', 'pantalons', 3, 'fr'),
('jeans', 'Jeans', 'jeans', 'shorts', 3, 'fr'),
('sport', 'Sport', 'sport', 'shorts', 3, 'fr'),
('cargo', 'Cargo', 'cargo', 'shorts', 3, 'fr'),
('bermudas', 'Bermudas', 'bermudas', 'shorts', 3, 'fr'),
('jean', 'Jean', 'jean', 'vestes-legeres', 3, 'fr'),
('cuir', 'Cuir', 'cuir', 'vestes-legeres', 3, 'fr'),
('bomber', 'Bomber', 'bomber', 'vestes-legeres', 3, 'fr'),
('harrington', 'Harrington', 'harrington', 'vestes-legeres', 3, 'fr'),
('teddy', 'Teddy', 'teddy', 'blousons', 3, 'fr'),
('pilote', 'Pilote', 'pilote', 'blousons', 3, 'fr'),
('laine', 'Laine', 'laine', 'manteaux', 3, 'fr'),
('trench', 'Trench', 'trench', 'manteaux', 3, 'fr'),
('pardessus', 'Pardessus', 'pardessus', 'manteaux', 3, 'fr'),
('doudounes', 'Doudounes', 'doudounes', 'manteaux', 3, 'fr'),
('gandoura', 'Gandoura', 'gandoura', 'vetements-traditionnels-homme', 3, 'fr'),
('qamis', 'Qamis', 'qamis', 'vetements-traditionnels-homme', 3, 'fr'),
('basique', 'Basique', 'basique', 'tops-t-shirts', 3, 'fr'),
('crop-top', 'Crop top', 'crop-top', 'tops-t-shirts', 3, 'fr'),
('dentelle', 'Dentelle', 'dentelle', 'tops-t-shirts', 3, 'fr'),
('habilles', 'Habillées', 'habilles', 'chemisiers-blouses', 3, 'fr'),
('satin', 'Satin', 'satin', 'chemisiers-blouses', 3, 'fr'),
('oversize', 'Oversize', 'oversize', 'chemisiers-blouses', 3, 'fr'),
('fleuris', 'Fleuris', 'fleuris', 'chemisiers-blouses', 3, 'fr'),
('gros-tricot', 'Gros tricot', 'gros-tricot', 'pulls-gilets-femme', 3, 'fr'),
('cardigan', 'Cardigan', 'cardigan', 'pulls-gilets-femme', 3, 'fr'),
('col-roule', 'Col roulé', 'col-roule', 'pulls-gilets-femme', 3, 'fr'),
('unis', 'Unis', 'unis', 'sweats-hoodies-femme', 3, 'fr'),
('imprimes', 'Imprimés', 'imprimes', 'sweats-hoodies-femme', 3, 'fr'),
('oversize', 'Oversize', 'oversize', 'sweats-hoodies-femme', 3, 'fr'),
('courtes', 'Courtes', 'courtes', 'robes', 3, 'fr'),
('midi', 'Midi', 'midi', 'robes', 3, 'fr'),
('longues', 'Longues', 'longues', 'robes', 3, 'fr'),
('soiree', 'Soirée', 'soiree', 'robes', 3, 'fr'),
('cocktail', 'Cocktail', 'cocktail', 'robes', 3, 'fr'),
('moulantes', 'Moulantes', 'moulantes', 'robes', 3, 'fr'),
('mariage', 'Mariage', 'mariage', 'robes-evenements', 3, 'fr'),
('fetes', 'Fêtes', 'fetes', 'robes-evenements', 3, 'fr'),
('courtes', 'Courtes', 'courtes', 'jupes', 3, 'fr'),
('plissees', 'Plissées', 'plissees', 'jupes', 3, 'fr'),
('jeans', 'Jeans', 'jeans', 'jupes', 3, 'fr'),
('crayon', 'Crayon', 'crayon', 'jupes', 3, 'fr'),
('longues', 'Longues', 'longues', 'jupes', 3, 'fr'),
('slim', 'Slim', 'slim', 'jeans-femme', 3, 'fr'),
('mom', 'Mom', 'mom', 'jeans-femme', 3, 'fr'),
('flare', 'Flare', 'flare', 'jeans-femme', 3, 'fr'),
('boyfriend', 'Boyfriend', 'boyfriend', 'jeans-femme', 3, 'fr'),
('skinny', 'Skinny', 'skinny', 'jeans-femme', 3, 'fr'),
('tailleur', 'Tailleur', 'tailleur', 'pantalons-femme', 3, 'fr'),
('palazzo', 'Palazzo', 'palazzo', 'pantalons-femme', 3, 'fr'),
('cargo', 'Cargo', 'cargo', 'pantalons-femme', 3, 'fr'),
('legging', 'Legging', 'legging', 'pantalons-femme', 3, 'fr'),
('jogging', 'Jogging', 'jogging', 'pantalons-femme', 3, 'fr'),
('blazer', 'Blazer', 'blazer', 'vestes-femme', 3, 'fr'),
('cuir', 'Cuir', 'cuir', 'vestes-femme', 3, 'fr'),
('denim', 'Denim', 'denim', 'vestes-femme', 3, 'fr'),
('biker', 'Biker', 'biker', 'blousons-femme', 3, 'fr'),
('bomber', 'Bomber', 'bomber', 'blousons-femme', 3, 'fr'),
('laine', 'Laine', 'laine', 'manteaux-femme', 3, 'fr'),
('trench', 'Trench', 'trench', 'manteaux-femme', 3, 'fr'),
('oversize', 'Oversize', 'oversize', 'manteaux-femme', 3, 'fr'),
('yoga', 'Yoga', 'yoga', 'sportwear-femme', 3, 'fr'),
('running', 'Running', 'running', 'sportwear-femme', 3, 'fr'),
('fitness', 'Fitness', 'fitness', 'sportwear-femme', 3, 'fr'),
('abaya', 'Abaya', 'abaya', 'mode-traditionnelle-femme', 3, 'fr'),
('caftan', 'Caftan', 'caftan', 'mode-traditionnelle-femme', 3, 'fr'),
('karakou', 'Karakou', 'karakou', 'mode-traditionnelle-femme', 3, 'fr'),
('coton', 'Coton', 'coton', 'boxers', 3, 'fr'),
('microfibre', 'Microfibre', 'microfibre', 'boxers', 3, 'fr'),
('sport', 'Sport', 'sport', 'boxers', 3, 'fr'),
('classiques', 'Classiques', 'classiques', 'slips', 3, 'fr'),
('taille-haute', 'Taille haute', 'taille-haute', 'slips', 3, 'fr'),
('echancres', 'Échancrés', 'echancres', 'slips', 3, 'fr'),
('push-up', 'Push-up', 'push-up', 'soutiens-gorge', 3, 'fr'),
('maintien', 'Maintien', 'maintien', 'soutiens-gorge', 3, 'fr'),
('balconnet', 'Balconnet', 'balconnet', 'soutiens-gorge', 3, 'fr'),
('sans-armatures', 'Sans armatures', 'sans-armatures', 'soutiens-gorge', 3, 'fr'),
('sport', 'Sport', 'sport', 'soutiens-gorge', 3, 'fr'),
('classiques', 'Classiques', 'classiques', 'culottes', 3, 'fr'),
('tailles-hautes', 'Tailles hautes', 'tailles-hautes', 'culottes', 3, 'fr'),
('tanga', 'Tanga', 'tanga', 'culottes', 3, 'fr'),
('string', 'String', 'string', 'culottes', 3, 'fr'),
('mode', 'Mode', 'mode', 'baskets', 3, 'fr'),
('running', 'Running', 'running', 'baskets', 3, 'fr'),
('training', 'Training', 'training', 'baskets', 3, 'fr');

-- Level 3 - Catégories principales pour Vêtements Homme (manquantes)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('costumes', 'Costumes', 'costumes', 'vetements-homme', 3, 'fr'),
('chemises', 'Chemises', 'chemises', 'vetements-homme', 3, 'fr'),
('pantalons-homme', 'Pantalons', 'pantalons-homme', 'vetements-homme', 3, 'fr'),
('jeans-homme', 'Jeans', 'jeans-homme', 'vetements-homme', 3, 'fr'),
('pulls-gilets-homme', 'Pulls & gilets', 'pulls-gilets-homme', 'vetements-homme', 3, 'fr'),
('vestes-manteaux-homme', 'Vestes & manteaux', 'vestes-manteaux-homme', 'vetements-homme', 3, 'fr'),
('polos', 'Polos', 'polos', 'vetements-homme', 3, 'fr'),
('t-shirts-homme', 'T-shirts', 't-shirts-homme', 'vetements-homme', 3, 'fr'),
('shorts-homme', 'Shorts', 'shorts-homme', 'vetements-homme', 3, 'fr'),
('sous-vetements-homme', 'Sous-vêtements', 'sous-vetements-homme', 'vetements-homme', 3, 'fr');

-- ARABIC
-- Level 0
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('mode-accessoires', 'ملابس رجالية ونسائية وملابس داخلية', 'mode-accessoires', NULL, 0, 'ar');

-- Level 1
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('vetements-homme', 'ملابس رجالية', 'vetements-homme', 'mode-accessoires', 1, 'ar'),
('marques-vetements-homme', 'ماركات ملابس رجالية', 'marques-vetements-homme', 'mode-accessoires', 1, 'ar'),
('accessoires-homme', 'إكسسوارات رجالية', 'accessoires-homme', 'mode-accessoires', 1, 'ar'),
('vetements-femme', 'ملابس نسائية', 'vetements-femme', 'mode-accessoires', 1, 'ar'),
('marques-vetements-femme', 'ماركات ملابس نسائية', 'marques-vetements-femme', 'mode-accessoires', 1, 'ar'),
('accessoires-femme', 'إكسسوارات نسائية', 'accessoires-femme', 'mode-accessoires', 1, 'ar'),
('sous-vetements-homme', 'ملابس داخلية رجالية', 'sous-vetements-homme', 'mode-accessoires', 1, 'ar'),
('lingerie-femme', 'ملابس داخلية نسائية', 'lingerie-femme', 'mode-accessoires', 1, 'ar'),
('nuit-interieur', 'ملابس نوم وداخلية', 'nuit-interieur', 'mode-accessoires', 1, 'ar'),
('sous-vetements-techniques', 'ملابس داخلية تقنية', 'sous-vetements-techniques', 'mode-accessoires', 1, 'ar'),
('chaussures-homme-femme', 'أحذية (رجالية ونسائية)', 'chaussures-homme-femme', 'mode-accessoires', 1, 'ar');

-- Level 2
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('t-shirts', 'تي شيرتات', 't-shirts', 'vetements-homme', 2, 'ar'),
('polos', 'بولو', 'polos', 'vetements-homme', 2, 'ar'),
('chemises', 'قمصان', 'chemises', 'vetements-homme', 2, 'ar'),
('pulls-gilets', 'كنزات وسترات', 'pulls-gilets', 'vetements-homme', 2, 'ar'),
('sweats-hoodies', 'سويت شيرت وهوديز', 'sweats-hoodies', 'vetements-homme', 2, 'ar'),
('debardeurs', 'صديرات', 'debardeurs', 'vetements-homme', 2, 'ar'),
('jeans', 'جينز', 'jeans', 'vetements-homme', 2, 'ar'),
('pantalons', 'بناطيل', 'pantalons', 'vetements-homme', 2, 'ar'),
('shorts', 'شورتات', 'shorts', 'vetements-homme', 2, 'ar'),
('survetements', 'بدل رياضية', 'survetements', 'vetements-homme', 2, 'ar'),
('vestes-legeres', 'سترات خفيفة', 'vestes-legeres', 'vetements-homme', 2, 'ar'),
('blousons', 'بلوزونات', 'blousons', 'vetements-homme', 2, 'ar'),
('manteaux', 'معاطف', 'manteaux', 'vetements-homme', 2, 'ar'),
('parkas-coupe-vent', 'باركا واقية من الرياح', 'parkas-coupe-vent', 'vetements-homme', 2, 'ar'),
('vestes-de-travail', 'سترات عمل', 'vestes-de-travail', 'vetements-homme', 2, 'ar'),
('costumes-smokings', 'بدلات واسموكينج', 'costumes-smokings', 'vetements-homme', 2, 'ar'),
('tenues-business', 'ملابس بيزنس', 'tenues-business', 'vetements-homme', 2, 'ar'),
('mode-urbaine', 'موضة عصرية', 'mode-urbaine', 'vetements-homme', 2, 'ar'),
('sportwear', 'ملابس رياضية', 'sportwear', 'vetements-homme', 2, 'ar'),
('tenues-outdoor', 'ملابس للخارج', 'tenues-outdoor', 'vetements-homme', 2, 'ar'),
('vetements-traditionnels-homme', 'ملابس تقليدية رجالية', 'vetements-traditionnels-homme', 'vetements-homme', 2, 'ar'),
('ceintures', 'أحزمة', 'ceintures', 'accessoires-homme', 2, 'ar'),
('cravates-noeuds-papillon', 'كرافات وربطات عنق', 'cravates-noeuds-papillon', 'accessoires-homme', 2, 'ar'),
('chapeaux-casquettes', 'قبعات وكابات', 'chapeaux-casquettes', 'accessoires-homme', 2, 'ar'),
('gants-echarpes', 'قفازات ووشاحات', 'gants-echarpes', 'accessoires-homme', 2, 'ar'),
('lunettes-soleil', 'نظارات شمسية', 'lunettes-soleil', 'accessoires-homme', 2, 'ar'),
('montres', 'ساعات', 'montres', 'accessoires-homme', 2, 'ar'),
('bijoux-homme', 'مجوهرات رجالية', 'bijoux-homme', 'accessoires-homme', 2, 'ar'),
('portefeuilles', 'محافظ', 'portefeuilles', 'accessoires-homme', 2, 'ar'),
('porte-cartes', 'محافظ بطاقات', 'porte-cartes', 'accessoires-homme', 2, 'ar'),
('sacoches-besaces', 'حقائب كتف', 'sacoches-besaces', 'accessoires-homme', 2, 'ar'),
('tops-t-shirts', 'توب وتي شيرتات', 'tops-t-shirts', 'vetements-femme', 2, 'ar'),
('chemisiers-blouses', 'بلوزات وقميصات', 'chemisiers-blouses', 'vetements-femme', 2, 'ar'),
('pulls-gilets-femme', 'كنزات نسائية', 'pulls-gilets-femme', 'vetements-femme', 2, 'ar'),
('sweats-hoodies-femme', 'سويت شيرت نسائي', 'sweats-hoodies-femme', 'vetements-femme', 2, 'ar'),
('debardeurs-bustiers', 'صديرات وبوستير', 'debardeurs-bustiers', 'vetements-femme', 2, 'ar'),
('robes', 'فساتين', 'robes', 'vetements-femme', 2, 'ar'),
('robes-evenements', 'فساتين مناسبات', 'robes-evenements', 'vetements-femme', 2, 'ar'),
('jupes', 'تنانير', 'jupes', 'vetements-femme', 2, 'ar'),
('jeans-femme', 'جينز نسائي', 'jeans-femme', 'vetements-femme', 2, 'ar'),
('pantalons-femme', 'بناطيل نسائية', 'pantalons-femme', 'vetements-femme', 2, 'ar'),
('collants-leggings-thermiques', 'كولونات وليقنغ حراري', 'collants-leggings-thermiques', 'vetements-femme', 2, 'ar'),
('vestes-femme', 'سترات نسائية', 'vestes-femme', 'vetements-femme', 2, 'ar'),
('blousons-femme', 'بلوزونات نسائية', 'blousons-femme', 'vetements-femme', 2, 'ar'),
('manteaux-femme', 'معاطف نسائية', 'manteaux-femme', 'vetements-femme', 2, 'ar'),
('doudounes-femme', 'بدل نسائية', 'doudounes-femme', 'vetements-femme', 2, 'ar'),
('capes-ponchos', 'كيب وبونشو', 'capes-ponchos', 'vetements-femme', 2, 'ar'),
('mode-chic', 'موضة شيك', 'mode-chic', 'vetements-femme', 2, 'ar'),
('mode-streetwear', 'موضة شارع', 'mode-streetwear', 'vetements-femme', 2, 'ar'),
('sportwear-femme', 'ملابس رياضية نسائية', 'sportwear-femme', 'vetements-femme', 2, 'ar'),
('beachwear', 'ملابس شاطئ', 'beachwear', 'vetements-femme', 2, 'ar'),
('mode-traditionnelle-femme', 'موضة تقليدية نسائية', 'mode-traditionnelle-femme', 'vetements-femme', 2, 'ar'),
('sacs-main', 'حقائب يد', 'sacs-main', 'accessoires-femme', 2, 'ar'),
('sacs-bandouliere', 'حقائب كتف', 'sacs-bandouliere', 'accessoires-femme', 2, 'ar'),
('pochettes', 'بوتشيت', 'pochettes', 'accessoires-femme', 2, 'ar'),
('porte-monnaie', 'محافظ نقود', 'porte-monnaie', 'accessoires-femme', 2, 'ar'),
('bijoux', 'مجوهرات', 'bijoux', 'accessoires-femme', 2, 'ar'),
('ceintures', 'أحزمة', 'ceintures', 'accessoires-femme', 2, 'ar'),
('foulards-echarpes', 'فولار ووشاحات', 'foulards-echarpes', 'accessoires-femme', 2, 'ar'),
('accessoires-cheveux', 'إكسسوارات شعر', 'accessoires-cheveux', 'accessoires-femme', 2, 'ar'),
('lunettes-soleil-femme', 'نظارات شمسية نسائية', 'lunettes-soleil-femme', 'accessoires-femme', 2, 'ar'),
('montres-femme', 'ساعات نسائية', 'montres-femme', 'accessoires-femme', 2, 'ar'),
('boxers', 'بوكسر', 'boxers', 'sous-vetements-homme', 2, 'ar'),
('slips', 'سليب', 'slips', 'sous-vetements-homme', 2, 'ar'),
('calecons', 'كلسون', 'calecons', 'sous-vetements-homme', 2, 'ar'),
('debardeurs-sous-maillots-thermiques', 'صديرات وملابس داخلية حرارية', 'debardeurs-sous-maillots-thermiques', 'sous-vetements-homme', 2, 'ar'),
('soutiens-gorge', 'سوتيان', 'soutiens-gorge', 'lingerie-femme', 2, 'ar'),
('culottes', 'كولوت', 'culottes', 'lingerie-femme', 2, 'ar'),
('ensembles-lingerie', 'طقم ملابس داخلية', 'ensembles-lingerie', 'lingerie-femme', 2, 'ar'),
('body-combinaisons', 'بودي وكومبينيزون', 'body-combinaisons', 'lingerie-femme', 2, 'ar'),
('guepieres', 'جبير', 'guepieres', 'lingerie-femme', 2, 'ar'),
('lingerie-sculptante', 'ملابس داخلية مشكلة', 'lingerie-sculptante', 'lingerie-femme', 2, 'ar'),
('lingerie-sexy-dentelle', 'ملابس داخلية جذابة ودانتيل', 'lingerie-sexy-dentelle', 'lingerie-femme', 2, 'ar'),
('pyjamas-homme-femme', 'بيجامات رجالية ونسائية', 'pyjamas-homme-femme', 'nuit-interieur', 2, 'ar'),
('nuisettes', 'نيزيت', 'nuisettes', 'nuit-interieur', 2, 'ar'),
('deshabilles', 'دشابيل', 'deshabilles', 'nuit-interieur', 2, 'ar'),
('peignoirs', 'روب', 'peignoirs', 'nuit-interieur', 2, 'ar'),
('robes-de-chambre', 'روب', 'robes-de-chambre', 'nuit-interieur', 2, 'ar'),
('homewear', 'ملابس منزلية', 'homewear', 'nuit-interieur', 2, 'ar'),
('sous-vetements-thermiques', 'ملابس داخلية حرارية', 'sous-vetements-thermiques', 'sous-vetements-techniques', 2, 'ar'),
('sous-couches-sport', 'طبقات رياضية', 'sous-couches-sport', 'sous-vetements-techniques', 2, 'ar'),
('chaussettes-techniques-compression', 'جوارب تقنية وضاغطة', 'chaussettes-techniques-compression', 'sous-vetements-techniques', 2, 'ar'),
('chaussures-habillees', 'أحذية رسمية', 'chaussures-habillees', 'chaussures-homme-femme', 2, 'ar'),
('mocassins', 'موكاسين', 'mocassins', 'chaussures-homme-femme', 2, 'ar'),
('chaussures-de-ville', 'أحذية مدينة', 'chaussures-de-ville', 'chaussures-homme-femme', 2, 'ar'),
('baskets', 'باسكيت', 'baskets', 'chaussures-homme-femme', 2, 'ar');

-- Level 3 (Arabic - sample of key subcategories)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('basiques', 'أساسية', 'basiques', 't-shirts', 3, 'ar'),
('imprimes', 'مطبوعة', 'imprimes', 't-shirts', 3, 'ar'),
('oversize', 'فضفاضة', 'oversize', 't-shirts', 3, 'ar'),
('techniques', 'تقنية', 'techniques', 't-shirts', 3, 'ar'),
('manches-courtes', 'أكمام قصيرة', 'manches-courtes', 'polos', 3, 'ar'),
('manches-longues', 'أكمام طويلة', 'manches-longues', 'polos', 3, 'ar'),
('sport', 'رياضية', 'sport', 'polos', 3, 'ar'),
('classiques', 'كلاسيكية', 'classiques', 'chemises', 3, 'ar'),
('slim', 'ضيقة', 'slim', 'chemises', 3, 'ar'),
('decontractees', 'كاجوال', 'decontractees', 'chemises', 3, 'ar'),
('slim', 'ضيق', 'slim', 'jeans', 3, 'ar'),
('straight', 'مستقيم', 'straight', 'jeans', 3, 'ar'),
('skinny', 'سكيني', 'skinny', 'jeans', 3, 'ar'),
('courtes', 'قصيرة', 'courtes', 'robes', 3, 'ar'),
('longues', 'طويلة', 'longues', 'robes', 3, 'ar'),
('soiree', 'سهرة', 'soiree', 'robes', 3, 'ar'),
('slim', 'ضيق', 'slim', 'jeans-femme', 3, 'ar'),
('mom', 'موم', 'mom', 'jeans-femme', 3, 'ar'),
('skinny', 'سكيني', 'skinny', 'jeans-femme', 3, 'ar'),
('push-up', 'بوش أب', 'push-up', 'soutiens-gorge', 3, 'ar'),
('maintien', 'دعم', 'maintien', 'soutiens-gorge', 3, 'ar'),
('sans-armatures', 'بدون أسلاك', 'sans-armatures', 'soutiens-gorge', 3, 'ar'),
('classiques', 'كلاسيكية', 'classiques', 'culottes', 3, 'ar'),
('tailles-hautes', 'خصر عالي', 'tailles-hautes', 'culottes', 3, 'ar'),
('tanga', 'تانغا', 'tanga', 'culottes', 3, 'ar'),
('string', 'سترينغ', 'string', 'culottes', 3, 'ar'),
('mode', 'موضة', 'mode', 'baskets', 3, 'ar'),
('running', 'جري', 'running', 'baskets', 3, 'ar'),
('training', 'تدريب', 'training', 'baskets', 3, 'ar');

-- Level 3 - Catégories principales pour Vêtements Homme (Arabic)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('costumes', 'بدلات', 'costumes', 'vetements-homme', 3, 'ar'),
('chemises', 'قمصان', 'chemises', 'vetements-homme', 3, 'ar'),
('pantalons-homme', 'بناطيل رجالية', 'pantalons-homme', 'vetements-homme', 3, 'ar'),
('jeans-homme', 'جينز رجالي', 'jeans-homme', 'vetements-homme', 3, 'ar'),
('pulls-gilets-homme', 'كنزات وسترات رجالية', 'pulls-gilets-homme', 'vetements-homme', 3, 'ar'),
('vestes-manteaux-homme', 'جاكيتات ومعاطف رجالية', 'vestes-manteaux-homme', 'vetements-homme', 3, 'ar'),
('polos', 'بولو', 'polos', 'vetements-homme', 3, 'ar'),
('t-shirts-homme', 'تيشيرتات رجالية', 't-shirts-homme', 'vetements-homme', 3, 'ar'),
('shorts-homme', 'شورتات رجالية', 'shorts-homme', 'vetements-homme', 3, 'ar'),
('sous-vetements-homme', 'ملابس داخلية رجالية', 'sous-vetements-homme', 'vetements-homme', 3, 'ar');

-- SPANISH
-- Level 0
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('mode-accessoires', 'Ropa de Hombre y Mujer y Ropa Interior', 'mode-accessoires', NULL, 0, 'es');

-- Level 1
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('vetements-homme', 'Ropa de Hombre', 'vetements-homme', 'mode-accessoires', 1, 'es'),
('marques-vetements-homme', 'Marcas Ropa Hombre', 'marques-vetements-homme', 'mode-accessoires', 1, 'es'),
('accessoires-homme', 'Accesorios Hombre', 'accessoires-homme', 'mode-accessoires', 1, 'es'),
('vetements-femme', 'Ropa de Mujer', 'vetements-femme', 'mode-accessoires', 1, 'es'),
('marques-vetements-femme', 'Marcas Ropa Mujer', 'marques-vetements-femme', 'mode-accessoires', 1, 'es'),
('accessoires-femme', 'Accesorios Mujer', 'accessoires-femme', 'mode-accessoires', 1, 'es'),
('sous-vetements-homme', 'Ropa Interior Hombre', 'sous-vetements-homme', 'mode-accessoires', 1, 'es'),
('lingerie-femme', 'Lencería Mujer', 'lingerie-femme', 'mode-accessoires', 1, 'es'),
('nuit-interieur', 'Ropa de Noche y Interior', 'nuit-interieur', 'mode-accessoires', 1, 'es'),
('sous-vetements-techniques', 'Ropa Interior Técnica', 'sous-vetements-techniques', 'mode-accessoires', 1, 'es'),
('chaussures-homme-femme', 'Zapatos (Hombre y Mujer)', 'chaussures-homme-femme', 'mode-accessoires', 1, 'es');

-- Level 2
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('t-shirts', 'Camisetas', 't-shirts', 'vetements-homme', 2, 'es'),
('polos', 'Polos', 'polos', 'vetements-homme', 2, 'es'),
('chemises', 'Camisas', 'chemises', 'vetements-homme', 2, 'es'),
('pulls-gilets', 'Jerseys y Chalecos', 'pulls-gilets', 'vetements-homme', 2, 'es'),
('sweats-hoodies', 'Sudaderas y Hoodies', 'sweats-hoodies', 'vetements-homme', 2, 'es'),
('debardeurs', 'Chalecos', 'debardeurs', 'vetements-homme', 2, 'es'),
('jeans', 'Vaqueros', 'jeans', 'vetements-homme', 2, 'es'),
('pantalons', 'Pantalones', 'pantalons', 'vetements-homme', 2, 'es'),
('shorts', 'Shorts', 'shorts', 'vetements-homme', 2, 'es'),
('survetements', 'Chándales', 'survetements', 'vetements-homme', 2, 'es'),
('vestes-legeres', 'Chaquetas Ligeras', 'vestes-legeres', 'vetements-homme', 2, 'es'),
('blousons', 'Cazadoras', 'blousons', 'vetements-homme', 2, 'es'),
('manteaux', 'Abrigos', 'manteaux', 'vetements-homme', 2, 'es'),
('parkas-coupe-vent', 'Parkas y Cortavientos', 'parkas-coupe-vent', 'vetements-homme', 2, 'es'),
('vestes-de-travail', 'Chaquetas de Trabajo', 'vestes-de-travail', 'vetements-homme', 2, 'es'),
('costumes-smokings', 'Trajes y Esmoquin', 'costumes-smokings', 'vetements-homme', 2, 'es'),
('tenues-business', 'Ropa de Negocios', 'tenues-business', 'vetements-homme', 2, 'es'),
('mode-urbaine', 'Moda Urbana', 'mode-urbaine', 'vetements-homme', 2, 'es'),
('sportwear', 'Ropa Deportiva', 'sportwear', 'vetements-homme', 2, 'es'),
('tenues-outdoor', 'Ropa Outdoor', 'tenues-outdoor', 'vetements-homme', 2, 'es'),
('vetements-traditionnels-homme', 'Ropa Tradicional Hombre', 'vetements-traditionnels-homme', 'vetements-homme', 2, 'es'),
('ceintures', 'Cinturones', 'ceintures', 'accessoires-homme', 2, 'es'),
('cravates-noeuds-papillon', 'Corbatas y Pajaritas', 'cravates-noeuds-papillon', 'accessoires-homme', 2, 'es'),
('chapeaux-casquettes', 'Sombreros y Gorras', 'chapeaux-casquettes', 'accessoires-homme', 2, 'es'),
('gants-echarpes', 'Guantes y Bufandas', 'gants-echarpes', 'accessoires-homme', 2, 'es'),
('lunettes-soleil', 'Gafas de Sol', 'lunettes-soleil', 'accessoires-homme', 2, 'es'),
('montres', 'Relojes', 'montres', 'accessoires-homme', 2, 'es'),
('bijoux-homme', 'Joyería Hombre', 'bijoux-homme', 'accessoires-homme', 2, 'es'),
('portefeuilles', 'Carteras', 'portefeuilles', 'accessoires-homme', 2, 'es'),
('porte-cartes', 'Portatarjetas', 'porte-cartes', 'accessoires-homme', 2, 'es'),
('sacoches-besaces', 'Sacos y Bandoleras', 'sacoches-besaces', 'accessoires-homme', 2, 'es'),
('tops-t-shirts', 'Tops y Camisetas', 'tops-t-shirts', 'vetements-femme', 2, 'es'),
('chemisiers-blouses', 'Blusas y Camisas', 'chemisiers-blouses', 'vetements-femme', 2, 'es'),
('pulls-gilets-femme', 'Jerseys y Chalecos Mujer', 'pulls-gilets-femme', 'vetements-femme', 2, 'es'),
('sweats-hoodies-femme', 'Sudaderas y Hoodies Mujer', 'sweats-hoodies-femme', 'vetements-femme', 2, 'es'),
('debardeurs-bustiers', 'Chalecos y Bustiers', 'debardeurs-bustiers', 'vetements-femme', 2, 'es'),
('robes', 'Vestidos', 'robes', 'vetements-femme', 2, 'es'),
('robes-evenements', 'Vestidos de Eventos', 'robes-evenements', 'vetements-femme', 2, 'es'),
('jupes', 'Faldas', 'jupes', 'vetements-femme', 2, 'es'),
('jeans-femme', 'Vaqueros Mujer', 'jeans-femme', 'vetements-femme', 2, 'es'),
('pantalons-femme', 'Pantalones Mujer', 'pantalons-femme', 'vetements-femme', 2, 'es'),
('collants-leggings-thermiques', 'Leotardos y Leggings Térmicos', 'collants-leggings-thermiques', 'vetements-femme', 2, 'es'),
('vestes-femme', 'Chaquetas Mujer', 'vestes-femme', 'vetements-femme', 2, 'es'),
('blousons-femme', 'Cazadoras Mujer', 'blousons-femme', 'vetements-femme', 2, 'es'),
('manteaux-femme', 'Abrigos Mujer', 'manteaux-femme', 'vetements-femme', 2, 'es'),
('doudounes-femme', 'Plumíferos Mujer', 'doudounes-femme', 'vetements-femme', 2, 'es'),
('capes-ponchos', 'Capas y Ponchos', 'capes-ponchos', 'vetements-femme', 2, 'es'),
('mode-chic', 'Moda Chic', 'mode-chic', 'vetements-femme', 2, 'es'),
('mode-streetwear', 'Moda Streetwear', 'mode-streetwear', 'vetements-femme', 2, 'es'),
('sportwear-femme', 'Ropa Deportiva Mujer', 'sportwear-femme', 'vetements-femme', 2, 'es'),
('beachwear', 'Ropa de Playa', 'beachwear', 'vetements-femme', 2, 'es'),
('mode-traditionnelle-femme', 'Moda Tradicional Mujer', 'mode-traditionnelle-femme', 'vetements-femme', 2, 'es'),
('sacs-main', 'Bolsos de Mano', 'sacs-main', 'accessoires-femme', 2, 'es'),
('sacs-bandouliere', 'Bolsos de Bandolera', 'sacs-bandouliere', 'accessoires-femme', 2, 'es'),
('pochettes', 'Pochettes', 'pochettes', 'accessoires-femme', 2, 'es'),
('porte-monnaie', 'Monederos', 'porte-monnaie', 'accessoires-femme', 2, 'es'),
('bijoux', 'Joyería', 'bijoux', 'accessoires-femme', 2, 'es'),
('ceintures', 'Cinturones', 'ceintures', 'accessoires-femme', 2, 'es'),
('foulards-echarpes', 'Fulares y Bufandas', 'foulards-echarpes', 'accessoires-femme', 2, 'es'),
('accessoires-cheveux', 'Accesorios para el Cabello', 'accessoires-cheveux', 'accessoires-femme', 2, 'es'),
('lunettes-soleil-femme', 'Gafas de Sol Mujer', 'lunettes-soleil-femme', 'accessoires-femme', 2, 'es'),
('montres-femme', 'Relojes Mujer', 'montres-femme', 'accessoires-femme', 2, 'es'),
('boxers', 'Boxers', 'boxers', 'sous-vetements-homme', 2, 'es'),
('slips', 'Slips', 'slips', 'sous-vetements-homme', 2, 'es'),
('calecons', 'Calzones', 'calecons', 'sous-vetements-homme', 2, 'es'),
('debardeurs-sous-maillots-thermiques', 'Chalecos y Ropa Interior Térmica', 'debardeurs-sous-maillots-thermiques', 'sous-vetements-homme', 2, 'es'),
('soutiens-gorge', 'Sujetadores', 'soutiens-gorge', 'lingerie-femme', 2, 'es'),
('culottes', 'Bragas', 'culottes', 'lingerie-femme', 2, 'es'),
('ensembles-lingerie', 'Conjuntos de Lencería', 'ensembles-lingerie', 'lingerie-femme', 2, 'es'),
('body-combinaisons', 'Bodies y Enterizos', 'body-combinaisons', 'lingerie-femme', 2, 'es'),
('guepieres', 'Guêpières', 'guepieres', 'lingerie-femme', 2, 'es'),
('lingerie-sculptante', 'Lencería Moldeadora', 'lingerie-sculptante', 'lingerie-femme', 2, 'es'),
('lingerie-sexy-dentelle', 'Lencería Sexy y Encaje', 'lingerie-sexy-dentelle', 'lingerie-femme', 2, 'es'),
('pyjamas-homme-femme', 'Pijamas Hombre y Mujer', 'pyjamas-homme-femme', 'nuit-interieur', 2, 'es'),
('nuisettes', 'Camisones', 'nuisettes', 'nuit-interieur', 2, 'es'),
('deshabilles', 'Desabille', 'deshabilles', 'nuit-interieur', 2, 'es'),
('peignoirs', 'Albornoces', 'peignoirs', 'nuit-interieur', 2, 'es'),
('robes-de-chambre', 'Batas', 'robes-de-chambre', 'nuit-interieur', 2, 'es'),
('homewear', 'Ropa de Casa', 'homewear', 'nuit-interieur', 2, 'es'),
('sous-vetements-thermiques', 'Ropa Interior Térmica', 'sous-vetements-thermiques', 'sous-vetements-techniques', 2, 'es'),
('sous-couches-sport', 'Capas Base Deporte', 'sous-couches-sport', 'sous-vetements-techniques', 2, 'es'),
('chaussettes-techniques-compression', 'Calcetines Técnicos y Compresión', 'chaussettes-techniques-compression', 'sous-vetements-techniques', 2, 'es'),
('chaussures-habillees', 'Zapatos de Vestir', 'chaussures-habillees', 'chaussures-homme-femme', 2, 'es'),
('mocassins', 'Mocasines', 'mocassins', 'chaussures-homme-femme', 2, 'es'),
('chaussures-de-ville', 'Zapatos de Ciudad', 'chaussures-de-ville', 'chaussures-homme-femme', 2, 'es'),
('baskets', 'Zapatillas', 'baskets', 'chaussures-homme-femme', 2, 'es');

-- Level 3 (Spanish - sample of key subcategories)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('basiques', 'Básica', 'basiques', 't-shirts', 3, 'es'),
('imprimes', 'Estampada', 'imprimes', 't-shirts', 3, 'es'),
('oversize', 'Oversize', 'oversize', 't-shirts', 3, 'es'),
('techniques', 'Técnica', 'techniques', 't-shirts', 3, 'es'),
('manches-courtes', 'Manga Corta', 'manches-courtes', 'polos', 3, 'es'),
('manches-longues', 'Manga Larga', 'manches-longues', 'polos', 3, 'es'),
('sport', 'Deporte', 'sport', 'polos', 3, 'es'),
('classiques', 'Clásica', 'classiques', 'chemises', 3, 'es'),
('slim', 'Slim', 'slim', 'chemises', 3, 'es'),
('decontractees', 'Informal', 'decontractees', 'chemises', 3, 'es'),
('slim', 'Slim', 'slim', 'jeans', 3, 'es'),
('straight', 'Recto', 'straight', 'jeans', 3, 'es'),
('skinny', 'Skinny', 'skinny', 'jeans', 3, 'es'),
('courtes', 'Corta', 'courtes', 'robes', 3, 'es'),
('longues', 'Larga', 'longues', 'robes', 3, 'es'),
('soiree', 'Fiesta', 'soiree', 'robes', 3, 'es'),
('slim', 'Slim', 'slim', 'jeans-femme', 3, 'es'),
('mom', 'Mom', 'mom', 'jeans-femme', 3, 'es'),
('skinny', 'Skinny', 'skinny', 'jeans-femme', 3, 'es'),
('push-up', 'Push-up', 'push-up', 'soutiens-gorge', 3, 'es'),
('maintien', 'Sostén', 'maintien', 'soutiens-gorge', 3, 'es'),
('sans-armatures', 'Sin Aros', 'sans-armatures', 'soutiens-gorge', 3, 'es'),
('classiques', 'Clásica', 'classiques', 'culottes', 3, 'es'),
('tailles-hautes', 'Cintura Alta', 'tailles-hautes', 'culottes', 3, 'es'),
('tanga', 'Tanga', 'tanga', 'culottes', 3, 'es'),
('string', 'String', 'string', 'culottes', 3, 'es'),
('mode', 'Moda', 'mode', 'baskets', 3, 'es'),
('running', 'Running', 'running', 'baskets', 3, 'es'),
('training', 'Training', 'training', 'baskets', 3, 'es');

-- Level 3 - Catégories principales pour Vêtements Homme (Spanish)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('costumes', 'Trajes', 'costumes', 'vetements-homme', 3, 'es'),
('chemises', 'Camisas', 'chemises', 'vetements-homme', 3, 'es'),
('pantalons-homme', 'Pantalones de Hombre', 'pantalons-homme', 'vetements-homme', 3, 'es'),
('jeans-homme', 'Jeans de Hombre', 'jeans-homme', 'vetements-homme', 3, 'es'),
('pulls-gilets-homme', 'Jerseys & Chalecos de Hombre', 'pulls-gilets-homme', 'vetements-homme', 3, 'es'),
('vestes-manteaux-homme', 'Chaquetas & Abrigos de Hombre', 'vestes-manteaux-homme', 'vetements-homme', 3, 'es'),
('polos', 'Polos', 'polos', 'vetements-homme', 3, 'es'),
('t-shirts-homme', 'Camisetas de Hombre', 't-shirts-homme', 'vetements-homme', 3, 'es'),
('shorts-homme', 'Pantalones Cortos de Hombre', 'shorts-homme', 'vetements-homme', 3, 'es'),
('sous-vetements-homme', 'Ropa Interior de Hombre', 'sous-vetements-homme', 'vetements-homme', 3, 'es');

-- GERMAN
-- Level 0
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('mode-accessoires', 'Herren- & Damenkleidung & Unterwäsche', 'mode-accessoires', NULL, 0, 'de');

-- Level 1
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('vetements-homme', 'Herrenkleidung', 'vetements-homme', 'mode-accessoires', 1, 'de'),
('marques-vetements-homme', 'Marken Herrenkleidung', 'marques-vetements-homme', 'mode-accessoires', 1, 'de'),
('accessoires-homme', 'Herrenaccessoires', 'accessoires-homme', 'mode-accessoires', 1, 'de'),
('vetements-femme', 'Damenkleidung', 'vetements-femme', 'mode-accessoires', 1, 'de'),
('marques-vetements-femme', 'Marken Damenkleidung', 'marques-vetements-femme', 'mode-accessoires', 1, 'de'),
('accessoires-femme', 'Damenaccessoires', 'accessoires-femme', 'mode-accessoires', 1, 'de'),
('sous-vetements-homme', 'Herrenunterwäsche', 'sous-vetements-homme', 'mode-accessoires', 1, 'de'),
('lingerie-femme', 'Damenunterwäsche', 'lingerie-femme', 'mode-accessoires', 1, 'de'),
('nuit-interieur', 'Nacht- & Innenbekleidung', 'nuit-interieur', 'mode-accessoires', 1, 'de'),
('sous-vetements-techniques', 'Technische Unterwäsche', 'sous-vetements-techniques', 'mode-accessoires', 1, 'de'),
('chaussures-homme-femme', 'Schuhe (Herren & Damen)', 'chaussures-homme-femme', 'mode-accessoires', 1, 'de');

-- Level 2
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('t-shirts', 'T-Shirts', 't-shirts', 'vetements-homme', 2, 'de'),
('polos', 'Polos', 'polos', 'vetements-homme', 2, 'de'),
('chemises', 'Hemden', 'chemises', 'vetements-homme', 2, 'de'),
('pulls-gilets', 'Pullover & Westen', 'pulls-gilets', 'vetements-homme', 2, 'de'),
('sweats-hoodies', 'Sweatshirts & Hoodies', 'sweats-hoodies', 'vetements-homme', 2, 'de'),
('debardeurs', 'Tanktops', 'debardeurs', 'vetements-homme', 2, 'de'),
('jeans', 'Jeans', 'jeans', 'vetements-homme', 2, 'de'),
('pantalons', 'Hosen', 'pantalons', 'vetements-homme', 2, 'de'),
('shorts', 'Shorts', 'shorts', 'vetements-homme', 2, 'de'),
('survetements', 'Trainingsanzüge', 'survetements', 'vetements-homme', 2, 'de'),
('vestes-legeres', 'Leichte Jacken', 'vestes-legeres', 'vetements-homme', 2, 'de'),
('blousons', 'Blousons', 'blousons', 'vetements-homme', 2, 'de'),
('manteaux', 'Mäntel', 'manteaux', 'vetements-homme', 2, 'de'),
('parkas-coupe-vent', 'Parkas & Windbreaker', 'parkas-coupe-vent', 'vetements-homme', 2, 'de'),
('vestes-de-travail', 'Arbeitsjacken', 'vestes-de-travail', 'vetements-homme', 2, 'de'),
('costumes-smokings', 'Anzüge & Smoking', 'costumes-smokings', 'vetements-homme', 2, 'de'),
('tenues-business', 'Business-Outfits', 'tenues-business', 'vetements-homme', 2, 'de'),
('mode-urbaine', 'Urbaner Stil', 'mode-urbaine', 'vetements-homme', 2, 'de'),
('sportwear', 'Sportbekleidung', 'sportwear', 'vetements-homme', 2, 'de'),
('tenues-outdoor', 'Outdoor-Bekleidung', 'tenues-outdoor', 'vetements-homme', 2, 'de'),
('vetements-traditionnels-homme', 'Traditionelle Herrenbekleidung', 'vetements-traditionnels-homme', 'vetements-homme', 2, 'de'),
('ceintures', 'Gürtel', 'ceintures', 'accessoires-homme', 2, 'de'),
('cravates-noeuds-papillon', 'Krawatten & Fliegen', 'cravates-noeuds-papillon', 'accessoires-homme', 2, 'de'),
('chapeaux-casquettes', 'Hüte & Kappen', 'chapeaux-casquettes', 'accessoires-homme', 2, 'de'),
('gants-echarpes', 'Handschuhe & Schals', 'gants-echarpes', 'accessoires-homme', 2, 'de'),
('lunettes-soleil', 'Sonnenbrillen', 'lunettes-soleil', 'accessoires-homme', 2, 'de'),
('montres', 'Uhren', 'montres', 'accessoires-homme', 2, 'de'),
('bijoux-homme', 'Herrenschmuck', 'bijoux-homme', 'accessoires-homme', 2, 'de'),
('portefeuilles', 'Geldbörsen', 'portefeuilles', 'accessoires-homme', 2, 'de'),
('porte-cartes', 'Kartenetuis', 'porte-cartes', 'accessoires-homme', 2, 'de'),
('sacoches-besaces', 'Aktentaschen & Umhängetaschen', 'sacoches-besaces', 'accessoires-homme', 2, 'de');

-- Level 3 - Catégories principales pour Vêtements Homme (German)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('costumes', 'Anzüge', 'costumes', 'vetements-homme', 3, 'de'),
('chemises', 'Hemden', 'chemises', 'vetements-homme', 3, 'de'),
('pantalons-homme', 'Herrenhosen', 'pantalons-homme', 'vetements-homme', 3, 'de'),
('jeans-homme', 'Herrenjeans', 'jeans-homme', 'vetements-homme', 3, 'de'),
('pulls-gilets-homme', 'Herrenpullover & -westen', 'pulls-gilets-homme', 'vetements-homme', 3, 'de'),
('vestes-manteaux-homme', 'Herrenjacken & -mäntel', 'vestes-manteaux-homme', 'vetements-homme', 3, 'de'),
('polos', 'Polos', 'polos', 'vetements-homme', 3, 'de'),
('t-shirts-homme', 'Herren-T-Shirts', 't-shirts-homme', 'vetements-homme', 3, 'de'),
('shorts-homme', 'Herrenshorts', 'shorts-homme', 'vetements-homme', 3, 'de'),
('sous-vetements-homme', 'Herrenunterwäsche', 'sous-vetements-homme', 'vetements-homme', 3, 'de');

-- ENGLISH
-- Level 0
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('mode-accessoires', 'Men''s & Women''s Clothing & Underwear', 'mode-accessoires', NULL, 0, 'en');

-- Level 1
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('vetements-homme', 'Men''s Clothing', 'vetements-homme', 'mode-accessoires', 1, 'en'),
('marques-vetements-homme', 'Men''s Clothing Brands', 'marques-vetements-homme', 'mode-accessoires', 1, 'en'),
('accessoires-homme', 'Men''s Accessories', 'accessoires-homme', 'mode-accessoires', 1, 'en'),
('vetements-femme', 'Women''s Clothing', 'vetements-femme', 'mode-accessoires', 1, 'en'),
('marques-vetements-femme', 'Women''s Clothing Brands', 'marques-vetements-femme', 'mode-accessoires', 1, 'en'),
('accessoires-femme', 'Women''s Accessories', 'accessoires-femme', 'mode-accessoires', 1, 'en'),
('sous-vetements-homme', 'Men''s Underwear', 'sous-vetements-homme', 'mode-accessoires', 1, 'en'),
('lingerie-femme', 'Women''s Lingerie', 'lingerie-femme', 'mode-accessoires', 1, 'en'),
('nuit-interieur', 'Nightwear & Loungewear', 'nuit-interieur', 'mode-accessoires', 1, 'en'),
('sous-vetements-techniques', 'Technical Underwear', 'sous-vetements-techniques', 'mode-accessoires', 1, 'en'),
('chaussures-homme-femme', 'Shoes (Men & Women)', 'chaussures-homme-femme', 'mode-accessoires', 1, 'en');

-- Level 2
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('t-shirts', 'T-shirts', 't-shirts', 'vetements-homme', 2, 'en'),
('polos', 'Polos', 'polos', 'vetements-homme', 2, 'en'),
('chemises', 'Shirts', 'chemises', 'vetements-homme', 2, 'en'),
('pulls-gilets', 'Sweaters & Vests', 'pulls-gilets', 'vetements-homme', 2, 'en'),
('sweats-hoodies', 'Sweatshirts & Hoodies', 'sweats-hoodies', 'vetements-homme', 2, 'en'),
('debardeurs', 'Tank Tops', 'debardeurs', 'vetements-homme', 2, 'en'),
('jeans', 'Jeans', 'jeans', 'vetements-homme', 2, 'en'),
('pantalons', 'Pants', 'pantalons', 'vetements-homme', 2, 'en'),
('shorts', 'Shorts', 'shorts', 'vetements-homme', 2, 'en'),
('survetements', 'Tracksuits', 'survetements', 'vetements-homme', 2, 'en'),
('vestes-legeres', 'Light Jackets', 'vestes-legeres', 'vetements-homme', 2, 'en'),
('blousons', 'Jackets', 'blousons', 'vetements-homme', 2, 'en'),
('manteaux', 'Coats', 'manteaux', 'vetements-homme', 2, 'en'),
('parkas-coupe-vent', 'Parkas & Windbreakers', 'parkas-coupe-vent', 'vetements-homme', 2, 'en'),
('vestes-de-travail', 'Work Jackets', 'vestes-de-travail', 'vetements-homme', 2, 'en'),
('costumes-smokings', 'Suits & Tuxedos', 'costumes-smokings', 'vetements-homme', 2, 'en'),
('tenues-business', 'Business Outfits', 'tenues-business', 'vetements-homme', 2, 'en'),
('mode-urbaine', 'Urban Style', 'mode-urbaine', 'vetements-homme', 2, 'en'),
('sportwear', 'Sportswear', 'sportwear', 'vetements-homme', 2, 'en'),
('tenues-outdoor', 'Outdoor Clothing', 'tenues-outdoor', 'vetements-homme', 2, 'en'),
('vetements-traditionnels-homme', 'Traditional Men''s Clothing', 'vetements-traditionnels-homme', 'vetements-homme', 2, 'en'),
('ceintures', 'Belts', 'ceintures', 'accessoires-homme', 2, 'en'),
('cravates-noeuds-papillon', 'Ties & Bow Ties', 'cravates-noeuds-papillon', 'accessoires-homme', 2, 'en'),
('chapeaux-casquettes', 'Hats & Caps', 'chapeaux-casquettes', 'accessoires-homme', 2, 'en'),
('gants-echarpes', 'Gloves & Scarves', 'gants-echarpes', 'accessoires-homme', 2, 'en'),
('lunettes-soleil', 'Sunglasses', 'lunettes-soleil', 'accessoires-homme', 2, 'en'),
('montres', 'Watches', 'montres', 'accessoires-homme', 2, 'en'),
('bijoux-homme', 'Men''s Jewelry', 'bijoux-homme', 'accessoires-homme', 2, 'en'),
('portefeuilles', 'Wallets', 'portefeuilles', 'accessoires-homme', 2, 'en'),
('porte-cartes', 'Card Holders', 'porte-cartes', 'accessoires-homme', 2, 'en'),
('sacoches-besaces', 'Briefcases & Shoulder Bags', 'sacoches-besaces', 'accessoires-homme', 2, 'en');

-- Level 3 - Main Categories for Men''s Clothing (English)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('costumes', 'Suits', 'costumes', 'vetements-homme', 3, 'en'),
('chemises', 'Shirts', 'chemises', 'vetements-homme', 3, 'en'),
('pantalons-homme', 'Men''s Pants', 'pantalons-homme', 'vetements-homme', 3, 'en'),
('jeans-homme', 'Men''s Jeans', 'jeans-homme', 'vetements-homme', 3, 'en'),
('pulls-gilets-homme', 'Men''s Sweaters & Vests', 'pulls-gilets-homme', 'vetements-homme', 3, 'en'),
('vestes-manteaux-homme', 'Men''s Jackets & Coats', 'vestes-manteaux-homme', 'vetements-homme', 3, 'en'),
('polos', 'Polos', 'polos', 'vetements-homme', 3, 'en'),
('t-shirts-homme', 'Men''s T-shirts', 't-shirts-homme', 'vetements-homme', 3, 'en'),
('shorts-homme', 'Men''s Shorts', 'shorts-homme', 'vetements-homme', 3, 'en'),
('sous-vetements-homme', 'Men''s Underwear', 'sous-vetements-homme', 'vetements-homme', 3, 'en');

-- ITALIAN
-- Level 0
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES ('mode-accessoires', 'Abbigliamento Uomo & Donna e Intimo', 'mode-accessoires', NULL, 0, 'it');

-- Level 1
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('vetements-homme', 'Abbigliamento Uomo', 'vetements-homme', 'mode-accessoires', 1, 'it'),
('marques-vetements-homme', 'Marchi Abbigliamento Uomo', 'marques-vetements-homme', 'mode-accessoires', 1, 'it'),
('accessoires-homme', 'Accessori Uomo', 'accessoires-homme', 'mode-accessoires', 1, 'it'),
('vetements-femme', 'Abbigliamento Donna', 'vetements-femme', 'mode-accessoires', 1, 'it'),
('marques-vetements-femme', 'Marchi Abbigliamento Donna', 'marques-vetements-femme', 'mode-accessoires', 1, 'it'),
('accessoires-femme', 'Accessori Donna', 'accessoires-femme', 'mode-accessoires', 1, 'it'),
('sous-vetements-homme', 'Intimo Uomo', 'sous-vetements-homme', 'mode-accessoires', 1, 'it'),
('lingerie-femme', 'Intimo Donna', 'lingerie-femme', 'mode-accessoires', 1, 'it'),
('nuit-interieur', 'Notte & Interno', 'nuit-interieur', 'mode-accessoires', 1, 'it'),
('sous-vetements-techniques', 'Intimo Tecnico', 'sous-vetements-techniques', 'mode-accessoires', 1, 'it'),
('chaussures-homme-femme', 'Scarpe (Uomo & Donna)', 'chaussures-homme-femme', 'mode-accessoires', 1, 'it');

-- Level 2
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('t-shirts', 'T-shirt', 't-shirts', 'vetements-homme', 2, 'it'),
('polos', 'Polo', 'polos', 'vetements-homme', 2, 'it'),
('chemises', 'Camicie', 'chemises', 'vetements-homme', 2, 'it'),
('pulls-gilets', 'Maglioni & Gilet', 'pulls-gilets', 'vetements-homme', 2, 'it'),
('sweats-hoodies', 'Felpe & Hoodie', 'sweats-hoodies', 'vetements-homme', 2, 'it'),
('debardeurs', 'Canottiere', 'debardeurs', 'vetements-homme', 2, 'it'),
('jeans', 'Jeans', 'jeans', 'vetements-homme', 2, 'it'),
('pantalons', 'Pantaloni', 'pantalons', 'vetements-homme', 2, 'it'),
('shorts', 'Shorts', 'shorts', 'vetements-homme', 2, 'it'),
('survetements', 'Tute', 'survetements', 'vetements-homme', 2, 'it'),
('vestes-legeres', 'Giacche Leggere', 'vestes-legeres', 'vetements-homme', 2, 'it'),
('blousons', 'Giacche', 'blousons', 'vetements-homme', 2, 'it'),
('manteaux', 'Cappotti', 'manteaux', 'vetements-homme', 2, 'it'),
('parkas-coupe-vent', 'Parka & Windbreaker', 'parkas-coupe-vent', 'vetements-homme', 2, 'it'),
('vestes-de-travail', 'Giacche da Lavoro', 'vestes-de-travail', 'vetements-homme', 2, 'it'),
('costumes-smokings', 'Completo & Smoking', 'costumes-smokings', 'vetements-homme', 2, 'it'),
('tenues-business', 'Outfit Business', 'tenues-business', 'vetements-homme', 2, 'it'),
('mode-urbaine', 'Stile Urbano', 'mode-urbaine', 'vetements-homme', 2, 'it'),
('sportwear', 'Abbigliamento Sportivo', 'sportwear', 'vetements-homme', 2, 'it'),
('tenues-outdoor', 'Abbigliamento Outdoor', 'tenues-outdoor', 'vetements-homme', 2, 'it'),
('vetements-traditionnels-homme', 'Abbigliamento Tradizionale Uomo', 'vetements-traditionnels-homme', 'vetements-homme', 2, 'it'),
('ceintures', 'Cinture', 'ceintures', 'accessoires-homme', 2, 'it'),
('cravates-noeuds-papillon', 'Cravatte & Papillon', 'cravates-noeuds-papillon', 'accessoires-homme', 2, 'it'),
('chapeaux-casquettes', 'Cappelli & Cappellini', 'chapeaux-casquettes', 'accessoires-homme', 2, 'it'),
('gants-echarpes', 'Guanti & Sciarpe', 'gants-echarpes', 'accessoires-homme', 2, 'it'),
('lunettes-soleil', 'Occhiali da Sole', 'lunettes-soleil', 'accessoires-homme', 2, 'it'),
('montres', 'Orologi', 'montres', 'accessoires-homme', 2, 'it'),
('bijoux-homme', 'Gioielli Uomo', 'bijoux-homme', 'accessoires-homme', 2, 'it'),
('portefeuilles', 'Portafogli', 'portefeuilles', 'accessoires-homme', 2, 'it'),
('porte-cartes', 'Porta Carte', 'porte-cartes', 'accessoires-homme', 2, 'it'),
('sacoches-besaces', 'Cartelle & Borse a Tracolla', 'sacoches-besaces', 'accessoires-homme', 2, 'it');

-- Level 3 - Categorie principali per Abbigliamento Uomo (Italian)
INSERT INTO categories (id, name, slug, parent_id, level, language) VALUES 
('costumes', 'Completo', 'costumes', 'vetements-homme', 3, 'it'),
('chemises', 'Camicie', 'chemises', 'vetements-homme', 3, 'it'),
('pantalons-homme', 'Pantaloni Uomo', 'pantalons-homme', 'vetements-homme', 3, 'it'),
('jeans-homme', 'Jeans Uomo', 'jeans-homme', 'vetements-homme', 3, 'it'),
('pulls-gilets-homme', 'Maglioni & Gilet Uomo', 'pulls-gilets-homme', 'vetements-homme', 3, 'it'),
('vestes-manteaux-homme', 'Giacche & Cappotti Uomo', 'vestes-manteaux-homme', 'vetements-homme', 3, 'it'),
('polos', 'Polo', 'polos', 'vetements-homme', 3, 'it'),
('t-shirts-homme', 'T-shirt Uomo', 't-shirts-homme', 'vetements-homme', 3, 'it'),
('shorts-homme', 'Shorts Uomo', 'shorts-homme', 'vetements-homme', 3, 'it'),
('sous-vetements-homme', 'Intimo Uomo', 'sous-vetements-homme', 'vetements-homme', 3, 'it');