// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const rawEnv = import.meta.env as unknown as Record<string, string | undefined>;
const SUPABASE_URL = rawEnv.VITE_SUPABASE_URL ?? rawEnv.SUPABASE_URL ?? '';
const SUPABASE_PUBLISHABLE_KEY =
  rawEnv.VITE_SUPABASE_PUBLISHABLE_KEY ??
  rawEnv.VITE_SUPABASE_ANON_KEY ??
  rawEnv.SUPABASE_ANON_KEY ??
  '';

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  isSupabaseConfigured ? SUPABASE_URL : 'https://placeholder.supabase.co',
  isSupabaseConfigured ? SUPABASE_PUBLISHABLE_KEY : 'public-anon-key'
);
